### ISSUE TITLE
Weird error about test_df now found

### ISSUE THREAD

**Issue by xiaodaigh** [r-lib/testthat#1003]
I am trying to write some tests for my package disk.frame. So in the `./test/testthat` folder I have a file say, `test-for-fun.r` and the file contains

```r
test_that("testing", {
  library(disk.frame)
  setup_disk.frame()
  test_df = as.disk.frame(cars, nchunks = 2)
  test_result = test_df %>%
    group_by(!!!syms(names(test_df))) %>%
    summarize(n=n()) %>% 
    collect
})
```

When I click "Run Tests" in Rstudio I get these errors 

```
test-for-fun.r:6: error: testing
object 'test_df' not found
Backtrace:
  1. dplyr::group_by(., !!!syms(names(test_df)))
  1. dplyr::summarize(., n = n())
  9. dplyr::collect(.)
 11. disk.frame::chunk_group_by(., !!!syms(names(test_df)))
 28. rlang:::map(x, sym)
 29. base::lapply(.x, .f, ...)
```

However if I just

```bash
Rscript test-for-fun.r
```
then there is no error, and when I do just the code in the REPL line by line it runs fine.

```
library(disk.frame)
  setup_disk.frame()
  test_df = as.disk.frame(cars, nchunks = 2)
  test_result = test_df %>%
    group_by(!!!syms(names(test_df))) %>%
    summarize(n=n()) %>% 
    collect
```

What could be causing the error? What is different about running tests using testthat?

**Comment by hadley** [comment]
This sort of failure typically suggests that a package is not evaluating your code in the right environment. I'd check with the disk.frame maintainer.
