### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by psteinb** [r-lib/testthat#1007]
When I open `https://testthat.r-lib.org/` on Apr 7, 2020, 2:54 pm CEST, I get:
![image](https://user-images.githubusercontent.com/1465603/78671528-b650a500-78df-11ea-9711-926811ed28cb.png)

**Comment by jimhester** [comment]
There is an incident report at https://www.githubstatus.com/incidents/f3xzj5fgfq5b

In any case this does not seem like a testthat specific issue, it will be resolved by GitHub.

**Comment by psteinb** [comment]
Ok, fair enough. I just wanted to report it in case the problem was something you could influence.

**Comment by jimhester** [comment]
Seems to be resolved now!
