### ISSUE TITLE
expect_equal failure output isn't useful when the difference is up to tolerance

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1010]
Consider:

```
expect_equal(1.02, 1.0200001)
# Error: 1.02 not equal to 1.0200001.
# 1/1 mismatches
# [1] 1.02 - 1.02 == -1e-07
```

LHS & RHS of the output are both `1.02`

This output would be most useful if `x` and `y` are totally different; would it make more sense to display the values more exactly if the difference is smaller than `1e-2`?

**Comment by hadley** [comment]
Will be fixed by #1005 —

```
Error: `actual` (1.02) not equal to `expected` (1.0200001).

`actual-expected`: -1.00000000058387e-07
`0`:               0                    
```

Let me know if you have better ideas for the output — it's hard to know exactly what to show when the difference is smaller than the usual printed precision.

**Comment by MichaelChirico** [comment]
Looks better I agree. Though I don't follow the last line (`` `0`:           0 ``)

**Comment by hadley** [comment]
Currently all the diffs are pairs, so the second line here just a line of zeros. It's not great, but I'm out of ideas at the moment. It's likely someone will figure out something better in the future.

**Comment by jimhester** [comment]
Could you always show it will the full precision to reveal the difference? e.g. i

``` r
num_diff <- function(actual, expected) {
  diff <- abs(actual - expected)
  num_format <- paste0("%.", ceiling(abs(log10(diff))), "f")
  nums <- sprintf(num_format, c(actual, expected))
  names <- c("actual", "expected")
  cat(sprintf("`%s`: %s\n", format(names), nums), sep = "")
}

num_diff(1.02, 1.020001)
#> `actual  `: 1.0200000
#> `expected`: 1.0200010

num_diff(1.02, 1.0200000001)
#> `actual  `: 1.0200000000
#> `expected`: 1.0200000001
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You might be able to do something better with the math to calculate the number of places more precisely, but even if you have an extra place in some cases I think is much clearer than the proposed output.

**Comment by hadley** [comment]
Good idea, now it's:

``` r
library(testthat)
expect_equal(1.02, 1.0200001)
#> Error: `actual` (1.02) not equal to `expected` (1.0200001).
#> 
#> `actual`:   1.0200000
#> `expected`: 1.0200001
expect_equal(sqrt(2) ^ 2, 2, tolerance = 0)
#> Error: `actual` (sqrt(2)^2) not equal to `expected` (2).
#> 
#> `actual`:   2.0000000000000004
#> `expected`: 2.0000000000000000
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
