### ISSUE TITLE
Mention expect_vector() in documentation for expect_length()

### ISSUE THREAD

**Issue by davidchall** [r-lib/testthat#1012]
The documentation for `expect_length()` says that it checks if a vector has the specified length. But {vctrs} has formalized the concept of a vector's "size", which is often the desired property (rather than its length). The vector size can be tested using `expect_vector()`.

I think it might be helpful to reference `expect_vector()` from the documentation of `expect_length()`, to improve the discoverability of this alternative function. It is needed when using S3 vectors derived from {vctrs} classes.

**Comment by hadley** [comment]
Done, thanks for filing the issue!
