### ISSUE TITLE
expect_inform()

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1024]
Motivated by me transitioning packages to communicate with the user via `rlang::inform()`.

Since `inform()` can potentially send output to stdout or stderr, depending on the context, I think it would be nice to have an `expect_inform()` that just does the right thing, so you never have to remember whether it should be `expect_message()` or `expect_output()`.

This also means that if `inform()` ever changed again (not super likely, I realize) and `expect_inform()` was duly updated, lots of tests and packages would just continue to work. Most of the usethis v1.6.0 revdep issues were around people testing our output. Now, that's already a red flag, for sure, but the stdout vs stderr thing also came up.

**Comment by hadley** [comment]
Because of the way that `inform()` is implemented, it looks like `expect_message()` will always work:

```R
library(testthat)
library(rlang, warn.conflicts = FALSE)

options(rlang_interactive = FALSE)
expect_message(inform("x"), "x")
expect_output(inform("x"), "x")
#> Error: `inform("x")` produced no output

options(rlang_interactive = TRUE)
expect_message(inform("x"), "x")
expect_output(inform("x"), "x")
```

(can't reprex this because, I think, of the way that knitr/evaluate handles messages)

**Comment by jennybc** [comment]
What do you think of defining `expect_inform <- expect_message` then?

**Comment by hadley** [comment]
It just feels a bit redundant to me

**Comment by jennybc** [comment]
My reasoning is that every time I go to write a test for something emitted by `inform()` I pause over whether I should use `expect_message()` or `expect_output()`. I am happy to learn `expect_message()` will always work! But if `expect_inform()` existed, I'd never even think twice about whether I'm doing it right.

**Comment by hadley** [comment]
I think that's maybe because you're too close to the implementation details of `inform()`; the magic we do in it is just to work around the RStudio colouring issue. From the outside, it's just a wrapper around `message()` in the same way that `abort()` is a wrapper around `stop()`.
