### ISSUE TITLE
Getting stats about tests and expects/asserts

### ISSUE THREAD

**Issue by melvidoni** [r-lib/testthat#1025]
Hello,

I would like to know if it is possible to know: 1) How many `test_that` functions a package has, and 2) how many `expect_something`* each test_that has.

Is this possible?

Yes, I know I can read line-by-line all the files, and count lines, but that wouldn't give me a match between a `test_that` function, and how many `expect_something` they have.

* saying `expect_something` to indicate the multiple variances of expects

**Comment by hadley** [comment]
You could write your own reporter to capture this information. That's not very well documented, so you'd have to read the source to figure out how.
