### ISSUE TITLE
Skip errors of class "packageNotFoundError"

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1026]
which are triggered when a package can't be loaded for any reason.

``` r
tryCatch(
  library(froofy),
  packageNotFoundError = function(e) {
    "Oh well..."
  }
)
#> [1] "Oh well..."
```

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Slightly related: The "summary" reporter should aggregate skips by reason, so that the output is not bloated.

**Comment by hadley** [comment]
After a bunch of internal discussion I've decided not to do this at this time: 

* There's some risk that it will make install failures of suggested packages less obvious on CI.
* It only helps a relatively small number of packages, mostly those that are not available on solaris (e.g. V8).
* On 3.5 and earlier you'll still need `skip_if_not_installed()`.
* It generally feels a bit too magical.
