### ISSUE TITLE
testthat 3e

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1027]
There are a number of components of the testthat API that we now regret, but are effectively impossible to remove because 100s of CRAN packages use them, including many packages that are not regularly maintained. Thanks to @jcheng5 I now have a framework for how we might start to more actively re-shape the API for active developers, while leaving the vast majority of packages as is. The key idea is to allow developers to opt-in to an "edition" or version of testthat, using something like  `tests/testthat.yml`, `edition: 2020`.

For this edition, I propose:

* Switching from `all.equal()`/`identical()` to waldo in `expect_equal()` and friends
* Changing the test working directory to the package root, and consequently deprecating `test_path()` (or `setwd(tempdir())` and **require** `test_path()`)
* Running each test file in its own process
* Formally deprecating the old testthat interface based around `expect_that()`
* Formally deprecating `context()` — needs some work to remove internal usage prior to deprecation.
* Formally deprecating bare expectations, `expect_is()`, `compare()`, `expect_known_output()`, ...
* Making `takes_less_than()`, `not()`, `expect_less_than()`, and `expect_greater_than()` defunct
* Deprecate `setup()` and `teardown()` in favour of test fixtures.
* `inst/testthat` should error

As a carrot for upgrading, we'd also make parallel tests available only for this edition.

**Comment by hadley** [comment]
Current best proposal for declaring the edition: in the `DESCRIPTION` add `Config/testthat/edition: 3`.

On first run, we'd set `Config/testthat/edition: 2` with a message pointing to more details about the different in the edition (presumably a vignette).

**Comment by hadley** [comment]
Implicit goal should be that converting from 2nd edition to 3rd edition should be less than an hours work for most packages.

**Comment by hadley** [comment]
Also consider whether testthat should swallow stdout and pass through stderr (i.e. the effective opposite of what it does now).

**Comment by gavinsimpson** [comment]
> Deprecate setup() and teardown() in favour of test fixtures.

Does this extend to the `setup-xyz.R` and `teardown-xyz.R` functionality? These are quite useful for having expensive objects created and available across all tests (such as models fitted by functions in other packages for which the current package provides additional functionality).

**Comment by hadley** [comment]
@gavinsimpson I'm not sure, I'll probably recommend against them but leave them around. They start to get more complicated once testing in parallel happens, because they're no longer going to be run once, but will be run once per process.

**Comment by hadley** [comment]
Split up into multiple issues: https://github.com/r-lib/testthat/labels/3e%20%3Abooks%3A
