### ISSUE TITLE
Adding methods to compare() for Bioconductor classes

### ISSUE THREAD

**Issue by omsai** [r-lib/testthat#1039]
I write packages that depend heavily on Bioconductor packages and need succinct and descriptive comparisons of those objects when tests fail.  I have created a package to add these comparisons:
https://gitlab.com/coregenomics/testthatbioc/-/blob/master/R/granges.R

Should I open a pull request for adding in `compare.MyClass()` and `format.mismatch_MyClass()` objects?  I'm worried about the dependency bloat it would add to testthat.

Additional problems with my having a separate package to extend `compare` and `format` generics are:

1. I have to use several unexported testthat functions in my implementation linked above which tells me I'm doing something I should not be.
2. Note that my package at the minute has a bug with making those methods visible, because simply modifying my `./tests/testthat.R` to import my `testthatbioc` instead of `testthat` and adding a test still invokes the `compare.default()` method:

```R
test_that("testthatbioc gives expected output", {
    expect_equal(GRanges(c("chr1:100:+",
                           "chr1:200:+",
                           "chr1:150:-",
                           "chr1:250:-")),
                 GRanges(c("chr1:100:+",
                           "chr1:200:+",
                           "chr1:450:-")))
})
```

**Comment by hadley** [comment]
The next version of testthat will use waldo, https://github.com/r-lib/waldo, which I suspect will resolve your problem without further customisation.

**Comment by omsai** [comment]
Excellent; thank you!
