### ISSUE TITLE
Show values of expected and actual values for comparisons

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#104]
I find it difficult to determine, for a failing `expect_equal` expectation, the actual value that has been computed. It would be great if, in this case, the expected and actual values would be printed. Is there an option to enable this?

If not: Perhaps a good place to implement this is a wrapper around `all.equal`, to be called by `compare.default`, that will return actual values in certain cases but otherwise call `all.equal`.

**Comment by wheelsandmetal** [comment]
Is there a way to do this now?

**Comment by krlmlr** [comment]
Commenting to a issue from four years ago isn't really helpful. For questions, please visit https://community.rstudio.com -- if this concerns code, a reproducible example helps a lot: https://reprex.tidyverse.org/.
