### ISSUE TITLE
Classed warning expectation doesn't fail

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#1052]
Should fail:

```r
testthat::expect_warning(warning("foo"), class = "bar")
#>
```

Reported in r-lib/lifecycle#50

**Comment by hadley** [comment]
Looks like this was never implemented and we're not using ellipsis, so the extra argument is just swallowed by `...`.

**Comment by hadley** [comment]
Ah yes, the challenge is that `expect_warning()` and `expect_message()` can collect multiple warnings/messages. So how should the class be applied if there are multiple messages?

**Comment by lionel-** [comment]
We fail if there is not at least one class with that message/class, and the rest are resignalled as if there were no `expect_warning()`?

**Comment by lionel-** [comment]
This also means that lifecycle warnings break tests using `expect_warning()` with deprecated functions because they will never fail.

**Comment by hadley** [comment]
Ok, that's a compelling reason to do this work.
