### ISSUE TITLE
expect_snapshot()

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1057]
Implement new snapshot mechanism inspired by jest and discussions with @jcheng5 (much in #1017)

```R
# in test-foo.R
test_that("title", {
  expect_snapshot(complicated())
})
```

On first run, would create `tests/testthat/snapshots/foo.yaml` containing:

```yaml
title:
- output of complicated()
```

On subsequent runs, would generate `tests/testthat/snapshots/foo.yaml.new`. If no difference from the previous run, the test succeeds and the file is be automatically deleted. If there are differences, the test fails. If it's a deliberate change, you run `snapshot_update()` to update stored snapshots.

At the end of the complete test run, all obsolete snapshots are automatically deleted.

When `expect_snapshot()` is run interactively (i.e. no `TESTTHAT_FILE` env var set), it would just print the value.

**Comment by hadley** [comment]
`verify_output()` would become `snapshot_md()` incorporating #1050, and automatically generating a path from a short label (e.g. `snapshot_md("print", ...)` generates `tests/testthat/snapshots/foo-print.md`)

**Comment by hadley** [comment]
Need to think about what `expect_snapshot()` should do with other types of output. Should it capture all output types, or should we have `expect_equal_snapshot()`, `expect_error_snapshot()` etc

**Comment by hadley** [comment]
Feedback from group meeting:

* Worth considering `expect_snapshot_equal()`, `expect_snapshot_output()` and `expect_snapshot_error()`
* Might be better to serialize to json rather than yaml, since better default handing for existing R data structures
* Should consider binary serialisation to rds, because we'll still get nice diffs with waldo, and sometimes it's worth it even if you can't get human readable diffs for PRs

**Comment by hadley** [comment]
`expect_snapshot_error()` should only check for presence/absence of error on CRAN, not precise class or values (#1013). Could also offer an argument that lets you include various fields in the comparison.

**Comment by jcheng5** [comment]
> Worth considering `expect_snapshot_equal()`, `expect_snapshot_output()` and `expect_snapshot_error()`

For `expect_snapshot_equal`, how about `expect_snapshot_value` instead? "value", "output", and "error" being the three things being compared--they're all expected to be equal to the snapshot.

**Comment by hadley** [comment]
Oh, yeah, that's a better name! I think `expect_snapshot_equal()` would probably use json, and have a `binary = TRUE` option if a binary `.rds` representation was better for your use case.
