### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1059]
Either change working directory to the package root, and consequently deprecating test_path(); or possibly setting the working directory to `tempdir()` and requiring `test_path()`.

**Comment by hadley** [comment]
After discussion at team meeting: we decided that it makes the most sense for `test_that()` to set the working directory to a temporary directory, in order to force you to use `test_path()`. Setting the working directory to the package root doesn't make sense because it implies that you can use any path inside the package — that's not true because the structure inside the package root is radically different between source, checking, and installed packages. Setting the working directory to a deliberate dummy path is that best we can do because at forces the problem to your attention while writing the test, so it can't later fail during `R CMD check`.

**Comment by gaborcsardi** [comment]
One advantage of the temp dir is that the test cases can dump stuff in it, and testthat can automatically clean everything up at the end of the test suite.

**Comment by hadley** [comment]
See discussion in linked PR
