### ISSUE TITLE
[feature request] more intuitive methods for comparing relative and absolute errors between floating point vectors

### ISSUE THREAD

**Issue by yl790** [r-lib/testthat#1062]
I have seen even the most seasoned R users wrongly assuming `expect_equal(float1, float2, tolerance = tol)` would check the absolute error between the actual and expected values, and would only find out that's not the case by first reading `?expect_equal` to realize it uses `all.equal`, and then reading `?all.equal` to see

```
     Numerical comparisons for ‘scale = NULL’ (the default) are
     typically on _relative difference_ scale unless the target values
     are close to zero: First, the mean absolute difference of the two
     numerical vectors is computed.  If this is smaller than
     ‘tolerance’ or not finite, absolute differences are used,
     otherwise relative differences scaled by the mean absolute
     ‘target’ value.  Note that these comparisons are computed only for
     those vector elements where ‘target’ is not ‘NA’ and differs from
     ‘current’.  If ‘countEQ’ is true, the equal and ‘NA’ cases are
     _counted_ in determining “sample” size.
```

and then finally realizing `expect_equal(float1, float2, tolerance = tol, scale = 1)` would actually check for absolute error, whereas what `expect_equal(float1, float2, tolerance = tol)` does is the outcome of some kind of decision tree as vaguely described in `?all.equal`.

This looks to me like too many indirections and cognitive overhead for something simple. It's also error-prone especially for people not reading documentation that well. Why not just have specialized methods `expect_approx_equal(x, y, max_abs_err = <abs tol>)` and `expect_approx_equal(x, y, max_rel_err = <rel tol>)` instead?

**Comment by hadley** [comment]
This will be resolved in the 3rd edtion of testthat which uses `waldo::compare()`, which implements this tolerance consistently and is well documented. I looked into making the existing behaviour of tolerance more consistent, but unfortunately any change is likely to break hundreds of packages on CRAN.
