### ISSUE TITLE
Improvements to CheckReporter

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1073]
New reporter designed for batch usage

* Should always display full backtraces in errors
* Print test names (so if tests crash you can see where)
* Saves test data to file (#875)

**Comment by hadley** [comment]
Or maybe this is just additional features in CheckReporter?

**Comment by gaborcsardi** [comment]
Could be, but this changes the `CheckReporter` so much, that it might make sense to create a `CheckReporter2` and make that the default?

**Comment by hadley** [comment]
Do you think people care strongly about the design of the existing CheckReporter?

**Comment by gaborcsardi** [comment]
I would not think so, well, except maybe for wishing that it was more verbose? :)

**Comment by hadley** [comment]
Yeah, so I think we can just change it. No need to make a new reporter. I'm looking at the code for it now, and it's _very_ minimal.

**Comment by gaborcsardi** [comment]
I guess then the question is whether we want the same (default) behavior on
- CRAN,
- CI, and
- in a local R CMD check.

If they can behave (mostly) the same way, then it is OK.

**Comment by hadley** [comment]
In many senses `R CMD check` is a batch environment (i.e. it's hard to debug) so it makes sense to me for them to all behave the same way.

**Comment by hadley** [comment]
Should also save `sessionInfo()` to a file.

**Comment by gaborcsardi** [comment]
> Should also save sessionInfo() to a file.

Actually, just adding a `sessioninfo::session_info()` call to the `testthat.R` file is also fine?
