### ISSUE TITLE
Wrong locus reported when a custom expectation fails

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1080]
usethis defines a custom expectation in `helper.R`, `expect_usethis_error()`:

https://github.com/r-lib/usethis/blob/e75c9ede59c6c77941de0ae9e84af525a5fce08f/tests/testthat/helper.R#L107-L109

In a PR branch, I just made a change that caused an instance of `expect_usethis_error()` to fail, which is great and the correct outcome. I did break something.

But the locus reported for this failure is not the file and line number of the failed expectation, but rather refers back to where `expect_usethis_error()` is defined. Here's an excerpt of the `devtools::test()` output:

```
✓ |   8       | use-vignette [0.3 s]
✓ |  16       | utils-git [0.1 s]
x |  25 1     | utils-github [0.2 s]
─────────────────────────────────────────────────────────────
helper.R:107: failure: github_remote_protocol() errors for unrecognized URL
`github_remote_protocol()` did not throw an error.
─────────────────────────────────────────────────────────────
✓ |   9       | utils
✓ |  20       | write helpers
```

Is this avoidable or is just the price you pay if you write a custom expectation?

**Comment by hadley** [comment]
Hmmm, I can't recreate this in testthat — I think I probably accidentally fixed it while refactoring `expect_error()` and friends.
