### ISSUE TITLE
Consider an option to suppress multiple warnings

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/testthat#1083]
It seems this change on `expect_warning()` is intentional and this doesn't break any tests in actual, but I feel a bit overwhelmed to see so many uncaptured warnings. For simple unit tests, we can (and should) expect the exact number of warnings. However, for an integration tests, it's often hard to expect or control how many times the warnings will be issued (I think this is one of the reasons why we sometimes face the same warnings multiple times on ggplot2...). Is it possible to provide some option to suppress further warnings?

### CRAN version

``` r
f <- function() {
  rlang::warn("foo")
  rlang::warn("foo")
}

testthat::expect_warning(f(), "foo")
```

<sup>Created on 2020-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Current GitHub master

``` r
f <- function() {
  rlang::warn("foo")
  rlang::warn("foo")
}

testthat::expect_warning(f(), "foo")
#> Warning: foo
```

<sup>Created on 2020-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Such a function already exists 😀 `suppressWarnings()`. (But we’ll definitely monitor this change to consider if it’s too annoying and consider some other way to mitigate)

**Comment by yutannihilation** [comment]
Yeah, `suppressWarnings()` is a beloved function...
