### ISSUE TITLE
Creating local functions in testthat files

### ISSUE THREAD

**Issue by Anirban166** [r-lib/testthat#1090]
I thought local non-imported functions are supported in testthat files, but I recently tried to create some new functions based on sorting algorithms within a testthat file and it turns out RCMD check() is producing an error for the same. (if I simply copy paste the function and corresponding test in the console and run it, it runs without an error or test passes)

For instance, I create a function for selection sort inside the scope of the second parameter for a `test_that` call, which results in a test fail: 
![1](https://user-images.githubusercontent.com/30123691/87001973-561b1900-c1d6-11ea-9f2b-5f1e3789ab15.png)

Also fails if I put my function outside the test_that block:
![2](https://user-images.githubusercontent.com/30123691/87002218-bf029100-c1d6-11ea-8815-39600b254cc9.png)

There isn't any problem with my function, as I've checked it locally as mentioned:
![2 5](https://user-images.githubusercontent.com/30123691/87002396-215b9180-c1d7-11ea-85a1-9a4065d4a8ee.png)

The other tests all work fine, which include functions from my package, other packages (imports or in suggests), and also normal ones such as the `sort()` function for instance in the pictures above. The problem persists (errors throw up at RCMD check()) for the functions that I locally create in testthat files. I also tested on a dummy function, which again fails:
![3](https://user-images.githubusercontent.com/30123691/87002472-4f40d600-c1d7-11ea-92fd-0c84c6650a1f.png)

Am I doing something wrong? I guess testthat supports creation of non-imported/user-defined functions within the testthat files, so what am I missing?

**Comment by gaborcsardi** [comment]
Hi, you'll need to show us your package, so we can actually try it.

**Comment by Anirban166** [comment]
Sure, you can find it [here](https://github.com/Anirban166/testComplexity), and either of these will work:
```r
devtools::install_github("Anirban166/testComplexity")
remotes::install_github("Anirban166/testComplexity")
```
Its fully functional at the current stage, but I haven't added/committed the testthat file shown above (so it compiles successfully without any RCMD check() errors).
For reproducibility, you can create a testthat file for the package and put this chunk of code in it:
```r
#library(testthat)

test_that("Merge sort test", {
  merge <-function(a,b)
  {
    r <-numeric(length(a)+length(b))
    ai<-1; bi<-1; j<-1;
    for(j in 1:length(r))
    {
      if((ai<=length(a) && a[ai]<b[bi]) || bi>length(b))
      {
        r[j] <- a[ai]
        ai <- ai+1
      } else
      {
        r[j] <- b[bi]
        bi <- bi+1
      }
    }
    return(r)
  }
  merge.sort<-function(A)
  {
    if(length(A)>1)
    { q <- ceiling(length(A)/2)
    a <- merge.sort(A[1:q])
    b <- merge.sort(A[(q+1):length(A)])
    merge(a,b)
    } else return(A)
  }
  df <- asymptoticTimings(merge.sort(sample(1:100, data.sizes, replace = TRUE)), data.sizes = 10^seq(1, 3, by = 0.5))
  expect_equal(asymptoticTimeComplexityClass(df), "loglinear")
})
```
then try saving it and running `check()` (that should throw up an error or test fail as it did for me)

**Comment by gaborcsardi** [comment]
This is a bug in your package and has nothing to do with testthat. E.g. this fails without testthat:

```
foo <- function() {
  merge_sort <- function(...) Sys.sleep(.2)
  asymptoticTimings(merge_sort(), 1:10)
}
foo()
```

The problem is that you `eval()` the expression in the wrong environment. This is the common idiom to evaluate a user-supplied expression, note the added `envir` argument.

```r
asymptoticTimings <- function(e, data.sizes, max.seconds, envir = parent.frame()) {

  ...

  lang.obj <- substitute(e)
  fun.obj  <- function(data.sizes) {
    eval(lang.obj, envir = envir)
  }
...
```

**Comment by Anirban166** [comment]
> This is a bug in your package and has nothing to do with testthat. E.g. this fails without testthat:
```r
foo <- function() {
  merge_sort <- function(...) Sys.sleep(.2)
  asymptoticTimings(merge_sort(), 1:10)
}
foo()
```

Thats not the input format actually, the user-provided algorithm should be a function of the `data.sizes` parameter, such as the `merge_sort()` function above is invalid, and should be converted into a legible form, something of the order of `merge_sort(data.sizes)` (the function operate internally on some data size, say N for `merge_sort(N)`) <br> for a proper example please try this with the merge sort function provided above:
```r
asymptoticTimeComplexityClass(asymptoticTimings(merge.sort(sample(1:100, data.sizes, replace = TRUE)), data.sizes = 10^seq(1, 3, by = 0.5)))
``` 
There are quite a few factors to take note of when predicting complexity, first being the outcome of computed benchmarks being compared to a particular data size per iteration (to map the values in generalized linear models that are used internally in the complexity classifying functions), which is the reason we require the user-provided function to have data sizes as its parameter. (and larger sets of sizes are preferred for higher accuracy, as after all complexity prediction's main goal is to account for larger N or data sizes)

> The problem is that you eval() the expression in the wrong environment. This is the common idiom to evaluate a user-supplied expression, note the added envir argument:
```r
asymptoticTimings <- function(e, data.sizes, max.seconds, envir = parent.frame()) {

  ...

  lang.obj <- substitute(e)
  fun.obj  <- function(data.sizes) {
    eval(lang.obj, envir = envir)
  }
...
```

I tried that but that fails as well, reason being `data.sizes` are not accessible:
![image](https://user-images.githubusercontent.com/30123691/87052262-34458480-c21e-11ea-9d4d-cf354a095d89.png)

**Comment by gaborcsardi** [comment]
> I tried that but that fails as well, reason being data.sizes are not accessible:

Yes, if you want that, then it is more difficult to construct the right evaluation environment. This is still not a testthat problem. Your function fails inside any function, not just `test_that()`.

**Comment by Anirban166** [comment]
> > I tried that but that fails as well, reason being data.sizes are not accessible:
> 
> Yes, if you want that, then it is more difficult to construct the right evaluation environment. This is still not a testthat problem. Your function fails inside any function, not just `test_that()`.

Ah okay that makes sense now! <br>
what would you suggest with regards to constructing a right evaluation environment in such a case that I described? (although not a testthat issue)

**Comment by gaborcsardi** [comment]
> what would you suggest with regards to constructing a right evaluation environment in such a case that I described? (although not a testthat issue)

Sorry, I can't do it here, but if you post your question at https://community.rstudio.com/ you might get an answer. I would suggest to send actual code that people can run, instead of screenshots, and to point your repository.

**Comment by Anirban166** [comment]
> > what would you suggest with regards to constructing a right evaluation environment in such a case that I described? (although not a testthat issue)
> 
> Sorry, I can't do it here, but if you post your question at https://community.rstudio.com/ you might get an answer. I would suggest to send actual code that people can run, instead of screenshots, and to point your repository.

I made an account and I've posted the [question], please see if you can help me there!

**Comment by Anirban166** [comment]
> > what would you suggest with regards to constructing a right evaluation environment in such a case that I described? (although not a testthat issue)
> 
> Sorry, I can't do it here, but if you post your question at https://community.rstudio.com/ you might get an answer. I would suggest to send actual code that people can run, instead of screenshots, and to point your repository.

I made an account and I've posted the [question](https://community.rstudio.com/t/creating-local-functions-in-testthat-files-gives-rcmd-check-error/72571), please see if you can help me there!
