### ISSUE TITLE
Document special files 

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1096]
Hi, 

I read in the references ([test_dir](https://testthat.r-lib.org/reference/test_dir.html)) that there are special files that can be loaded before the tests.

This information was very interesting but I found it by chance only. I think it deserves a little article of its own.

Moreover, it was not very clear what the difference between helpers and setup is. If the only difference is the relation to `devtools::load_all()`, it might be useful to state it clearly. It might also be useful to state which one is called first and maybe give some examples of use for each one.

**Comment by hadley** [comment]
This documentation is now included in every function that you might use to writes tests: https://testthat.r-lib.org/reference/test_package.html#special-files

And I've already made a note to improve the documentation of this feature in #1042.
