### ISSUE TITLE
Consider adding a replacement for expect_known_hash() in 3e

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/testthat#1101]
In the NEWS for testthat 3e, you mention:

> expect_known_output(), expect_known_value(), expect_known_hash(), and expect_equal_to_reference() are all deprecated in favour of expect_snapshot_output() and expect_snapshot_value()

But I think one important use case is not covered by expect_snapshot_value().

I use hashes because they are a very space-efficient representation of possibly very large objects. I have several dozens of tests for functions that produce relatively large objects. If I were to use `expect_snapshot_value()`, I would very quickly go over the 5 MB limit on CRAN. I also don't think adding these files to `.Rbuildignore` would be a satisfactory solution as I want these tests to run on CRAN (with `cran = TRUE`).

A possible solution within the framework you defined for 3e would be to add `style = "hash"` as an option in `expect_snapshot_value()` and it would save the hash in the snapshot file.

**Comment by hadley** [comment]
I'm not sure I want to support this usage, because it's such a special case, and because you can still do `expect_snapshot_output(hash(your_object))`.

**Comment by hadley** [comment]
Also you can continue to use `expect_known_snapshot()` if you use the 2nd edition (which you can activate for a single test with `local_edition(2)`).
