### ISSUE TITLE
Support tests with Unicode, crayon and non-80 width

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1102]
In pillar I'm testing Unicode, color and non-standard width. Can we expose the arguments of `local_reproducible_output()` to `local_test_context()`, or export `local_reproducible_output()`?

Follow-up to #1054. Detected by checks for dev versions and bisection (because the test failure was masked by another problem): https://github.com/r-lib/pillar/actions?query=workflow%3A%22rcc+dev%22.

**Comment by gaborcsardi** [comment]
I think you can write your own `local_*` function inside the `test_that()` blocks, to switch to a different setup. You can also switch based on an env var, etc.

**Comment by krlmlr** [comment]
I'd have to do that in pillar and tibble, other packages might need to do the same. I need to write custom code to undo the breakage, where it feels much easier to expose or export.

Perhaps we can enable this only for edition 3?

**Comment by hadley** [comment]
I think exporting `local_reproducible_output()` is probably reasonable. I'm not sure how much we can back out the behaviour change to apply only to the 3rd edition given the variation in the location of the old code.
