### ISSUE TITLE
custom expectations

### ISSUE THREAD

**Issue by MyKo101** [r-lib/testthat#1106]
I'm running into a problem that I think probably has a simple solution, but this solution should probably be **made explicit in the vignette for Custom Expectation**.

When we have defined one, where do we put the code for it? Should it go in a file in the `R/` directory, in a file in the `tests/testthat/` directory, or somewhere else?

Intuitively, I originally put them in my `testthat.R` file, but that doesn't seem to be working. I also have a few other lines of code (e.g. defining dataset) that I would like to run before my tests.

**Comment by hadley** [comment]
It should usually go in `R/`.
