### ISSUE TITLE
Keep argument all for expect_warning() and expect_message() (or something similar?)

### ISSUE THREAD

**Issue by torockel** [r-lib/testthat#1109]
In some cases I liked the argument `all` from `expect_warning()` and `expect_message()` and I am rather unsure how to cure the removement in the upcoming version with multiple calls to `expect_message()/ expect_warning()` or `suppressMessages()/suppressWarnings()` (which is given as tip in the new help page). For example, sometimes I want to test, if only a warning of one type is given. This one type of warning can occur multiple times. However, I want to be sure that only this type of warning is given. 

Maybe a reprex does a better job at explaining this case than my text. A reprex for the behavior of testthat 2.3.2:
``` r
library(testthat)

fun_2_types_of_warnings <- function(later_warning = TRUE, n_warn_first = 2L) {
  for(i in seq_len(n_warn_first)) {
    warning("warning type 1")
  }
  if (later_warning) {
    warning("warning type 2")
  }
}
expect_warning(fun_2_types_of_warnings(FALSE),
               "warning type 1",
               all = TRUE)

expect_warning(fun_2_types_of_warnings(TRUE),
               "warning type 1",
               all = TRUE)
#> Error: `fun_2_types_of_warnings(TRUE)` produced unexpected warnings.
#> Expected match: warning type 1
#> Actual values:
#> * warning type 1
#> * warning type 1
#> * warning type 2
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Everything looks fine. The second ` expect_warning()` catches the unexpected “warning type 2”, as it should.

How should a test like this be done, if `all` is removed and `n_warn_first` is not that small? If we just suppress all warnings with `suppressWarnings ()`, the second type of warning will go unnoticed.  And for something like `n_warn_first = 20` we would need 20 calls to `expect_warning()`, if I understand the help page correctly. Not really encouraging. The first solution that came to my mind was:
``` r
library(testthat) # commit 9650fdd

fun_2_types_of_warnings <- function(later_warning = TRUE, n_warn_first = 2L) {
  for(i in seq_len(n_warn_first)) {
    warning("warning type 1")
  }
  if (later_warning) {
    warning("warning type 2")
  }
}

expect_silent(
  withCallingHandlers(
    expect_warning(fun_2_types_of_warnings(FALSE),
                   "warning type 1"),
    warning = function(cnd) {
      if(cnd$message == "warning type 1")
        rlang::cnd_muffle(cnd)
    }
  )
)

expect_silent(
  withCallingHandlers(
    expect_warning(fun_2_types_of_warnings(TRUE),
                   "warning type 1"),
    warning = function(cnd) {
      if(cnd$message == "warning type 1")
        rlang::cnd_muffle(cnd)
    }
  )
)
#> Error: `withCallingHandlers(...)` produced warnings.
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, I am not really happy with this solution. First, it is rather verbose. Second, the error message is uninformative. 

If I understand the news correctly, an argument `all` is not really feasible/meaningful for the new behavior of the condition catchers (only one condition at the time). However, I wanted to raise this issue just in I case I am not the only one who liked this feature.

**Comment by torockel** [comment]
PS: In general, I like the behavior of the new condition capturer to capture only one condition. At least to me, it seems much saver. For example, in testthat 2.3.2 the warning type 2 just would go unrecognized, if `all = FALSE` (the default!). This behavior is documented. But, I tend to forget this stuff. With the new version, I am forced to expect/handle every condition and this is good! Thank you very much for your hard work on testthat. 👍

**Comment by hadley** [comment]
For this case, I'd consider `expect_snapshot()` — it's not exactly the same test, but I think it's likely to be equivalent.

**Comment by hadley** [comment]
Yeah, now that I've done #1110, I'm reasonably sure that's what you need. Please give it a go and let me know if doesn't feel quite right. I really appreciate the feedback from one of the likely few people who uses `all = TRUE` 😁
