### ISSUE TITLE
Custom parallel reporter

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1111]
* Should report which files are being run in progress bar that remains at bottom of output
* Spinner runs continuously to show you that its working
* On completion of file, show summary of tests, along with any problems, and how long it took to run
* Exploring event throttling to make sure it's not adding unnecessary overhead

**Comment by gaborcsardi** [comment]
I tried event throttling in https://github.com/r-lib/testthat/tree/feature/parallel-throttling but it did not seem to make a big difference.

It seems that a simple expectation like `expect_true(TRUE)` takes longer than sending the message to the main process (on macOS), so probably that is why.

This can change if multiple processes are flooding the main process with messages, we'll see. For now, I don't think we need to merge that branch, but it is quite straightforward, and we can easily do it later, should we need it.
