### ISSUE TITLE
Graceful parallel start up and tear down

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1112]
* [x] Report error if fails to start workers
* [x] Automatically `load_all()` if working on test that?
* [x] Handle failures in the helper, startup, and teardown files.
* [x] Handle process cleanup on OSes that ps does not support.

**Comment by gaborcsardi** [comment]
For catching the startup errors, I need to improve callr, because it runs the startup in the R profile currently, and it does not catch the errors there. It should be easy.

**Comment by gaborcsardi** [comment]
OK, callr can now handle errors in the startup hook: https://github.com/r-lib/callr/pull/163

**Comment by gaborcsardi** [comment]
@hadley Do you remember what "Automatically load_all() if working on test that?" means?

**Comment by gaborcsardi** [comment]
Seems like teardown errors are always ignored currently: #1165.

**Comment by hadley** [comment]
@gaborcsardi I _think_ I was thinking about the problem where the parallel workers used installed testthat rather than dev testthat.

**Comment by gaborcsardi** [comment]
Right, that would make sense.
