### ISSUE TITLE
Best practices for using external objects

### ISSUE THREAD

**Issue by noeliarico** [r-lib/testthat#1115]
Hi,

about this code:

```
set.seed(2020)
m1 <- t(replicate(5, sample(1:10, 5)))
```

I wrote these lines into a test-foo.R. The resulting matrix is not the same when I run the two lines on the console (or the tests using `devtools::test()`) than when I run the tests using the "Run tests" button on the editor (which are the same than using the "Check" button on the "Build" window). I guess this is something related to [this](https://stackoverflow.com/questions/47199415/is-set-seed-consistent-over-different-versions-of-r-and-ubuntu/56381613#56381613). 

To avoid this problem with the random seed, I want to load the matrix from an external file. Any advise on how should I do it? I'm not sure if there are any recommendations or good practices about this. Some of my ideas are:

a) Copying the results of `dput(m1)` in a file and them make the tests source that file
b) Create a .RData file containing the matrix and then load it in `test-foo.R`

Tanks in advance!
Noelia

**Comment by hadley** [comment]
For this case, I think `dput()` would be your best bet. As a general principle, you want your tests to be as simple and self-contained as possible.
