### ISSUE TITLE
Use enquo() in test_that() and eval_tidy() in test_code()

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#1124]
This would make it easier to write wrappers around `test_that()` for running multiple similar tests with different descriptions

This linked issue suggested that there was going to be an attempt to do exactly this, but it didn't happen for some reason.
https://github.com/r-lib/testthat/issues/626

As a quick example, in furrr I run the same test over various parallel strategies and over multiple sets of cores. I want the `test_that()` `desc` to be informative about what combination fails. I've come up with the following solution, where the commented lines are what I actually do, but it would be cool to be able to unquote in `test_that()` directly.

<details>

```r
furrr_test_that <- function(desc, code) {
  test_code <- enquo(code)

  # Ensure that we reset to sequential plan even on error to
  # close any straggler processes
  on.exit(plan(sequential), add = TRUE)

  for (strategy in supported_strategies()) {
    for (cores in seq2(1L, supported_max_cores(strategy))) {
      if (identical(strategy, "sequential")) {
        plan(strategy)
      } else {
        plan(strategy, workers = cores)
      }

      test_desc <- paste0(desc, " / strategy - ", strategy, " / cores - ", cores)
      #test_expr <- expr(test_that(!!test_desc, !!test_code))

      #eval_tidy(test_expr)
      
      # Would be cool to just do this
      test_that(test_desc, !!test_code)
    }
  }
}
```

</details>

**Comment by hadley** [comment]
I looked into the minimal possible change, and it caused tests like this to break:

```R
test_that("default labels use unquoting", {
  x <- 2
  expect_failure(expect_equal(1, !! x), "1 not equal to 2", fixed = TRUE)
})
```

(presumably because unquoting happened too early).

I think that means you'll need to stick with your explicit strategy.
