### ISSUE TITLE
plural version of capture_condition()

### ISSUE THREAD

**Issue by damianooldoni** [r-lib/testthat#1126]
I was just working with `capture_warning()` and `capture_message()` and I found useful to have the correspondent plural versions, `capture_warnings()` and `capture_messages()`. I would find very useful to have `capture_conditions()` too. What do you think about it? Thanks in advance for the fantastic work :clap:

**Comment by hadley** [comment]
I no longer think these really belong in testthat. I totally agree that they’re useful (and I wanted myself a couple of weeks ago) but testthat doesn’t seem like the right place for them.
