### ISSUE TITLE
Confirm local_edition() is fully functional

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1129]
In my hands, `local_edition()` doesn't seem to work as widely as promised (emphasis mine):

>` local_edition()` allows you to temporarily (within a single test or a **single test file**) change the active edition of testthat.

Specifically, I only get its effect *inside* a test.

I don't know how to reconcile what I'm seeing with what I see in this vignette: https://testthat.r-lib.org/articles/third-edition.html, where `local_edition()` *appears* to have the documented scope. But maybe some global option is also in effect when that vignette is rendered.

``` r
library(testthat)

packageVersion("testthat")
#> [1] '2.99.0.9000'

# something's definitely happening!
local_edition(3)
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `deferred_run()`.
#>   * Clear (without executing) with `deferred_clear()`.

# I'm still getting "old" testthat behaviour, i.e. no waldo
expect_equal(structure("good", class = "foofy"), "good")
#> Error: structure("good", class = "foofy") not equal to "good".
#> Attributes: < Modes: list, NULL >
#> Attributes: < Lengths: 1, 0 >
#> Attributes: < names for target but not for current >
#> Attributes: < current is not list-like >
#> target is foofy, current is character

# I'm still getting "old" testthat behaviour, i.e. no waldo
test_that("I understand how to wield local_edition()", {
  expect_equal(structure("good", class = "foofy"), "good")  
})
#> ── <text>:13:3: failure: I understand how to wield local_edition() ───────────────────
#> structure("good", class = "foofy") not equal to "good".
#> Attributes: < Modes: list, NULL >
#> Attributes: < Lengths: 1, 0 >
#> Attributes: < names for target but not for current >
#> Attributes: < current is not list-like >
#> target is foofy, current is character

# NOW I get 3e behaviour, i.e. waldo comparison
test_that("I understand how to wield local_edition()", {
  local_edition(3)
  expect_equal(structure("good", class = "foofy"), "good")  
})
#> ── <text>:19:3: failure: I understand how to wield local_edition() ───────────────────
#> structure("good", class = "foofy") (`actual`) not equal to "good" (`expected`).
#> 
#> `actual` is an S3 object of class <foofy>
#> `expected` is a character vector ('good')
```

<sup>Created on 2020-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Possibly related — https://github.com/r-lib/testthat/pull/1121/files#diff-0c8cbe8fac595d97e4c3798e25c341a0

**Comment by hadley** [comment]
This now works for me outside of `reprex()` (but not inside). Was that always the case?

**Comment by hadley** [comment]
Minimal reprex for reprex issue:

``` r
library(testthat)
local_edition(3)
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `deferred_run()`.
#>   * Clear (without executing) with `deferred_clear()`.
testthat:::edition_get()
#> [1] 2
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Hmmm, the reprex issue is possibly a defer issue:

``` r
withr::defer(print("Bye"))
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `deferred_run()`.
#>   * Clear (without executing) with `deferred_clear()`.
#> [1] "Bye"
print("Hi")
#> [1] "Hi"
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jennybc** [comment]
It may be relevant that `reprex_render()` explicitly evaluates in the global environment. This is due to S3 registration issues.

https://github.com/tidyverse/reprex/blob/d3fc4b8bedeb9622b9941faa073ee65b3ebd7dbb/R/reprex_render.R#L97

**Comment by jennybc** [comment]
> This now works for me outside of `reprex()` (but not inside). Was that always the case?

I sort of thought I saw this in general? But that could be wrong. And I definitely see what you see right now, i.e. problem appears to be limited to inside `reprex()`.

**Comment by jennybc** [comment]
I think it **is** due to how `reprex_render()` works. The local edition stuff works as advertised if I allow the default `rmarkdown::render(..., envir = parent.frame(), ...)` to happen.

**Comment by hadley** [comment]
I think I probably fixed the general problem in https://github.com/r-lib/testthat/pull/1121/files#diff-0c8cbe8fac595d97e4c3798e25c341a0

**Comment by jennybc** [comment]
I still see the problem.

``` r
library(testthat)

packageVersion("testthat")
#> [1] '2.99.0.9000'

edition_get()
#> [1] 2

local_edition(3)
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `withr::deferred_run()`.
#>   * Clear (without executing) with `withr::deferred_clear()`.

edition_get()
#> [1] 2

withr::deferred_run()

edition_get()
#> [1] 2
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Right, but it's now a reprex/withr problem right? I don't see what testthat could be doing differently here.
