### ISSUE TITLE
Typo in snapshot.R

### ISSUE THREAD

**Issue by tanho63** [r-lib/testthat#1133]
Noticed a typo in Hadley's webinar and wondered if you guys had caught this yet: 

https://github.com/r-lib/testthat/blob/9e643d8ee9772c58d5a6bf0846e16bf78dde59f9/R/snapshot.R#L189

says "shapshot" instead of "snapshot"?

**Comment by hadley** [comment]
I had to read your comment like 3 times before I spotted the problem 😆 Thanks for reporting!

**Comment by david-barnett** [comment]
i think the "Shapshot" is still lurking here in snapshot-file

https://github.com/r-lib/testthat/blob/47935141d430e002070a95dd8af6dbf70def0994/R/snapshot-file.R#L76
