### ISSUE TITLE
Export `get_edition()`?

### ISSUE THREAD

**Issue by jonkeane** [r-lib/testthat#1137]
I'm really excited for the new release of testthat, and all of the great enhancements of the third edition.

Would you be opposed to a PR that exported `get_edition()` for use by other packages? I'm working on making sure my testing package is compatible with both versions, and being able to detect and condition on which version was (currently) running would be awesome.

**Comment by hadley** [comment]
Can you please give me an example of how you'd use this? You're in control of which edition you're using, so I can't quite see why you'd need to get the current value.

**Comment by jonkeane** [comment]
Yeah, absolutely. First, I will absolutely admit that the package I'm working on is a bit unique in that it's designed to be used as a test framework itself alongside test that so I want to make sure that it works without surprises for both testtaht 2e and 3e. 

The way I've started doing this is to run my tests with both 2e and 3e to ensure that my code is compatible with both editions. For the most part all of my tests run just fine with 2e and 3e and I can run my whole test suite with both, but there are a small handful of the breaking changes that I need to have two tests for. So I would like to be able to do something like:

```
if (get_edition() < 3) {
  expect_message(add_dittodb_to_helper(f), "Creating")
} else {
 expect_message(expect_message(add_dittodb_to_helper(f), "Creating"), "Adding library")
}
```

And then I could run the whole set of tests with both 2e and 3e ensuring my package is compatible with both.

**Comment by hadley** [comment]
Makes sense 😄

**Comment by jonkeane** [comment]
Awesome, thanks! I did notice that I made the dyslexic slip in naming this issue and describing it, it looks like the code, namespace export, etc. all have `edition_get()` but I called it `get_edition()`. I also sent in #1148 to fix up the docs to match everywhere else.
