### ISSUE TITLE
Account for execution while `knitr.in.progress`

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1138]
![Screen Shot 2020-08-14 at 3 54 48 PM](https://user-images.githubusercontent.com/599454/90320235-3f15c800-def4-11ea-94ef-16f42218997d.png)

I call `devtools::test()` on a toy package in R Packages and the above is how it looks. It seem like the progress-related effects should be suppressed when tests are being run non-interactively or, more, specifically, when `knitr.in.progress`.

**Comment by hadley** [comment]
This is a bit of a special case (since we don't generally expect people to be running the interactive progress reporter in Rmds), so you'll also have to do `options("testthat.default_reporter" = ProgressReporter$new(update_interval = Inf))` somewhere in the setup.
