### ISSUE TITLE
Faster parallel startup

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#1139]
Parallel startup is really slow currently. It includes
* starting the R process
* loading testthat
* loading the tested package + helpers
* running setup files

For 4 processes this takes ~ 2.5 seconds for testthat. For a better interactive performance we could keep the sub-processes alive if the session is interactive.

**Comment by gaborcsardi** [comment]
Here is a quick try that keeps the queue. It has 4 processes and 4 test files that just sleep for 1 second:

```
❯ system.time(testthat::test_local(filter = "throttle"))
✔ |  OK F W S | Context
✔ |   1       | parallel-throttle-1
✔ |   1       | parallel-throttle-2
✔ |   1       | parallel-throttle-3
✔ |   1       | parallel-throttle-4

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 3.7 s

[ PASS x4 FAIL x0 WARN x0 SKIP x0 ]
   user  system elapsed
  0.189   0.050   3.863

❯ system.time(testthat::test_local(filter = "throttle"))
✔ |  OK F W S | Context
✔ |   1       | parallel-throttle-1
✔ |   1       | parallel-throttle-2
✔ |   1       | parallel-throttle-3
✔ |   1       | parallel-throttle-4

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 1.2 s

[ PASS x4 FAIL x0 WARN x0 SKIP x0 ]
   user  system elapsed
  0.080   0.004   1.286
```

**Comment by hadley** [comment]
The only problem is that it won't work with the usual invocation of `devtools::test()` since RStudio runs it in a separate process.

**Comment by gaborcsardi** [comment]
Yeah, I think we can close this for now, and come back to it later.
