### ISSUE TITLE
expect_error reports a failure when expected message and actual message are the same

### ISSUE THREAD

**Issue by ksvanhorn** [r-lib/testthat#1142]
I have a test suite that includes the following:

```
test_that("new_observations() checks that endDate + 1 is in history", {
  endDate <- as.Date('2019-10-30')
  dfhist <- data.frame(dates=as.Date('2019-11-01'), values=100)
  err <- expect_error(new_observations(endDate, dfhist), "history must include endDate + 1")
})

```
When I run the test, I get this failure:

```
test-models.R:145: failure: new_observations() checks that endDate + 1 is in history
`new_observations(endDate, dfhist)` threw an error with unexpected message.
Expected match: "history must include endDate + 1"
Actual message: "history must include endDate + 1"
Backtrace:
 1. testthat::expect_error(new_observations(endDate, dfhist), "history must include endDate + 1") tests/testthat/test-models.R:145:2
 6. LoadForecasting::new_observations(endDate, dfhist)
 7. LoadForecasting::assert((endDate + 1) %in% dfhistory$dates, "history must include endDate + 1") R/models.R:51:2

```

As you can see, the "expected match" and "actual message" are the same.

This is with testthat version 2.3.2.

**Comment by gaborcsardi** [comment]
The expected match is a regular expression by default, you need `fixed = TRUE`:

```r
❯ testthat::expect_error(stop("this+1"), "this+1")
Error: `stop("this+1")` threw an error with unexpected message.
Expected match: "this+1"
Actual message: "this+1"

❯ testthat::expect_error(stop("this+1"), "this+1", fixed = TRUE)
```

**Comment by ksvanhorn** [comment]
Oh, missed that. Thanks. An improved failure message would be very useful here.

**Comment by gaborcsardi** [comment]
Yeah, maybe just 
```
Expected regexp: "this+1"
Actual message:  "this+1"
```

**Comment by hadley** [comment]
With the new condition handling in 3.0.0, the error now bubbles up:

``` r
testthat::expect_error(stop("this+1"), "this+1")
#> Error in eval_bare(quo_get_expr(.quo), quo_get_env(.quo)): this+1
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by gaborcsardi** [comment]
> With the new condition handling in 3.0.0, the error now bubbles up:

I think the issue is that `expect_error()` uses a regexp by default, and if you know that, the expectation failure is not very informative. Does the new error help with that?

**Comment by hadley** [comment]
No, because you just get the regular error; there's now no place to put any extra messaging.

**Comment by gaborcsardi** [comment]
Not to beat a dead horse, but, if there is no error class, then we must catch the error to check the message, and then re-throw it if it does not match, so in theory we could stick some extra message in the error object. E.g. if the message does not match as regex, but would match as fixed text? 

I admit, this is a bit wonky. OTOH, I think this is common mistake with `expect_error()`, and the current error is not helpful at all.

**Comment by hadley** [comment]
We're not technically rethrowing for complicated reasons, so this is more complicated than you'd probably expect.

**Comment by gaborcsardi** [comment]
OK, I am off the horse then. :)
