### ISSUE TITLE
Testthat errors out with 'no item called "imports" on the search list'

### ISSUE THREAD

**Issue by torfason** [r-lib/testthat#1144]
In preparation for a new release of the `import` package (see [here](https://github.com/smbache/import)), I have been adding unit tests through testthat. However, although the tests work when sourced interactively (or through `reprex::reprex()`), they fail when run through `devtools::test()`.

The error message is  `no item called "imports" on the search list` (`imports` is the name of the environment into which the functions are being imported), so I'm guessing that the creation of the environment (search list entry) is failing.

I realize that it is not obvious that a test should be able to create a search list entry in a protected environment such as the testthat tests. And in fact, I've jerry-rigged an alternative test harness that starts up an `Rscript` process to run each of the unit test files. I then use `expect_match()` in the main process to check if the Rscript proces got through the file without any issues. Clunky, but this actually works fine locally (both on MacOS and Windows), but on GitHub Actions (Windows only), that approach fails for strange reasons and this is precluding CI from running the unit tests on Windows.

So, I'm really hoping that there is a setting or other way to do the tests inside the testthat environment, instead starting a new process, because this `Rscript` workaround is probably always going to be quite fragile.

Below is a (hopefully reproducible) demonstration of this issue. 

First a how this works outside `devtools::test()` (this is an actual `reprex::reprex()`, but no output was expected, just that it runs without error):
``` r
library(testthat)
context("Demonstration of search list issue")
test_that("Basic import works", {
  expect_silent( import::from(dplyr, select) )
})
```

Then the results of a running `devtools::test()` with a file containing the above text in the `testthat` directory.

```
==> devtools::test()

Loading import
The import package should not be attached.
Use "colon syntax" instead, e.g. import::from, or import:::from.
Testing import
✓ |  OK F W S | Context
x |   0 1     | Demonstration of search list issue [0.3 s]
─────────────────────────────────────────────────────────────────────────────────────────────────────────
test_import.R:9: error: Basic import works
no item called "imports" on the search list
Backtrace:
  1. testthat::expect_silent(import::from(dplyr, select)) tests/testthat/test_import.R:9:2
  9. import::from(dplyr, select)
 10. base::exists("?", into, mode = "function", inherits = FALSE) R/from.R:224:2
```

**Comment by hadley** [comment]
I think the only way we could look into this is if you could create a reprex that illustrates the problem without using import. This test, which attaches an environment to the search path works fine for me (inside and outside of `test())`:

```R
test_that("can attach to search path", {
  e <- new.env()
  e$a <- 1
  attach(e, name = "test_env")
  on.exit(detach("test_env"))

  expect_true("test_env" %in% search())
  expect_equal(a, 1)
})
```

**Comment by igelstorm** [comment]
Sorry to comment on a closed issue, but @torfason, I was wondering if you managed to work out what caused this error? I'm now getting the same error when using `devtools::load_all()` inside a package that uses `import::from` in some source files:

```
> devtools::load_all()
Loading nameofproject
Error in as.environment(where) : 
  no item called "imports" on the search list
```

Sourcing each file on its own doesn't error – it seems to be something about using `import` via `devtools`, maybe. This issue is the only thing that comes up on a Google search for this error, and `devtools` seems to be involved here as well, so I thought it might be related to what you were experiencing?

I'd be happy to try to put together a reprex and post it as an issue in [rticulate/import](https://github.com/rticulate/import) – I just thought I would ask here first!

**Comment by torfason** [comment]
Probably best to post an issue on [rticulate/import](https://github.com/rticulate/import) (I'm involved with that package, so I'll take a look at it there). It looks like it has to do with the sequence of attached and detached namespaces. Note the guidelines incorporated with the new release, it is advised to not use `import::from()` in a "recursive" scenario but to use `import::here()` instead. It could be that this is what is happening issue is fixable in that way. But we can continue discussions over there.
