### ISSUE TITLE
Check failures possibly related to tolerance

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1150]
## jsonlite

      `x` not equal to `expected`.
      3/4 mismatches (average diff: 0.000586 secs)
      [1] 2020-08-25 22:33:12 - 2020-08-25 22:33:12 == -0.000586 secs
      [2] 2020-08-25 22:33:13 - 2020-08-25 22:33:13 == -0.000586 secs
      [4] 2020-08-25 22:33:14 - 2020-08-25 22:33:14 == -0.000586 secs

``` r
x <- y <- Sys.time()
y[[1]] <- as.integer(y)
all.equal(x, y)
#> [1] "Mean absolute difference: 0.8276219"

testthat::compare(x, y)
#> 1/1 mismatches
#> [1] 2020-08-26 07:36:16 - 2020-08-26 07:36:16 == 0.828 secs
testthat::expect_equal(x, y)
#> Error: `x` not equal to `y`.
#> 1/1 mismatches
#> [1] 2020-08-26 07:36:16 - 2020-08-26 07:36:16 == 0.828 secs
```

Was this previously rounding?

## gluedown

```
Error: unused argument (tolerance = tolerance)
Backtrace:
     █
  1. └─md_disallow(a) %>% expect_equal(b) test-6.11-disallow-raw-html.R:10:2
  2.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       └─gluedown:::`_fseq`(`_lhs`)
  6.         └─magrittr::freduce(value, `_function_list`)
  7.           ├─base::withVisible(function_list[[k]](value))
  8.           └─function_list[[k]](value)
  9.             └─testthat::expect_equal(., b)
 10.               └─testthat::compare(act$val, exp$val, ..., tolerance = tolerance)
```

https://github.com/kiernann/gluedown/blob/master/tests/testthat/test-6.11-disallow-raw-html.R#L36

Probably related to glue's compare method

**Comment by hadley** [comment]
## abdiv

```
── Failure: Alpha diversity values are consistent with QIIME2 tests (test-alpha.
invsimpson(x_enspie1) not equal to 2.25.
1/1 mismatches
[1] 2.25 - 2.25 == 0.000125
```

Others: fundata, investr, LambertW, lavaSearch2, mashr, MittagLeffleR, Morpho, msm, and many more

**Comment by jeroen** [comment]
Here is a smaller reprex that shows the case of jsonlite. We see that `expect_equal` fails even though `compare` does not.

```r
# negligible difference: less than 1ms
x <- structure(1598527669.80042, class = c("POSIXct", "POSIXt"))
y <- structure(1598527669.80000, class = c("POSIXct", "POSIXt"))
testthat::compare(x,y) # Equal
testthat::expect_equal(x,y) # Fails in new testthat
```

I think the problem is that `expect_equal` is now unconditionally passing a `tolerance` to the `compare` method, which is a much lower tolerance than the default for `compare.POSIXt`.
