### ISSUE TITLE
Differences when running parallel tests in console vs RStudio build pane

### ISSUE THREAD

**Issue by pat-s** [r-lib/testthat#1158]
When running `devtools::test()` directly in the console, I get

```r
Error in default_num_cpus() : `getOption(Ncpus)` must be integer
Backtrace:
1: stop("`getOption(Ncpus)` must be integer")
2: default_num_cpus()
3: test_files(test_dir = test_dir, test_package = test_package, 
4: test_files(test_dir = path, test_paths = test_paths, test_package = package, 
5: (function (path, filter = NULL, reporter = NULL, env = NULL, 
6: do.call(testthat::test_dir, testthat_args)
7: force(code)
8: withr::with_envvar(c(r_env_vars(), TESTTHAT_PKG = pkg$package), 
9: force(code)
10: withr::with_options(c(useFancyQuotes = FALSE), withr::with_envvar(c(r_env_vars(), 
11: force(code)
12: withr::with_collate("C", withr::with_options(c(useFancyQuotes = FALSE), 
13: devtools::test()
```

despite having both option `Ncpus` and env var `TESTTHAT_MAX_CPUS` set.
Running the same command via the build pane trigger "test package" (cmd+shift+T) works.

**Comment by gaborcsardi** [comment]
So what is `getOption(Ncpus)` then?

**Comment by pat-s** [comment]
```r
getOption("Ncpus")
[1] 10
```

Set in my `.Rprofile`.
(Also note that the error message is missing quotes around `Ncpus`.)

However, when creating a reprex, it seems that this option is not respected for some reason.

Anyways, in an active R session with this option set, I get the error above - but only in the console.

**Comment by gaborcsardi** [comment]
Are you sure that it is an integer? Set it to an integer:
```r
options(Ncpus = 10L)
```

I guess we should accept double values as well.

**Comment by pat-s** [comment]
Thanks, that was it! I assume the build pane invocation infers the number of process in the background and hence it works there?

(silly me ;) )

**Comment by gaborcsardi** [comment]
The build pane runs in a subprocess, and for some reason it does not have the option set. I don't know why, maybe it does not load `.Rprofile`, or your setup is such.
