### ISSUE TITLE
Parallel: in some instances no tests are being executed

### ISSUE THREAD

**Issue by pat-s** [r-lib/testthat#1159]
In some packages of mine, no tests are being executed when setting `Config/testthat/parallel: true`.

I see the processes starting and then get a quick return with no tests in the summary:

```r
Starting 8 test processes
✓ |  OK F W S | Context
                                                                                             
══ Results ══════════════════════════════════════════════════════════════════════════════════
Duration: 18.4 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
```

Running sequentially is fine.

This happens when executing `devtools::test()` via the "Build" pane in RStudio.
Currently parallel testing does not work for me in the console at all, hence no reprex (see #1158).

**Comment by gaborcsardi** [comment]
This will be fixed when #1112 is fixed.
