### ISSUE TITLE
extra 'Done!' printed after result summary when running single test file

### ISSUE THREAD

**Issue by kevinushey** [r-lib/testthat#1169]
When clicking the 'Run Test' button for a test file, I see the following output:

<img width="644" alt="Screen Shot 2020-09-02 at 10 52 50 AM" src="https://user-images.githubusercontent.com/1976582/92018780-72d15a00-ed0a-11ea-9863-b492720ba099.png">

Note the extra `Done!` following the summary output -- is that expected? If so, then it may just be an RStudio issue (perhaps it's no longer necessary for RStudio to write 'Test complete' after running tests)

(This also shows the overflowing-rule issue described in https://github.com/r-lib/testthat/issues/1168)

**Comment by hadley** [comment]
Yeah, either RStudio shouldn't display "test complete" or the CompactProgressReporter should detect this scenario and not print `Done!`.

It would be nice if the whole thing looked more like:

```
==> Testing test-python.output.R
Loading reticulate
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 5]
Test complete
```

**Comment by hadley** [comment]
I think I've done everything I can from the testthat side. Now RStudio just needs something like:

```R
if (packageVersion("testthat") >= "2.99") {
  test_file(path, CompactProgressReporter$new(rstudio = TRUE))
} else {
  test_file(path)
}
```
