### ISSUE TITLE
Cannot library(tidyr) when using testthat::test_file

### ISSUE THREAD

**Issue by tbrown122387** [r-lib/testthat#1171]
Inside a [function](https://github.com/tbrown122387/gradeR/blob/47a6efdcd7e73779606c13ee17b78a8adb32a74e/R/grade.r#L192) I am 

- creating a new environment (call it `testEnv`),
- `source`ing some script (call it `code.R`) and storing the results in this new environment, and
- calling `testthat::test_file` with the argument `env = new.env(parent = testEnv))` to evaluate some tests found in a file (call it `test_file.R`).

This has always worked just fine. But the problems started once I attach `tidyr` inside `code.R`, or in other words, when I insert the line 

```
library(tidyr)
```

into `code.R`. When I add this one line, all the tests that used to be pass now fail. When I ssh into the server, when I am running `R` interactively, I can `library(tidyr)` just fine. So I think that the script is being sourced just fine, and it's `test_file` that's not able to find the variables that were sourced in.

My questions are:

1. why is this happening,
2. even though I think I am running the tests **after** I source `code.R`, could calling `library(tidyr)` in `code.R` cause `testthat::matches` to be masked by masked by `tidyr::matches` to be masked, and
3. if so, why would that matter, and 
4. does this have anything to do with the following sentence found in the documentation to `test_file`: "[y]ou are responsible for ensuring that the functions to test are available in the global environment."
 
I have tried removing `library(testthat)` from `test_file.R`, and instead prefixing all the function calls with `testthat::` but the same problem occurs.

**Comment by hadley** [comment]
I didn't analyse your code deeply, but I doubt `testEnv <- new.env()` is the right environment — that creates an environment that inherits from the current environment, which will have parents up via the NAMESPACE of your package. I suspect you want something more like `testEnv <- new.env(parent = globalenv())`.

**Comment by tbrown122387** [comment]
@hadley unfortunately that didn't work. Might this have to do with how `library(testthat)` is called in the first line of `testthat::test_file`?

**Comment by hadley** [comment]
It's more likely to be how your custom evaluation interacts with the search path. I think it's unlikely that there's much testthat can do here.
