### ISSUE TITLE
Loaded functions overriding helper-data variables with same name

### ISSUE THREAD

**Issue by andrewmarx** [r-lib/testthat#1173]
If a variable in the helper-data.R file has the same name as a loaded function, the function is used instead of the variable while running tests. For a simple repro, create the following two files in a testthat directory:

_helper-data.R_
```
abs = 1:5
something_else = 5:1
```

_test-repro.R_
```
str(abs)
str(something_else)
```

_output from devtools::test()_
```
function (x)  
 int [1:5] 5 4 3 2 1
```

This issue only started happening when I built a new computer and installed R version 4. Currently have the latest version of testthat installed (2.4.2). On my old computer with R 3.6, it was not an issue, but I also probably had an older version of testthat installed, so I don't know if the change in behavior originated with R or the testthat package.

**Comment by hadley** [comment]
Unfortunately, I can't reproduce that behaviour, and it'd pretty surprising to me if testthat was responsible for it. I'd recommend creating a reprex — I suspect in that process you'll discover what's going wrong in your package.
