### ISSUE TITLE
Fix teardown test case when running in parallel

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#1174]
`test-teardown-2` might be running slightly before `test-teardown-1`.

**Comment by gaborcsardi** [comment]
Two ways to fix this. One is to use a dummy package with, and run `test_local()` or `test_dir()` on it. 

The order is to run `test-teardown-1.R` as the first test, and then it will surely run before `test-teardown-2.R`.

**Comment by hadley** [comment]
Maybe put this in its own file:

```R
local_edition(2)
setup(write_lines("test", "teardown.txt"))
teardown(file.remove("teardown.txt"))

test_that("file is created", {
  expect_true(file.exists("teardown.txt"))
})
```

Then the actual test would  be:

```R
test_that("teardown run at end of each file", {
  test_file("otherfile.R", "silent")
  expect_false(file.exists("teardown.txt"))
})
```

**Comment by hadley** [comment]
I think that does a better job of expressing the intent of the test, rather than relying on the tests being run in a specific order.

**Comment by gaborcsardi** [comment]
Yeah, I agree.
