### ISSUE TITLE
Expect_snapshot_file() hint is not very helpful in R CMD check

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1179]
Because when such a test fails in R CMD check, one cannot run snapshot_review()?

**Comment by maelle** [comment]
In one particular case, I had to open an artefact from GitHub Actions to see what had changed* -- I wonder whether that's too niche for adding one line or too to the snapshotting vignette. 

*: And realize I had to add a repo secret for that one thing.

**Comment by hadley** [comment]
Downloading the artefact is very much what I expect you should do, so is probably worth a sentence or two.

**Comment by maelle** [comment]
And could the hint depend on whether the test is run in `test()` vs `check()`?

* in `test()`, "run snapshot_review()"
* in `check()`, "locate the check artefact" (and compare files by hand/with your usual tools)

**Comment by hadley** [comment]
I like that idea, although off the top of my head I'm not sure how to tell if you're running inside R CMD check. 

Maybe there's actually three cases:

* Running tests interactively where you can use `snapshot_review()`
* Running R CMD check locally where you just need to look in the check directory
* Running R CMD check on ci where you'll need to download the artifact

?

**Comment by gaborcsardi** [comment]
> I like that idea, although off the top of my head I'm not sure how to tell if you're running inside R CMD check.


```
Sys.getenv("_R_CHECK_PACKAGE_NAME_", "") != ""
```

IDK how fragile this is...

**Comment by hadley** [comment]
That's probably fine; it's not a big deal if it gives the wrong result, as you'll just get an unhelpful hint.

**Comment by maelle** [comment]
Should I make a PR (tweaking the hint, adding a few lines about debugging/reviewing to the vignette)?

Reg GitHub Actions, since discovering one can add Markdown reports/images in "checks", I have been wondering what use cases there could be, and with snapshots I'd love to see a Markdown report of the diff between snapshots, but it's a bit too much effort compared to the ease of downloading artefacts :-) https://docs.github.com/en/rest/reference/checks#runs

**Comment by maelle** [comment]
Another note, the first hint should be "Run `testthat::snapshot_review('create_registry')` to review changes" i.e. namespaced, which makes it easier to copy-paste from RStudio build pane to RStudio console (as I was doing right now :grin:).
