### ISSUE TITLE
R6 classes with mocked functions support

### ISSUE THREAD

**Issue by aalucaci** [r-lib/testthat#1185]
Hello,
according to

[testthat 3rd edition](https://testthat.r-lib.org/articles/third-edition.html)

`testthat::with_mock` will be deprecated. While I'm looking forward to this edition, I have difficulties in replacing `testthat::with_mock`.
I could not find a way to mock external functions in R6 methods which are called via expressions. `mockery` claims that one can mock external functions in R6 methods, but this seems to me to work only if the external functions are called directly.
As you can see in the example below, this works with `testthat::with_mock`.

```
external_function <- function() {
  message("this is the external_function")
}

A <- R6::R6Class(
  classname = "A",
  public = list(
    initialize = function() {
      message("initialize")
    }

    , run1 = function() {
      message(external_function())
    }

    , run2 = function(expr) {
      eval(expr)
    }

    , run3 = function(expr) {
      withCallingHandlers(
        expr = expr,
        error = function(e) {
          message(e$message)
        },
        warning = function(w) {
          message(w)
        }
      )
    }

  )
)

obj <- A$new()
obj$run1() #this is the external_function

m <- mockery::mock("this is the mock")
obj <- A$new()
mockery::stub(
  where = obj$run1,
  what = "external_function",
  how = m
)
obj$run1() #this is the mock

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
obj$run2(print(external_function())) #this is the external function

mockery::stub(
  where = obj$run2,
  what = "external_function",
  how = m
)
obj$run2(print(external_function())) #this is the external function <<-- NOT MOCKED
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

obj$run3(print(external_function())) #this is the external function

mockery::stub(
  where = obj$run3,
  what = "external_function",
  how = m
)
obj$run3(print(external_function())) #this is the external function <<-- NOT MOCKED

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
m2 <- mockery::mock("this is the mock")
testthat::with_mock(
  external_function = m2,
  obj$run3(print(external_function()))  #this is the mocked <<- OK
)
```

Can you give a hint what to do in this case?
Or should I rather contact the developers of the `mockery` package?

My first naive expectation was that replacing `testthat::with_mock` should be easy, but as usual, the devil is in the detail. Or did I miss an obvious way to do this?

Thank you in advance for your time,
Angela

**Comment by hadley** [comment]
Why are you mocking R6 classes? I'd think it would be easier to create a subclass.

**Comment by aalucaci** [comment]
Hello,
I'm not sure that creating a subclass for each test I want to make is feasible. Or maybe I misunderstand what you mean?

To clarify, let's assume my class does some complicated calculations based on an input. And I want to test its behaviour based on different inputs (e.g. input data does not exist, or the input data does not fulfil some conditions, etc). 

With `testthat::test_mock`, this is straightforward, as in my example above. Creating a class which inherits from my class, but overwrites the function that retrieves the inputs is of course doable, but is definitely more work, and requires rewriting existing  tests, so this would rather be a breaking change for me.

I understand that upgrading to a newer version sometimes requires more work, I just wanted to ask if there is a more straightforward solution which I might have missed.

Kind regards,
Angela

**Comment by hadley** [comment]
Sorry I missed that it's an external function, not a method of the object. In that case, I think mocking makes sense, and you'll need to file a bug with the mockery package in order to support this use case with R6 objects.
