### ISSUE TITLE
Set _R_CHECK_LENGTH_1_CONDITION_  and _R_CHECK_LENGTH_1_LOGIC2_ environment variables to "warn"

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1195]
in edition 3?

These help detect non-scalar values in conditions and `&&` and `||` : https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools . These errors also seem to be caught by `R CMD check`, setting these variables here would give earlier feedback.

**Comment by hadley** [comment]
Doesn't feel like this belongs in testthat to me. Would we also warn on partial args etc? Not sure where this would stop. I think it's better to recommend that people put these settings in their `.Rprofile`. Or have some package (e.g. https://github.com/hadley/strict) that turns all the needful settings on.
