### ISSUE TITLE
Set a distinct environment variable in verify_output()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1196]
Use case: I don't want downstream packages to rely on tibble's output, because it's subject to change. I'd like the `format.tbl_df()` method (and `trunc_mat()`) to emit `<output created by the tibble package>` in regular tests (if the `TESTTHAT` environment variable is set). I'm fine with the full output in `verify_output()`, because it allows to preview the output and is ignored on CRAN.

Suggesting to either unset the `TESTTHAT` environment variable in `verify_output()`, or to set a new `TESTTHAT_OUTPUT` environment variable.

**Comment by hadley** [comment]
This doesn't feel like the right approach to me, especially given that `verify_output()` is superseded in favour of snapshot tests.
