### ISSUE TITLE
expect_equal(25.6, 24,6) passes

### ISSUE THREAD

**Issue by hamstr147** [r-lib/testthat#1201]
I noticed something weird with `expect_equal` - I made a typo (used a comma rather than period separator for a decimal point) and found something like `expect_equal(25.6, 24,6)` just passes without throwing an error. I'm using v2.3.2 on macOS, R version 4.0.2  and was running my tests interactively .

**Comment by gaborcsardi** [comment]
Yes, testthat 2.3.2 just calls `base::all.equal()` and the third argument is the tolerance:
```r
❯ all.equal(25.6, 24,6)
[1] TRUE
```

In testthat 3e this will fail:
```r
❯ testthat::local_edition(3)
❯ testthat::expect_equal(25.6, 24,6)
Error: 25.6 (`actual`) not equal to 24 (`expected`).

  `actual`: 26
`expected`: 24
```
