### ISSUE TITLE
auto_test_package() stops on failure

### ISSUE THREAD

**Issue by mbojan** [r-lib/testthat#1214]
`auto_test_package()` calls `test_dir()` which uses `stop_on_failure = TRUE` by default. The function exits in case of errors while it should not but keep monitoring the source tree.

**Comment by mbojan** [comment]
Would you like a separate PR or append #1212 ?

**Comment by hadley** [comment]
Just append please.

**Comment by mbojan** [comment]
Appended. This can be closed as soon as #1212 is merged.
