### ISSUE TITLE
test_dir() not working in parallel

### ISSUE THREAD

**Issue by mllg** [r-lib/testthat#1216]
Steps to reproduce:

Install `testthat` and run `testthat::test_dir("tests/testthat")` in the package root.

```
> testthat::test_dir("tests/testthat")
Starting 4 test processes
✔ |  OK F W S | Context
⠇ [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ] Starting up...

Error: testthat subprocess failed to start, stderr:
Error in getNamespace(ns) : attempt to use zero-length variable name
Calls: callr_startup_hook ... get_env_retired -> is_environment -> asNamespace -> getNamespace

Backtrace:
  1. testthat::test_dir("tests/testthat")
  2. testthat:::test_files(...)
  3. testthat:::test_files(...)
  9. testthat:::parallel_event_loop_smooth(queue, reporters)
 10. queue$poll(poll_time)
 11. base::lapply(...)
 12. testthat:::FUN(X[[i]], ...)
 13. private$handle_error(msg, i)

```

**Comment by hadley** [comment]
@gaborcsardi do you know what the problem is?

**Comment by gaborcsardi** [comment]
More or less, I think so. It is how we pass / create the namespace where the tests run. We probably pass or don't pass the package name where we should do the opposite. `test_local()` should be correct, but apparently `test_dir()` is not. I can look at this and fix it.

**Comment by gaborcsardi** [comment]
@mllg So, if you are using `test_dir()` on a package, then you need to specify the `package` argument, according to the docs:

>  package: If these tests belong to a package, the name of the package.

E.g. this works for me:
```
❯ testthat::test_dir("../webfakes/tests/testthat", package = "webfakes")
Starting 2 test processes
✔ |  OK F W S | Context
✔ |   2       | app [0.1 s]
✔ |  11       | base64 [0.4 s]
⠋ [ FAIL 0 | WARN 0 | SKIP 0 | PASS 14 ] @ app-process, delay                                ^C
```

This is actually mostly independent of the parallel tests. I.e. non-parallel tests will not work, either, unless you load the package first with `load_all()` or the package is installed and loaded, or you specify the `load_package = "source"`.

**Comment by hadley** [comment]
I think the underlying issue is that the docs are confusing — you probably shouldn't be using `test_dir()`.
