### ISSUE TITLE
Broken interaction with RStudio -> Build -> Issues pane

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#1220]
Something seems to have happened with the RStudio->Build->Issues pane when running testthat. I run tests with CMD+SHIFT+T and normally I can click the Issues pane and quick jump to test failures. But when I try to double click here I get a “No such file or directory” error. The line numbers look a little garbled, could something have broken in testthat?

This error happens with testthat 3.0.0, but testthat 2.3.2 works fine when I revert back to it.

![Screen Shot 2020-11-03 at 11 24 19 AM](https://user-images.githubusercontent.com/19150088/98013325-3ed8ea80-1dc8-11eb-9f11-a16da7d73f49.png)

**Comment by kevinushey** [comment]
Did the format of testthat errors change? If so we probably need to change RStudio to adapt to the new format.

**Comment by gaborcsardi** [comment]
It has indeed changed. 

I think it would be better not to rely on the output of testthat, but use the return value of `devtools::test()`. If this lacks some information that you need, then we can add it.

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/rstudio/rstudio/issues/8505
