### ISSUE TITLE
Writing testthat-problems.rds is slow

### ISSUE THREAD

**Issue by llrs** [r-lib/testthat#1223]
I've seen reports that testthat is slower (from several people), from Bioconductor slack:
 ```
                                    ----- i386 ----      ----- x64 -----
                         version    before    after      before    after
AllelicImbalance          1.28.0     20.84    63.71       31.92    66.62
basilisk                   1.2.0        NA   717.82          NA  1016.89
beachmat                   2.6.0    399.70   819.65      245.78   255.62
BiocFileCache             1.14.0     48.90    53.20       42.64    55.89
BiocSingular               1.6.0     59.26    62.54       61.84    59.20
bsseq                     1.26.0    357.04  1413.62      385.04       NA
DelayedMatrixStats        1.12.0    994.31  1059.82      977.29   960.76
DESeq2                    1.30.0    264.89   335.20      312.71   348.40
ensembldb                 2.14.0    445.39   401.29      292.98   265.43
mbkmeans                   1.6.0    319.50   264.25      294.00   274.32
Modstrings                 1.6.0     67.04    44.76       70.93    60.10
SingleCellExperiment      1.12.0     28.15    39.85       29.64    42.70
Structstrings              1.6.0     97.85   109.87      117.48   136.31
TreeSummarizedExperiment   1.6.0     28.14    22.89       23.07    21.32
transite                   1.8.0    220.87   209.56      230.71   244.39
tRNA                       1.8.0     45.59    38.56       39.73    49.95
tximport                  1.18.0    242.21   217.57      231.71   180.04
VariantExperiment          1.4.0     25.54    19.93       19.36    22.34
xcms                      3.12.0    388.43  1795.46      377.57       NA
zinbwave                  1.12.0    289.23   239.04      274.15   245.39
------------------------------------------------------------------------
total                              4342.88  7210.77     3295.94  3288.78
(basilisk excluded from i386 & x64 totals, bsseq and xcms excluded from
x64 totals)
```

Seems like the new parallelization doesn't work well with other systems: https://github.com/Bioconductor/BiocParallel/issues/127. Hope the speed can be reduced.

**Comment by hadley** [comment]
Isn't this now resolved in the linked issue?

**Comment by llrs** [comment]
For Bioconductor BiocParallel apparently yes, but the devel servers of Bioconductor for windows are down and I think they couldn't test it longer. Also I've seen the same comments elsewhere: differences between running test_dir and checking the package. Just that you are aware of this if you weren't before.

**Comment by gaborcsardi** [comment]
## slowdown

> I've seen reports that testthat is slower (from several people), from Bioconductor slack:

Can you please show us how you got these numbers? I just ran 
```r
devtools::test(reporter = "check")
```
on xcms 3.12.0, R 4.0.2, Windows 10, first with testthat 2.3.2 and got:
```
   user  system elapsed
  17.42     0.9   77.87
```
and then with testthat 3.0.0:
```
   user  system elapsed
  17.19    0.87   83.78
```
which seems OK, the user time is actually even a bit smaller.
(About 129 tests are failing though, with all suggested packages installed.)

Do you think you can show some simple commands that show the increased running time?

## parallel vs BiocParallel

> Seems like the new parallelization doesn't work well with other systems: https://github.com/Bioconductor/BiocParallel/issues/127.

Seems like this was fixed already. For the record, parallel testthat is off by default and based on the diagnosis at the issue it didn't have much to do with the slowdown. 

It is unclear if parallel testthat is compatible with BiocParallel, my guess is that depending on how you use BiocParallel, they could be compatible. But you can also just not turn on parallel testthat, if they are not.

## `test_dir`

> Also I've seen the same comments elsewhere: differences between running test_dir and checking the package.

`test_dir` was never exactly the same as checking the package, so can you please share the details on this? Maybe https://github.com/r-lib/testthat/issues/1219 is the same issue?

**Comment by llrs** [comment]
I don't have access to the Bioconductor server, nor did I run the reported time. But I see I am wasting your time so I close the issue. Have a nice weekend!

**Comment by gaborcsardi** [comment]
You are not wasting our time at all. We would just need more information about these issues, to handle them efficiently. 

I can certainly try to run other packages as well to try see the slowdown, but if you or somebody from Bioconductor knows why I am not seeing the difference, that would help pinpointing these issues better.

**Comment by LTLA** [comment]
I don't have a great deal of insight to provide, but some clues may be found in the generation of `testthat-problems.rds`.

To illustrate, we can create a `testthat/` directory containing a single file, `test-warn.R`:

```r
A <- function(i) {
    warning(i[1])
    TRUE
}

B <- function(i) {
    do.call(A, list(i))
}

test_that("what's going on here?", {
    X <- matrix(rnorm(1e8), nrow=10000)
    expect_true(B(X))
})
````

Then, if I were to run the following chunk with **testthat** 3.0.0, I get:

```r
library(testthat)
system.time(test_dir("testthat", reporter=check_reporter()))
## ── Warning (test-warn.R:12:5): what's going on here? ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## -0.244815327661744

## ══ testthat results  ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## Warning (test-warn.R:12:5): what's going on here?

## [ FAIL 0 | WARN 1 | SKIP 0 | PASS 1 ]
##    user  system elapsed 
##  34.449   0.609  35.717 
```

By comparison, with 2.3.2, I get:

```r
library(testthat)
system.time(test_dir("testthat", reporter=check_reporter()))
## ══ testthat results  ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## [ OK: 1 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 0 ]
##    user  system elapsed 
##   5.358   0.307   5.666 
```

Inspection of `testthat-problems.rds` begins to reveal the problem:

```
$ ls -al
total 749844
drwxr-xr-x 3 luna luna      4096 Nov  8 10:42 .
drwxr-xr-x 4 luna luna      4096 Nov  7 23:30 ..
drwxr-xr-x 2 luna luna      4096 Nov  5 23:42 _snaps
-rw-r--r-- 1 luna luna 767819048 Nov  8 10:39 testthat-problems.rds
-rw-r--r-- 1 luna luna       198 Nov  8 10:38 test-warn.R
```

This files records the trace for all (unexpected) warnings and errors, which is all well and good - but when we have `do.call()` calls anywhere in the stack, the arguments are deparsed and inserted into the `$trace` of the `expectation_warning` object. This can get pretty big for some of the genome-level datasets that I usually deal with, which may explain the observed slow-down with 3.0.0. For 2.3.2, this wasn't an issue because unexpected warnings didn't trigger any additional behavior from **testthat**.

A simple fix may be to limit the number of deparsed lines here, akin to the `max.lines=` argument in `traceback()`.

**Comment by gaborcsardi** [comment]
@LTLA Thanks, that makes sense!

**Comment by hadley** [comment]
@LTLA you can also fix this on your end, by not inlining the object into the call:

```R
B <- function(i) {
    do.call(A, list(quote(i)))
}
```

We'll also consider if there's something we can do on the testthat side.
