### ISSUE TITLE
Snapshot testing and plots

### ISSUE THREAD

**Issue by raphael-lorenzdelaigue** [r-lib/testthat#1227]
If I do snapshot testing on a plot, e.g.

``` r
test_that("plot", {
  local_edition(3)
  expect_snapshot(plot(x=c(1,2,3),y=c(4,5,6)))
})
```

I get the following error message
``` r
-- Error (Line 3): plot -----------------------------------------------------------------------------------
Error: no applicable method for 'snapshot_replay' applied to an object of class "recordedplot"
Backtrace:
 1. testthat::expect_snapshot(plot(x = c(1, 2, 3), y = c(4, 5, 6)))
 2. testthat:::verify_exec(quo_get_expr(x), quo_get_env(x), snapshot_replay)
 4. base::lapply(results, replay)
 5. testthat:::FUN(X[[i]], ...)
```

Shouldn't plots be handled by the snapshot test?

**Comment by hadley** [comment]
You can't snapshot test a plot because there's no obvious way to turn a plot into text. You can instead save the plot to a file and use `expect_snapshot_file()`, but be aware that creating pixel identical plots can be quite challenging.

**Comment by raphael-lorenzdelaigue** [comment]
Thanks for the quick answer! 
For what it's worth, the reason why I asked (aside obviously from my still very sketchy knowledge) is that the vignette explicitly mentions that snapshot testing can be used for plots.

```
The goal of a unit test is to record the expected output of a function using code. This is a powerful technique because because not only does it ensure that code doesn’t change unexpectedly, it also expresses the desired behaviour in a way that a human can understand.

However, it’s not always convenient to record the expected behaviour with code. Some challenges include:
[...]
* **Binary formats like plots or images**, which are very difficult to describe in code: **i.e. the plot looks right**, the error message is useful to a human, the print method uses colour effectively.

**For these situations, testthat provides an alternative mechanism: snapshot tests.**
```

This was a bit confusing to my understanding of relevant use cases. 

The vignette might of course be referring to other instances I am not currently aware of.

**Comment by raphael-lorenzdelaigue** [comment]
Thanks for the quick answer!
For what it's worth, the reason why I asked (aside obviously from my still rather sketchy knowledge) is that the vignette explicitly mentions that snapshot testing can be used for plots.


> The goal of a unit test is to record the expected output of a function using code. This is a powerful technique because not  only does it ensure that code doesn’t change unexpectedly, it also expresses the desired behaviour in a way that a human can understand.

> However, it’s not always convenient to record the expected behaviour with code. Some challenges include:
> [...]
> * **Binary formats like plots or images**, which are very difficult to describe in code: **i.e. the plot looks right**, the error message is useful to a human, the print method uses colour effectively.

> **For these situations, testthat provides an alternative mechanism: snapshot tests.**
</br>

This was a bit confusing to my understanding of relevant use cases.

The vignette might of course be referring to other instances I am not aware of.
