### ISSUE TITLE
Phantom test failures

### ISSUE THREAD

**Issue by marko-stojovic** [r-lib/testthat#1229]
I am running unit tests in an R package. In the case of three of the files listed under 'Context' in the attached picture, counts initially appear in the 'F' (Fail) column, only to disappear and reappear under 'OK'. This happens for all three tests of 'calculate_term_frequencies.R', and in two other isolated instances.  The end-result is an absence of any fails in the top table but a tally of five fails under 'Results'.  I have manually clicked through the test files in question, and no errors are raised.

![goodbad](https://user-images.githubusercontent.com/25044519/98694600-8c75ca00-2369-11eb-894c-2127ccaf7e07.png)

**Comment by gaborcsardi** [comment]
Most likely these are errors/warnings that happen outside of `test_that()` blocks. 

Also, I think you have an older testthat version, and this is already fixed in 3.0.0.

**Comment by marko-stojovic** [comment]
Thanks for the comment. There are three errors and there are three unit tests that I've written for that file and nothing outside the test_that() blocks. However, I'll see if an upgrade solves it.

**Comment by marko-stojovic** [comment]
Just to be clear, is this a known bug that was fixed or something unlikely to be provoked by my unit tests?  You seem to be saying both.

**Comment by gaborcsardi** [comment]
> nothing outside the test_that() blocks

Errors that happen while running the setup or helper files are also outside of `test_that()` blocks. Maybe even code in `.onLoad()`.

> Just to be clear, is this a known bug that was fixed or something unlikely to be provoked by my unit tests? You seem to be saying both.

testthat not reporting them properly is bug I suppose. The errors/warnings themselves are probably bugs in your package.

Anyway, for better and more specific help, you'd need to show us some code that produces this. Without that, this is just guesswork.

**Comment by marko-stojovic** [comment]
Thanks for the pointers.  Doesn't sound like it's definitely a bug so I'll close it and reopen if warranted.
