### ISSUE TITLE
bang bang bang throws error in expect_snapshot()

### ISSUE THREAD

**Issue by mgirlich** [r-lib/testthat#1232]
Happens with CRAN version of testthat and current dev version. The same issue exists also for bang bang.

    library(testthat)

    test_that("", {
      local_edition(3)
      df <- tibble::tibble(
        a = c(1L, 1L, 2L),
        b = c(1L, 2L, 1L),
        c = c("b", "a", "a")
      )
      expect_snapshot(tibble::tibble(!!!df))
    })
    #> No snapshotter active. Current value: 
    #> Code
    #>   tibble::tibble(a = <int: 1L, 1L, 2L>, b = <int: 1L, 2L, 1L>, c = <chr: "b", "a",
    #>     "a">)
    #> Error <simpleError>
    #>   <text>:1:20: unexpected '<'
    #>   1: tibble::tibble(a = <
    #>                          ^
    #> ── Skip (???):  ────────────────────────────────────────────────────────────────
    #> Reason: empty test

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.7      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       UTC                         
    #>  date     2020-11-13                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                         
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                 
    #>  backports     1.2.0      2020-11-02 [1] CRAN (R 4.0.2)                 
    #>  callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.2)                 
    #>  cli           2.1.0      2020-10-12 [1] CRAN (R 4.0.2)                 
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.0)                 
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                 
    #>  devtools      2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                 
    #>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                 
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                 
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                 
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                 
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                 
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                 
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                 
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.1)                 
    #>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)                 
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                 
    #>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.0)                 
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.0)                 
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.1)                 
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.1)                 
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                 
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.0)                 
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                 
    #>  processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)                 
    #>  ps            1.4.0      2020-10-07 [1] CRAN (R 4.0.2)                 
    #>  R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                 
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.1)                 
    #>  rlang         0.4.8      2020-10-08 [1] CRAN (R 4.0.2)                 
    #>  rmarkdown     2.5        2020-10-21 [1] CRAN (R 4.0.2)                 
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.0)                 
    #>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.0.2)                 
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                 
    #>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                 
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                 
    #>  testthat    * 3.0.0.9000 2020-11-13 [1] Github (r-lib/testthat@b78e9a9)
    #>  tibble        3.0.4      2020-10-12 [1] CRAN (R 4.0.2)                 
    #>  usethis       1.6.3      2020-09-17 [1] CRAN (R 4.0.2)                 
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                 
    #>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                 
    #>  xfun          0.19       2020-10-30 [1] CRAN (R 4.0.2)                 
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                 
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by hadley** [comment]
This is because (for possibly bad reasons) all expectations support a limited form of quasiquotation that allows you to customise expectation messages. I think unfortunately it's hard to back out that decision, so instead you'll need to run `tibble(!!!df)` outside of the expectation.

**Comment by mgirlich** [comment]
Do you think this should be mentioned in the documentation of `expect_snapshot()` and in the vignette? I'm happy to provide a PR for this

**Comment by hadley** [comment]
Not really, because it affects every single expectation.  Although most expectations have a link to quasi-label, which provides more details.
