### ISSUE TITLE
Add option to auto-accept snapshots

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1233]
Perhaps as another `Config/testthat` in `DESCRIPTION` ?

I'm relying on Git diffs, having to manually accept snapshots is cumbersome in my workflow.

For now I'm using the following in `setup.R`:

```
if (basename(getwd()) == "testthat" && basename(dirname(getwd())) == "tests") {
  withr::defer(testthat::snapshot_accept(path = "."), teardown_env())
}
```

**Comment by hadley** [comment]
I think this is antithetical to the idea of snapshots, so isn't something that should be built in.

**Comment by krlmlr** [comment]
I now see the advantage:

- New `test_that()` blocks are added automatically with a warning
- Removed `test_that()` blocks are silently removed (is this a good idea?)
- Only changed `test_that()` blocks (or code changes that lead to changed outputs) trigger an error and require `snapshot_accept()`.

Do we need to tweak the documentation?
