### ISSUE TITLE
Parallel testing, expect_snapshot() and cli_alert_*()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1236]
`expect_snapshot()` does not correctly capture `cli_alert_info()`, `cli_alert_warning()` and similar messages in parallel mode.

Link to failing CI run: https://github.com/krlmlr/dm/pull/457/checks?check_run_id=1410020289#step:15:506

Suspicious output in the same CI run: https://github.com/krlmlr/dm/pull/457/checks?check_run_id=1410020289#step:15:190

Link to PR: https://github.com/krlmlr/dm/pull/457, it only enables parallel runs. Tests succeed in the base branch.

The callr package has special handling for `"cli_message"` messages, could this be the reason here?

Do you need more information?

**Comment by gaborcsardi** [comment]
Yeah, we need to think a bit what to do with this. We could probably still change cli to _not_ add the `callr_message` class by default, and then callr will leave the messages alone: https://github.com/r-lib/cli/blob/b2b162765ec2bfea74003c36305a7cfc2e6542c8/R/cli.R#L514

**Comment by krlmlr** [comment]
Why does cli add a class for a different package? What are the consequences if we remove this class?

**Comment by gaborcsardi** [comment]
Why not? :) 

The consequence is that cli messages are not passed automatically to the main process by `callr::r_session`. Which is probably fine.

**Comment by krlmlr** [comment]
Are cli messages really that special? Should `callr::r_session` optionally relay all messages (cli or not) to the server process, would that work?

**Comment by gaborcsardi** [comment]
> Are cli messages really that special? 

For some they are, for others they are not. 

> Should callr::r_session optionally relay all messages (cli or not) to the server process, would that work?

No, that would cause even more problems like this.

I'll change cli to not add the class, but make the class configurable. There aren't many use cases for this currently.

**Comment by gaborcsardi** [comment]
@krlmlr Can you pls try https://github.com/r-lib/cli/pull/185 ? Thanks!

**Comment by gaborcsardi** [comment]
OK, this will be in cli 2.2.0, will submit today. So in testthat we'll need to depend on cli 2.2.0, we can leave this issue open until cli is published.

**Comment by hadley** [comment]
@gaborcsardi does this need anything other than a requirement bump?

**Comment by gaborcsardi** [comment]
Just the bump, yeah.
