### ISSUE TITLE
expect_error or expect_condition for testing custom skippers?

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1240]
- In the vignette `expect_error()` is recommended however if one uses it it displays a message about the skipping reason (in the tests results)

- In testthat tests itself, `expect_condition()` is used. 

https://github.com/r-lib/testthat/blob/537ff4bff3db2076e93f398339db881b7ad72981/R/expect-self-test.R#L50-L52

Should the vignette be updated? Happy to make a PR if it is the case.

**Comment by hadley** [comment]
Yeah, a PR would be great.
