### ISSUE TITLE
Error: cannot coerce class 'structure("MyersMbaSes", package = "diffobj")' to a data.frame

### ISSUE THREAD

**Issue by mikemahoney218** [r-lib/testthat#1245]
Hi all,

While using testthat (run via `devtools::check()` and `devtools::test_file()`) against a package that uses S4 classes, I periodically get the error message `Error: cannot coerce class 'structure("MyersMbaSes", package = "diffobj")' to a data.frame`. It appears to me that this error occurs when I am testing a package where I've changed an S4 object and re-tested without re-building and installing the package; the error will persist until I rebuild the package (I've only tested this using the Ctrl+Shift+B shortcut, have not tried simply reloading). 

I'm using testthat 3.0.0, waldo 0.2.3, and diffobj 0.3.2.

I'm not entirely sure what a reprex for this would look like, as I haven't been able to narrow down exactly what causes the issue more than I've described above! Please let me know if I could provide any additional information to be helpful. 

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.3  magrittr_2.0.1  tools_4.0.3     htmltools_0.5.0
#>  [5] yaml_2.2.1      stringi_1.5.3   rmarkdown_2.5   highr_0.8      
#>  [9] knitr_1.30      stringr_1.4.0   xfun_0.19       digest_0.6.27  
#> [13] rlang_0.4.8     evaluate_0.14
```

<sup>Created on 2020-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Unfortunately there's not much we can do without a reprex, but if it happens again, a traceback would be useful.

**Comment by mikemahoney218** [comment]
Still no idea where a reprex starts here, but backtrace in case someone with more sense of root-cause than myself is ever googling this...
```
Error: cannot coerce class 'structure("MyersMbaSes", package = "diffobj")' to a data.frame
Backtrace:
  1. testthat::expect_equal(head_nomd, readRDS("testdata/head_nomd.rds")) test-base_methods.R:10:2
  2. testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
  3. testthat:::waldo_compare(...)
  4. waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)
  5. waldo:::compare_structure(x, y, paths = c(x_arg, y_arg), opts = opts)
  6. waldo:::compare_character(is(x), is(y), glue("is({paths})"))
  7. waldo:::diff_element(x, y, paths, quote = quote, max_diffs = max_diffs)
  8. waldo:::ses_context(x, y, elementwise = elementwise)
  9. waldo:::ses(x, y, elementwise = elementwise)
 10. diffobj::ses(x, y, max.diffs = if (elementwise) 1 else 100, warn = FALSE)
 12. diffobj:::as.character(...)
 15. base::as.data.frame.default(x)
```

**Comment by hadley** [comment]
@mikemahoney218 If it happens again, could you please also provide `rlang::last_trace()`? Are you reloading the package with `load_all()`?

@brodieG from the error it looks like _maybe_ the S4 object bit is getting stripped from the MyersMbaSes object, but I have no idea why that would be happening.

**Comment by brodieG** [comment]
@hadley yes something odd like that seems to be happening, or alternatively the S4 method database is corrupted and the "as.data.frame" method for "MyersMbaSes" objects is not being found, which leads to the default method and the error.  

Absent an actual failing piece of code to debug this with I'm not going to be able to help much beyond this though.

For future reference, [`as.character` calls `as.data.frame`](https://github.com/brodieG/diffobj/blob/860484829aa60fb31fe06c3fbdcde38e6d6e9172/R/core.R#L32), and it seems likely the error happens on the data frame call.

**Comment by mikemahoney218** [comment]
@hadley After altering tests (no changes to functions, just moving a data file and changing a test) and then re-running with `devtools::test()` (so I did not `load_all` or build & install manually, though I haven't checked to see if devtools is running `load_all` in the course of testing) and getting the same backtrace as above, rlang doesn't provide a ton of color:

```
> rlang::last_trace()
<error/rlang_error>
Can't show last error because no error was recorded yet
Backtrace:
    x
 1. \-rlang::last_error()
 ```
 
 Sorry to not be able to be more informative than this! I _also_ wish I was providing you more to work with :)

**Comment by rickhelmus** [comment]
I am getting the exact same error, but in my case it's caused by _any_ of the `expect_known_output()` calls. I tried debugging it, but so far no luck yet. It fails when trying to instantiate a new object in `diffobj::diff_myers()`:

```r
res.s4 <- try(do.call("new", c(list("MyersMbaSes", a = a, 
        b = b), res)))
```
Actually this line works fine, but fails when trying to print out (as I guess `expect_known_output()` wants to?)
```r
Browse[12]> x <- do.call("new", c(list("MyersMbaSes", a = a, b = b), res))
Browse[12]> x
Error in as.data.frame.default(x) : 
  cannot coerce class 'structure("MyersMbaSes", package = "diffobj")' to a data.frame
```
If I do the exact same (ie equal values for `a`, `b` and `res`) in a separate session all seems fine...

For reference:
```r
Browse[12]> print(a)
[1] "\"Applying minimum analyses filter... Done! Filtered 150 (25.30%) groups. Remaining: 443.\""
Browse[12]> print(b)
[1] "\"Applying minimum analyses filter... Done! Filtered 150 (25.30%) groups. Remaining: 443.\""
Browse[12]> res
$type
[1] Match
Levels: Match Insert Delete

$length
[1] 1

$offset
[1] 1

$diffs
[1] 0

Browse[12]> package.version("testthat"); package.version("waldo"); package.version("diffobj")
[1] "3.0.1"
[1] "0.2.3"
[1] "0.3.2"
```

Thanks,
Rick

**Comment by brodieG** [comment]
@rickhelmus will you provide the full set of steps you're using to get to the point of failure, especially if you can get it to happen consistently?  Ideally a minimal example (if you can do it without `testthat` at all it would be perfect, if not the minimal `testthat` command that produces the result, ideally starting from a clean R session).

**Comment by rickhelmus** [comment]
Uhrf... guess not :-/

I did the tests from a fresh R console and also a cleaned up rstudio session and the error disappeared. I will get back to it once it surfaces again.
