### ISSUE TITLE
double negation in skip_if_not() message

### ISSUE THREAD

**Issue by dpprdan** [r-lib/testthat#1247]
The `message` in `skip_if_not()` is always appended with " is not TRUE". This makes sense for the `deparse(substitute(condition))` default. It may not for custom messages. 

Case in point is the googledrive package, where `skip_if_not(drive_has_token(), "No Drive token")` [results in](https://github.com/tidyverse/googledrive/runs/1391398269?check_suite_focus=true#step:11:36) "No Drive token is not TRUE".

This can be easily fixed IMHO if `skip_if_not()` is modelled after `skip_if()`, i.e. if custom messages are shown as is and only the default message is "{condition} is not TRUE".

I can make a PR, if you agree.

**Comment by hadley** [comment]
Yeah, agreed, and a PR would be great 😄
