### ISSUE TITLE
`expect_snapshot_error()` does not include `code` block in snapshot

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#1249]
This snapshot

```r
  expect_snapshot_error(
    gen(iterate(for (x in 1:10) yield(x)))(),
    cran = TRUE
  )
```

produces

```md
# iterate() fails informatively inside generators (#31)

    Can't use `iterate()` within a generator.
    i `for` loops already support iterators in generator functions.
```

I would expect to see a `Code` section as in regular snapshots.

**Comment by hadley** [comment]
This is going to be hard to change because it will make all existing snapshots fail. I think if you want this behaviour you could just use `expect_snapshot()`?

**Comment by hadley** [comment]
I think I'd prefer the solution in #1200
