### ISSUE TITLE
expect_warning() does only silence the first matching warning

### ISSUE THREAD

**Issue by akersting** [r-lib/testthat#1255]
In testthat v3:
```
> testthat::test_that("expected warnings are silenced", {
+   testthat::expect_warning({
+     warning("W1")
+   })
+   
+   testthat::expect_warning({
+     warning("W2")
+     warning("W3")
+   })
+ })
── Warning (Line 6): expected warnings are silenced ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
W3
Backtrace:
 1. testthat::expect_warning(...)
 2. testthat:::expect_condition_matching(...)
 3. testthat:::quasi_capture(...)
 6. rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))

```

I did some debugging: 

On the second warning signalled under expect_warning() the condition `!is.null(matched) || !matches(cnd)` in `capture_matching_condition()` (https://github.com/r-lib/testthat/blob/master/R/expect-condition.R#L262) evaluates to `TRUE`. Should it read `!is.null(matched) && !matches(cnd)` instead?

**Comment by gaborcsardi** [comment]
This is by design: https://github.com/r-lib/testthat/pull/1068/files#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197eaR3

You can try `expect_snapshot()` to catch all warnings and write them to a snapshot.

**Comment by akersting** [comment]
But the help says different (https://github.com/r-lib/testthat/blob/master/man/expect_error.Rd#L94-L99):

> New in the 3rd edition, **if the code throws conditions that don't match regexp/class they will bubble up** outside of the expectation, so if they're important you'll need to catch them with additional expect_message()/expect_warning() calls, or if they're unimportant you can ignore with suppressMessages()/suppressWarnings().

There is no mentioning of only the **first** matching condition being caught.
