### ISSUE TITLE
C++ tests fail on Solaris

### ISSUE THREAD

**Issue by clauswilke** [r-lib/testthat#1257]
C++ tests run via `testthat::run_cpp_tests()` appear to fail on Solaris. Here are three examples:

- https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/isoband-00check.html

- https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/briskaR-00check.html

- https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/testthat-00check.html

Note that the last one is for testthat itself.

**Comment by gaborcsardi** [comment]
It seems that Catch is not enabled by default on Solaris, probably for a reason:
https://github.com/r-lib/testthat/blob/b684f1ee7fd806ff55a9d901174c4cc77c38b7d0/inst/include/testthat/testthat.h#L14

So you would need to skip or omit these test on Solaris, I am afraid.
