### ISSUE TITLE
Can no longer call `test_path()` directly in an R script

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#1270]
Original issue came from yardstick where i have patched this with https://github.com/tidymodels/yardstick/commit/168a3d5b94b6bff40a3dbeeec2053edadf648627

In testthat 3.0.0, when `test_path()` is called in a `helper-*.R` file, but outside of any function, it now fails with:

```r
> devtools::load_all(".")
ℹ Loading testtestpath
Error: Can't find `tests/testthat/` in current directory.
```

I have made a small test package where this issue occurs
https://github.com/DavisVaughan/testtestpath

In [helper-data.R](https://github.com/DavisVaughan/testtestpath/blob/master/tests/testthat/helper-data.R), I try to load some "expensive" data in one time, so that I can call `get_data()` multiple times throughout testing to access a version of the data that has already been loaded into memory. The `test_path()` call here no longer works.

```r
# This doesn't work with testthat 3.0.0
my_data <- readRDS(test_path("data", "data.rds"))

get_data <- function() {
  my_data

  # This does work in testthat 3.0.0
  # readRDS(test_path("data", "data.rds"))
}
```

**Comment by d-sci** [comment]
I have the exact same issue. More general problem appears to be that whereas in 2.3.2 calling `test_path()` when the working directory was already `tests/testthat` (as when sourcing helper files via `load_all()`) used to work: 

```r
setwd('pkgroot/tests/testthat')
testthat::test_path()
#> [1] "."
```

In 3.0.0 it fails:

```r
setwd('pkgroot/tests/testthat')
testthat::test_path()
#> Error: Can't find `tests/testthat/` in current directory.
```

Looks like we lost  `in_testing_dir()` in exchange for `is_testing() && !isTRUE(getOption("testthat_interactive"))`

**Comment by hadley** [comment]
I'm not sure if there's anything we can do here. I can't remember why I made the change, but presumably I had some good reason. I'm going to close this issue since it's easy enough to work around.
