### ISSUE TITLE
Document the alternative for testing R6 classes

### ISSUE THREAD

**Issue by harell** [r-lib/testthat#1271]
Until v3.0.0, a typical way to test whether an R6 object is of a specific class was with `expect_is()`. 
Today `expect_is` is deprecated and instead of it, three options are advised: `expect_type()`, `expect_s3_class()`, or `expect_s4_class()` 

None of these suggestions is an adequate replacement when testing R6 objects. For example:

```
Cars <- R6::R6Class(classname = "Cars")


# Before v3.0.0
expect_is(Cars, "R6ClassGenerator") # Pass
expect_is(Cars$new(), "Cars") # Pass

# Today
expect_type(Cars, "R6ClassGenerator")
#> Error: `Cars` has type `environment`, not `R6ClassGenerator`.
expect_type(Cars$new(), "Cars")
#> Error: Cars$new() has type `environment`, not `Cars`.

```

While `expect_type` does exactly what it should do, it doesn't substitute `expect_is` 

What is the advice in testing R6 classes?

**Comment by gaborcsardi** [comment]
R6 adds S3 classes to both class and the object, so you can do this:

```r
❯ class(processx::process)
[1] "R6ClassGenerator"

❯ testthat::expect_s3_class(processx::process, "R6ClassGenerator")

❯ p <- processx::process$new("true")
❯ class(p)
[1] "process" "R6"

❯ testthat::expect_s3_class(p, c("process"))
❯ testthat::expect_s3_class(p, c("R6"))
```
