### ISSUE TITLE
Overly long code for expect_snapshot()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1282]
throws an error.

Seen in dm.

``` r
local({
  testthat::local_edition(3)
  testthat::expect_snapshot(1 %>% base::identity() %>% base::identity() %>% base::identity() %>% base::identity() %>% base::identity() %>% base::identity() %>% base::identity())
})
#> Error: ``%>%`(...)` threw an unexpected error.
#> Message: <text>:2:0: unexpected end of line
#> 1: 1 %>% base::identity() %>% base::identity() %>% base::identity() %>% base::
#>    ^
#> Class:   simpleError/error/condition
```

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Looks like the underlying problem is in `rlang::expr_deparse()`

**Comment by hadley** [comment]
Presumably this error was previously recorded in a snapshot, which is the motivation for adding the new `error` argument 😄

**Comment by krlmlr** [comment]
Can we increase the `width` argument as a stop gap?

**Comment by krlmlr** [comment]
Also, I wonder if testthat should use `paste(collapse = TRUE)` at some point.
