### ISSUE TITLE
pkgload - testthat circular dependency, Ubuntu 20.04

### ISSUE THREAD

**Issue by rwhetten** [r-lib/testthat#1284]
In upgrading R packages from an 18.04 installation to 20.04, I encountered the following set of error messages related to 'testthat' and 'pkgload':
Error: package or namespace load failed for ‘pkgload’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: NULL
  error: package ‘testthat’ was installed before R 4.0.0: please re-install it
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/pkgload’
ERROR: dependency ‘pkgload’ is not available for package ‘testthat’
* removing ‘/usr/local/lib/R/site-library/testthat’

What is the best way to update these two packages to R v4.0?

**Comment by hadley** [comment]
What have you tried?

**Comment by rwhetten** [comment]
The error message in the original post was from running install.packages(c("pkgload","testthat"),lib="/usr/local/lib/R/site-library") in an R terminal session running with sudo privileges to install packages for all users.
I tried removing the outdated versions of 'testthat' and 'pkgload' individually in the same R terminal session, but both jobs failed with an error that no package by that name is installed. I also tried pkgr from the bash command line, which returned the same error as shown in the R ouput: "package 'testthat' was installed before R 4.0.0: please re-install it". I have not tried updating through the RStudio interface - would that provide additional functionality?

**Comment by gaborcsardi** [comment]
This is clearly not a testthat issue, but an `install.packages()` issue. 

To work around it, I suggest to delete both packages first from all of your libraries, then install pkgload, and then install testthat.

**Comment by rwhetten** [comment]
That seems to have worked. The problem was that remove.packages() doesn't look in all the system libraries, just in the first one on the list in .libPaths(), and the old installation of 'testthat' was in a library farther down in the list. Thanks.
