### ISSUE TITLE
Can we make it easier to test UTF-8 handling?

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#1285]
Porting the UTF-8 tests of rlang to testthat3 was a bit tricky. The `waldo_compare()` function called by all testthat expectations calls `reporter$local_user_output()` which automatically skips the test when the locale is set to non-utf-8.

I found this workaround:

```r
local_utf8_test <- function(frame = caller_env()) {
  reporter <- get_reporter()

  old <- reporter$unicode
  defer(reporter$unicode <- old, envir = frame)

  reporter$unicode <- FALSE
}
```

This doesn't seem like a proper long-term solution though.

**Comment by gaborcsardi** [comment]
Yeah, that should not happen. `local_reproducible_output()` should probably not skip anything when not called for its primary purpose.

**Comment by gaborcsardi** [comment]
@lionel- FWIW this is how cli tests Unicode and colors now: https://github.com/r-lib/cli/pull/231/files#diff-6481dd5af605948a35f35754a60e76df1c572fed58f647c29822fa5861eac1b9R6

**Comment by krlmlr** [comment]
This affects tests in {utf8}.

Reprex:

``` r
library(testthat)

test_that("WAT", {
  withr::local_locale(LC_CTYPE = "C")
  expect_true(TRUE)
})
#> ── Skip (<text>:5:3): WAT ──────────────────────────────────────────────────────
#> Reason: non utf8 locale
```

<sup>Created on 2021-07-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

I have confirmed that this comes from `local_reproducible_output(unicode = TRUE)`, I'm not sure which component is calling this.

**Comment by hadley** [comment]
I _think_ the behaviour of `local_reproducible_output(unicode = TRUE)` is ok; if you're deliberately requesting unicode output and you're in a non-UTF-8 locale, there's nothing you can do except for skipping. The problem arises because it's called automatically by the reporters, which have to switch back and forth between "reproducible output" (inside tests) and "user output" (outside testthat).
