### ISSUE TITLE
Helpers are scoped correctly with R CMD check but not `devtools::test()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#1286]
This concerns both CRAN and dev testthat. Add these files to a package:

```diff
2 files changed, 5 insertions(+)
tests/testthat/helper-test.R | 1 +
tests/testthat/test-test.R   | 4 ++++

new file   tests/testthat/helper-test.R
@@ -0,0 +1 @@
+list <- list("my list")
new file   tests/testthat/test-test.R
@@ -0,0 +1,4 @@
+
+test_that("helper is in scope", {
+  expect_equal(list, list("my list"))
+})
```

This fails with `devtools::test()`:

```
✔ |  OK F W S | Context
✖ |   0 1     | test [0.1 s]
────────────────────────────────────────────────────────────────────────────────
Failure (test-test.R:3:3): helper is in scope
`list` (`actual`) not equal to list("my list") (`expected`).

`actual` is a primitive function
`expected` is a list
```

But works fine with R CMD check.

This worked with `test()` in testthat pre-3.0.

**Comment by hadley** [comment]
testthat already has test for exactly this situation, so I think I'll need more of a reprex.

**Comment by hadley** [comment]
Are you using parallel tests? (In which case this would be #1298)

**Comment by lionel-** [comment]
I just checked and I can still reproduce with CRAN and latest testthat. I am not using parallel tests. What can I do to make the reprex above more complete?

**Comment by hadley** [comment]
Are you using the 3rd edition?

**Comment by lionel-** [comment]
Yes, I believe this is a 3e-only bug.

**Comment by hadley** [comment]
Ok, I see it on a new package. So why doesn't it fail with testthat?

**Comment by hadley** [comment]
If I add `message("Hello")` the file is clearly run, so it must be run in the wrong environment. Maybe it's run in the testthat environment, which is why it works for testthat itself.

**Comment by lionel-** [comment]
oops scratch that. I wrote this based on

> This worked with test() in testthat pre-3.0.

which does not mean 3e. I just tested with 3e disabled and can reproduce the issue. So it's a 3.0 issue that affects both editions.

**Comment by hadley** [comment]
Problem probably lies somewhere between `test_files_setup_env()` and `test_env()`

**Comment by hadley** [comment]
Ooops, no, helpers are run in `test_files_setup_state()`

**Comment by hadley** [comment]
Hmmm it works if I run `test_local()`

**Comment by hadley** [comment]
I think the problem is that `devtools::test()` should now allow testthat to do all the setup, instead of doing part of itself.

**Comment by hadley** [comment]
Moved to https://github.com/r-lib/devtools/issues/2320
