### ISSUE TITLE
Tests on functions using *Cluster fail

### ISSUE THREAD

**Issue by csgillespie** [r-lib/testthat#129]
If I have a function that starts/stops a cluster, then the tests will fail.

For example, this [repo](https://github.com/csgillespie/testthat-pkg-test) contains the [function](https://github.com/csgillespie/testthat-pkg-test/blob/master/R/fakepackage.r)

``` r
parthree = function() {
  cl = makeCluster(2)
  stopCluster(cl)
  3
}
```

If the function is [called](https://github.com/csgillespie/testthat-pkg-test/blob/master/tests/testthat/test-1.R#L3) in the test suite, then `R CMD check` hangs. The output in `test-all.Rout` is:

``` r
> library(testthat)
> test_check("goodpackage")
Loading required package: goodpackage
.Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'startup.Rs': No such file or directory
Execution halted
```

This is the same error message as https://github.com/hadley/testthat/issues/86

**Comment by fabian-s** [comment]
I had the same problem of tests involving calls to `makeCluster()` etc working if sourced directly or called by `devtools::test()`, but not if they were run via  `devtools::check()` or `R CMD check`. 

Directly setting `R_TESTS = ""` within the offending `test_that()`-command solved this issue for me:

```r
test_that("parallelization works for vector-valued stats", {
  # see https://github.com/RevolutionAnalytics/checkpoint/commit/a8d713dd067734a2108f78ea706ceaa73e17ac3e
  # as fix for https://github.com/hadley/testthat/issues/129, https://github.com/hadley/testthat/issues/144
  Sys.setenv("R_TESTS" = "") 
  lmcoef <- function(data, ...) {
    coef(lm(..., data = data))
  }
  city_coef <- jack(data = testdata, statistic = lmcoef, 
    formula = y ~ x1 + x2)$replicates
  expect_equivalent(
    jack(data =  testdata, statistic = lmcoef, formula = y ~ x1 + x2, 
      ncpus = 2, parallel = "multicore")$replicates,
    city_coef)
  expect_equivalent(
    jack(data =  testdata, statistic = lmcoef, formula = y ~ x1 + x2, 
      ncpus = 2, parallel = "snow")$replicates,
    city_coef)})
```

sessionInfo:

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jack_0.1       testthat_0.9.1 devtools_1.6.1

loaded via a namespace (and not attached):
[1] boot_1.3-9     digest_0.6.4   parallel_3.1.2 Rcpp_0.11.3    roxygen2_4.0.2
[6] stringr_0.6.2  tools_3.1.2   
```

**Comment by harrysouthworth** [comment]
Same problem here. Same solution.
 Sys.setenv("R_TESTS" = "") inside test_that
Thanks

**Comment by eheikomuni** [comment]
-- 1. Error: (unknown) (@test-spectralIndices.R#4)  ----------------------------
there is no package called ‘pls’
1: suppressPackageStartupMessages(library(pls)) at testthat/test-spectralIndices.R:4
2: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
3: library(pls)
4: stop(txt, domain = NA)

-- 2. Error: (unknown) (@test-superClass.R#4)  ---------------------------------
there is no package called ‘pls’
1: suppressPackageStartupMessages(library(pls)) at testthat/test-superClass.R:4
2: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
3: library(pls)
4: stop(txt, domain = NA)

**Comment by eheikomuni** [comment]
How can I solve this problem??

-- 1. Error: (unknown) (@test-spectralIndices.R#4)  ----------------------------
there is no package called ‘pls’
1: suppressPackageStartupMessages(library(pls)) at testthat/test-spectralIndices.R:4
2: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
3: library(pls)
4: stop(txt, domain = NA)

-- 2. Error: (unknown) (@test-superClass.R#4)  ---------------------------------
there is no package called ‘pls’
1: suppressPackageStartupMessages(library(pls)) at testthat/test-superClass.R:4
2: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
3: library(pls)
4: stop(txt, domain = NA)

-- 3. Error: (unknown) (@test-validateMap.R#4)  --------------------------------
there is no package called ‘pls’
1: suppressPackageStartupMessages(library(pls)) at testthat/test-validateMap.R:4
2: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
3: library(pls)
4: stop(txt, domain = NA)

== testthat results  ===========================================================
OK: 469 SKIPPED: 2 FAILED: 3
1. Error: (unknown) (@test-spectralIndices.R#4) 
2. Error: (unknown) (@test-superClass.R#4) 
3. Error: (unknown) (@test-validateMap.R#4) 

Error: testthat unit tests failed
