### ISSUE TITLE
Special considerations with snapshot tests and the cli package

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1296]
I'm adopting cli in reprex and testthat 3e and snapshot tests. And I happen to be installed from dev crayon.

The use of unicode and crayon w.r.t. saving snapshots seems to be broken with testthat and dev crayon.

See #1295.

**Comment by gaborcsardi** [comment]
@jennybc Does dev reprex reproduce this? If not, how is it the easiest to reproduce?

**Comment by jennybc** [comment]
I'm working on that. Snapshotting cli-produced alerts works for me in the branch associated with #1295, so now I need to figure out why that is not true in reprex.

**Comment by jennybc** [comment]
This PR https://github.com/tidyverse/reprex/pull/351 in reprex shows the problem. The use of Unicode and ANSI colours by cli inside a test is, by default, **not** under the control of the current values of seemingly relevant options, nor is it under the control of whatever `cli::cli_sitrep()` reports.

Instead, if a cli "app" happens to already be running, *its* state is what matters. (I will be opening a companion issue in cli.) It's hard to predict what causes the cli app to start. From #1295 here in testthat, it seems one is not running prior to the first snapshot test involving cli, but https://github.com/tidyverse/reprex/pull/351 in reprex shows the opposite. Does it have something to do with the nature of the cli calls inside the package?

How did I know to bark up the "app" tree? Conversing with @hadley elsewhere about my frustrations, he suggested that I explicitly call `cli::start_app()` in the affected tests (the ones snapshotting code that contains cli calls) and this resolved the problem.

Here's the conclusion in terms of testthat: Perhaps `local_reproducible_output()` should know* about cli and, when cli is in use, should call `cli::start_app(.auto_close = TRUE)`.

* I'm not entirely sure what "know" should mean here. Is it that cli appears in Imports of the package under test? Or that the cli namespace is loaded?

**Comment by jennybc** [comment]
I'll reiterate a second testthat conclusion from #1295, which is that there are saved snapshots in testthat containing unicode/ANSI escapes that are probably not what's intended.

**Comment by jennybc** [comment]
It appears this was due to an actual bug in cli, which has been fixed (https://github.com/r-lib/cli/issues/210). That is also born out in the reprex PR I made illustrating the problem (https://github.com/tidyverse/reprex/pull/351).

If a testthat maintainer concurs with these conclusions, I think the only things to do here now are

1. Take a hard look at the snapshots that contain ANSI escapes and, presumably, re-make them with (dev) cli.
2. *maybe?* Add a test for the desired and expected behaviour of cli inside snapshot tests (https://github.com/tidyverse/reprex/pull/351 could be used)

**Comment by gaborcsardi** [comment]
1. Yeah.
2. IDK if we need to test this in testthat, I guess it does not hurt. I should also add test cases in cli, I'll do that now.

**Comment by gaborcsardi** [comment]
Re 1., as it happens colors are explicitly turned on in the test cases that would be affected, probably to make them work cross platform. So we are perfectly fine with dev cli/crayon as well.

I added a test case to cli. 

So I think we can close this issue.
