### ISSUE TITLE
Global variables are not passed into parallel tests

### ISSUE THREAD

**Issue by byoung** [r-lib/testthat#1298]
I'm trying to upgrade to the third edition of testthat to leverage the parallel test capabilities, but the globals I define in my setup file are not getting passed into the individual test threads. When I run the tests with a single thread using test_file everything passes, but when I use parallel tests (even with TESTTHAT_CPUS=1) the single thread does not see the globals defined in my setup file.

Is the difference in behavior between the two ways of executing tests working as designed or is it a bug?

**Comment by gaborcsardi** [comment]
Can you please provide an example? Thanks.

**Comment by byoung** [comment]
Below is a simple example of running ```test_file``` vs ```test_local``` with a global that is loaded from ```helper_config.R```. I'm guessing that helpers are not loaded when tests run in parallel?
 
```
TEST FILE (works)
root@5b588c4c1616:/mnt/app# Rscript -e "devtools::load_all(); testthat::test_file('tests/testthat/test_error_summary.R', load_helpers=T)"
Loading myproj.r

══ Testing test_error_summary.R ═════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 183 ] Done!



TEST LOCAL (does not work)
root@5b588c4c1616:/mnt/appRscript -e "devtools::load_all(); testthat::test_local('.', load_helpers= T)"
Loading myproj.r
Starting 1 test process
✔ |  OK F W S | Context
✖ |   0 1     | error_summary [2.1 s]                                                                                                
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error: object 'MY_GLOBAL' not found
Backtrace:
 1. base::suppressWarnings(...)
 3. myproj.r:::getErrorSummaryMetrics(df = TestData, err = CompCondensed)
 4. base::apply(...) R/get_error_summary.R:190:2
 5. myproj.r:::FUN(newX[, i], ...)
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
^C
Execution halted
root@5b588c4c1616:/mnt/app# 



tests/testthat/helper_config.R
MY_GLOBAL <- 0.95


DESCRIPTION
Config/testthat/edition: 3
Config/testthat/parallel: true

```

**Comment by gaborcsardi** [comment]
Helper files are indeed not loaded on parallel workers. Setup files are loaded, however, so maybe you can use a `setup-*.R` file?

**Comment by byoung** [comment]
Is the fact that helpers are not loaded for parallel workers working as designed? If so, where is it documented with the rationale?

When I rename the file to the setup*.R convention both cases fail to find the global.

**Comment by gaborcsardi** [comment]
This is the way parallel tests work:
https://testthat.r-lib.org/articles/parallel.html#basic-operation

This does not mention helper files, we can think about whether it would make sense to load them as well. I would think yes.

**Comment by byoung** [comment]
Yeah, I saw the docs but no mention of helpers. IMHO the behavior for parallel/not should be the same or some docs should indicate it's not with the rationale.

Also wondering why the setup file was not loaded in either case. Does load_helpers suppress setup files from getting loaded?

**Comment by gaborcsardi** [comment]
Actually, I misspoke, helper files are loaded in parallel sub-processes as well, here is an example: https://github.com/r-lib/cli/compare/testthat-parallel-global

It works properly:
```
❯ Rscript -e "devtools::load_all(); testthat::test_local('.', filter = 'global', load_helpers= T)"
Loading cli
unloadNamespace("cli") not successful, probably because another loaded package depends on it. Forcing unload. If you encounter problems, please restart R.
Starting 1 test process
✔ |  OK F W S | Context
✔ |   1       | global

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 1.2 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ]
```

So I am afraid we still need a reproducible example.

**Comment by byoung** [comment]
That's true, but I only figured this out once I removed devtools::load_all(). Maybe this feature should be documented a little better?

**Comment by gaborcsardi** [comment]
So why is https://github.com/r-lib/testthat/issues/1298#issuecomment-759417905 failing for you?

**Comment by byoung** [comment]
My first example is test_file which is single threaded, the second example runs in parallel. I was only able to get the parallel case to work by removing the devtools::load_all(). I should have updated this ticket once I got it working but I didn't

Looking at your example @gaborcsardi it's interesting how devtools:load_all() works.

 I'll chalk up the load all discrepancy to some strange R interactions on this large project I'm working on.
