### ISSUE TITLE
Error: 'test_dir' is not an exported object from 'namespace:testthat'

### ISSUE THREAD

**Issue by maxachis** [r-lib/testthat#1299]
I will preface this by saying that I am an R novice and it would not surprise me at all if the answer to this is obvious. 

I attempted to follow the instructions (at r-pkgs.org)[https://r-pkgs.org/tests.html] on setting up testthat. However, upon getting to the "devtools::test()" command, I obtain an error.

``` devtools::test()
Loading testthat
Error in get(genname, envir = envir) : object 'compare' not found
Error in get(genname, envir = envir) : object 'compare' not found
Error in get(genname, envir = envir) : object 'testthat_print' not found
Error in get(genname, envir = envir) : object 'compare' not found
Testing testthat
Error: 'test_dir' is not an exported object from 'namespace:testthat'
```

Let me know if additional information is needed.

**Comment by hadley** [comment]
I think this probably means you just need to install a newer version of testthat.

**Comment by maxachis** [comment]
Unfortunately, it seems I do have the latest version of Testthat. 3.0.1. I never used Testthat until the past two weeks, and I installed it and reinstalled it a few times with the command 'install.packages("testthat")'. The error still appears.
