### ISSUE TITLE
Documentation error of snapshot_accept? Old pizza?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/testthat#1302]
The docs at https://testthat.r-lib.org/articles/snapshotting.html say

```
bullets <- function(text, id = NULL) {
  paste0(
    "<ul", if (!is.null(id)) paste0(" id=\"", id, "\""), ">\n", 
    paste0("<li>", text, "</li>\n", collapse = ""),
    "</ul>\n"
  )
}
test_that("bullets", {
  expect_snapshot_output(cat(bullets("a")))
  expect_snapshot_output(cat(bullets("a", "b")))
})
#> ── Failure (<text>:9:3): bullets ───────────────────────────────────────────────
#> Snapshot of `cat(bullets("a"))` has changed:
#> `old`: "<ul>" "  <li>a</li>" "</ul>"
#> `new`: "<ul>" "<li>a</li>"   "</ul>"
#> 
#> Run `snapshot_accept('pizza')` if this is a deliberate change
```

Its confusing where `snapshot_accept('pizza')` came from - is this an old version of the docs?

**Comment by hadley** [comment]
See the paragraph above:

> The name of the snapshot matches your test file name — e.g. if your test is test-pizza.R then your snapshot will be saved in test/testthat/_snaps/pizza.md. As the file name suggests, this is a markdown file, which I’ll explain shortly.

This is all a made up example because there's no real file here.
