### ISSUE TITLE
Warnings in test_dir when using UNC paths

### ISSUE THREAD

**Issue by rjnb50** [r-lib/testthat#1304]
When I make a call to `test_dir("\\\\serverxxx1\\DriveName\\Path")` I get the following warnings (repeated many times):

```
In normalizePath(path.expand(path), winslash, mustWork) :
path[1] = "\\serverxxx1": The specified path is invalid

In normalizePath(path.expand(path), winslash, mustWork) :
path[1] = ".": Access is denied
```

Everything works fine if I convert the UNC path to a mapped network drive path (Z:\Path). However it would be very convenient for corporate systems if you could silence these warnings. Thank you.

**Comment by rjnb50** [comment]
It seems to be related to calling the 'context' function.

**Comment by hadley** [comment]
Could you please do `options(warn = 2)` and then provide a `traceback()`?

**Comment by hadley** [comment]
Since I don't have enough information to diagnose the issue, I'm closing it.
