### ISSUE TITLE
unequal behavior between testthat and test coverage

### ISSUE THREAD

**Issue by neonira** [r-lib/testthat#1306]
On bottom left, the acceptable character set used. 
On top left, the current function to test
On top right the test results. This shows that everything runs fine and **all tests pass.** 
On bottom left the same test suite used by devtools::test_coverage. **This systematically fails.**

Reason apparently is that the used character set seems to break ordering set under C locale. 
Got some questions, about this
a. Why does not C locale rely on US-ASCII character set ordering? It seems that order under C locale for letters is A a B b C c and not A B ... Z a b ... z
a. How could I tell test_coverage to skip test if not working under an UTF8 locale?

![Screenshot from 2021-01-19 11-17-06](https://user-images.githubusercontent.com/37214634/105020836-1a47f280-5a48-11eb-9ffc-dd2b3c92584d.png)

**Comment by hadley** [comment]
If you want to enforce a specific locale for a test, I suggest using `withr::local_collate()`
