### ISSUE TITLE
testthat subprocess exits when running tests in parallel

### ISSUE THREAD

**Issue by byoung** [r-lib/testthat#1310]
When running tests in parallel and without any explanation, one of the threads dies on the same file. 

```
Error: testthat subprocess exited in file `my_tests.R`
15747Backtrace:
15748     █
15749  1. └─testthat::test_local(".", reporter = c("progress", "fail"))
15750  2.   └─testthat::test_dir(...)
15751  3.     └─testthat:::test_files(...)
15752  4.       └─testthat:::test_files(...)
15753  5.         ├─testthat::with_reporter(...)
15754  6.         │ ├─base::withRestarts(...)
15755  7.         │ │ └─base:::withOneRestart(expr, restarts[[1L]])
15756  8.         │ │   └─base:::doWithOneRestart(return(expr), restart)
15757  9.         │ └─base::force(code)
15758 10.         └─testthat:::parallel_event_loop_chunky(queue, reporters)
15759 11.           └─queue$poll(Inf)
15760 12.             └─base::lapply(...)
15761 13.               └─testthat:::FUN(X[[i]], ...)
15762 14.                 └─private$handle_error(msg, i)
15763Execution halted
15764The command "docker-compose run --entrypoint="bin/runTests.sh" myproj" exited with 1.
15765
15766
15767Done. Your build exited with 1.
```

**Comment by hadley** [comment]
I think you're going to have to make us a reprex.

**Comment by byoung** [comment]
Mystery solved!

This exception was getting thrown by a docker container running in Travis, but not my local environment. As the image running in Travis and my local env were the same I was wondering how the same image in two env could behave differently. As it turns out, the amount of memory in Travis is much smaller than what is allocated for my local env. By reducing the amount of memory available in my local env I was able to reproduce the error.

I'll leave the issue open for now in case you want to add some OOM handling/logging to better indicate the underlying issue.

**Comment by hadley** [comment]
Given that we don't have any way to reproduce the problem, and it seems relatively esoteric, I think we'll have to leave as is.
