### ISSUE TITLE
ProgressReporter with redirected stdout

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1315]
If stdout is redirected, the ProgressReporter should not show progress; the equivalent of `update_interval = Inf` and perhaps `max_failures = Inf` should be used.

**Comment by hadley** [comment]
How do we detect if stdout is redirected?

**Comment by krlmlr** [comment]
I see how that's tricky. We really want to know if the output is likely to end up in a file where the progress messages would be disturbing only. Can we check if `/dev/stdout` points to a file and/or if the `CI` environment variable is set?

**Comment by gaborcsardi** [comment]
Hmmm, maybe you can select a different reporter if you are redirecting the output?

**Comment by hadley** [comment]
Yeah, sounds like that might be a better approach to me.
