### ISSUE TITLE
Error message in expect_s3_class() is confusing

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1322]
During testing, it can be common to make some trial-and-error.

This can lead to this kind of awkward error message.

``` r
library(testthat)
x=iris
class(x$Sepal.Length)
#> [1] "numeric"
typeof(x$Sepal.Length)
#> [1] "double"
expss::var_lab(x$Sepal.Length) = "Sepal length"

#lets say I mixed the concepts of classes and types
expect_s3_class(x$Sepal.Length, "double")
#> Error: x$Sepal.Length inherits from `labelled/numeric` not `double`.

expect_s3_class(x$Sepal.Length, "labelled/numeric")
#> Error: x$Sepal.Length inherits from `labelled/numeric` not `labelled/numeric`.
```
<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Maybe this function can either accept this syntax or specifically handle this situation (for instance by throwing a special message when a class contains `/`).

**Comment by hadley** [comment]
I think the best thing to do here would be to tweak the error message slightly:

```
Error: x$Sepal.Length inherits from `labelled/numeric` not `double`.
# ->
Error: x$Sepal.Length inherits from 'labelled'/'numeric' not 'double'.
```
