### ISSUE TITLE
Clarify third edition documentation about warnings

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1340]
I'm currently migrating my package testing to use `testthat`'s third edition and I'm very excited to use all those awesome-looking features.

However, the greatest issue I'm facing so far is that warnings are now limited to one output only, which leads to quite an intense refactoring in my code (but perhaps it is a hint it was flawed in the first place).

Since it has been described as a feature and not a bug in https://github.com/r-lib/testthat/issues/1255, I guess it is a matter of documentation.

First, it would be nice if this change could be mentioned in https://testthat.r-lib.org/articles/third-edition.html#changes, as this is most likely the first place one may start to learn how to migrate. 

Also, in https://testthat.r-lib.org/reference/expect_snapshot.html, the case of warnings is not crystal-clear. You have to read the help up to the `class` argument to figure out that `expect_snapshot_error()` can accept warnings. 

But most importantly, the naming is quite surprising: 

> `expect_snapshot_error()` captures just error messages.

Warnings and messages are not usually considered errors, so one would not expect to catch them with this function. Also, since errors can have classes, I found it further surprising to say that warnings are of some subclass of error. 

I would rather have expected something like `expect_snapshot_condition(x, type=c("error", "warning", "message"), class=NULL, cran=FALSE)`, with `class` to catch some specific subclass of error/warning, best along with handy helpers like `expect_snapshot_error()`, `expect_snapshot_warning()`, and `expect_snapshot_message()`.

In addition, note that `expect_snapshot()` comes with a `error=FALSE` option, but not with a `warning=FALSE` option. If this is not a feature you would consider adding, it would be nice to describe there how this function is meant to behave regarding warnings.

Finally, in https://testthat.r-lib.org/reference/expect_error.html, the "In the 3rd edition" mention is not very obvious, shouldn't it be in a specific section, or in bold at least?

Thanks again for your incredible work.

**Comment by hadley** [comment]
* `vignette("third-edition")` gives more details on changed handling of warnings in #1424
* `expect_snapshot_error()` shouldn't be used to capture warnings; I'm not sure why I wrote the documentation that way. Instead just use `expect_snapshot()`. Generally, you should prefer `expect_snapshot()` for almost every situation; `expect_snasphot_error()` seemed interesting initially, but subsequent experience suggests it's only rarely useful.
* If you want to suppress warnings in a snapshot, just use `suppressWarnings()`
* `expect_error()` seems to label 3rd edition consistently with other functions so I think I'll leave that as is. I think the new section in the vignette should mean that this change in behaviour is less likely to trip folks up.
