### ISSUE TITLE
Issue in expect_snapshot_file, expect_snapshot_output, ... and so on. 

### ISSUE THREAD

**Issue by harsh9898** [r-lib/testthat#1347]
When I am trying to run any of the expect_snapshot function, it's giving me the following errors:

Error in edition_require(3, "expect_snapshot_output()") : 
  `expect_snapshot_output()` requires the 3rd edition.

Error in edition_require(3, "expect_snapshot_file()") : 
  `expect_snapshot_file()` requires the 3rd edition.

First, I have a edition 3. I checked into the DESCRIPTION of testthat. Let me give you more details. i went through the code of these functions, after analyzing the code, I think it'  not able to get the testthat_env variable. I am not getting from where it's taking it. Please help me with this error. Hope to hear from you soon.

**Comment by hadley** [comment]
@harsh9898 it is not appropriate to `@` mention many people on your issue. You are using freely produced open source software and you are not entitled to demand help from other people.

**Comment by harsh9898** [comment]
Sorry about that. I didn't know that. I edited the comment
