### ISSUE TITLE
expect_equal breaks up vctrs records

### ISSUE THREAD

**Issue by maxheld83** [r-lib/testthat#1349]
`testthat::expect_equal()` appears to "break up" [vctrs records](https://vctrs.r-lib.org/reference/new_vctr.html).

I've observed a similar (related?) behavior in purrr https://github.com/tidyverse/purrr/issues/819.

Crucially, `testthat::expect_equal()` *does* otherwise respect equalities set by [`vctrs::vec_proxy_equal()`](https://vctrs.r-lib.org/reference/vec_proxy_equal.html).

This just affects records, AFAIK, and, as per the output, it's natural that it would happen, because testthat (or waldo?) seems to compare the record *fields* as opposed to the entire record.

Apologies:
- the reprex ain't short; unfortunately setting up a record takes a bit, including a format method.
    This is from the vignette.
- I'm not sure whether this belongs in testthat or vctrs.

``` r
library(vctrs)
library(testthat)
new_rational <- function(n = integer(), d = integer()) {
  # assertions from vignette dropped
  new_rcrd(list(n = n, d = d), class = "vctrs_rational")
}

format.vctrs_rational <- function(x, ...) {
  n <- field(x, "n")
  d <- field(x, "d")

  out <- paste0(n, "/", d)
  out[is.na(n) | is.na(d)] <- NA

  out
}

gcd <- function(x, y) {
  r <- x %% y
  ifelse(r, gcd(y, r), y)
}

vec_proxy_equal.vctrs_rational <- function(x, ...) {
  n <- field(x, "n")
  d <- field(x, "d")
  gcd <- gcd(n, d)

  data.frame(n = n / gcd, d = d / gcd)
}

# works now
new_rational(1, 1) == new_rational(2, 2)
#> [1] TRUE

# but testthat does not respect this
test_that("Rationals can be compared", {
  expect_equal(new_rational(1, 1), new_rational(2, 2))
})
#> ── Failure (<text>:36:3): Rationals can be compared ────────────────────────────
#> new_rational(1, 1) not equal to new_rational(2, 2).
#> Component "n": Mean relative difference: 1
#> Component "d": Mean relative difference: 1
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
I don't think this is a really problem with vctrs or testthat — it's just that `expect_equal()` has a confusing name because it doesn't use `==`, it tests for equality of the underlying datastructure.

**Comment by maxheld83** [comment]
So would this be an appropriate workaround then (appended to above reprex)?

```r
test_that("Rationals can be compared", {
  expect_true(all(new_rational(1, 1) == new_rational(2, 2)))
})
```

Or would you consider adding an `expect_equalish()` (bad name) which would just use `==` or is that better left to users?

**Comment by hadley** [comment]
I'd do `expect_equal(new_rational(1, 1) == new_rational(2, 2), TRUE)`
