### ISSUE TITLE
Use output of LocationReporter in the reporter used on CRAN

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1356]
Otherwise it's difficult to see the location of a crash, e.g. https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/RSQLite-00check.html:

```
checking tests ... [40s/224s] ERROR
  Running ‘testthat.R’ [39s/223s]
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(RSQLite)
  >
  > test_check("RSQLite")
  terminate called after throwing an instance of 'Rcpp::eval_error'
    what(): Evaluation error: oops.
```

**Comment by hadley** [comment]
We did try that, but unfortunately it gives way too much output for revdep checks. So I think if you're experiencing crashes, you'll have to manually use LocationReporter.
