### ISSUE TITLE
Interactive testing no longer stops at first error

### ISSUE THREAD

**Issue by vspinu** [r-lib/testthat#1357]
In the newer versions of testthat running tests interactively no longer stops at first error and no longer throws a proper error. 

All I am seeing a sequence of 

```
Test passed 🥇
Test passed 🥇
Test passed 😸
Test passed 😀
Test passed 😀
Test passed 🥇
```
with errors in between.  I am running tests in a loop, hundreds of them, so I don't want the emoticon on every test. (Also they don't display properly in terminal and emacs as there is a limited support for emoticons even in common font sets like DejaVu).

It it possible to get to the old behavior somehow? Also get rid of the emoticons? Thanks!

**Comment by vspinu** [comment]
Found a way for now:

```
if (interactive())
  set_reporter(StopReporter$new())
```

**Comment by gaborcsardi** [comment]
I am not sure what you mean by "running tests interactively", but this stops on the first error for me:

```r
❯ testthat::test_that("", { stop("oops"); stop("not this") })
── Error (Line 1):  ────────────────────────────────────────────────────────────
Error: oops
```

If you want to get rid of the emojis, set the `cli.unicode` option to `FALSE`.

**Comment by vspinu** [comment]
I mean this 
```
> for (i in 1:5) {
+   testthat::test_that("", { stop(i) })
+ }
── Error (Line 2):  ────────────────────────────────────────────────────────────
Error: 1

── Error (Line 2):  ────────────────────────────────────────────────────────────
Error: 2

── Error (Line 2):  ────────────────────────────────────────────────────────────
Error: 3

── Error (Line 2):  ────────────────────────────────────────────────────────────
Error: 4

── Error (Line 2):  ────────────────────────────────────────────────────────────
Error: 5

```

I need it to stop after first error, so that I can debug the error. I am setting global error state in each test so that I can debug interractively when stuff breaks. The tests have to be run in a loop ... 1000nds of them in fact. 

> If you want to get rid of the emojis, set the cli.unicode option to FALSE.

That would disable all unicode support, which I don't want as most of it works fine. Only emojis don't work. 

I also want to disable the printing of "Test passed" line if possible.

**Comment by gaborcsardi** [comment]
I am afraid that there is no reporter that looks exactly what you want, but you can modify an existing one. If it is OK to stop in a debugger, then `DebugReporter` might work for you.

Also, running `test_local()` might be better than running thousands of `test_that()` calls interactively.

**Comment by vspinu** [comment]
Yes, DebugReporter  is a good option, thanks! StopReporter does the work, but still prints the messages. 

> Also, running test_local() might be better than running thousands of test_that() calls interactively.

Not sure how it can help. I am not in a package. My use case is that I have 1k production samples, and I run tests on all of them in a loop. When one of them breaks I want to debug etc.
