### ISSUE TITLE
Stack trace excluding most relevant stack frames

### ISSUE THREAD

**Issue by TMiguelT** [r-lib/testthat#1361]
Under `testthat` 3.0.2 and R version 4.0.3, my testthat stack traces are incredibly short, to the extent that they don't give me any relevant information to solve the error. For example:
```
testthat::test_local(filter='example')
```
```
Error (test-multiqc-examples.R:6:3): We can read the MultiQC example WGS file
Error: `.x` must be a vector, not a function
Backtrace:
  1. multiqc::load_multiqc_file(...) test-multiqc-examples.R:6:2
 45. purrr:::stop_bad_type(...)
```

So I know which test this is from, and what part of the *internal* purrr code raised an error, but not my code caused that to happen. Is there a verbose mode or reporter to assist with this?

**Comment by hadley** [comment]
`options(rlang_backtrace_on_error = "full")` might work, otherwise you'll have to run the code interactively. This sort of traceback may indicate some funky usage of `eval()` that's causing the backtrace collapsing algorithm to over prune.

**Comment by TMiguelT** [comment]
Thank you for the suggestion. Unfortunately `options(rlang_backtrace_on_error = "full")` doesn't help here.
