### ISSUE TITLE
Cucumber json reporter?

### ISSUE THREAD

**Issue by vspinu** [r-lib/testthat#1363]
AWS codebuild can parse tests results in 6 different formats. AFAICS testhtat does not provision for any of those. Cucumber seems the most widely used among the 6.

 https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html

**Comment by hadley** [comment]
Why not use the JUnit format?

**Comment by vspinu** [comment]
I see. There is a junit reporter. It's not listed in the [Reporter](https://rdrr.io/cran/testthat/man/Reporter.html) docs, so I missed it.
