### ISSUE TITLE
Get total number of tests with `test_package` in case of warnings

### ISSUE THREAD

**Issue by lcougnaud** [r-lib/testthat#1366]
I would like to report the total number of unit tests that passed/failed in a R package, in a context of package validation.

In case some warnings are triggered inside an expectation, the number of tests reported (with `as.data.frame` on the `testthat_results`) is not the number of actual unit tests (expectations), but rather the number of warnings:
```
# create example package
pkgName <- "./testPackage"
package.skeleton(name = pkgName)

# and testthat structure
usethis::use_test("example")

# add dummy test with warnings
cat(
  "test_that('test with warnings', {",
    "expect_length({",
    "  warning('test 1')",
    "  warning('test2')",
    "  1",
    }, 1)",
    "expect_true(TRUE)",
    "})", 
    file = file.path(pkgName, "tests", "testthat", "test-example.R"),
    sep = "\n"
)

resTests <- testthat::test_local(
	pkgName, 
	reporter = "silent", 
	stop_on_failure = FALSE
)
as.data.frame(resTests)
```
I expected the 'nb' in the output to be the number of tests/expectations, so 2 (and not 4).
|file           |context |test               | nb| failed|skipped |error | warning|  user| system|  real| passed|
|:--------------|:-------|:------------------|--:|------:|:-------|:-----|-------:|-----:|------:|-----:|------:|
|test-example.R |        |test with warnings |  4|      0|FALSE   |FALSE |       2| 0.187|      0| 0.186|      2|

Is there a way to extract the number of tests (expectations)?

Many thanks in advance!

(Example tested with testthat version 3.0.2)

**Comment by hadley** [comment]
You could just add together `failed` + `passed`.
