### ISSUE TITLE
Set max.print option

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1367]
for consistent output. I override this in my `.Rprofile` to avoid occasional surprises.

**Comment by hadley** [comment]
To the default of 99999, or something else?

**Comment by krlmlr** [comment]
Would 1000 be enough? I think the default is too large to be useful.

Should we print a header with all options defined at the top of each `.md` file? This would give

- clarity
- a way for us to change default options later on in a self-explanatory way: output changes caused by a testthat update would coincide with a diff in the header and perhaps also with a warning

**Comment by hadley** [comment]
My only concern is that it might affect revdeps, so we'd probably need run the revdeps in the PR to check it's not causing too much breakage (I don't think it would, but you never know). 

It also affects things other than snapshot tests, so I don't think exposing only in `.md`s would be adequate.

**Comment by hadley** [comment]
I think we should just set it to the default — this protects you against variations in your `.Rprofile` and should have minimal impacts on revdeps. You can also override locally for a specific test if needed. I'll put together a PR shortly.
