### ISSUE TITLE
expect_character & co

### ISSUE THREAD

**Issue by pkrog** [r-lib/testthat#1369]
I am missing several `expect_*` for testing more easily returned types (in the way [chk](https://cran.r-project.org/web/packages/chk/index.html) package tests parameters):
 * `expect_character`
 * `expect_integer`
 * `expect_double`
 * `expect_numeric`
 * `expect_logical`

Also I would have the use for methods like `expect_empty` (tests `length(object) == 0`), `expect_not_empty`, `expect_length_gte`, `expect_number`, `expect_string`, ...

Those functions are shortcuts, but would be very handy at my opinion.

Would you allow me to make such a contribution to your package?

**Comment by hadley** [comment]
You can use the generic `expect_vector()` for these tests. I think having many small helpers like this is not a good fit for testthat.
