### ISSUE TITLE
Build of testthat fails

### ISSUE THREAD

**Issue by linusheinz** [r-lib/testthat#1373]
When I try to build the current master it fails with 
`
../inst/include/testthat/vendor/catch.h:6495:33: error: size of array ‘altStackMem’ is not an integral constant-expression

 6495 |         static char altStackMem[SIGSTKSZ];

size of array ‘altStackMem’ is not an integral constant-expression

 6546 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};

`
With gcc version: 11.1.1

**Comment by linusheinz** [comment]
glibc changed `MINSIGSTKSZ` to be a syscall instead
of being constant. #https://github.com/catchorg/Catch2/issues/2178

**Comment by Enchufa2** [comment]
Yeap, this is failing in Fedora rawhide with the latest glibc version.

**Comment by gavinsimpson** [comment]
This just bit me today trying to get R 4.1 on Fedora (which is only available on rawhide currently) set up so that I could resolve all the changes that were made to *testthat* and *vdiffr* with the latest release. Compiling *testhat* from source there failed with the same issues as reported by @linusheinz and @Enchufa2

**Comment by clauswilke** [comment]
Any suggestions on how to fix this?

**Comment by Enchufa2** [comment]
Two options:

- Change `SIGSTKSZ` with some fixed value (this is the [quick&dirty patch](https://src.fedoraproject.org/rpms/R-testthat/blob/rawhide/f/R-testthat-sigstksz-not-constant.patch) we have in place for now in Fedora). Not very elegant nor portable. Not sure if this could cause trouble in some architectures.
- Allocate the array dynamically with `SIGSTKSZ`, which is now a syscall. This is what many project have been doing. See e.g. [this](https://github.com/catchorg/Catch2/commit/395d7c024c830c0b608b8de8edd456190a618f75).

**Comment by clauswilke** [comment]
Actually, looks like this has been fixed in the upstream code and it's just a matter of updating catch to the latest release: https://github.com/catchorg/Catch2/releases/tag/v2.13.5
(I'm linking to the release that has the fix. We're already one release past that.)

**Comment by Enchufa2** [comment]
Ah, I didn't realise it was vendored code. So that's it, you just need to update. :)

**Comment by jimhester** [comment]
Unfortunately it is not entirely trivial to update the Catch code, as the current code uses Catch1, not Catch2, which has some breaking changes. The most significant of which is that Catch2 requires full support for C++11.
