### ISSUE TITLE
Wrong specification of regexp in `snap_from_md`

### ISSUE THREAD

**Issue by Akirathan** [r-lib/testthat#1375]
In this line: https://github.com/r-lib/testthat/blob/master/R/snapshot-serialize.R#L19, the regexp is specified as `grepl("^-{3, }", ...)`. Note that there is a space in front of } which is, according to the regex documentation, wrong. For an unknown reason, R accepts this specification, but throws an error in this case `grepl("^-{3, 5}, ...)`. If you try to use the pattern `^-{3, }`, it should match this string "-{3, }". R wrongly ignores the space there.

The correct pattern should be "^-{3,}".

**Comment by hadley** [comment]
Given that it works, I don't see that a change is needed.

**Comment by Akirathan** [comment]
I forgot to mention that I reported this issue because I am working on the support for a newer version of `testthat` on FastR (https://github.com/oracle/fastr), an alternative interpreter of R, which does not have this same buggy behavior as GNU-R does. Nevertheless, I respect your comment and I will try to implement some workaround for FastR to support `testthat`.

**Comment by hadley** [comment]
In that case, just provide a PR.
