### ISSUE TITLE
Custom comparison function for `expect_snapshot_file()`

### ISSUE THREAD

**Issue by nbenn** [r-lib/testthat#1378]
I have been struggling a bit with trying to get some tests on plot outputs to pass on gh action runs. With a bit of trial and error, I believe I managed to get both my local machine and the actions VM produce images that are identical on a pixel level, however non-identical wrt the current [comparison function](https://github.com/r-lib/testthat/blob/e3cb86d8332238ad9bd2d760a52c7a7edcfecada/R/snapshot-file.R#L188-L192)

```r
compare_file_binary <- function(old, new) {
  old <- brio::read_file_raw(old)
  new <- brio::read_file_raw(new)
  identical(old, new)
}
```

A potentially worthwhile addition to the `expect_snapshot_file()` API could be an argument for specifying a custom comparison function. For my use-case for example

```r
compare_img_data <- function(old, new) {
  old <- magick::image_read(old)
  new <- magick::image_read(new)
  identical(magick::image_data(new), magick::image_data(old))
}
```

would do the trick. This could make `expect_snapshot_file()` much more powerful than it currently is. For example, again using the magick package, a user could test for image similarity by thresholding the result of `magick::image_compare_dist()`, etc.

My suggestion would be to add a minor change to [`expect_snapshot_file()`](https://github.com/r-lib/testthat/blob/e3cb86d8332238ad9bd2d760a52c7a7edcfecada/R/snapshot-file.R#L56-L81), something along the lines of https://github.com/nbenn/testthat/commit/9f91064703ff75eb08e6ec44295468c1f4c7a6fd. I'm happy to expand this to a proper PR if this is of interest to others as well.

**Comment by lionel-** [comment]
This suggestion makes sense but I would perhaps deprecate the `binary` argument and export the comparison functions instead. Otherwise `binary` is ignored when `compare` is supplied, which is not ideal.

**Comment by nbenn** [comment]
Sure, even better! I made my suggestion to not break with the current API. But given that this is clearly marked experimental, this makes total sense.

Thanks for considering my suggestion.

Let me know if you want me to change and submit a PR.

**Comment by hadley** [comment]
Yeah, that sounds reasonable to me. It'd be worth a quick github search or `expect_snapshot_file()` just to double check that it isn't going to affect a bunch of existing code (which I doubt).

**Comment by lionel-** [comment]
These packages are using `binary = `: rmarkdown, vmr, dm, pkglite, reportfactory. I'll deprecate the argument so they can update whenever they are working on a new release.

@nbenn I have cherry-picked your commit in #1400 so I can go forward with the release. Thanks for this!

**Comment by nbenn** [comment]
Thanks!
