### ISSUE TITLE
Request: ignore warnings when loading libraries

### ISSUE THREAD

**Issue by david-cortes** [r-lib/testthat#1379]
It's quite common in R for windows to see warnings like these when loading a library installed from CRAN:
`package 'data.table' was built under R version 4.0.3`

These register as warnings when running tests on a different package when loading such libraries inside a test file. Would be nice if `testthat` would ignore such warnings.

**Comment by gaborcsardi** [comment]
Do you mean the packages loaded in `R CMD check`, from the `testthat.R` file? Or when they are loaded via `devtools::test()` and similar?

**Comment by david-cortes** [comment]
I mean from `devtools::test()` (or as done in RStudio in case it doesn't use that).

**Comment by hadley** [comment]
I don't see an obvious way to do this; you can always do `suppressWarnings(library(...))`
