### ISSUE TITLE
Add expect_no_match

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/testthat#1380]
This FR is to have a complete function to expect_match that handles the negative case. This is a pattern that exists in other frameworks. Here's an example from python:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertNotRegex

I have a working version of this. Would you be interested in a patch?

**Comment by MichaelChirico** [comment]
This would lend itself naturally to switching from `grepl()` as the workhorse to `grep()` which already comes with an `invert` argument.

**Comment by hadley** [comment]
PR would be great thanks!
