### ISSUE TITLE
Support setting the value of testthat edition via an environment variable

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/testthat#1384]
Hi team!

I hope this finds you well, and thanks for all of the great work on `testthat`.

We use a build system to support R at Google, which unfortunately makes it somewhat difficult to access a package's description file when running tests. Instead, we've modified `testthat` internally to be able to set the edition using an environment variable.

Is this something worth supporting for other users?

Thanks!

**Comment by gaborcsardi** [comment]
Edition 3 is not compatible with edition 2, and vice versa. Whether a package's tests work with edition 2 or edition 3 is the property of the package. Hence the current system of putting this in `DESCRIPTION`. 

So I am unsure how many users would benefit from this. Possibly I just don't understand your setup?

**Comment by michaelquinn32** [comment]
Thanks for the clarification!

I think there is a little confusion in how we manage binaries, tests, packages, etc. at Google. 

*  Binaries are executable bits of code; we run R jobs like [C++ binaries](https://docs.bazel.build/versions/master/tutorial/cpp.html#understand-the-build-file)
* Tests are special binaries that are integrated into the test system
* Packages/libraries are the dependencies of binaries

Because packages are the dependencies of tests, and not the other way around, something like the testthat edition is a property that we set for the test when we run it. Within our build system, you could have multiple sets of tests for the same package, 

*  Sets of tests could have different dependencies (some tests run using RUnit, some with testthat)
*  Sets of tests could have different build configurations (valgrind on or off)
*  And so on

Again, maybe no one else cares about this. But if anyone else does, I could create a PR with our changes.

**Comment by gaborcsardi** [comment]
Right. So if I understand correctly, the tests are not actually in the package, but you write them separately. 

I think one current workaround that you can do is to put 
```
testthat::local_edittion(3)
```
at the top of the test file. This also lets you mix testthat 3e and testthat 2e test files in the same test suite, so you don't have to migrate all test files to 3e at once. Does this work for you?

We could have an env var as well, but as I don't expect many users for it, and it is somewhat cumbersome to test this feature, so I am afraid that we would unintendedly break it in the future.

**Comment by michaelquinn32** [comment]
#1386 has the solution that we're currently using. Please let me know what you think!
