### ISSUE TITLE
`test_that()` changes random seed of the global env

### ISSUE THREAD

**Issue by weiyaw** [r-lib/testthat#1387]
Hi,

Is `test_that()` supposed to change the seed of the global environment?

For example:

```R
> set.seed(1)
> sum(.Random.seed)
[1] 4070365163
> testthat::test_that('a', {testthat::expect_equal(1, 1)})
Test passed 😀
> sum(.Random.seed)
[1] 18842168632
> testthat::test_that('a', {testthat::expect_equal(1, 1)})
Test passed 🌈
> sum(.Random.seed)
[1] 18842168633
> testthat::test_that('a', {testthat::expect_equal(1, 1)})
Test passed 🎊
> sum(.Random.seed)
[1] 18842168634
```
Note that `sum(.Random.seed)` increases by `1` after each subsequent run of `test_that()`. Is this an expected behaviour?

Regards,

Kenyon

**Comment by weiyaw** [comment]
Update: This behaviour only seems to happen when running `expect_*()` within `test_that()`.

```R
> set.seed(1)
> sum(.Random.seed)
[1] 4070365163
> testthat::test_that('a', {})
── Skip (???): a ───────────────────────────────────────────────────────────────
Reason: empty test

> sum(.Random.seed)
[1] 4070365163
> testthat::expect_equal(1, 1)
> sum(.Random.seed)
[1] 4070365163
> testthat::test_that('a', {testthat::expect_equal(1, 1)})
Test passed 😀
> sum(.Random.seed)
[1] 18842168632
> testthat::test_that('a', {testthat::expect_true(T)})
Test passed 🌈
> sum(.Random.seed)
[1] 18842168633
```

**Comment by gaborcsardi** [comment]
> Is `test_that()` supposed to change the seed of the global environment?

I don't see why it would not be allowed to. Pretty much any R code can change the random seed I think.

If you need some reproducible seed in a test case, you must take care of that explicitly.

**Comment by weiyaw** [comment]
Thanks for you prompt reply.

It is certainly legal for a function to change the random seed, but I just wasn't expecting `test_that()` to do this as it does not generate any random output (as far as I know).

For example, `ggplot2` was changing the user's random seed upon loading the package (see [this](https://github.com/hadley/r-pkgs/issues/447) and [this](https://github.com/tidyverse/ggplot2/pull/2409)). Given that this package is authored/maintained by the same group of developers (and also the author of [this guide](https://r-pkgs.org/r.html#code-r-landscape)), I wasn't expecting `test_that()` to change the users' global setting.

Anyway, thanks for all the hard work on developing this package. It does make life much easier when writing R packages.

**Comment by gaborcsardi** [comment]
>  it does not generate any random output (as far as I know).

The "Test passed" messages and emojis are random.

>  I wasn't expecting test_that() to change the users' global setting.

I don't think generating a random number changes the user's global setting.

But you are right, testthat should be careful about the random seed. For example ideally within a `test_that()` block, it should not change it, to let you run a test case with a fixed seed:

```r
test_that("...", {
  withr::local_seed(123)
  ...
})
```

So if an `expect_*()` changed the seed, that would be probably a bug. 

But I don't think that this is happening here. Only `test_that()` uses randomness, after the test are done, if the test block had any expectations.

**Comment by weiyaw** [comment]
>> I wasn't expecting test_that() to change the users' global setting.

> I don't think generating a random number changes the user's global setting.

Sorry, I was meant to say global 'state', not global 'settings'.

**Comment by gaborcsardi** [comment]
> Sorry, I was meant to say global 'state', not global 'settings'

That's how I understood it. That is perfectly fine as well. 

Packages should only use randomness without changing the seed in exceptional situations. E.g. the cited ggplot2 issue is one of those situations. (But even that is somewhat subjective.) If you generate a random number and then you restore the seed, then there is no randomness.

In theory testthat could use its own stream of random numbers, that is independent of the random stream used for the tested code. But it does not do that currently, and considering that you can have code between `test_that()` calls in test files, it is not trivial to implement it at all.

So the current recipe is: if your test case depends on the state of the RNG, (re)set the seed at the beginning of the `test_that()` block. You cannot expect the random seed to stay the same between `test_that()` blocks, and even less between test files.
