### ISSUE TITLE
Nested expect_error(expect_message()) ignores message

### ISSUE THREAD

**Issue by mcol** [r-lib/testthat#1389]
This is similar to #1327, but it also doesn't work when using the  3rd edition (with testthat 3.0.2):

```
message_and_stop <- function() {
    message("correct message")
    stop("here is an error")
}
local_edition(2)
expect_error(expect_message(message_and_stop(),
                            "wrong message"),
             "error")
# (no output)

local_edition(3)
expect_error(expect_message(message_and_stop(),
                            "wrong message"),
             "error")
# correct message
```

**Comment by hadley** [comment]
@lionel- can you take a look when you get a minute please?

**Comment by lionel-** [comment]
In edition 2 we incorrectly capture unexpected messages instead of letting them through. In edition 3 this is fixed, hence the extra output `"correct message"`. I think we are observing expected behaviour.

**Comment by mcol** [comment]
So in edition 3, if I wanted to test a message as well as an error, instead of nesting the expectations I'd have to do this:
```r
test_that("wrong message 3e", {
  local_edition(3)
  msg <- capture.output(expect_error(message_and_stop(), "error"),
                        type="message")
  expect_equal(msg, "correct message")
})
```
Or are there less clunky alternatives?

**Comment by lionel-** [comment]
Just test for the correct message:

```r
expect_error(
  expect_message(message_and_stop(), "correct message"),
  "error"
)
```

**Comment by gaborcsardi** [comment]
This never seems to fail the test, unfortunately:

```r
test_that("...", {
  expect_error(
    expect_message(message_and_stop(), "actually, this"),
    "error"
  )
})
```

```
#> correct message
#> Test passed 😸
```

(And yeah, `correct message` goes through...)

**Comment by gaborcsardi** [comment]
I guess the wrong message going through is OK, because that's a _different_ message, and it can be suppressed with `suppressMessages()`. 

But if the expected message did not happen that should be a test failure, no? Even if the code errors?

**Comment by lionel-** [comment]
> But if the expected message did not happen that should be a test failure, no? Even if the code errors?

The failure can only happen when `expect_message()` returns. So if an error is thrown in the mean time, `expect_message()` never gets a chance finish its course. To make it fail, we'd need to move the check in the on exit hook. Would it be worth the added complexity?

**Comment by gaborcsardi** [comment]
You are right, thanks for the explanation. This seems to work better:

```r
test_that("...", {
  expect_message(
    expect_error(message_and_stop(), "error"),
    "actually, this"
  )
})
```

**Comment by gaborcsardi** [comment]
In general, if you expect multiple conditions (errors, warnings, messages, etc.) from a function, then maybe it is simpler to use snapshot tests:

```r
test_that("...", {
  expect_snapshot(message_and_stop(), error = TRUE)
})
```

```
#> Can't compare snapshot to reference when testing interactively
#> i Run `devtools::test()` or `testthat::test_file()` to see changes
#> i Current value:
#> Code
#>   message_and_stop()
#> Message <simpleMessage>
#>   correct message
#> Error <simpleError>
#>   here is an error
#> Test passed 🌈
```

OTOH this has the risk that some downstream code introduces new output.

**Comment by mcol** [comment]
Thanks @gaborcsardi, swapping the order of the expectations to be `expect_message(expect_error(...), ...)` is enough for what I intended to do. I wonder if this could be documented somewhere?
