### ISSUE TITLE
`snapshot_reject()`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#1390]
I have had a number of cases where I accidentally generate a bunch of "new" snapshot files because of a bug I introduced. After fixing the bug, I have to manually go in and delete all the snapshot files. The RStudio git pane recognizes them as new files, so you can't just git revert them in the Git pane.

It would be great to have `snapshot_reject()`, and mainly I'd just want it to reject all the new files by default

**Comment by gaborcsardi** [comment]
FWIW `git clean -f tests` ?

**Comment by hadley** [comment]
Also if you run the whole test suite, any old snapshot files should also get cleaned up.
