### ISSUE TITLE
Tracebacks when piping into an expectation

### ISSUE THREAD

**Issue by ianeveperry** [r-lib/testthat#1391]
I've noticed that when piping into an expectation a failed test always comes with a traceback even in situations where it seems like one isn't warranted.

For example,
```
f = function(x) x
test_that("testing", {
  f(1) %>% expect_equal(2)
})
```
yields a traceback where this doesn't output one:
```
f = function(x) x
test_that("testing", {
   expect_equal(f(1), 2)
})
```

Is this expected?/Is there a way to turn off the traceback in this situation?

Thanks!

**Comment by lionel-** [comment]
This is expected. You will also get a backtrace in this similar case:

```r
f <- function(x) x

test_that("testing", {
   identity(expect_equal(f(1), 2))
})
```
