### ISSUE TITLE
Tests skip_on_cran are skipped with (local) R CMD check

### ISSUE THREAD

**Issue by lcougnaud** [r-lib/testthat#1395]
I have noticed that in case the package is checked with `R CMD check` locally (so not on CRAN), the tests containing `skip_on_cran` are skipped.

The issue seems to be due to the fact that if the variable `NOT_CRAN` is NOT set, `skip_on_cran` will return TRUE (as not identical to 'true', see this [line](https://github.com/r-lib/testthat/blob/master/R/skip.R#L131)).

Thanks in advance for feedback!

**Comment by gaborcsardi** [comment]
That is by design, you need to set `NOT_CRAN` on your local machine if you call `R CMD check` from the console. Or you can use `devtools::test()` or `devtools::check()` which set it automatically.

**Comment by lcougnaud** [comment]
Ok, I will use the `NOT_CRAN` variable.
Thanks for the quick feedback!
