### ISSUE TITLE
Could skip_if_not_installed take several packages as argument?

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1398]
At the moment I'm wrapping different calls in one helper function.

**Comment by hadley** [comment]
Will need a little care to vectorise `minimum_version` correctly.

**Comment by hadley** [comment]
I had a go at this, but getting the messaging right is hard, and overall it just seems like too much work for insufficient reward. I think writing your own helper function is the way to go.

**Comment by MichaelChirico** [comment]
>  too much work for insufficient reward

I would encourage taking another look -- maybe the reward isn't clear yet, so I'll add our context. Our environment is pretty minimalist so having Suggests unavailable is the default.

The problem with the one-by-one setup is we can't tell all of the missing packages at once. Consider:

```r
skip_if_not_installed("foo")
skip_if_not_installed("bar")
```

Now I have to run the test suite twice to figure out which packages I should include.

After the first run of the test suite, I see `foo cannot be loaded (1)` in my output, and mark `foo` for inclusion.

Then I run again and only then do I see `bar cannot be loaded (1)`.

This is somewhat tedious and could be avoided if `skip_if_not_installed` had an interface to summarize all the packages needed for a given suite.
