### ISSUE TITLE
expect_equal() ignores waldo argument ignore_attr

### ISSUE THREAD

**Issue by nkehrein** [r-lib/testthat#1399]
When comparing data.frames, I would like to ignore row names as I will be comparing different parts of the data.frames against each other. Resetting/removing names is therefore not an option/impossible because these are automatically set by R. Unfortunately, expect_equal() ignores the argument that would tell waldo to ignore changes in names:

```
df <- data.frame(x=rep(1,5),y="a")

waldo::compare(df[1:4,], df[2:5,], ignore_attr = TRUE) # ignores names
testthat::expect_equal(df[1:4,], df[2:5,], ignore_attr = TRUE) # throws an error
```
Thanks.

**Comment by hadley** [comment]
Are you using the 3rd edition?

**Comment by nkehrein** [comment]
Yes, version 3.0.2.

**Comment by hadley** [comment]
Edition, not version. That's important here because only the 3rd edition uses waldo:

``` r
library(testthat)
df <- data.frame(x=rep(1,5),y="a")

test_that("fails in second edition", {
  local_edition(2)
  expect_equal(df[1:4,], df[2:5,], ignore_attr = TRUE) 
})
#> ── Failure (<text>:6:3): fails in second edition ───────────────────────────────
#> df[1:4, ] not equal to df[2:5, ].
#> Attributes: < Component "row.names": Mean relative difference: 0.4 >

test_that("succeeds with third edition", {
  local_edition(3)
  expect_equal(df[1:4,], df[2:5,], ignore_attr = TRUE) 
})
#> Test passed 🎊
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by nkehrein** [comment]
Thank you, I wasn't aware of this difference.
