### ISSUE TITLE
testthat removes active bindings

### ISSUE THREAD

**Issue by tzakharko** [r-lib/testthat#1405]
My package uses an active binding to provide a global pronoun that has a context-dependent value. It seems that when testing a package, `testthat` will clone the package environment which turns the active bindings into frozen values. I can still make my tests pass by prefixing the active bindings with  explicit package namespace, but this behavior definitely seems unexpected. 

Here is a quick example (using a mock package `active_binding_test`):

```r
#' @export active_binding
makeActiveBinding("active_binding", function() value, environment())

value <- NULL

#' @export
set_value <- function(x) value <<- x
```

and the test:

```r
# this will fail
test_that("active_binding works correctly", {
  set_value("a value")
  expect_identical(active_binding, "a value")
})

# this will succeed
test_that("active_binding_test::active_binding works correctly", {
  set_value("another value")
  expect_identical(active_binding_test::active_binding, "another value")
})
```

**Comment by hadley** [comment]
Can you please make a reprex package?

**Comment by tzakharko** [comment]
I was not sure how to package a package (pun) in a reprex snippet, so I have prepared a small repository with a minimal R package instead. The `run.R` file will invoke the tests. The package is here: https://github.com/tzakharko/testhat_active_binding

The traceback shows the exact point where the active binding gets erased:

```
▆
  1. ├─devtools::test()
  2. │ └─testthat::test_local(...)
  3. │   └─testthat::test_dir(...)
  4. │     └─testthat:::test_files(...)
  5. │       └─testthat:::test_files(...)
  6. │         └─testthat:::test_files_setup_env(...)
  7. │           ├─env %||% test_env(test_package)
  8. │           └─testthat::test_env(test_package)
  9. │             └─rlang::env_clone(asNamespace(package))
```

I hope that this is usable. Thank you!

**Comment by lionel-** [comment]
There is a new API in R 4.1 which we can use to clone active bindings. There is also a workaround for older R versions (at least 3.6 and older, possibly 4.0 and older I don't remember).

I opened https://github.com/r-lib/rlang/issues/1228 upstream.

**Comment by hadley** [comment]
Closing since it's been fixed upstream in rlang. Given the rarity of the problem, I don't think it's worth adding special handling to testthat.
