### ISSUE TITLE
package 'testthat' is not installed for 'arch = i386'

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#1420]
Looks like R-devel is gradually dropping support for i386. In https://cran.r-project.org/bin/windows/contrib/4.2/testthat_3.0.4.zip, the `libs/i396` directory is missing.

This affects testthat tests, they now give an error: https://github.com/patperry/r-utf8/pull/14/checks?check_run_id=3149294904#step:13:244 .

One workaround is to use `require(testthat)` in `testthat.R`, as in [`1bc3353` (#14)](https://github.com/patperry/r-utf8/pull/14/commits/1bc3353f8addca0ebc5935958dc767221b9491db). Do we need to adapt usethis?

**Comment by hadley** [comment]
I think we're going to attack this problem upstream.
