### ISSUE TITLE
add ability to skip_on M1 Mac?

### ISSUE THREAD

**Issue by cboettig** [r-lib/testthat#1421]
As you know, CRAN is beginning to enforce checks on M1 Macs, sending the usual "Please correct to safely retain" emails when tests fail.  Like Solaris, some of these failures can occur when an upstream dependency installs on the platform but does not actually run.  (Obviously doing `skip_on("mac")` would be a bit overkill).  Not sure how to detect architecture though.  Thanks for considering or any other suggestions on how to approach this.

**Comment by gaborcsardi** [comment]
The OS:

```
❯ Sys.info()[["sysname"]]
[1] "Darwin"
```

The arch:

```
> R.version$arch
[1] "aarch64"
```

**Comment by hadley** [comment]
I'm happy to implement this but I'm stuck on what to call it.

**Comment by gaborcsardi** [comment]
How about we add an `arch` argument to `skip_on_os()`?

**Comment by hadley** [comment]
What are the other possible architectures apart from `x86_64` and `aarch64`?

**Comment by gaborcsardi** [comment]
There are others, like s390x, ppc64el, other arms, etc. Maybe just let the user specify whatever, and match it to `R.version$arch`?

**Comment by hadley** [comment]
IMO part of the benefit of `skip_on_os()` is that you can (e.g.) specify "mac" and it figures out that you need "darwin". I'd like to keep something similar for arch.

**Comment by hadley** [comment]
But maybe I can just put them in the documentation..

**Comment by gaborcsardi** [comment]
I think that is fine as well. Then you could have `intel` and `m1` for `mac` only, and nothing else.

People can always skip on other arches with `if (R.version$arch == ...) skip(...)`...

**Comment by gaborcsardi** [comment]
Or you could have some aliases, and fall back to compare to the exact value.

**Comment by cboettig** [comment]
thanks :pray:, this looks great :tada: 

Yeah, it's really all about the documentation here.  Of course we can use `if (R.version$arch == ...) skip(...)` but that's not easy to do if you don't have access to said architecture and cannot easily determine what string R has decided to use...  the `skip_on_` docs have always been a great go-to to look up such arcana

**Comment by jlmelville** [comment]
with apologies for bringing this thread back from the dead, this may be of use to @cboettig: a package of mine that somehow has become an ubuntu or Debian package was failing tests on arm64, ppc64el and s390x. An Ubuntu developer was kind enough to provide the `R.version$arch` values for those architectures and for the record they are `"aarch64"`, `"powerpc64le"` and  `"s390x"` respectively. In all cases `Sys.info()[["sysname"]] == "Linux"`,  so I am currently hoping that `skip_on_os("linux", arch = c("aarch64", "powerpc64le", "s390x"))`  will do the trick. Maybe this will help others if they find their way to this issue the same way I did.
