### ISSUE TITLE
expect_known_value function does not allow return values passed by reference

### ISSUE THREAD

**Issue by yasushm** [r-lib/testthat#1431]
[https://github.com/r-lib/testthat/blob/master/R/expect-known.R](url)

In expect_known_value function as first time, the tested object runs twice. 
That means the arguments passed by reference will not be usable in test code: for example the sort functions in data.table package. Finally error happens due to not using original arguments.
I have confirmed by using breakpoint at RStudio.

  act <- quasi_label(enquo(**object**), label, arg = "object")

  if (!file.exists(file)) {
    warning("Creating reference value", call. = FALSE)
    saveRDS(**object**, file, version = version)
    succeed()

I think the act$val can be re-used in saveRDS function at the file existence check.
I needed to make the output file manually to make workarounds.

I noticed a year ago, but I now face again. So make it.

this is the function
```
expect_known_value <- function(object, file,
(omit)
  )

  act <- quasi_label(enquo(object), label, arg = "object")

  if (!file.exists(file)) {
    warning("Creating reference value", call. = FALSE)
    saveRDS(object, file, version = version)
    succeed()
  } else {
    ref_val <- readRDS(file)
    comp <- compare(act$val, ref_val, ...)
    if (update && !comp$equal) {
      saveRDS(act$val, file, version = version)
    }
```

**Comment by hadley** [comment]
`expect_known_value()` is deprecated in the 3rd edition, so we are no longer providing improvements to it. I'd recommend upgrading to the 3rd edition and using `expect_snapshot()` and friends.

**Comment by yasushm** [comment]
I see. Thanks for your quick reply.
