### ISSUE TITLE
PDF image comparisons with snapshotting fails to correctly identify the image has not changed

### ISSUE THREAD

**Issue by thebioengineer** [r-lib/testthat#1435]
## Issue 

Comparing image file snapshots generated with the `pdf()` function fails due to underlying differences with the files. The same underlying plot could be generated, but file differences not related to content cause failure. 

## Inspection/Theory 
On inspection of the file created, this is due to that on creation of pdf file, `pdf()` saves info related to creation datetime, modification datetime.  These will inherently be different since we can't control that. This may require a more sophisticated comparison specifically for PDFs. This may also be outside the scope of {testthat}, but I wanted to bring this to your attention. 

## Reprex

Since we cant do the snapshot comparison interactively, I have provided as small a test case as I could think of for a package. Create a package skeleton, then add the following R function and test code.

sample_plot_file.R: 

```r

## simple function that generates the same plot, only argument is the file path.
generate_pdf_image <- function(file) {

  pdf(file = file)
  plot(c(1,2,3,4))
  dev.off()

  return(file)
}
```

test-sample_plot_file.R
```r
test_that("png generation works", {
  expect_snapshot_file(
    generate_pdf_image(
      file = "test.pdf"
    )
  )
})

```

**Comment by thebioengineer** [comment]
The function under `expect_snapshot_file()`, `compare_file_binary()` is doing its job correctly and I think this is more of a weird case. But an official verdict/one that people can search and see how to resolve would be great

**Comment by hadley** [comment]
Yeah, this is a known problem with many of the graphics devices built in to R. If you're trying to comparing graphics, I'd recommend using a graphics device designed specifically for the problem, e.g. https://vdiffr.r-lib.org

**Comment by thebioengineer** [comment]
Thanks @hadley - The specific case I am running into is that the industry I work in often requires pdf outputs of plots/etc. to be shared. So the deliverable for comparison is the actual PDF file and the historical "golden" test for validation/verification/qualification/ is a person opening up the file to confirm it is as expected visually. 

This is a specific and somewhat weird situation, so its fine that {testthat} doesn't support it out of the box directly.

**Comment by hadley** [comment]
I have a vague recollection than you hack around this by inspecting the first few bytes of the pdf — the date is always in the same place, so it's relatively easy to overwrite.

**Comment by thebioengineer** [comment]
yeah, that is true. However, I couldn't figure out how to get R to load the entire file as a string to edit. It would come across EOF lines before the end of the actual file it seems. :shrug:

I wrote this up last night to do comparisons for PDFs: https://github.com/thebioengineer/valtest/blob/main/R/pdf.R
I am working under the assumption that its the visual we care about, so converting the rendered pdf into a png and doing the comparison

**Comment by hadley** [comment]
Yeah, you need to load it into a raw vector.
