### ISSUE TITLE
system quoting fails with testthat + CMD check

### ISSUE THREAD

**Issue by scottkosty** [r-lib/testthat#144]
Below is a minimal example:

Put the following in tests/testthat.R:

```
options(warn = 2)
library(testthat)
test_check("anRpackage", report = "summary")
```

In tests/testthat/test.R

```
extcmd <- 'R -e \'print("hello")\''
system(extcmd, intern = TRUE)
```

Then run `R CMD check` (either with 3.1 or with the current devel version), I get the following error:

```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  > library(testthat)
  > 
  > test_check("anRpackage", report = "summary")
  Loading required package: anRpackage
  Error in file(filename, "r", encoding = encoding) : 
    cannot open the connection
  Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> source -> file
  In addition: Warning message:
  In file(filename, "r", encoding = encoding) :
    cannot open file 'startup.Rs': No such file or directory
  Execution halted
  Error: (converted from warning) running command 'R -e 'print("hello")'' had status 1
  Execution halted
```

If I source `test.R` or run `R CMD BATCH test.R` or put `test.R` directly in the `tests` folder and then run `R CMD check`, it runs fine.

The error is similar to #129 and #86.

I'm using Ubuntu 64-bit, both 13.10 and 14.04.

**Comment by fabian-s** [comment]
Just came here to confirm that adding
```r
Sys.setenv("R_TESTS" = "")
```
to the testfile seems to take care of these issues.

**Comment by dtenenba** [comment]
Has this been reported to R-core? If so, where? Thanks.

**Comment by grayskripko** [comment]
this trick helped with Microsoft R Open 3.4.1, but something has changed for 3.4.3
