### ISSUE TITLE
Test both output and warnings

### ISSUE THREAD

**Issue by torbjorn** [r-lib/testthat#1445]
Is there a way to test both output and warnings in the same go?

One way would be like this I guess:

        expect_output(
            expect_warning(
                {
                    print("foo")
                    warning("bar")
                },
                "bar"
            ),
            "foo"
        )

But it gets a bit messy rather fast.

Is there another way that's intended for this?

**Comment by hadley** [comment]
Use a pipe?

```R
f <- function() {
  print("foo")
  warning("bar")
}

f() %>%
  expect_output("foo") %>% 
  expect_warning("bar")
```
