### ISSUE TITLE
Placeholder tests

### ISSUE THREAD

**Issue by tiQu** [r-lib/testthat#1447]
When setting up a series of tests, placeholders can serve as reminders for those that still need to be implemented. While we can use `stop("still need to finish this")` as an interim solution it would be great to have a function that allows placeholders to show up in the summary after running `test()`, something along the lines of 
```
test_that("save a file", {
  placeholder("This test isn't ready yet")
})
```

In JavaScript, for example, Mocha has pending tests which don't count as failed tests: 
https://mochajs.org/#pending-tests

There's an [old issue from 2012](https://github.com/r-lib/testthat/issues/47) that suggested something similar but figured it might be worth revisiting.

**Comment by hadley** [comment]
You can just leave the test empty or use a `skip()` if you want to supply more details. (I think this is almost exactly what mocha does except what mock calls "pending" we call "skipped".)
