### ISSUE TITLE
Add a condition to the 3e warning on braced code

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/testthat#1455]
Hi team!

In https://github.com/google/patrick/issues/7, a user pointed out that `patrick` is throwing a lot of warnings in testthat 3e. I've tracked it down to this condition:
https://github.com/r-lib/testthat/blob/0ce7295b2954d752b445e240e5e218c987cc72b2/R/test-that.R#L46

I'm happy to catch this with a calling handler (the line numbers still appear to be correct in `patrick`), but I would appreciate a more robust way to identify this warning. Right now, I'm checking the string contents of the message. Would it be possible to add a class here, ala `rlang::warn()`?
https://rlang.r-lib.org/reference/abort.html

If you're fine with the change, I'd be happy to submit the PR.

Thanks!

**Comment by hadley** [comment]
Sure!

**Comment by michaelquinn32** [comment]
Thanks for the quick response!
