### ISSUE TITLE
Add `transform` support to `expect_snapshot_file()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1474]
I just did something janky with `expect_snapshot(writeLines(read_utf8(path)), transform = scrub_testpkg)` when what I really wanted was `expect_snapshot_file(path, transform = scrub_testpkg)`.

https://github.com/r-lib/usethis/pull/1507/commits/e9a4bec1b6427fe56ef2a88b058c0159e0994bef

**Comment by hadley** [comment]
The fiddly bit is that the defaults for `expect_file_snapshot()` imply that the files are binary (not text), so it would be a weird if `transform` was parameterised in the same way as `expect_snapshot()` (i.e. transforming a character vector). Maybe I can make `compare` a bit smarter so it can default to `NULL` and then guess based on the file extension.
