### ISSUE TITLE
deprecated support for expect_known_value update=F

### ISSUE THREAD

**Issue by harvey131** [r-lib/testthat#1477]
In the older variants of expect_known_value, you could use the update = F to test the output of a function against a value in a file, without writing the filesystem.  This would allow a package to test output without requiring it to modify local files, especially in a non-interactive manner. 

Now that it is deprecated in e3, the snapshot tests seem to always write the local filesystem on failures and are suggested to only be used interactively.  Is the plan to drop the non-interactive functionality of expect_known_value, or could it be added to snapshots so we could test output to a known value in a file, and just report a failure without having to write to the _snaps directory etc.

If this is available with snapshots in e3 and I missed it, please let me know.  Thanks

**Comment by hadley** [comment]
Failures in snapshot tests don't overwrite the existing snapshots, so it seems to be that they're already basically equivalent to `update = FALSE`.
