### ISSUE TITLE
Snapshotting.Rmd examples broken

### ISSUE THREAD

**Issue by scottewebster** [r-lib/testthat#1478]
I think the example output in the [snapshot documentation](https://github.com/r-lib/testthat/blob/master/vignettes/snapshotting.Rmd) is not working properly. The text says "If you run the test again, it’ll succeed:" but then the output complains about not being able to snapshot to reference when running interactively and ends with "empty test". See for example, [here](https://cloud.r-project.org/web/packages/testthat/vignettes/snapshotting.html) or [here](https://testthat.r-lib.org/articles/snapshotting.html). It seems that most of the example output shown on these pages has the same problem. Apologies if this isn't technically an issue with this repo...

**Comment by hadley** [comment]
Thanks for reporting this — it turns out the bug actually lies in withr, https://github.com/r-lib/withr/issues/186, so I'll work on it there.
