### ISSUE TITLE
Should snapshot_accept() succeed from within tests/?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1485]
I sometimes run tests like

```
setwd('tests')
source('testthat.R')
```

However, this conflicts with using snapshot tests; after the output updated, I was instructed to run `snapshot_accept(...)`, but this failed:

```
snapshot_accept(...)
No snapshots to update
```

However, it did create the temp (.new) file, and succeeded like so:

```
setwd('..')
snapshot_accept(...)
Updating snapshots:
* ...
```

**Comment by hadley** [comment]
This feels like a sufficiently unusual workflow that we're unlikely to work on it, but I'd review a PR for it.

**Comment by MichaelChirico** [comment]
ran into this again :sweat_smile:

**Comment by MichaelChirico** [comment]
Now noticed `snapshot_accept()` has a `path` argument that I could change to `testthat` from the default `tests/testthat`.

I think what's most confusing here is the misleading message:

```
* Run `testthat::snapshot_accept('$DIR')` to accept the change.
* Run `testthat::snapshot_review('$DIR')` to interactively review the change.
```

Would adding `Run `snapshot*()` **from the package directory** to ...` be too distracting for the default use case?

**Comment by hadley** [comment]
Yeah, I think so.

Are you changing the path with code? (e.g. with `withr::local_dir()`)?

**Comment by hadley** [comment]
Ah yeah, in that case I'd just case you have an unusual workflow and you're on your own.

You could make life a little easier on yourself by running `source("tests/testhat.R", chdir = TRUE)`
