### ISSUE TITLE
Snapshots are created by `devtools::test()` but not `devtools::check()`

### ISSUE THREAD

**Issue by davidskalinder** [r-lib/testthat#1486]
Not sure whether this belongs here or in devtools, but I figured I'd start here -- please let me know if I should report it in the devtools repo.

Learning to use the new snapshot functionality proved a challenge for me because I kept running my tests as I usually do, using `devtools::check()`, and no snapshots were created.  (Indeed, I suspect that the snapshot tests were not run at all, but I don't know how to confirm this.)  Finally I realized that `devtools::test()` ran as expected, which made me think that this was a bug in the way `testthat` interacts with `devtools` (or perhaps `R CMD check`?).

Apologies for the long reprex -- please feel free to point me toward any guidance on how to more efficiently set up the testing environment in reprexes!

``` r
setup_blank_package <- function(name) {
  usethis::create_package(file.path(tempdir(), name), open = TRUE)
  usethis::use_testthat(3)
  usethis::use_mit_license()
  # Add snapshot test
  cat(
    file = testthat::test_path("test-new-file.R"),
    'test_that("snapshot the number 999", {expect_snapshot(999)})'
  )
}

# devtools::check() doesn't work as expected:

setup_blank_package("bugtest1")
#> [Boring output removed]

devtools::check(quiet = TRUE)
#> ℹ Loading bugtest1
#> ── R CMD check results ──────────────────────────────── bugtest1 0.0.0.9000 ────
#> Duration: 5.4s
#> 
#> 0 errors ✓ | 0 warnings ✓ | 0 notes ✓

file.exists("tests/testthat/_snaps/new-file.md")
#> [1] FALSE

# But devtools::test() works just fine:

setup_blank_package("bugtest2")
#> [Boring output removed]

devtools::test()
#> ℹ Loading bugtest2
#> ℹ Testing bugtest2
#> ✓ | F W S  OK | Context
#> ⠏ |         0 | new-file                                                        ✓ |   1     1 | new-file
#> ────────────────────────────────────────────────────────────────────────────────
#> Warning (test-new-file.R:1:39): snapshot the number 999
#> Adding new snapshot:
#> Code
#>   999
#> Output
#>   [1] 999
#> ────────────────────────────────────────────────────────────────────────────────
#> 
#> ══ Results ═════════════════════════════════════════════════════════════════════
#> [ FAIL 0 | WARN 1 | SKIP 0 | PASS 1 ]

file.exists("tests/testthat/_snaps/new-file.md")
#> [1] TRUE
```

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Well `check()` does create them, they just created inside the checked package, which is in a temporary directory that's thrown away. So this is operating as designed 😄

**Comment by davidskalinder** [comment]
Ah, I see.  So IIUC that means that if a user only ever uses `check()` to run tests (and doesn't move any files manually), then:

1. a newly-created snapshot test will never fail
2. new snapshots will never be established, even if an old snapshot is already present

Both of these outcomes can be avoided in two ways: the user can find the temporary directory that `check()` creates and then manually copy the snapshot file into `[package]/tests/testthat/_snaps` (creating it if necessary); or `test()` can be run instead of `check()` (at least once after test creation to avoid item 1, and for every new snapshot to avoid item 2).

Have I got that right?  If so, that seems pretty counterintuitive, and like it could easily trick users who (like me) don't understand the details of how `check()` manages directories into the bad situation of believing that their tests are passing when they aren't?

Perhaps it's at least worth making this behavior clearer in the documentation?  [This passage](https://github.com/r-lib/testthat/blob/f8ccf033a74d89e2d1d3cb2ec3c6c4f63ca69055/vignettes/snapshotting.Rmd#L237) in the "Whole file snapshotting" section of the `snapshotting` vignette is the only place I can find in the `testthat` docs that suggests that `check()` might behave differently than other ways of running snapshot tests, and it doesn't mention the possibility of (apparent) false passes.  That passage mentions briefly that manually copying the snapshot can help, but gives no guidance on where that file would be, that the problem can be avoided by running `test()`, or that the behavior is not limited to `expect_snapshot_file()`.

In the meantime, my main takeaway is that it would be very easy to forget to do the laborious file-copying remedy every time a new snapshot is created, and so the best thing to do is simply to not trust `check()` to run snapshots and to use `test()` instead?

**Comment by davidskalinder** [comment]
> 2. new snapshots will never be established, even if an old snapshot is already present

Also worth noting is that without the manual-copying trick, this behavior renders useless the advice offered in the output of `check()` upon finding an old snapshot with changes:

```
devtools::check()
[...]
#>   Run `snapshot_accept('new-file')` if this is a deliberate change
[...]
snapshot_accept('new-file')
#> No snapshots to update
```

Again, I can't find any documentation of `snapshot_accept()` that makes this clear (though of course I could be missing something!).

**Comment by hadley** [comment]
Snapshots are fundamentally designed to be used as a part of an interactive testing flow; I think it's pretty rare to only use `check()` to run tests — you really should be using `test()` for your typical testing workflow.

**Comment by davidskalinder** [comment]
> Snapshots are fundamentally designed to be used as a part of an interactive testing flow; I think it's pretty rare to only use `check()` to run tests — you really should be using `test()` for your typical testing workflow.

Got it, that's what I'll do (and advise others to do).  Thanks!
