### ISSUE TITLE
Unicode mismatch in snaps is obfuscated on Windows

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1488]
My saga continues :smiley: 

I am running into an issue where the snapshot generated on Windows is show in CI as a mismatch, but appears to be mismatched invisibly:

https://github.com/MichaelChirico/potools/runs/4186076793?check_suite_focus=true

```
old[16:31] vs new[14:29]
  "Output"
  "  ------------------------------------------------------------------------"
  "  Oh no you don't!"
- "  <U+5F53><U+7136><U+4E0D><U+4F1A>!"
+ "  <U+5F53><U+7136><U+4E0D><U+4F1A>!"
  "Message <simpleMessage>"
  "   ** PLURAL MESSAGES **"
  "Output"
  "  ------------------------------------------------------------------------"
  "  small fail\\n"
- "  <U+5931><U+8D25><U+4E86>\\n"
+ "  <U+5931><U+8D25><U+4E86>\\n"
  "  ------------------------------------------------------------------------"
  "  big fail\\n"
- "  <U+5931><U+8D25><U+4E86>\\n"
+ "  <U+5931><U+8D25><U+4E86>\\n"
  "Message <simpleMessage>"
  "  Beginning new translations for zh_CN (Mainland Chinese/<U+666E><U+901A><U+8BDD>); found 2 untranslated messages"
  "  (To quit translating, press 'Esc'; progress will be saved)"
```

Because it's on CI I don't really have any way to look at the raw bytes & see why they're not matching

**Comment by hadley** [comment]
BTW you can download the check artefact and look at the actual files being compared. That might help narrow down the problem.

Thanks for being willing to keep walking into these rough edges 😄

**Comment by MichaelChirico** [comment]
The pay-off will be well worth it if it can happen.

Good idea to check the artefact! But I'm not sure it can help. I suspect whatever renderings been done (either CI VM --> GitHub upload or GitHub backend producing the Download log archive output) has flattened out the difference even at a byte level:

```
writeLines(data.table::tstrsplit(grep("Z [-+].*\".*U", gha_log, value=TRUE), " [+-] ")[[2]])
"  <U+5F53><U+7136><U+4E0D><U+4F1A>!"
"  <U+5F53><U+7136><U+4E0D><U+4F1A>!"
"  <U+5931><U+8D25><U+4E86>\\n"
"  <U+5931><U+8D25><U+4E86>\\n"
"  <U+5931><U+8D25><U+4E86>\\n"
"  <U+5931><U+8D25><U+4E86>\\n"
```

```
lapply(data.table::tstrsplit(grep("Z [-+].*\".*U", gha_log, value=TRUE), " [+-] ")[[2]], charToRaw)
[[1]]
 [1] 22 20 20 3c 55 2b 35 46 35 33 3e 3c 55 2b 37 31 33 36 3e 3c 55 2b 34 45 30 44 3e 3c 55 2b 34 46 31 41 3e 21 22

[[2]]
 [1] 22 20 20 3c 55 2b 35 46 35 33 3e 3c 55 2b 37 31 33 36 3e 3c 55 2b 34 45 30 44 3e 3c 55 2b 34 46 31 41 3e 21 22

[[3]]
 [1] 22 20 20 3c 55 2b 35 39 33 31 3e 3c 55 2b 38 44 32 35 3e 3c 55 2b 34 45 38 36 3e 5c 5c 6e 22

[[4]]
 [1] 22 20 20 3c 55 2b 35 39 33 31 3e 3c 55 2b 38 44 32 35 3e 3c 55 2b 34 45 38 36 3e 5c 5c 6e 22

[[5]]
 [1] 22 20 20 3c 55 2b 35 39 33 31 3e 3c 55 2b 38 44 32 35 3e 3c 55 2b 34 45 38 36 3e 5c 5c 6e 22

[[6]]
 [1] 22 20 20 3c 55 2b 35 39 33 31 3e 3c 55 2b 38 44 32 35 3e 3c 55 2b 34 45 38 36 3e 5c 5c 6e 22
```

**Comment by hadley** [comment]
Sorry, I meant download the .tar.gz of package that should be stored as part of the action

**Comment by MichaelChirico** [comment]
Sorry, I am still not quite following... what would I do with that .tar.gz? Without access to a Windows machine/VM, that is...

In any case, I am suspecting this may be a bug in testthat -- the snapshot _does_ have other non-ASCII characters in it:

```
grep -P "[^\x00-\x7f]" tests/testthat/_snaps/translate-package.md 
      Beginning new translations for zh_CN (Mainland Chinese/普通话); found 6 untranslated messages
      Found existing R translations for fa (Farsi/فارسی) in ./po/R-fa.po. Running msgmerge.
      Found existing R translations for zh_CN (Mainland Chinese/普通话) in ./po/R-zh_CN.po. Running msgmerge.
      当然不会！
      失败了\n
      失败了\n
      Beginning new translations for zh_CN (Mainland Chinese/普通话); found 2 untranslated messages
      Found existing R translations for zh_CN (Mainland Chinese/普通话) in ./po/R-zh_CN.po. Running msgmerge.
      Found existing src translations for zh_CN (Mainland Chinese/普通话) in ./po/zh_CN.po. Running msgmerge.
```

The mismatch in _`message()`_ output doesn't trigger this platform issue; the three cases triggering the fault are all in the `Output` sections. So I am now looking at why something captured as coming from `cat() / writeLines()` might be handled differently vs. `message()`

**Comment by hadley** [comment]
Hmmm, I can't see how you are you supposed to download it but the "Upload check results" uploads a tar.gz of the complete check directory, which will include the snapshot files (both old and new). Maybe @jimhester knows how to download it?

**Comment by MichaelChirico** [comment]
Oh, right! Now I see what you mean. The `.new.md` file is included in that. Found it!

And I am confirming the issue is what I was starting to suspect:

```
# IN _snaps/file.md
       ** SINGULAR MESSAGES **
    Output
      ------------------------------------------------------------------------
      Oh no you don't!
      当然不会！
    Message <simpleMessage>
       ** PLURAL MESSAGES **
    Output
      ------------------------------------------------------------------------
      small fail\n
      失败了\n
      ------------------------------------------------------------------------
      big fail\n
      失败了\n
```

vs

```
# IN _snaps/file.new.md AS RETRIEVED
       ** SINGULAR MESSAGES **
    Output
      ------------------------------------------------------------------------
      Oh no you don't!
      <U+5F53><U+7136><U+4E0D><U+4F1A>!
    Message <simpleMessage>
       ** PLURAL MESSAGES **
    Output
      ------------------------------------------------------------------------
      small fail\n
      <U+5931><U+8D25><U+4E86>\n
      ------------------------------------------------------------------------
      big fail\n
      <U+5931><U+8D25><U+4E86>\n
```

i.e., the "true" snaps are using the correct UTF-8 characters (`当然不会` etc.), while what's being produced on Windows is the 'unicodified' versions (literally `<U+5F53><U+7136><U+4E0D><U+4F1A>!`).

So they're indeed not matching, but it's become confusing because the diff that testthat displays unicodifies the original too. Updating the issue title to better reflect the UX issue.

Isn't encoding fun :)

**Comment by hadley** [comment]
Oh this is starting to bring back memories now — I think I looked into this but couldn't figure out how to make it work 😞 

In `local_reproducible_output()`, we automatically set `cli.unicode` to `FALSE` unless `unicode = TRUE` and:

```
  if (unicode) {
    # If you force unicode display, you _must_ skip the test on non-utf8
    # locales; otherwise it's guaranteed to fail
    skip_if(!l10n_info()$`UTF-8`, "non utf8 locale")
  }
```

I think @gaborcsardi probably remembers more about this.

**Comment by gaborcsardi** [comment]
I don't think it is possible to output UTF-8 characters on Windows.Is that what you are doing in the tests? 

I can't find the failures you showed in https://github.com/r-lib/testthat/issues/1488#issuecomment-968408570 Where are these test cases?

**Comment by MichaelChirico** [comment]
Let me try and make a minimal package that reproduces...

**Comment by MichaelChirico** [comment]
A minimal version of "testthat diff output looks the same even though the test fails" is at

https://github.com/MichaelChirico/test_snapshot/commit/d73b4234c43eede39a786f379556be31f045a2a7

That probably suffices for this issue.

PS I am still trying to reproduce my own issue, which is a bit more nuanced. Apparently some unicode output _does_ match on Windows, while others don't. If I can understand why that'll probably help me get unblocked.

**Comment by gaborcsardi** [comment]
Yes, that is not going to work, for a couple of reasons.

The main reason is that all functions that output text to the console will convert it to the native encoding, except when R is running in RGui (including RStudio).

For example on Windows you have this:
```r
oh <- "\u0151"
oh
#> [1] "o"

Encoding(oh)
#> [1] "UTF-8"

charToRaw(oh)
#> [1] c5 91
```

So far so good. But if you print it + capture it, then it is converted to native, latin1 in this case:

```r
woh <- capture.output(type = "message", message(oh))
woh
#> [1] "o"

Encoding(woh)
#> [1] "unknown"

charToRaw(woh)
#> [1] 6f
```

There are several things you could for your tests, depending on how far you are willing to go. 

The cli package has an internal function that can produce UTF-8 output on Windows. It internally flips a switch, so R thinks that it is printing to RGui, and then captures the output. To avoid messing up the current R session, it uses a sub-process. It works like this:

```r
u8oh <- cli:::r_utf8(function() message("\u0151", domain = NA))
u8oh
#> $status
#> [1] 0
#> 
#> $stdout
#> [1] "o\r\n"

Encoding(u8oh$stdout)
#> [1] "UTF-8"

charToRaw(u8oh$stdout)
#> [1] c5 91 0d 0a
```

However, note the `domain = NA` there. If you call gettext, then that will always convert to the native encoding AFAICT. (I haven't yet investigated if it is possible to get UTF-8 translated messages out of gettext.)

An easier way to go would be to 
1. record the test snapshots on an UTF-8 machine, and
2. skip the tests if the current platform is not UTF-8 (use ` l10n_info()$`UTF-8` to decide).

If you haven't done that yet, I suggest going through this: https://github.com/gaborcsardi/rencfaq/blob/main/what-every.md 
The README there has more information, but it is very incomplete. This is overkill for most people, but since you are dealing with translations, it might make sense to skim through it.

We should work out if it is possible at all to make gettext return UTF-8 text, and add the findings to that FAQ.

**Comment by gaborcsardi** [comment]
I have experimented a bit with gettext, and it seems that
- translations can be specified in various encodings (not very surprisingly),
- many translated message files in base R are in UTF-8, but not all.
- `gettext()` indeed converts the output to the current native encoding, even if the translation was not found. (Even if it is called from a package that does not have translations.) This is latin1 windows:

    ```r
    oh <- "\u0151"
    gettext(oh)
    #> [1] "o"
    Encoding(gettext(oh))
    #> [1] "unknown"
    charToRaw(gettext(oh))
    #> [1] 6f
    ```

So ideally, we would not pass any non-ascii text to `gettext()`. This also means that calling `message()`, `warning()`, `stop()` should be called with ASCII text only or with `domain = NA`. Or with condition objects, those are not translated.

**Comment by MichaelChirico** [comment]
Thanks Gabor. I'll take a closer look at your suggestions now, but I'm a bit hamstrung from not having Windows in front of me :\

Meanwhile, certainly I'd be a lot less puzzled if all of the non-ASCII strings I'm producing in my snapshot were getting dinged as wrong in the Windows CI. But what's odd is it's _only_ those three lines triggering the test failure:

https://github.com/MichaelChirico/potools/blob/13dc814ed386ab48c3818ac45e0af6c9b819fc96/tests/testthat/_snaps/translate-package.md?plain=1#L138-L147

Others, e.g. this one, don't show up as being mismatched:

https://github.com/MichaelChirico/potools/blob/13dc814ed386ab48c3818ac45e0af6c9b819fc96/tests/testthat/_snaps/translate-package.md?plain=1#L111

So in part I'm trying to understand why that's happening.

**Comment by gaborcsardi** [comment]
Can you create a simplified test for the ones that seem to show up correctly?

**Comment by hadley** [comment]
🤞 Hopefully this will disappear with the UCRT builds

**Comment by gaborcsardi** [comment]
> 🤞 Hopefully this will disappear with the UCRT builds

Mostly, yes, in a couple of years. But Unix systems can be non-UTF-8 as well, and I _think_ there is still such a CRAN machine.

**Comment by hadley** [comment]
@gaborcsardi ah good point. Do we have an example of configuring a non-UTF-8 check environment on mac/linux?

**Comment by gaborcsardi** [comment]
`debian-clang-devel` on R-hub, or the `rhub/debian-clang-devel` Docker image.

**Comment by hadley** [comment]
@gaborcsardi sorry, I meant can we configure on GHA?

**Comment by gaborcsardi** [comment]
It goes like this on Ubuntu:
https://github.com/r-hub/rhub-linux-builders/blob/18a40adb9811520b828d930905cbec113c0938b8/debian-clang-devel/Dockerfile#L21-L29
I can create an example workflow.

**Comment by hadley** [comment]
I updated @MichaelChirico's PR to use the latest version of testthat (which now uses brio everywhere, including in one key spot in `waldo::compare()`) and I no longer see the weird utf-8 differences (https://github.com/MichaelChirico/potools/runs/4710322075?check_suite_focus=true), so I think this is solved.
