### ISSUE TITLE
expect_snapshot fails in CI

### ISSUE THREAD

**Issue by kurt-o-sys** [r-lib/testthat#1504]
I'm having a project using `expect_snapshot`. I added `Config/testthat/edition: 3` to my `DESCRIPTION`.

When I'm running it locally (inside rstudio or in a terminal), all tests pass fine. However, when I run de tests (`devtools::test()`) in a CI (continuous integration), it fails.

If I just use `expect_snapshot(...)`, this is the result:
```
── 1. Error: beltpress additives check flow (@test_nutricas_nrr_additives_beltpr
could not find function "expect_snapshot"
[...]
```

So I tried to explicitely call it `testthat::expect_snapshot(...)` which results in:
```
── 1. Error: beltpress additives check flow (@test_nutricas_nrr_additives_beltpr
'expect_snapshot' is not an exported object from 'namespace:testthat'
Backtrace:
 1. testthat::expect_snapshot
 2. base::getExportedValue(pkg, name)
```

What am I missing? How can I make it work in the CI as well?

**Comment by hadley** [comment]
It sounds like you might not be installing the right version of testthat in your CI environment.
