### ISSUE TITLE
testthat 3.1.1 and empty lines in snapshots

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1509]
With testthat 3.1.1 empty lines are removed from snapshots.

E.g. if a function is

```r
bla <- function() {
  cli::cli_inform("thing")
  cli::cli_h2("bla")
  cli::cli_inform("another thing")
}
```

the snapshot will show no empty lines before and after the H2 whereas it used to.

**Comment by maelle** [comment]
The reason is https://github.com/r-lib/testthat/commit/ccc4194b4db29bf35104a507cfb531d017729ec8#diff-5d849f3782ddfdd6b0053b841b4be729f4fdaa33c9262caf6757aa185e5f5658

**Comment by zkamvar** [comment]
I'm curious, [if we went ahead and fixed these broken snaps](https://github.com/carpentries/sandpaper/commit/a4f657d14b66aacf7822af4b90718a5d7d2bc096), will they break again on a newer release?

**Comment by hadley** [comment]
Yes
