### ISSUE TITLE
`expect_error(call = )`

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#1517]
One way we could help authors check their error calls is to add a `call` argument to `expect_error()` and a global option that, if set, would make the following equivalent:

```r
expect_error(foo(...))
expect_error(foo(...), call = quote(foo(...)))
```

We could set `call = zap()` to disable the error call check.

This would dramatically increase test coverage for error calls without having to convert everything to snapshots. Thanks to the global option that makes call checking opt-in, the default behaviour would be backward compatible.

**Comment by hadley** [comment]
Also need to add to `expect_snapshot_error()`

**Comment by hadley** [comment]
Instead of an option for this, what if we made a 3.1 edition that turned on this behaviour + used the new rlang error formatting in snapshots?

**Comment by lionel-** [comment]
Good idea.

Also I guess the `call` check should loop through the parents. This would be consistent with message checking and improve resilience in case a tested error becomes wrapped by intervening code.

**Comment by hadley** [comment]
I agree that something like that is likely to be useful, but it feels a bit speculative at this point, so I'm going to close this issue. Feels like something we'll come back to in the future and will take us a few tries to get right.
