### ISSUE TITLE
expect_equal on dataframes with NA

### ISSUE THREAD

**Issue by tansaku** [r-lib/testthat#1518]
I am using `expect_equals` to compare two dataframes, however I'm finding that NA values seem to be mismatched.  I'm getting errors like this:

> Length mismatch: comparison on first 43 components
> Component “MyVar”: Modes: character, logical
> Component “MyVar”: target is character, current is logical

I appear to have replicated the issue like so:

```R
test_that('can compare NA in DFs', {
  df1 <- data.frame(test = 'NA',
                    stringsAsFactors = FALSE)
  df2 <- data.frame(test = NA)
  expect_equal(df1, df2)
})
```

> `df1` not equal to `df2`.
> Component “test”: Modes: character, logical
> Component “test”: target is character, current is logical

although I am not using 'NA' as a string in my failing test ... just wondering if there is some way to ensure that the NA equality is handled with a little more flexibility?

**Comment by hadley** [comment]
If you use the 3rd edition, you get a more informative message:

``` r
library(testthat)

test_that('can compare NA in DFs', {
  local_edition(3)
  
  df1 <- data.frame(test = 'NA', stringsAsFactors = FALSE)
  df2 <- data.frame(test = NA)
  expect_equal(df1, df2)
})
#> ── Failure (<text>:8:3): can compare NA in DFs ─────────────────────────────────
#> `df1` (`actual`) not equal to `df2` (`expected`).
#> 
#> `actual$test` is a character vector ('NA')
#> `expected$test` is a logical vector (NA)
#> Error: Test failed
```

<sup>Created on 2022-01-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The problem is that `NA` and `"NA"` are different things.
