### ISSUE TITLE
`expect_snapshot_output()` should not print to console

### ISSUE THREAD

**Issue by mgirlich** [r-lib/testthat#1552]
In one test I just want to check the message. I thought it makes most sense to use `expect_snapshot_output()` rather than `expect_snapshot()` but this print the message to the console which is not that nice when running the tests.

![image](https://user-images.githubusercontent.com/18258854/148953613-72fd6d67-96c0-4666-bcf9-6e499e402208.png)

``` r
testthat::expect_snapshot_output(message("a"))
#> a
#> Can't compare snapshot to reference when testing interactively
#> ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
#> ℹ Current value:
#> 

testthat::expect_snapshot(message("a"))
#> ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
#> ℹ Current value:
#> Code
#>   message("a")
#> Message <simpleMessage>
#>   a
```

**Comment by gaborcsardi** [comment]
`message()` does not produce (standard) output, it prints to standard error:
```r
❯ capture.output(message("a"))
a
character(0)
```
So I am afraid you'll need to use `expect_snapshot()`.

**Comment by mgirlich** [comment]
Wow, that's a fast response! Thanks.
I forgot about this annoying behaviour of `message()`... Now I remembered about `expect_message()` which works good enough for me.
