### ISSUE TITLE
Resolve/Evaluate variables in `expect_match()`

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/testthat#1557]
I am just learning about unit testing in R, and playing with the examples provided in https://r-pkgs.org/tests.html

I noticed when I run:
```
string <- "Testing is fun!"
test_that("string tests", {
  # Fails, match is case-sensitive
  expect_match(string, "testing")
})
```
The test fails, correctly; yet, the message states: 
```
── Failure (test_str_length.R:36:3): string test ───────────────────────────────
`string` does not match "testing".
Actual value: "Testing is fun!"
```

I actually expected that string gets evaluated on the message would rather be: `'Testing is fun!' does not match 'testing`

Or is that intended behavior, and I’m doing something wrong?

**Comment by hadley** [comment]
It's indented behaviour — it shows you what you typed in `expect_match()`.
