### ISSUE TITLE
Problem formatting test output expect_snapshot on GitHub CI actions

### ISSUE THREAD

**Issue by ambica-aas** [r-lib/testthat#1559]
Please help with the problem of different output on the received snapshot in the local PC and compare with the created snapshot on CI (GitHub action). The only difference is the formatting of the output due to the width, which will result in a test failure. See my picture.

![obrazek](https://user-images.githubusercontent.com/62553806/151161585-d2be313b-6daa-4046-b770-b26bfb019bb4.png)

Thank you for solving the problem. Any workaround would also help.

**Comment by gaborcsardi** [comment]
Is you package public? Can you share the code?

**Comment by ambica-aas** [comment]
Unfortunately, I do not have permission to publish the code. Repository is private. However, the output of the tested function is the sheet inside which is the tibble object.

**Comment by hadley** [comment]
I think you're mostly likely to find help asking at the tibble repo, as they might have some idea why you're seeing differences.
