### ISSUE TITLE
Snapshot error on Windows (encoding problem)

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1574]
In this reprex package https://github.com/maelle/encoding.problem I have a test

```r
test_that("multiplication works", {
  bla <- list(someone = "Maëlle")
  expect_snapshot_output(print(bla))
})
```

I created the snapshot on Ubuntu. On Windows the test fails https://github.com/maelle/encoding.problem/actions/runs/1845617963

With error 

```r
> test_check("encoding.problem")
Error in gsub("\n", paste0("\n", prefix), x, fixed = TRUE) : 
Error: Error: R CMD check found ERRORs
  input string 1 is invalid UTF-8
Calls: test_check ... vapply -> FUN -> paste0 -> indent_add -> paste0 -> gsub
Execution halted
```

Which comes from `indent_add()` and functions it calls.

**Comment by hadley** [comment]
Is this fixed in R4.2? If so, do you need it to work in R4.1 too? (It's likely to be a couple of hours work for me, so I'd prefer to use that time on other things if your motivating issue is resolved by updating R).

**Comment by maelle** [comment]
Indeed it now works https://github.com/maelle/encoding.problem/actions/runs/3103119734
We can definitely work without a fix :slightly_smiling_face:

**Comment by hadley** [comment]
I fixed this anyway, thanks to a @cderv's analysis and a hint from Kurt Hornik.
