### ISSUE TITLE
any way to weaken the "braces required" warning in test_that()?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1583]
The following throws  a warning:

```
test_that("desc", foo()))
```

in the test suite, this is fixed by adding inline braces:

```
test_that("desc", { foo() })
```

an issue with this is that `styler` explodes this:

```
styler::style_text('test_that("debug_reporter_test", { fun() })')
# test_that("debug_reporter_test", {
#   fun()
# })
```

It's even worse (IMO) for cases where the test description is long:

```
styler::style_text('
test_that(
  "A really long descriptive name for what this simple test is testing for",
  { expect_true(TRUE) }
)
')
# test_that(
#   "A really long descriptive name for what this simple test is testing for",
#   {
#     expect_true(TRUE)
#   }
# )
```

(this is because of the strict rules around braces in the style guide: https://style.tidyverse.org/syntax.html#indenting)

This is especially cumbersome in cases where we're writing a wrapper to `test_that` like

```
setup_teardown_test_that(x, desc, code) {
  setup(x)
  on.exit(teardown(x))

  test_that(desc, code)
}
```

is requiring `tryCatch()` for the `testthat_braces_warning` (or `suppressWarnings()`) really required here?

We are working on rule that blocks one-expression `{` usage because of all the extra whitespace it causes, it looks like we'll need a carve-out for `test_that()` 😐

_Originally posted by @MichaelChirico in https://github.com/r-lib/testthat/pull/1281#discussion_r818267041_

**Comment by hadley** [comment]
The problem is that without braces, you don't get good tracebacks, so you are giving up quite important functionality in when a failure occurs, in return for saving two lines of text.
