### ISSUE TITLE
Consistency of info= argument

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1594]
Should all `expect_*` have an `info=` argument?

We have a linter for `expect_equal(length(x), n)` to recommend `expect_length(x, n)` instead, but it can't apply in cases where `info=` is passed to `expect_equal()` because `expect_length()` doesn't have the corresponding argument.

Should it? Here's a quick pass at which `expect*` functions in testthat don't have an `info=` argument:

```
 expect_length
 expect_setequal
 expect_silent
 expect_type
 expect_gt
 expect_less_than
 expect_invisible
 expect_more_than
 expect_snapshot_error
 expect_failure
 expect_equal_to_reference
 expect_snapshot_file
 expect_vector
 expect_visible
 expect_lte
 expect_success
 expect_lt
 expect_s3_class
 expectation
 expect_snapshot
 expect_snapshot_value
 expect_cpp_tests_pass
 expect_known_hash
 expect_snapshot_output
 expect_s4_class
 expect_mapequal
 expect_gte
```

It would be nice to avoid the maintenance overhead of writing exceptions for which `expect*` linters need to be aware of whether `info=` is used/available: https://github.com/r-lib/lintr/issues/952

**Comment by MichaelChirico** [comment]
This also applies to the `label=` argument

**Comment by MichaelChirico** [comment]
OK... any plans to deprecate it in those expectations that currently have it?

**Comment by hadley** [comment]
In principle I think we should deprecate it (at least in the 3rd edition, although even that ship might have sailed), but it's unlikely that I'll find the time to do it since it's a relatively small payoff.

**Comment by MichaelChirico** [comment]
For completeness, what is the recommended refactor for cases already using `info=`?

For context, I'm looking at {DBItest}:

https://github.com/r-dbi/DBItest/blob/00060442200eb230350a308c37e30f797a371f95/R/expectations.R#L28-L31

There, `info=` is used to provide a better test failure in a wrapper expectation (where `expect_true()` might not be expected by the top-level caller, e.g.).

**Comment by hadley** [comment]
`label`?

**Comment by MichaelChirico** [comment]
c.f.

```r
expect_true(0 > 0, "Must be strictly positive!")
# Error: 0 > 0 is not TRUE

# `actual`:   FALSE
# `expected`: TRUE 
# Must be strictly positive!
expect_gt(0, 0, label="Must be strictly positive!")
# Error: Must be strictly positive! is not strictly more than 0. Difference: 0
```

`label` is about how the first argument `object` is "labelled"

https://testthat.r-lib.org/reference/comparison-expectations.html

**Comment by hadley** [comment]
Hmmm, for that case, I wonder if creating a new expectation is the right path (e.g. `expect_has_method()`)

**Comment by MichaelChirico** [comment]
That's good for this specific case, but the more general "what should I do when writing new expectations as wrappers of low-level ones" remains.

But I think the answer is, you should be using `expect()` directly in such cases, is that right?

https://testthat.r-lib.org/articles/custom-expectation.html

**Comment by hadley** [comment]
Yeah, I think so.
