### ISSUE TITLE
`stopifnot()` snapshots differently on R 3.4 vs. R >3.4

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1599]
I'm updating snapshots in some packages now that testthat 3.1.3 is out.

I find that `stopifnot()` snapshots differently on R 3.4 (aka oldrel-4) than on more recent versions of R.

---

Self-contained reprex. Save this as `foo.R`:

``` r
f <- function(x = "a") {
  stopifnot(x == "b")
}

testthat::local_edition(3)

testthat::expect_snapshot(f(), error = TRUE)
```

On R version 4.1.2 Patched I see:

```
> testthat::test_file("foo.R")

══ Testing foo.R ═══════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Can't compare snapshot to reference when testing interactively
ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
ℹ Current value:
Code
  f()
Condition
  Error in `f()`:
  ! x == "b" is not TRUE
 Done!
```

whereas on R version 3.4.4 (2018-03-15) (via RStudio Cloud), I see:
```
> testthat::test_file("foo.R")

══ Testing foo.R ════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Can't compare snapshot to reference when testing interactively
ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
ℹ Current value:
Code
  f()
Error <simpleError>
  x == "b" is not TRUE
 Done!
```

---

Here's what's happening in a real package.

The CI run when I updated googledrive's snapshots, note the ubuntu-18.04 (oldrel-4) failure:
https://github.com/tidyverse/googledrive/actions/runs/2079820862

Same outcome, after I tried depending explicitly on current rlang:
https://github.com/tidyverse/googledrive/actions/runs/2080590556

This is indicative of all the snapshot failures:

```
Snapshot of code has changed:
old vs new
 "Code"
 "  drive_extension(dribble())"
 "Condition"
- "  Error in `drive_extension()`:"
+ "  Error:"
 "  ! is.character(type) is not TRUE"
```

**Comment by jennybc** [comment]
It has not escaped my notice that we won't be testing on R 3.4 once R 4.2 comes out, hopefully later this month. So it is conceivable this is not worth addressing.

**Comment by hadley** [comment]
Now that 4.2 is out I think we can close this

**Comment by devo6970** [comment]
> I'm updating snapshots in some packages now that testthat 3.1.3 is out.
> 
> I find that `stopifnot()` snapshots differently on R 3.4 (aka oldrel-4) than on more recent versions of R.
> 
> Self-contained reprex. Save this as `foo.R`:
> 
> ```r
> f <- function(x = "a") {
>   stopifnot(x == "b")
> }
> 
> testthat::local_edition(3)
> 
> testthat::expect_snapshot(f(), error = TRUE)
> ```
> 
> On R version 4.1.2 Patched I see:
> 
> ```
> > testthat::test_file("foo.R")
> 
> ══ Testing foo.R ═══════════════════════════════════════════════════════════════════
> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Can't compare snapshot to reference when testing interactively
> ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
> ℹ Current value:
> Code
>   f()
> Condition
>   Error in `f()`:
>   ! x == "b" is not TRUE
>  Done!
> ```
> 
> whereas on R version 3.4.4 (2018-03-15) (via RStudio Cloud), I see:
> 
> ```
> > testthat::test_file("foo.R")
> 
> ══ Testing foo.R ════════════════════════════════════════════════════════════════════════════════════════════
> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Can't compare snapshot to reference when testing interactively
> ℹ Run `devtools::test()` or `testthat::test_file()` to see changes
> ℹ Current value:
> Code
>   f()
> Error <simpleError>
>   x == "b" is not TRUE
>  Done!
> ```
> 
> Here's what's happening in a real package.
> 
> The CI run when I updated googledrive's snapshots, note the ubuntu-18.04 (oldrel-4) failure: https://github.com/tidyverse/googledrive/actions/runs/2079820862
> 
> Same outcome, after I tried depending explicitly on current rlang: https://github.com/tidyverse/googledrive/actions/runs/2080590556
> 
> This is indicative of all the snapshot failures:
> 
> ```
> Snapshot of code has changed:
> old vs new
>  "Code"
>  "  drive_extension(dribble())"
>  "Condition"
> - "  Error in `drive_extension()`:"
> + "  Error:"
>  "  ! is.character(type) is not TRUE"
> ```
