### ISSUE TITLE
"Adding new file snapshot" reports confusing path

### ISSUE THREAD

**Issue by bersbersbers** [r-lib/testthat#1600]
`snapshot_file_equal` reports a file being created with an incorrect path, namely, `paste0("tests/testhat/_snaps/", snap_name)`. It is completely ignoring the other components of `snap_test_dir` (in particular, those between `"tests/testhat/_snaps"` and `snap_name`).

https://github.com/r-lib/testthat/blob/aab0464b555c27dcb2381af5f71c395a084a8643/R/snapshot-file.R#L174-L190

**Comment by hadley** [comment]
Fixed as part of #1610 where I noticed it.
