### ISSUE TITLE
local_reproducible_context() is active when the snapshot advice is printed

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#1606]
Which means that the advice will have no hyperlinks.

**Comment by hadley** [comment]
Ndd `self$local_user_output()` in the appropriate place in the reporter.

**Comment by hadley** [comment]
Hmmm, the challenge is that the hint is emitted by `expect_snapshot_helper()` which doesn't currently have any way to access the active ProgressReporter.
