### ISSUE TITLE
Run show() for S4 objects in expect_output?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1624]
IIUC `expect_output` is meant as a more concise way of doing `expect_match(capture.output(expr), pattern)` --> `expect_output(expr, pattern)`.

However that analogy breaks down for S4 objects because (IINM) S4 objects are auto-printed with `show()`, not `print()` or `cat()`:

```
# example from ?methods::show
setClass("track", slots = c(x="numeric", y="numeric"))
setClass("trackCurve", contains = "track", slots = c(smooth = "numeric"))
     
t1 <- new("track", x=1:20, y=(1:20)^2)
     
tc1 <- new("trackCurve", t1)
     
setMethod("show", "track",
  function(object)print(rbind(x = object@x, y=object@y))
)
```

The method will now be used for automatic printing of t1

```
t1
#   [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20]
# x    1    2    3    4    5    6    7    8    9    10    11    12    13    14    15    16    17    18    19    20
# y    1    4    9   16   25   36   49   64   81   100   121   144   169   196   225   256   289   324   361   400
```

The same comes from `capture.output()`:

```
capture.output(t1)
# [1] "  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15] [,16] [,17] [,18] [,19] [,20]"
# [2] "x    1    2    3    4    5    6    7    8    9    10    11    12    13    14    15    16    17    18    19    20"
# [3] "y    1    4    9   16   25   36   49   64   81   100   121   144   169   196   225   256   289   324   361   400"
```

But `expect_output()` fails (as expected given the current description in the manual that only `print()` / `cat()` are tried):

```
expect_output(t1, "x")
Error: `t1` produced no output
```

So, should `expect_output()` be extended for this case, or should such tests be completely relegated to snapshots?

**Comment by hadley** [comment]
`expect_output()` doesn't handle auto-printing, so yeah, either do `expect_output(print(t1), "x")` or use a snapshot test.
