### ISSUE TITLE
Vectorize `regexp` and `class` for `expect_{warning,message,condition}`

### ISSUE THREAD

**Issue by AshesITR** [r-lib/testthat#1625]
The 3e behaviour of only matching one warning seems useful as a default, however in the presence of multiple expected warnings, the test code gets very messy:

```r
expect_warning(
  expect_warning(
    expect_warning(
      expect_lint(
        file = "dummy_projects/project/partially_matched_exclusions.R",
        checks = rex::rex("semicolons"),
        parse_settings = FALSE
      ),
      rex::rex("Could not find linter named ", anything, "s")
    ),
    rex::rex("Could not find linter named ", anything, "bogus_linter")
  ),
  rex::rex("Could not find linters named ", anything, "hokus_pokus", anything, "bogus")
)
```

It would be very practical if `expect_warning()` and others were instead vectorised over their `regexp` and `class` arguments in the sense that the above code would be equivalent to

```r
expect_warning(
  expect_lint(
    file = "dummy_projects/project/partially_matched_exclusions.R",
    checks = rex::rex("semicolons"),
    parse_settings = FALSE
  ),
  regexp = c(
    rex::rex("Could not find linter named ", anything, "s"),
    rex::rex("Could not find linter named ", anything, "bogus_linter"),
    rex::rex("Could not find linters named ", anything, "hokus_pokus", anything, "bogus")
  )
)
```

That is, require exactly `length(regexp)` warnings to be issued and `warnings()[i]` to match `regexp[i]`.

**Comment by hadley** [comment]
I'd suggest using the pipe instead:

```R
expect_lint(
  file = "dummy_projects/project/partially_matched_exclusions.R",
  checks = rex::rex("semicolons"),
  parse_settings = FALSE
) |> 
  expect_warning(rex::rex("Could not find linter named ", anything, "s")) |> 
  expect_warning(rex::rex("Could not find linter named ", anything, "bogus_linter")) |> 
  expect_warning(rex::rex("Could not find linters named ", anything, "hokus_pokus", anything, "bogus")
```

Vectorising `expect_warning()` and friends would have pretty big consequences that we'd need to carefully analyse.

**Comment by AshesITR** [comment]
The pipe, if available, looks a bit cleaner indeed.

Vectorising would also allow for programmatic generation of the expected warnings, though.
Let me know if there are things I could do to help your assessment of this change.

See here for a workaround to achieve that:
https://github.com/r-lib/lintr/blob/1ae01287f9c97536e097715beb08e88a25632067/tests/testthat/test-linter_tags.R#L36-L54
