### ISSUE TITLE
FR: allow snapshot_review() to run in the background

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1634]
`snapshot_review()` is an incredible tool, but running it can be cumbersome, as starting the nice shiny interface will forbid further use of the console.

Would it be possible to have it run in a background process?

For now I'm using this code which works quite well, although I can't get it to open the interface in the Viewer:

```r
snapshot_review_bg = function(...){
    # brw = function(url) .Call("rs_browseURL", url, PACKAGE="(embedding)") #not working
    brw = Sys.getenv("R_BROWSER")
    callr::r_bg(function() testthat::snapshot_review(...),
                package=TRUE,
                env = c(R_BROWSER = brw))
}
snapshot_review_bg ("my-test")
```

The problem of having them outside RStudio is that plainly closing the web page (without hitting Accept) seems to have Rterm.exe processes hanging around for nothing (but maybe I'm using `callr` wrong).

For reference, https://wlandau.github.io/posts/2020-12-18-non-blocking-app/ used another approach using `{target},`.

BTW, the info message when running `snapshot_review()` might be true on Linux but not on Windows (where is should be `Echap` instead of `Ctrl+C`):

>      Starting Shiny app for snapshot review
>      i Use Ctrl + C to quit

**Comment by hadley** [comment]
I think we'd only want to do this in testthat if shiny offered some standard way of running without blocking the console. Otherwise, as you've noticed it'll be hard to get rid of the external processes.
