### ISSUE TITLE
Add `expect_snapshot_message()`

### ISSUE THREAD

**Issue by dpprdan** [r-lib/testthat#1641]
I think a `expect_snapshot_message()` should be added 

1. for consistency. There are `expect_snapshot_error()` and `expect_snapshot_warning()` (#1536). 
2. because "sometimes you just want to capture the ~~output or errors~~ message in which you might want to use ~~[expect_snapshot_output()](https://testthat.r-lib.org/reference/expect_snapshot.html) or [expect_snapshot_error()](https://testthat.r-lib.org/reference/expect_snapshot.html)~~ `expect_snapshot_message()`." 
quote from https://github.com/r-lib/testthat/blob/426eb523f6772c76175d6e8d7ca04355b1ee7ad5/vignettes/snapshotting.Rmd#L216
3. one might want to use the explicit `class` argument (cf. https://github.com/r-lib/testthat/pull/1616#issuecomment-1116208903)

This is futile of course, should `expect_snapshot_error()` be discouraged/deprecated (#1548, #1616)

**Comment by hadley** [comment]
I think we generally to want steer people awy from the individual snapshot helpers and towards `expect_snapshot()`, so I don't think we want to add `expect_snapshot_message()`.
