### ISSUE TITLE
Change the structure of package autotesting: from "tests/testthat/*" to "tests/*"

### ISSUE THREAD

**Issue by avraam-inside** [r-lib/testthat#1644]
Hi! 

I actively use the autotesting functionality, there are already hundreds of tests and dozens of test files in the package, and for many months of work I have felt the MAXIMUM discomfort from an extra click on `tests/testthat/*`.

As a user, this extra nesting seems a bit superfluous to me.

There is some magic combination of settings via `options`/`.Rprofile`/etc which will allow me to place test files immediately in the `tests/` folder, without `testthat/`-folder?

**Comment by hadley** [comment]
No, it's not possible with the way that testthat is designed, sorry.

**Comment by avraam-inside** [comment]
> No, it's not possible with the way that testthat is designed, sorry.

Why is it impossible? It is only expected to delete the extra folder level. This extra click on the folder is not particularly useful.

**Comment by avraam-inside** [comment]
Sorry, I forgot about our conversation...

In general, I did the "impossible":
```r
test <- function() {
    testthat::test_dir(here::here('tests'))
    return(invisible(NULL))
}

testFile <- function() {
    testthat::test_file(rstudioapi::getSourceEditorContext()$path)
    return(invisible(NULL))
}
```

And I read the documentation well, but it's IMPOSSIBLE not to go directly into the file, I have a lot of fine work with environments, folders, etc. that needs to be debugged directly in tests. In python, I also go directly to the test files with colleagues when we test the backend of the Process Mining web service.

But in a good way, take and drag these functions directly into testthat, so that it is not my local setting.
