### ISSUE TITLE
Ability to transform output printing in expect_snapshot()

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1651]
For instance if one is testing a function that outputs a tibble, the default printing of tibble in the snapshot file might be less preferrable than JSON.

I wonder whether something like a new argument

```r
expect_snapshot(code, transform_output = function(x) toJSON(x, pretty = TRUE))
```

would make sense.

This might actually be related to @krlmlr's comment in another issue: https://github.com/r-lib/testthat/issues/1294#issuecomment-1068867832=

**Comment by hadley** [comment]
Yeah, lets close in favour of that other issue.
