### ISSUE TITLE
expect_snapshot fails to create the snapshot when the test_that desc has more than one line

### ISSUE THREAD

**Issue by zsigmas** [r-lib/testthat#1654]
# Problem
When test descriptions are long it is nice to break them in two lines, so they are readable without side-scrolling.

# Reproducible by
Using this as a test file
```r
test_that(
    "TWO
    LINES",{
        "A" %>% expect_snapshot()
    }
)

test_that(
    "SINGLE LINE",
    {
        "A" %>% expect_snapshot()
    }
)
```

The first test keeps throwing a warning and continuously rewriting the snapshot for that test.

### Contents of snapshot
```
# TWO
    LINES

    Code
      .
    Output
      [1] "A"

# SINGLE LINE

    Code
      .
    Output
      [1] "A"
```

### Possible solution
Maybe identifying the snapshot by a hash of the description and include the description below, for human-readability?

Thanks!

**Comment by hadley** [comment]
test names should only be a single line; we don't have any plan to support multi-line names.
