### ISSUE TITLE
`expect_output` not match?

### ISSUE THREAD

**Issue by josherrickson** [r-lib/testthat#1658]
Is there a way to use `expect_output` to check for the absence of a particular regexp? I'd like to check if particular inputs/arguments suppress certain parts of the output, so I need to ensure that the regexp isn't matched. I could do it manually with `capture_output` but it seems like there should be a way to do it directly in `expect_output` (or a similar function, e.g. `expect_not_in_output`).

**Comment by hadley** [comment]
I'd suggest doing it manually for now.
