### ISSUE TITLE
Inconsistent loading of methods

### ISSUE THREAD

**Issue by ms609** [r-lib/testthat#1661]
I am running tests in my package "TreeSearch" that make use of S4 methods in an underlying package "TreeTools".

When I run tests interactively, or using the "Run tests" button for a single test file within RStudio, the correct methods are loaded from TreeTools and used; the tests pass.

When I run the entire test suite using the Build tab (Shift-Ctrl-T), the methods are not loaded; the tests fail.  The tests also fail at `R CMD check`.

Here's a minimal reproducible example:

```r
library("TreeTools") # Same results are seen if the library is loaded within the test function

test_that("Methods are loaded", {
  print(findMethods(`%in%`))
  expect_gt(length(findMethods(`%in%`)), 1) # Is the %in%,Splits,Splits-method found?

  # The "Splits" %in% method returns a named vector; the generic does not return names
  expect_equal(
    length(names(as.Splits(BalancedTree(8)) %in% as.Splits(PectinateTree(8)))),
    5
  )
})
```

Am I missing something here?  (I'm not super familiar with S4 methods.)  It seems strange that testthat's behaviour would differ depending on how tests are initiated.

## Additional details

Running R-devel on Windows 10 in RStudio 2022.06.0

testthat 3.1.4.9000 downloaded from GitHub 2022-07-22

My `test/testthat.R` file contains
```r
library("testthat")
library("TreeSearch")

test_check("TreeSearch")
```

**Comment by hadley** [comment]
Unfortunately there's not much we can do about this. It's likely to be a bug in either pkgload or S4, but it would require significant effort to track down and we don't currently have the resources.
