### ISSUE TITLE
expect_identical do no destinguish NA from NaN

### ISSUE THREAD

**Issue by sorhawell** [r-lib/testthat#1671]
Hello wonderful people. 

I was wondering if code example below is the intended behavior of testthat::expect_identical()

I'm running testthat 3.1.4 on macOS

```
  #yields failure
  expect_true(identical(NA_real_,NaN))
  
  #yields to my surprise a success
  expect_identical(NA_real_,NaN)
```

**Comment by hadley** [comment]
Looks like a waldo issue so tracking in https://github.com/r-lib/waldo/issues/150
