### ISSUE TITLE
`skip_if_auto_test`: option to skip some test when using `auto_test()` or `auto_test_package()`

### ISSUE THREAD

**Issue by StatisMike** [r-lib/testthat#1698]
I am curently developing a package wrapping around some external REST API. There are a lot of simple tests for objects and requests constructors and response translations which run lightingly-fast and are ideal for `auto_test()` and `auto_test_package()`. I think it would be helpful if there was a `skip_if` helper that would allow skipping longer running tests (in my example: request send and response verification).

Currently I need to add `skip()`  when developing code to all of these longer-running tests (for `auto_test_package()`) or keep all fast-running tests in different directory (for `auto_test()`).

Unless there is actually some option for that already - I would suggest adding it to `auto_test()` documentation.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
