### ISSUE TITLE
The text "Done!" is not showing in the workbench results 

### ISSUE THREAD

**Issue by astayleraz** [r-lib/testthat#1707]
We started to see this test fail with build 2022.12.0-daily-267 on Oct 12, 2022 4:05 AM.  We have some test testing testthat and they are failing as we are expecting it to show `Done!` at the end of the results. The test checks for the text `Test complete` already so that is good but this check fails: `expected: [ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ] Done!`

Kevin mentioned it might be it thinks it is not RStudio. https://github.com/r-lib/testthat/blob/05b07d4353ff0c2ec81e90a7110476b613a1cd2d/R/reporter-progress.R#L367-L369

Below is the test that we run and the output.

<img width="1050" alt="Screen Shot 2022-10-14 at 9 10 31 AM" src="https://user-images.githubusercontent.com/1482677/195896195-ce057d42-e644-4498-be70-b0ebd63cf26a.png">

**Comment by hadley** [comment]
Can you provide a bit more detail about exactly how you're running the tests?

**Comment by astayleraz** [comment]
This is the steps we take to do this and assumes any expected packages are installed.

1. In the console type `.rs.api.executeCommand('newSourceDoc')`
2. Add the following to the source doc:
```
library(testthat)
test_that("Sample tests", {expect_equal(1, 1)})
```
3. Save the file.
4. Click the Run Tests button.
5. observe Tests tab output.

expected: [ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ] Done!

Note: I just ran this now and I see the following which seems odd.

```
==> Testing R file using 'testthat'

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ]
Test complete
```

**Comment by hadley** [comment]
The multiple line issue is #1561 come back to life. Sounds like everything else is ok from the IDE side.
