### ISSUE TITLE
Test results are mixed-up with `cat()` outputs of tested functions

### ISSUE THREAD

**Issue by netique** [r-lib/testthat#1708]
There is a strange output in both RStudio and GitHub Actions when the function being tested (or the test itself) prints to the console via `cat()` and, possibly, others. It is not apparent in `reprex`:

``` r
test_code <- '
test_that("cat is not cut", {
  cat("Lorem ipsum dolor sit amet...")
  expect_true(TRUE)
})
'

temp_file <- tempfile()

writeLines(test_code, temp_file)

testthat::test_file(temp_file)
#> 
#> ══ Testing file7ed178c5cc1b ════════════════════════════════════════════════════
#> 
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Lorem ipsum dolor sit amet...
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ] Done!
```

<sup>Created on 2022-10-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

However, in the console or Build pane in RStudio (or in GHA log), this output is shown to me:

<img width="615" alt="Snímek obrazovky 2022-10-14 v 22 17 00" src="https://user-images.githubusercontent.com/34926852/195934887-fcd158d0-3137-4654-ac8d-ac9781d28aac.png">

I don't know, but this seems like a carriage return thing or so, but I don't understand testthat reporters nor the output mechanism (R6 is a little bit hard to debug for me).

Have you encountered a similar issue? I think there should be a global option to suppress any console output of the tested, but that's for another issue I guess (I'm aware of `testthat_print` generic, but I do not fancy creating methods for every outputting function in my package).

Thanks for any insight!

**Comment by hadley** [comment]
In general, we believe it's your responsibility to suppress additional output. We preserve it because it's occasionally useful when debugging your own tests (particularly if they crash the R session). If we swallowed all output, there'd be no way to debug.

**Comment by hadley** [comment]
It suggests that the output is missing a final new line.

**Comment by netique** [comment]
Just FYI, I reported that on 3.1.4. For the current 3.1.5, it works seamlessly. Maybe changes around {crayon} -> {cli} helped. Thank you!
