### ISSUE TITLE
Compiled code warning on CRAN R-devel from `test-runner`

### ISSUE THREAD

**Issue by danielinteractive** [r-lib/testthat#1715]
Hi testthat developers,

we just got an email from the CRAN team that warns as follows about https://github.com/openpharma/mmrm/blob/main/src/test-runner.cpp which is merely the standard file from `testthat` for C++ unit tests:
![image](https://user-images.githubusercontent.com/1071227/205735949-9e29c319-ace9-46d3-810e-c51800281474.png)
(see https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/mmrm-00check.html for the full log).
This is on R-devel (starting from 2022-12-03 r83400), but it seems only on Linux OS (Debian, Fedora) and not Windows.

I would guess this is observed in other R-packages using the Catch framework via `testthat` as well. Is there something we can help to fix this in `testthat`? (and as you would guess we only have 13 days now to fix this...)

Thanks,
best regards
Daniel

**Comment by danielinteractive** [comment]
@hadley @lionel- fyi

**Comment by lionel-** [comment]
I see that testthat got the warning on r-devel as well: https://cran.r-project.org/web/checks/check_results_testthat.html

Can you please tell them that this warning comes from files in included from our `inst/` folder, that CRAN checks already flag us for it, and that we'll send a fix soon @danielinteractive?

**Comment by danielinteractive** [comment]
Thanks @lionel- we still have some other fixes to address CRAN problems, but if we submit our next version before `testthat` is ready I will mention that, yes. Thanks for working on this!

**Comment by lionel-** [comment]
From https://github.com/wch/r-source/commit/a0dfa3df365e3ee2b4496fc2374963ff20da7043

**Comment by hadley** [comment]
Fixed in #1716

**Comment by hadley** [comment]
@danielinteractive I think you'll need to install dev testthat and then run `use_catch()` in your package to fix this.

**Comment by danielinteractive** [comment]
Thanks @hadley and team for the super fast fix!
(So this does not impact us locally anyway, basically it is just a CRAN check problem. As soon you have the new `testthat` version on CRAN it will fix the problem for us on CRAN.)
