### ISSUE TITLE
Hyperlinks in test output are broken if test run in parallel

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#1719]
I ran the {dm} tests locally with a fairly recent RStudio daily build and I see this when clicking that `test-zoom.R:99` hyperlink you see in the background

<img width="1181" alt="Screen Shot 2022-12-12 at 11 09 56 AM" src="https://user-images.githubusercontent.com/19150088/207095425-b86b5091-b592-45fe-99c5-70b0dfca33e5.png">

The error box shows that it isn't looking in the right place for that test file

dm uses `Config/testthat/parallel: true` and if I set it to `false` and rerun then the links work

I'm not sure if this can be fixed, but probably?

```r
> packageVersion("testthat")
[1] ‘3.1.6’
> packageVersion("cli")
[1] ‘3.4.1’
```

RStudio 2022.12.0-preview+299 "Elsbeth Geranium" Preview (24e7bc9fedf84de448c6476fcb6844f1da2c034f, 2022-11-01) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0-preview+299 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by DanChaltiel** [comment]
I have the same issue with Rstudio "Elsbeth Geranium" Release (7d165dcf, 2022-12-03) for Windows when testing package {crosstable}.

**Comment by hadley** [comment]
I'm pretty sure it's this issue: https://github.com/r-lib/cli/issues/587
