### ISSUE TITLE
Set the number of workers in RStudio

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1723]
Hi,

When using multiple files in parallel, we can use options or envvar to control the number of workers, as per [the documentation](https://testthat.r-lib.org/articles/parallel.html#basic-operation).

However, when using the "Test" button in RStudio's "Build" pane, the number of workers is 2, whatever the configuration (see https://stackoverflow.com/q/74938469/3888000 for some tests in helpers or in .Rprofile).

In https://github.com/r-lib/testthat/issues/1114#issuecomment-674754455, it was proposed to add some control in the DESCRIPTION file, this would be awesome!

I guess `Config/testthat/target-ncpus` would make a nice name, as it seems it can be overridden by the envvar `TESTTHAT_MAX_CPUS`.

**Comment by hadley** [comment]
You can set `TESTTHAT_CPUS` in your `.Renviron`

**Comment by fh-mthomson** [comment]
It took me a bit to find this great option via issues. Would it be possible to add this to the Vignette?
