### ISSUE TITLE
expect_silent() doesn't have an opposite expectation - either with a parameter, a sister function, or negation

### ISSUE THREAD

**Issue by daattali** [r-lib/testthat#1724]
Related to #303

Test for output: `expect_output(x)`
Test for no output: `expect_output(x, NA)` 
Test for warning: `expect_warning(x)`
Test for no warning: `expect_warning(x, NA)`   (or the experimental expect_no_warning)
Test for message: `expect_message(x)`
Test for no message: `expect_message(x, NA)`   (or the experimental expect_no_message)

If I want to combine all of them to a more general test, I can use `expect_silent(x)`. But:
- `expect_silent()` doesn't support another parameter
- There is no `expect_not_silent()`
- Using a `not(expect_silent())` does work, but it's deprecated

Therefore, I cannot find a non-deprecated way to expect not silent

**Comment by hadley** [comment]
I think we'd generally expect you to assert what the function does it, e.g. use one of `expect_output()`, `expect_message()` etc.
