### ISSUE TITLE
Hyperlink to r-pkgs.org broken

### ISSUE THREAD

**Issue by annweideman** [r-lib/testthat#1728]
The hyperlink in `testthat.R` file in tests folder is broken. Perhaps update to https://r-pkgs.org/testing-basics.html ?

```
This file is part of the standard setup for testthat.
# It is recommended that you do not modify it.
#
# Where should you do additional test configuration?
# Learn more about the roles of various files in:
# * https://r-pkgs.org/tests.html
# * https://testthat.r-lib.org/reference/test_package.html#special-files

library(testthat)
library(Canopy2)

test_check("Canopy2")}
```

**Comment by zknitter** [comment]
+1 on this issue. 
This broken link is also present in testthat's [`_pkgdown.yml`](https://github.com/r-lib/testthat/blob/main/_pkgdown.yml) at line 16.

**Comment by hadley** [comment]
Link to check that redirect works: <https://r-pkgs.org/tests.html>

**Comment by hadley** [comment]
Now fixed 😄
