### ISSUE TITLE
Option to call `test_local()` with `NOT_CRAN = "false"`

### ISSUE THREAD

**Issue by larmarange** [r-lib/testthat#1737]
On CRAN, there are checking that overall check time is < 10 minutes.

Therefore, it could be helpful to run all tests of a local package with `NOT_CRAN = "false"` to identify where tests are long to run and where it could be relevant to add `skip_on_cran()`

It would be therefore useful to have an option to call `test_local()` with `NOT_CRAN = "false"`. Currently, `NOT_CRAN` is set to `"TRUE"` within `test_local()`, cf. https://github.com/r-lib/testthat/blob/9cd6e01be008376b1f7f2d8d528d725b87c0d01e/R/test-package.R#L64

**Comment by hadley** [comment]
I think it will be hard for folks to find this option. Instead, I think you could look at the timings that (e.g.) `devtools::test()` reports for each file, and use that to narrow down where the slow tests are.

**Comment by larmarange** [comment]
The issue with `devtools::test()` id that it provides the total run time of all tests within the file. If you have many tests skipped on CRAN, it does not provide the timing of the tests run by CRAN checks. You will have to manually check the run time of each tests within your test file.

Ideally, the best would be to have an option `devtools::test(NOT_CRAN = FALSE)`

**Comment by larmarange** [comment]
But to implement it, you need to have such an option in `testthat::test_local()`, i.e. a NOT_CRAN option when calling the function.

Right now, `testthat::test_local()` force `NOT_CRAN = "true"`

**Comment by hadley** [comment]
See also #1466

**Comment by larmarange** [comment]
thanks
