### ISSUE TITLE
Should the namespace in each `test_that()` call be isolated?

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/testthat#1759]
Related [SO post](https://stackoverflow.com/questions/75822979/why-do-packages-loaded-inside-test-that-provide-their-methods-outside-of-te)

### Description

Sometimes, we want to load external packages in tests. One example is if our package provides functions and methods for a lot of different models. In this case, we load the packages that implement these models in the tests so that we can check the outputs of our functions.

The problem is that even if we load the packages inside `test_that()` and split the tests across different `test-*` files, loading the packages also "contaminates" the namespace in other `test_that()` calls, and this can have side effects.

### Reprex

In the example below, we can see that loading `insight` in the second test contaminates the namespace of the third test:
``` r
library(testthat)
packageVersion("testthat")
#> [1] '3.1.7.9000'

test_that("foo 1", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] FALSE
#> ── Skip (???): foo 1 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 2", {
  invisible(insight::get_parameters)
})
#> ── Skip (???): foo 2 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 3", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] TRUE
#> ── Skip (???): foo 3 ───────────────────────────────────────────────────────────
#> Reason: empty test
```

### Issue / question

Someone answered my SO post saying that it's not possible to clean the namespace with a function, the most reliable way to do so being to restart R (the answer there uses a more vanilla testing framework, which is why I'm opening this issue).

1. I guess this is correct but can you confirm this?
2. If `testthat` cannot deal with this, even using [test fixtures](https://testthat.r-lib.org/articles/test-fixtures.html), I think this should be mentioned in the docs as it is probably undesirable.

**Comment by hadley** [comment]
We have a discussion of this in https://r-pkgs.org/testing-design.html#sec-testing-design-self-contained; I think this is generally a bit outside of the scope of the testthat docs.
