### ISSUE TITLE
Allow `expect_snapshot_value()` to ignore attributes

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#1772]
Attributes are often of lesser importance and checking on them unnecessarily clutters the output. 

For instance, `expect_snapshot_value(x, ignore_attributes=TRUE)` would be very nice to use.

Also, this could sometimes allow using nicer styles, as shown in #1771.

**Comment by hadley** [comment]
Isn't `...` already passed on to `waldo::compare()`? That's certainly what the docs and code suggests to me.
