### ISSUE TITLE
Line starting 'Config/testthat/edit ...' is malformed!

### ISSUE THREAD

**Issue by dbdimitrov** [r-lib/testthat#1783]
Hi,

Recently, some (windows?) users of a tool I developed have been unable to install it due to the following error message:
```
Error: Failed to install 'unknown package' from GitHub:
Line starting 'Config/testthat/edit ...' is malformed!
```

I'm not able to reproduce their issue (Ubuntu user), so I was hoping that you might know what might be the cause.

https://github.com/saezlab/liana/issues/109
https://github.com/saezlab/liana/issues/102

Thanks in advance.
Daniel

**Comment by hadley** [comment]
No idea, sorry. And without any other examples of the problem, it's hard to know what might be causing it.
