### ISSUE TITLE
Bug with parallel testing + file snapshots

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#1811]
I've installed dev testthat and see weird behavior for a package that uses parallel testing and snapshot tests of files. Originally that package is [fledge](https://github.com/cynkra/fledge/) but I've created [snappy](https://github.com/maelle/snappy) as a reprex.

- There's an error in the test run. As the latest commit breaks the test by changing what's in the file, I'd expect an error à la "the snapshot was modified". https://github.com/maelle/snappy/actions/runs/5176278617/jobs/9324893919
- The snapshot file is deleted (at least on my machine but not in the log above :zany_face: ). I also got this before my latest testthat installation but don't get this with the CRAN version.

**Comment by hadley** [comment]
Yeah, I'm seeing this locally too as I'm working on re-enabling parallel testing for testthat itself.

(FWIW the CRAN version never deletes any snapshots, which was a different bug that we're trying to fix)
