### ISSUE TITLE
Testthat trace_length() resulting in || failure with reticulate?

### ISSUE THREAD

**Issue by pbulsink** [r-lib/testthat#1833]
An issue [originally raised in r-lib/rlang](https://github.com/r-lib/rlang/issues/1637) looks like it belongs better here.

Errors raised by reticulate via rlang might cause `trace_length()` to return an NA or length 0 vector, which is causing `||` to error at https://github.com/r-lib/testthat/blob/53cd6dd53eeaadd4229c4702f380ca283ec74b52/R/expectation.R#L165

Minimal reprex from @t-kalinowski below:

```
ex <-reticulate::py_eval("Exception('msg')")

# ex is a condition, fulfills the condition contract
inherits(ex, "condition")
#> [1] TRUE
cat(conditionMessage(ex))
#> Exception: msg
#> Run `reticulate::py_last_error()` for details.
conditionCall(ex)
#> NULL

# cnd_type(ex) signals an error
rlang::cnd_type(ex)
#> Error in `rlang::cnd_type()`:
#> ! `cnd` is not a condition object.
#> Backtrace:
#>     ▆
#>  1. ├─rlang::cnd_type(ex)
#>  2. └─rlang::abort(message = message)
```

See original [CMD CHK workflow errors](https://github.com/SCasanova/f1dataR/actions/runs/5385032984/jobs/9773619355) from [scasanova/f1dataR](https://github.com/SCasanova/f1dataR/issues/105) if you need more info

**Comment by lionel-** [comment]
Thanks, however this is much more likely to be an rlang or reticulate issue. We'll be tracking from rlang.
