### ISSUE TITLE
Should `with_mocked_bindings()` follow withr argument style?

### ISSUE THREAD

**Issue by jameslairdsmith** [r-lib/testthat#1834]
I got momentarily confused using `with_mocked_bindings()` because I'm used to using withr, where the `with_*` functions have the temporary state as the first argument, and the `code=` as the second argument. withr also usually makes `new=` its own argument rather than using the dots. I don't know if it's worth harmonising `with_mocked_bindings()` with that pattern?

**Comment by hadley** [comment]
I think it's probably too late for that 😞
