### ISSUE TITLE
Override subset operators 

### ISSUE THREAD

**Issue by FlippieCoetser** [r-lib/testthat#1847]
Given I explicitly and on purpose override subset operators: `env[['[[.' |> paste0(component)]] <- getter` where getter is a function and component a specific class. When running a unit test I get an error saying bindings are locked.

However, when I test the intended functionality manually using the terminal everything works as expected.

How can I allow the override of subset operators inside the environment used by testthat, for one specific test? 
It seems such use case is not supported. If true, this is a feature request to support the above use case

**Comment by hadley** [comment]
You'll need to change the bindings in a different environment. `rlang::local_bindings()` might be helpful.
