### ISSUE TITLE
`find_edition()` / `find_description()` may have too strong a preference for an installed package

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1858]
This is a discovery made during the package development masterclass as posit conf.

We asked participants to check the test coverage for `hadley/stringb` and there would be no reason for anyone to have _installed_ that package. And `devtools::test_coverage()` fails in this case.

```
> devtools:::test_coverage()
ℹ Computing test coverage for stringb
Error in idesc_create_package(self, private, package) : 
  Cannot find DESCRIPTION for installed package stringb
```

It goes like this: `devtools::test_coverage()` ➡️ `testthat::local_test_directory(pkg$path, pkg$package)` ➡️ `find_edition(path, package)` ➡️ `find_description(path, package)`:

https://github.com/r-lib/testthat/blob/29018e067f87b07805e55178f387d2a04ff8311f/R/edition.R#L14C1-L23

I think `find_description()` is too eager to consult an installed package. It seems to assume that's safe and preferred if you happen to know the package's name.

I was able to "fix" the devtools problem by not passing the package name, but I don't think that's a great solution (https://github.com/r-lib/devtools/pull/2536). That has other downsides, e.g., the package name won't be available for setting the `TESTTHAT_PKG` environment variable.

https://github.com/r-lib/testthat/blob/29018e067f87b07805e55178f387d2a04ff8311f/R/local.R#L188

**Comment by hadley** [comment]
Consulting that `path` isn't going to work either (and I can't see that it ever did) because the `path` is to the test directory, not the package directory.

**Comment by hadley** [comment]
Maybe `test_coverage()` just shouldn't call `local_test_directory()` at all? `package_coverage()` installs the package to a temporary location and then calls `testInstalledPackage()` which presumably calls `tests/testthat` and there is already existing infrastructure to correctly detect the edition?

**Comment by hadley** [comment]
Also need to consider `test_coverage_active_file()`.

**Comment by hadley** [comment]
I've made https://github.com/hadley/testcoverage as a test — it contains two tests that will fail if either the edition or the `TESTTHAT_PKG` are set incorrectly.
