### ISSUE TITLE
`rlang::local_interactive()` causes snapshot tests to be run on CRAN

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1868]
I discovered this while doing revdep checks for the glue branch that proposes a change to the print method. I saw one failure that used `capture.output()` on a printed glue object, which is not a surprise.

But then I saw another failure in pillar for a snapshot test and it is **not** a case of `expect_snapshot(cran = TRUE)`. It's a normal snapshot test, so it should never error when `NOT_CRAN` is unset.

But this particular test needs a `local_interactive()` to trigger the user-facing output that's being snapshotted:

https://github.com/r-lib/pillar/blob/92095fcc0fffa6d2b2d42c3ec6017e7501c0c99b/tests/testthat/test-tbl-format-footer.R#L94-L100

From testthat's tests, it seems like this behaviour might be known / intentional:

https://github.com/r-lib/testthat/blob/fe01a6308153d30309ef9bf28c385848818bb96c/tests/testthat/test-skip.R#L68-L69

But is that really how it should be? I think it means you can't use snapshot tests in combination with `local_interactive()`. Or I guess you have to place an explicit `skip_on_cran()` in such a test, before the `local_interactive()` call.

**Comment by jennybc** [comment]
Maybe this should be `interactive()` instead of `is_interactive()`:

https://github.com/r-lib/testthat/blob/fe01a6308153d30309ef9bf28c385848818bb96c/R/skip.R#L252

**Comment by hadley** [comment]
Yeah, I think so.
