### ISSUE TITLE
Expect_error fails with waldo

### ISSUE THREAD

**Issue by latot** [r-lib/testthat#1884]
Hi, I'm trying to write a test where the expected error is generated by waldo.

```R
library(testthat)

e <- sprintf(
  "%s\n%s",
  "type mismatch",
  waldo::compare(
    "other type",
    "sfnetworks",
    x_arg = "typeof(value)",
    y_arg = "expected"
  )
)

expect_error({stop(e, call. = FALSE)}, e)
```

This test should pass, instead we get a weird error:

```R
expect_error({stop(e, call. = FALSE)}, e)
Error in grepl(regexp, cnd_message(x), ...) : 
  invalid regular expression 'type mismatch
`typeof(value)`: "other type"
`expected`:      "sfnetworks"', reason 'Missing ']''
In addition: Warning message:
In grepl(regexp, cnd_message(x), ...) :
  TRE pattern compilation error 'Missing ']''
```

Well, I used some very brute ways, and the text is not regex, I have tested with regex with ```^foo$``` or ```\bfoo\b```, sadly still the same word.

Maybe I'm just using it bad, no idea if is a bug or I'm using waldo bad with testthat.

Thx!

**Comment by hadley** [comment]
The second argument to `expect_error()` is supposed to be a single regular expression. For this sort of problem, I'd **strongly** recommend `expect_snapshot()` instead.

**Comment by latot** [comment]
@hadley I check the snapshot one! thx :D they are great and so useful for a lot of things!

I just didn't know they exists, I didn't check all the types that exists.

Moving to snapshots!
