### ISSUE TITLE
Not accurate test counting in normal and Rmarkdown runs

### ISSUE THREAD

**Issue by Ahill25** [r-lib/testthat#1898]
Hey all, I have been trying to get an accurate test count on testthat package testing but seem to be running into faults. When running a test it may give numbers like shown below on the command line but when put into a dataframe the results are missing 26 tests. Where are these test numbers going? How is the result on the command line different from the actual variable assigned results? Thanks.

![image](https://github.com/r-lib/testthat/assets/112655180/eb304f92-4809-441b-9a59-59cae8c45586)

**Comment by hadley** [comment]
I don't really understand what you're asking here. Counting tests isn't an advertised feature of testthat.

**Comment by Ahill25** [comment]
https://github.com/r-lib/testthat/issues/1366#issue-856151829 This is a close answer to what I am trying to find but what if a test errors? I would have to manually count expectations I presume?

**Comment by hadley** [comment]
I don't ever use that functionality, so I don't have any insight, sorry.
