### ISSUE TITLE
`testthat::test_file` prevents `testthat::it` from accessing global variables

### ISSUE THREAD

**Issue by TymekDev** [r-lib/testthat#1926]
Hi, I just noticed that code inside `testthat::it` (specifically with `testthat::`) does not have access to global variables when invoked with `testthat::test_file()` (or other runners). Sourcing the same file works fine. Using `library(testthat)` and just `it` works fine too. See examples below.

testthat version: 3.2.0

### File
```r
# reprex_library.R
library(testthat)
x <- "asdf"
describe("a", {
  it("b", {
    force(x)
  })
})
```
### Output
```r
source("reprex_library.R")
# Test passed 🌈

testthat::test_file("reprex_library.R")
# ══ Testing reprex_library.R ═══════════════
# [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ] Done!
```

### File
```r
# reprex_colons.R
x <- "asdf"
testthat::describe("a", {
  testthat::it("b", {
    force(x)
  })
})
```
### Output
```r
source("reprex_colons.R")
# Test passed 🎊

testthat::test_file("reprex_colons.R")
# ══ Testing reprex_colons.R ══════════════════
# [ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
# 
# ── Error (reprex_colons.R:4:5): b ───────────
# Error in `force(x)`: object 'x' not found
# Backtrace:
#     ▆
#  1. └─base::force(x) at reprex_colons.R:4:5
# [ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
```

**Comment by hadley** [comment]
I agree that this seems like a bug, but since there's an obvious workaround (just use `it()` as we generally recommend), unfortunately I'm not going to have time to dig into it further.
