### ISSUE TITLE
Support magrittr syntax for expect_error() 

### ISSUE THREAD

**Issue by ctbrown** [r-lib/testthat#194]
I don't know if this is technical possible because of the way magrittr is designed, but it would be consistent to support a syntax such as:

```
expr %>% expect_error()
```

this throws an error if `expr` evaluates to an error.

**Comment by osazuwa223** [comment]
Food for thought, an operator that proceeded the error throwing expression, perhaps that did something with 'try' functionality?  Something like;
%E>% expr %>% expect_error 
Maybe more appropriate for magrittr issues.
