### ISSUE TITLE
Guide for mocking `interactive`

### ISSUE THREAD

**Issue by pawelru** [r-lib/testthat#1945]
Currently the guide recommends to set `interactive <- NULL` but I think it's safer to keep it as function and do `interactive <- base::interactive` instead. It's important when there is a function call in the package code, i.e. `if (interactive()) ...`. If set to `NULL` this would throw.

**Comment by maelle** [comment]
is https://rlang.r-lib.org/reference/is_interactive.html relevant to your use case?

**Comment by pawelru** [comment]
Actually, I was wrong. This is fully functional.

``` r
interactive <- NULL
interactive()
#> [1] FALSE
`if`(interactive(), 1, 2)
#> [1] 2
```

<sup>Created on 2024-03-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

And thanks for a good resource. I think it would be nice to link it somewhere in https://testthat.r-lib.org/reference/local_mocked_bindings.html?q=interactive#base-functions. For now, closing this.
