### ISSUE TITLE
line end with snapshots?

### ISSUE THREAD

**Issue by olivroy** [r-lib/testthat#1958]
If snapshots are updated on macOS vs Windows, a ghost snapshot file can show in the git pane.

I suspect this related to line-end. Could snapshot files be written in a platform independent way to ensure that git doesn't show modifications where there are none?

Or should that be managed per project in git config?

**Comment by hadley** [comment]
Snapshot files should already be written with consistent line ending, so if you're seeing problems that's definitely a bug.

**Comment by olivroy** [comment]
Oh, okay! Cool.

But I am surprised to see it hasn't come up before...

The simple way to get this is simply to work with snapshots on mac and Windows and you start seeing some ghost diffs appear.

I thought this was a pure git problem:

Here is what I tried:

* Using specific line ending in .Rproj
* Try to configure it git wise (I don't really understand this)
* Try to set gitattributes line ending for snapshots, but I couldn't resolve it.

I still think it can be solved with using the correct git setting. If it is, it may be worth documenting it?

**Comment by hadley** [comment]
It's possible that testthat uses the unix line endings for all the text it generates but it's possible that pkgdown is producing OS-varying line endings. Regardless, testthat should automatically process snapshots to remove `\r`.

**Comment by hadley** [comment]
I did some exploration, and, as far as I can tell, this isn't a testthat problem.

**Comment by olivroy** [comment]
Thanks for confirming! Means my git settings are probably not correct.

I have this in my global git config

```
[core]
	excludesFile = C:/Users/user/.gitignore
	editor = \"C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code\" --wait
	autocrlf = input
	whitespace = cr-at-eol
```
