### ISSUE TITLE
expect_setequal error message is reversed

### ISSUE THREAD

**Issue by ambevill** [r-lib/testthat#1962]
When `expect_setequal` fails, the labels are reversed:

> Only in **`expected`**: {values that are only in the **object**}
> Only in **`actual`**: {values that are only in the **expected**}

Test case:
```
testthat::expect_setequal(object = 'actual', expected = 'expected')
```

```
Error: sample(c("actual", letters)) (`actual`) and sample(c("expected", letters)) (`expected`) don't have the same values.
* Only in `expected`: "actual"
* Only in `actual`: "expected"
```

A more complex test case:
```
testthat::expect_setequal(
  object = sample(c('actual', letters)),
  expected = sample(c('expected', letters)))
```
...gives the same result.

testthat 3.2.1.1 Windows binary R 4.2.2

**Comment by ambevill** [comment]
https://github.com/r-lib/testthat/blob/main/R/expect-setequal.R lines 45 and 47

**Comment by hadley** [comment]
I am so bad at these 😭
