### ISSUE TITLE
Could the stack trace of `expect_no_*()` be reduced?

### ISSUE THREAD

**Issue by olivroy** [r-lib/testthat#1965]
if I have the following

```r

test_that("test", {

  expect_no_error(function_that_throws_a_warning())

})

```

I get the following trace in the build pane on Windows. I am noting that the `expect_no_error()` traceback takes 11 lines, but it doesn't seem very interesting to know that expect_no_error calls all these functions? Lines 2 to 11 don't feel relevant to me.

![image](https://github.com/r-lib/testthat/assets/52606734/851aa317-727a-49f5-9d8d-c9d8b5d89ed8)

Is there a solution for that?

Verify also if the trace from `expect_warning(regexp = NA)` is smaller?

**Comment by hadley** [comment]
The mechanisms exist in rlang to trim the call stack; the challenge will be figuring out exactly what should form the `top` of the callstack and how do we get that information to where the back trace is generated.

**Comment by hadley** [comment]
I think I'm going to close this, just because when we've tried to automatically minimise the stack we've hit a case where we accidentally hide info that we do actually want.
