### ISSUE TITLE
Exported functions missing from "Expectation Internals" section of website's reference index

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/testthat#1968]
[Expectation internals](https://testthat.r-lib.org/dev/reference/index.html#expectation-internals) section on the reference page doesn't include exported functions documented in https://testthat.r-lib.org/dev/reference/expect_success.html.

**Comment by hadley** [comment]
i.e. `expect_success()`

**Comment by IndrajeetPatil** [comment]
Also, `expect_failure()` and `show_failure()`. 

It's actually the last one that I was looking for, and which led to this issue.  

P.S. Possibly has the same root cause as #1941.

**Comment by hadley** [comment]
Looks like this is fixed in the dev version: https://testthat.r-lib.org/dev/reference/index.html#expectation-internals
