### ISSUE TITLE
Installation on R < 4.0 fails on `evaluate` now requiring R >= 4.0

### ISSUE THREAD

**Issue by lachlansimpson** [r-lib/testthat#1969]
Seen in zendesk ticket 106807. Mentioned here: https://github.com/r-lib/evaluate/issues/173#issuecomment-2204831910

Solved by installation of older version using `devtools`

```
install.package('devtools')
require('devtools')
install_version("evaluate", version = "0.23", repos = "http://cran.us.r-project.org")
install.packages('testthat')
```

Ideally `testthat` installation candidate will install the version of `evaluate` required per the version of R being run, or `testthat` have a requirement of R>=4.0 as well.

**Comment by hadley** [comment]
That version of evaluate hasn't been released yet, so I'm surprised it's causing problems.

**Comment by hadley** [comment]
Oh it is in the released version; ooops.

**Comment by hadley** [comment]
Having read through that support log, I'm pretty confident the right fix is to ensuring we're requiring 4.0.0 for testthat, which I believe will happen naturally as part of our release process.

**Comment by hadley** [comment]
Given that it seems like 3.6 is going to be around for a while, we want to at least reserve the possibility of continuing test some packages on 3.6. That means we should formally declare 3.6 support in testthat and add it to our testing matrix.

**Comment by hadley** [comment]
After more time has elapsed it seems like requiring R 4.0.0 caused few problems (especially once we changed our GitHub action to install older versions if necessary).
