### ISSUE TITLE
Ability to filter tests globally based on the test description

### ISSUE THREAD

**Issue by sebffischer** [r-lib/testthat#1971]
When developing without a repl, I often find myself in a situation where I want to run a single test. I know that `test_file` supports the `desc` argument, but there it is also necessary to pass the name of the file, which is a little inconvenient. Is there currently a way to globally filter tests with respect to their description without passing the file name argument? It would for example be nice if the file names were added to the description of a test so that two tests that have the same description but are in different files can be distinguished by name. 

Thanks for the great package!

**Comment by hadley** [comment]
I think that's probably out of scope for testthat, but you want want to try out the tooling in positron that allows you to easily re-run one or more tests.
