### ISSUE TITLE
`getParseData()` always returns NULL in IDEs tests

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/testthat#2008]
Hi,

My package tests are failing because of this very peculiar bug and I have unfortunately no idea how to debug it.

The following test fails in the RStudio build pane and in Positron test suite, but succeeds in any R console.
Running `testthat::test_file()` in the console succeeds, but clicking the buttons "Run tests" in the file or "Test" in the Build pane fails.

```r
test_that("multiplication works", {
  # a = getParseData(parse(text="# foobar")) #same result
  a = getParseData(parse(text="a=1"))
  expect_false(is.null(a))
})
```

**Comment by hadley** [comment]
Set `keep.source = TRUE` in `parse()`?

**Comment by DanChaltiel** [comment]
Yes, that works! I would never guess that was the fix.
Thanks a lot, Hadley 🙏
That fixed my problem, you can close the issue if nothing should change on your end.
