### ISSUE TITLE
FR: `expect_inherits()`

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/testthat#2016]
Now that `base::inherits()` can accept any object in the `what` argument, and S7 encourages using reified class objects instead of class names as character vectors, it might be useful to add an `expect_inherits()` function. This function would generally behave like `expect_s3_class()` but could dispatch `nameOfClass()` on the second argument when needed.

For example, it could replace tests like those seen here: https://github.com/cole-brokamp/fr/pull/15

Possibly related issue: https://github.com/r-lib/testthat/issues/1448

**Comment by hadley** [comment]
I feel like a more tactical change would be to implement `expect_s7_class()` because it has no implications for existing `expect_s3_class()` usage. It makes it more clear what the expectation does, and allows argument checking to be more precise.
