### ISSUE TITLE
using test_that with Jenkins (fork)

### ISSUE THREAD

**Issue by floybix** [r-lib/testthat#22]
G'day Hadley

I'm wanting to get test_that reports into a form that can be understood by Jenkins (http://www.jenkins-ci.org/). Basically that means the jUnit XML format -- Jenkins will highlight failing tests, giving options for more detail, show timing of groups of tests, overall trends etc. 

So I went ahead and wrote a JUnitReporter at https://github.com/floybix/test_that

One problem was the need to identify tests stably over time even though they may start failing. For that I am using the deparsed expect_that() call itself. Currently it works to my satisfaction with expect_that() but not with expect_equals() etc. 

Also the invocation is a little awkward to redirect to a file... output goes to standard out by default so in the ideal case where nothing else gets printed one could simply

```
sink("testjunit.xml")
test_package("testthat", reporter = "jUnit")
sink()
```

But the safer option is something like

```
test_package("testthat", reporter = JUnitReporter$clone()$do(self$file <- "testjunit.xml"))
```

What do you think?

**Comment by zachmayer** [comment]
Did this pull request ever happen?

**Comment by lauritssn** [comment]
I'm also very keen on knowing the status of this one - is it possible to get JUnit XML output from testhat?

**Comment by sebastian-c** [comment]
This request seems to have been continued in #260, where @jspitzen is working on it.

**Comment by sebastian-c** [comment]
There's further work that stopped in July. Pull request #481 relates to this issue.
