### ISSUE TITLE
Code coverage?

### ISSUE THREAD

**Issue by rlegendi** [r-lib/testthat#45]
Is there any tools to evaluate code coverage for R scripts using the `testthat` package?

I found nothing by Google except a mention of the topic in the Future work section of an [RJournal article](http://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf). I also asked around at [StackOverflow](http://stackoverflow.com/questions/12313886/r-code-coverage-for-the-testthat-package) but nobody was able to help :-)

I really appreciate any help, thanks in advance!

**Comment by gonike** [comment]
Note that there's now [covr](https://github.com/jimhester/covr). It doesn't have the beautiful output you proposed, but it does calculate the coverage per line. Works with `testthat`, among others.

**Comment by jimhester** [comment]
@gonike covr actually does have an interactive shiny app you can use to display your coverage results
```
cov <- package_coverage()
shine(cov)
```
