### ISSUE TITLE
FR: Run tests in parallel

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#486]
to speed up TDD.
- One task per context
- Need special care to avoid mixing output
  - Can be achieved by making reporter$cat() collect all output and print it in reporter$.end_context()
- Can use the "parallel" package for simplicity
  - Some backends need to load the package and the helpers on each node

**Comment by russellpierce** [comment]
Just a thought: Being able to opt out for some tests might be good.(unless testthat is only intended for use with unit tests and excludes integration tests)

**Comment by jeffpollock9** [comment]
Hi, what needs to be done to get this (or similar) accepted? I think it would be a great addition.
