### ISSUE TITLE
How do you write custom expectations?

### ISSUE THREAD

**Issue by klmr** [r-lib/testthat#562]
In previous versions of ‹testthat› I used a negated version of `is_identical_to`, `is_not_identical_to`. It was essentially a copy of `is_identical_to` with a trivial change. Unfortunately, this function stopped working because the unexported function `testthat:::find_expr` no longer exists.

How would I implement this function, or an `expect_not_identical`, using the current ‹testthat› API? Unfortunately there’s no user guide for writing custom expectations, and the single trivial example in the “testing” chapter of r-pkgs doesn’t cover this case.

Of course I could just wrap it in `expect_false(identical(foo, bar))` but I’d like to get the labels right, and `testthat:::make_label` is once again not exported.

Generally, what’s the best practice for negating expectations now that `not` is deprecated?

**Comment by cogmind** [comment]
From what I can gather by the documentation and as you indicated I guess that "...prefer using the testthat wrappers" as stated in the use_catch (with C++) documentation applies here too. 

One option is perhaps to extend [make-expectation.R](https://github.com/hadley/testthat/blob/master/R/make-expectation.R) within the package itself. Currently, make_expectation only offers equality conditions. As the documentation refers to this as a convenience function I am not sure if it is considered legacy or 'core'.

A final option is to create custom expectations using [expectation.R](https://github.com/hadley/testthat/blob/master/R/expectation.R)

My 2 cents

**Comment by klmr** [comment]
Apparently [`make_label` is now exported](https://github.com/hadley/testthat/commit/c505a888b3afd32eb20ec44a0e0cf3847666f66a), which will make it easier to implement custom expectations. Unfortunately this change hasn’t been released yet (no version number increment).

It would still be good to have a more comprehensive guide/documentation for creating custom expectations.

**Comment by hadley** [comment]
I'll write this once #626 and #621 are done.

**Comment by hadley** [comment]
Fixed in 2c6f9b9. It's rough but should be enough to give you the general ideas. PRs to improve it would be much appreciated!
