### ISSUE TITLE
Reconsider directory layout

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#591]
(i.e. the working directory needs to be the project root)

This needs to be a long term plan, but would make testthat more consistent with other packages. Would need to start by emitting warnings so that R CMD check doesn't fail, but you're encouraged to update your tests.

**Comment by hadley** [comment]
It might be possible to do this as part of a bigger behaviour switch:

* Put tests directly in `tests/`
* Eliminate use of `context()`

**Comment by krlmlr** [comment]
I like the idea of putting tests under `tests`, but why do we need to eliminate bare expectations?

**Comment by hadley** [comment]
Just because it adds a bunch of extra code and I’d rather push people towards one consistent style. I might be wrong.

**Comment by hadley** [comment]
`content()` is no longer necessary as of 2.1.0

**Comment by hadley** [comment]
Superseded by #1027
