### ISSUE TITLE
not_shows_message and not_prints_text

### ISSUE THREAD

**Issue by wush978** [r-lib/testthat#64]
I think it might be useful for `not_shows_message` or `not_prints_text` which is similar to `shows_message` and `prints_text` except that the test is fail instead of pass.

For example, I need to test if executing an external program _does not_ produces warning message.

**Comment by muschellij2** [comment]
Is this still the case since `not()` is becoming deprecated?

Or should it be something like `testthat::expect_failure(expect_warning(expr))`
