### ISSUE TITLE
Multiple C++ test files

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#644]
If I have a package with a lot of C/C++ code, it would be nice to be able to select only a subset to run. UI-wise maybe this can be achieved by adding a file parameter to `expect_cpp_tests_pass`:

```
expect_cpp_tests_pass(mypackage, file = "connections.c")
```

Btw. would it make sense for the `package` argument to default to the calling package?

**Comment by kevinushey** [comment]
FWIW, Catch supports the concept of tags: https://github.com/philsquared/Catch/blob/master/docs/command-line.md#filenames-as-tags

So perhaps we can make use of that if we were to build a feature like this.

**Comment by hadley** [comment]
Are either of you interested in working on this (at some point in the future)? Otherwise, since there seems to be relatively little interest, I will probably close this issue.

**Comment by gaborcsardi** [comment]
I will not have time, sorry. :(
