### ISSUE TITLE
Weird output for tests that modify the character locale

### ISSUE THREAD

**Issue by patperry** [r-lib/testthat#648]
I get this output when running the development version of testthat:

```
✔ |  5       | text_split_tokens
✔ |  1       | text_stats
✔ | 22       | text_sub
✔ | 16       | text_tokens
✔ |  6       | text_types
✔ |  6       | text-stats
✔ | 16       | text
✔ | 13       | utf8_encode_encode
<U+2714> | 112       | utf8_format [0.2 s]
<U+2714> | 16       | utf8_normalize
<U+2714> | 31       | utf8_print [0.1 s]
<U+2714> | 10       | utf8_valid
<U+2714> |  8       | utf8_width
<U+2714> |  3       | wordlist
```

This is likely because I have tests that do the equivalent of `Sys.setlocale("LC_CTYPE", "C")` followed by `on.exit(Sys.setlocale("LC_CTYPE", ""))`.

To reporoduce:

```r
tmp <- tempfile()
system2("git", c("clone", "--recursive",
                 shQuote("https://github.com/patperry/r-corpus.git"), shQuote(tmp)))
devtools::test(tmp)
```

**Comment by gaborcsardi** [comment]
Can you restore the locale at the end of the test?

**Comment by gaborcsardi** [comment]
@hadley But in general, we need to fix the issue of UTF-8 characters on non UTF-8 capable screens.

**Comment by patperry** [comment]
@gaborcsardi I do restore the locale, with `on.exit(Sys.setlocale("LC_CTYPE", ""))`. Are you saying that I shouldn't be using `on.exit` within a test?

**Comment by gaborcsardi** [comment]
What's wrong with the current output? Looks good to me.

**Comment by patperry** [comment]
It should say `utf8_encode` instead of `utf8_encode_encode` and `utf8_width` instead of `utf8_width8_width`.

**Comment by gaborcsardi** [comment]
Oh, OK, got it.

**Comment by hadley** [comment]
@patperry I bet that's because `<U+asdfsd>` is written transiently, and then when the line is overwritten it doesn't clear out all the space. Regardless, #652, will fix the issue
