### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by patperry** [r-lib/testthat#651]
With the old version of testthat (1.0.2), it takes about 6 seconds to run my package tests. With the development version (1.0.2.9000), it takes about 12 seconds. This seems like a small difference, but it's noticeable. Is there any way to get performance back to what it used to be? Possibly by providing an option to not display the progress? I'd much rather have fast tests than nice output.

Reproducible example:

```r
tmp <- tempfile()
system2("git", c("clone", "--recursive",
                 shQuote("https://github.com/patperry/r-corpus.git"), shQuote(tmp)))
devtools::compile_dll(tmp)
system.time(devtools::test(tmp))
```

**Comment by gaborcsardi** [comment]
> I'd much rather have fast tests than nice output.

Why do you think that the output makes it slower? Anyway, you can use the old reporter if you like:
```
devtools::test(reporter = "summary")
```

Set the `testthat.default_reporter` option to make this the default:
```
options(testthat.default_reporter = "summary")
```

**Comment by patperry** [comment]
Good point, the nice output is not slowing anything down. (In fact, the nice output makes things **faster**!):

### 1.0.2

```
> time Rscript --vanilla -e 'devtools::test()'
...
real	0m6.265s
user	0m5.731s
sys	0m0.298s
```


### 1.0.2.9000 

```
> time Rscript --vanilla -e 'devtools::test()'
...
real	0m12.156s
user	0m11.617s
sys	0m0.308s
```

### 1.0.2.9000 reporter = "summary"

```
> time Rscript --vanilla -e 'devtools::test(reporter = "summary")'
...
real	0m13.380s
user	0m12.775s
sys	0m0.342s
```

**Comment by jimhester** [comment]
I can reproduce the performance regression locally. I tracked it down and it looks like the regression is due to a forced `gc()` call at https://github.com/jimhester/testthat/blob/b5c945bc5526d022823cfaaa146775e8213b564e/R/test-files.R#L122

If we remove this call the performance is equivalent to the previous testthat release.

The `gc()` was included because of https://github.com/r-lib/testthat/issues/535, but that issue doesn't say why it is necessary @hadey any ideas why and can it be removed?

**Comment by hadley** [comment]
I forced it because the `teardown()` will often delete objects, and it's not uncommon for them to have finalisers, and ideally those would be run before the next test starts.  I could instead make it part of `teardown_run()` and only run if there are any tear-downs.  But why does running `gc()` once per file take so long?

**Comment by patperry** [comment]
I don't know how to explain this. From a new R session:

```r
> devtools::load_all()
Loading corpus
> system.time(gc())
   user  system elapsed 
  0.033   0.000   0.033 
> system.time(gc())
   user  system elapsed 
  0.033   0.000   0.033 
> system.time(gc())
   user  system elapsed 
  0.034   0.000   0.034 
> devtools::test()
```
After running testthat:
```r
> devtools::test()
... (output omitted)

> system.time(gc())
   user  system elapsed 
  0.140   0.000   0.141 
> system.time(gc())
   user  system elapsed 
  0.126   0.000   0.126 
> system.time(gc())
   user  system elapsed 
  0.128   0.000   0.129 
```

I have 36 test files. The gc() calls add about 5 seconds.

**Comment by patperry** [comment]
Forgot this:

```r
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] corpus_0.9.3.9000   testthat_1.0.2.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13        xml2_1.1.1          magrittr_1.5       
 [4] roxygen2_6.0.1      devtools_1.13.1     munsell_0.4.3      
 [7] colorspace_1.3-2    tm_0.7-1            lattice_0.20-35    
[10] R6_2.2.2            rlang_0.1.2         fastmatch_1.1-0    
[13] quanteda_0.99.9     plyr_1.8.4          stringr_1.2.0      
[16] tools_3.4.2         parallel_3.4.2      grid_3.4.2         
[19] gtable_0.2.0        data.table_1.10.4   withr_2.0.0        
[22] commonmark_1.2      lazyeval_0.2.0      RcppParallel_4.3.20
[25] digest_0.6.12       tibble_1.3.4        crayon_1.3.4       
[28] Matrix_1.2-11       NLP_0.1-10          ggplot2_2.2.1      
[31] clisymbols_1.2.0    memoise_1.1.0       slam_0.1-40        
[34] stringi_1.1.5       compiler_3.4.2      scales_0.4.1       
[37] lubridate_1.6.0    
> ls()
character(0)
```

**Comment by patperry** [comment]
More info on the slowdown:

```r
> system.time(gc())
   user  system elapsed 
  0.012   0.000   0.012 
> library(Matrix); system.time(gc())
   user  system elapsed 
  0.073   0.000   0.073 
> library(quanteda); system.time(gc())
quanteda version 0.99.9
Using 3 of 4 threads for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

   user  system elapsed 
  0.099   0.000   0.102 
```

I don't know why `gc()` slows down so much. Maybe this is a bug in base R? Seems to be related to S4 classes.

**Comment by jimhester** [comment]
It might just be due to the increase in the symbol table size after loading the methods package / quanteda?

**Comment by hadley** [comment]
The symbol table doesn't get gc'd though? I wonder if it's something to do with S4?

It might be a good idea to ask on R-devel.

**Comment by patperry** [comment]
Could be something related to caching, also. Both `Matrix` and `quanteda` are huge packages. I can imagine a world where if these packages aren't loaded, then all of the R memory fits in the cache, so gc() is fast. When the `Matrix` is loaded, the address spaces gets fragmented and the objects no longer fit. The cache misses cause gc() to slow down. In-cache memory access is an order of magnitude faster than out-of-cache.

**Comment by hadley** [comment]
Doing the `gc()` conditionally reduces the time the testthat tests take from ~15s to ~9s

**Comment by hadley** [comment]
I've tweaked the progress reporter to display the total duration at the end. Hopefully that'll make it easier to spot this sort of problem in the future (and is also generally useful)
