### ISSUE TITLE
Enable `expect_*()` to directly compare values of expressions?

### ISSUE THREAD

**Issue by egnha** [r-lib/testthat#655]
The new `expect_*()` assertions enquote expressions before comparing their values. However, it is still useful to retain the ability to compare the values directly, _without_ going through enquoting.

I've encountered two scenarios where being able to fallback to the previous behavior would be useful:

1. **Circumvent an unquoting bug** (cf. https://github.com/tidyverse/rlang/issues/280)
    ```R
    x <- pairlist(0)
    expect_equal(quos(UQS(x), y), quos(0, y))
    expect_equal(quos(!!! x, y), quos(0, y))
    #> Error: quos(0, y, y) not equal to quos(0, y).
    #> Length mismatch: comparison on first 2 components 
    ```
   The problem is that, currently, unquoting may produce undesirable side-effects (mutation of `x` in this case). One way to work around this is to directly compare the value of the expression of the objects, e.g., by assigning values, say, `obj1 <- quos(UQS(x), y)`, `obj2 <- quos(!!! x, y)` and then comparing `obj1` and `obj2` to `quos(0, y)`.

2. **Allow literal unquoting** (cf. https://github.com/tidyverse/rlang/issues/264)

    For example, the following assertion fails,
    ```R    
    foo <- function(x) bar(UQ(x))
    expect_equal(foo, function(x) bar(UQ(x)))
    #> Error in function (x)  : object 'x' not found 
    ```
    because the `UQ()` in the function body of the expectation is being interpreted. However, what is actually intended here is a comparison to the _value_ of the expression. One can work around this with
    ```R    
    expect_equal(foo, UQ(quote(function(x) bar(UQ(x)))))
    ```
   If `expect_equal()` had the option to compare values of (raw) expressions, then such contortions could be avoided—the _semantics_ of the assertion would be more transparently articulated.

Admittedly, these examples are rather contrived. Nonetheless, they accurately reflect the spurious incompatibilities between the tests in [nofrills](https://github.com/egnha/nofrills) and the current devel testthat.

I can resolve these incompatibilities with an _ad hoc_ wrapper:
```R
expect_equal_ <- function(object, expected, ...) {
  force(object)
  force(expected)
  expect_equal(object, expected, ...)
}
```
While this works for my purposes, a more robust alternative within testthat would be preferable. (Perhaps for a future release, if I am the only one having this problem en route to 2.0.0.)

**Comment by MilesMcBain** [comment]
I hit the `expect_equal` issue. Eventually I whittled it down to this reprex: 

``` r
  double_col <- function(dat, arg1) {
    
    dplyr::mutate(dat, result = !!rlang::enquo(arg1) * 2)
  }
  head(double_col(mtcars, cyl)) 
#>    mpg cyl disp  hp drat    wt  qsec vs am gear carb result
#> 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4     12
#> 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4     12
#> 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1      8
#> 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1     12
#> 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2     16
#> 6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1     12
  
  testthat::expect_equal({
    double_col <- function(dat, arg1) {
      
      dplyr::mutate(dat, result = !!rlang::enquo(arg1) * 2)
    }
    head(double_col(mtcars, cyl))
    TRUE
  },
  {
    TRUE
  })
#> Error in (function (x) : object 'arg1' not found
```

Created on 2018-05-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Which seemed absurd so I went hunting and found this issue. I can implement the work-around wrapper provided by @egnha but I have to admit I do not understand why it is required. Can either of you break it down a little for me, please?

**Comment by egnha** [comment]
@MilesMcBain, I believe the invocation of `expect_equal()` is failing in your case because it is interpreting the `!!` in the body of the function `double_col()` _before_ the comparison is carried out. In the wrapper `expect_equal_()`, forcing `object` and `expected` causes them to be evaluated in the usual way, before comparison.

**Comment by MilesMcBain** [comment]
Thanks! So why does `expect_equal` not evaluate in the usual way?

**Comment by egnha** [comment]
This is explained in NEWS.md: unquoting of expectation expressions is a feature.

**Comment by hadley** [comment]
Given that this issue appears to affect very few people, I think the first place to start is to actually document the behaviour so it's not so confusing. After that's been in the wild for some time, we can assess whether or not an alternative to `expect_equals()` needs to exist.
