### ISSUE TITLE
Vignette for using Reporters

### ISSUE THREAD

**Issue by jimhester** [r-lib/testthat#657]
The documentation for reporters is really sparse, particularly for how to use them in `test()`, `test_package()`. It is probably worth having a short vignette to explain how to use them / pass options to reporters, and maybe defining a new reporter.

**Comment by jimhester** [comment]
This was originally brought up by https://community.rstudio.com/t/good-resources-for-testthats-reporters/2102

**Comment by coatless** [comment]
@jimhester any eta on when this will likely happen?

**Comment by hadley** [comment]
The documentation was generally so poor that I think that's the place to start, rather than a vignette. It's still far from perfect, but it should be substantially better now.
