### ISSUE TITLE
Post-mortem debugging?

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#658]
Special reporter that uses `dump.frames`

**Comment by aryoda** [comment]
Great idea!

It would be great to consider that `dump.frames` writes the evaluation environments (frames) of the stack trace "forgets" to save the workspace too if you set the parameter to.file = TRUE. Therefore important objects may be missing when you start your post-mortem analysis.

See SO post: https://stackoverflow.com/questions/40421552/r-how-make-dump-frames-include-all-variables-for-later-post-mortem-debugging

**Comment by hadley** [comment]
I no longer think this is necessary due to the improvements in latest version of CheckReporter — you now get full back traces, which should allow you to rapidly zero into on the problem.
