### ISSUE TITLE
Further improving the progress reporter

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#666]
This is not for the soon-to-be-released version of `testthat`, but just a bunch of ideas for later.

<img width="648" alt="screen shot 2017-10-19 at 12 27 58 am" src="https://user-images.githubusercontent.com/660288/32047422-d09f4a96-ba3d-11e7-9f12-9ae04153ac8a.png">

Ideas: 
* make it easier to see which context the skips/warnings/failures belong to, by indenting their code.
* make it easier to spot abnormal results, by the harsh coloring at the beginning of the line
* make it easier to see where a skip/warning/failure log begins and where it ends, by leaving an empty line above and below, and coloring the background.
* make the `OK F W S` thinner, because most of the time it is empty. So we only show the number passing tests, and the rest is shown below.
* making the summary line at the end a single line, to save space
* showing a nice (full) stack for errors, potentially with references to the source code
* showing the nicely highlighted code where the error happened

**Comment by hadley** [comment]
What should a context show after (say) 5 successes and a failure and another few successes?  i.e. how do you know that there's a failure part way through? Or do you just wait until the end of that context?

This would also mean we could eliminate the spinner because you'd just see the PASS numbers updating

**Comment by gaborcsardi** [comment]
Good question. I guess it could be the same way as currently, the PASS numbers spin (but we could also show there that there were some failures already), and the details are printed after.

The other way would be to print failures ASAP, and then the summary line of the test file comes at the end. This might be better for interactive use.

**Comment by hadley** [comment]
We should also think about how this might work if test files were processed in parallel

**Comment by hadley** [comment]
Could also print file names instead of contexts
