### ISSUE TITLE
Should expect_s3_class() check for identical class vectors?

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#667]
```r
x <- structure(list(), class = c("foo", "bar", "baz"))

# Failure:
expect_s3_class(x, c("foo", "baz"))

# Success:
expect_s3_class(x, c("foo", "bar", "baz"))
```

**Comment by lionel-** [comment]
Or maybe `expect_s3_all()`, `expect_s3_any()` and `expect_s3_only()` following new rlang functions.

**Comment by lionel-** [comment]
I think the current behaviour would be more intuitive if it was called `expect_inherits()`.

I would imagine most people using `expect_s3_class()` to check that their constructors work correctly and with inherits semantics some bugs could go unnoticed.

**Comment by lionel-** [comment]
Related to `inherits_all()` and `inherits_any()` in rlang 0.2.0.

**Comment by jimhester** [comment]
Oh, I would expect most people to be testing the type of objects returned from functions they do not necessarily control and ensuring it is of a type they need for their function to work.

**Comment by lionel-** [comment]
That's a reasonable assumption. Fine-grained testing is always possible with `expect_true()` so feel free to close.

**Comment by hadley** [comment]
I'm going to close. I think testing for inheritance is correct in general (because you want to allow the original author to return a more specific subclass), and if you're testing a constructor you can use something more specific.
