### ISSUE TITLE
expect_output / capture_output is broken on non UTF-8 platforms

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#672]
The problem is that even if the output is not UTF-8, `read_lines` always marks it as UTF-8. Actually, even if you try to output (`cat`) proper UTF-8 like I do below, R will convert it to the native encoding (as much as possible), so the recorded output will not be UTF-8.

The behavior is better on the current stable version (1.0.2), because there readLines is used to read back the output, without a specified encoding, so the encoding of the output will be "unknown". This is still better than the current non-UTF-8 output marked as UTF-8. It also works fine in the checks, even if the encoding is not specified.

This is old testthat (example not self-contained, sorry):

```r
o1 <- paste(capture.output(print(boxx(""))), collapse = "\n")
o2 <- capture_output(print(boxx("")))
Encoding(o1)
#> [1] "latin1"
Encoding(o2)
#> [1] "unknown"
o1 == o2
#> [1] TRUE
expect_equal(o1, o2)
expect_match(o1, o2, fixed = TRUE)
expect_match(o2, o1, fixed = TRUE)
```

And this is new testthat. The raw representation of the output is still the same, i.e. it is `latin1`, but the output is marked as UTF-8:

```r
o3 <- capture_output(print(boxx("")))
Encoding(o3)
#> [1] "UTF-8"
stringi::stri_enc_isutf8(o3)
#> [1] FALSE
o3 == o1
#> [1] FALSE
all(charToRaw(o1) == charToRaw(o3))
[1] TRUE
```

And the check results are pretty bad, you get the same for using `expect_output()` directly, of course:

```r
expect_equal(o1, o3)
#> Error in nchar(x) : invalid multibyte string, element 1
expect_match(o1, o3, fixed = TRUE)
#> Error in grepl(regexp, act$val, perl = perl, fixed = fixed, ...) : 
#>   regular expression is invalid UTF-8
expect_match(o3, o1, fixed = TRUE)
#> Error: `o3` does not match "+------+\n¦      ¦\n¦      ¦\n¦      ¦\n+------+".
#> Actual value: "+------+\n<U+00A6>      <U+00A6>\n<U+00A6>      <U+00A6>\n<U+00A6>      #> <U+00A6>\n+------+"
#> In addition: Warning message:
#> In grepl(regexp, act$val, perl = perl, fixed = fixed, ...) :
#>   input string 1 is invalid UTF-8
```

I'll be happy to do a PR, but first we need to think about the correct solution....

**Comment by gaborcsardi** [comment]
For the record, this is the re-encoding that R's `cat` is doing:
https://github.com/wch/r-source/blob/aeed807df6e4017ddac4035eae8bb97c739b625d/src/main/builtin.c#L458-L491

**Comment by gaborcsardi** [comment]
Also, this is how `WinUTF8out` is set:
```
void WinCheckUTF8(void)
{
    if(CharacterMode == RGui) WinUTF8out = (SinkCons[R_SinkNumber] == 1);
    else WinUTF8out = FALSE;
}
```

https://github.com/wch/r-source/blob/e0dd628546eda5a7fa45b5a006d73fe04519f6c7/src/main/connections.c#L5102-L5108

So, on windows it is UTF-8 for RGui, and it is not otherwise.

**Comment by gaborcsardi** [comment]
So, effectively, if a sink is active, like in our case, `cat` will always re-encode to the native encoding. Even if you specify a `file` to `cat` and the `file` has a different encoding. 

I.e. even if you `cat` a marked UTF-8 string to an UTF-8 connection, `cat` will re-encode it to native first, and then the connection will re-encode it to UTF-8. Not quite ideal.

Even more surprisingly, even if you set the default encoding to UTF-8, `cat` still re-encodes:
```r
bar <- "\u2551"
x1 <- withr::with_locale(c(LC_CTYPE = "en_US.ISO8859-1"), {
  withr::with_options(list(encoding = "UTF-8"), {
    cat(bar)
    temp <- file(encoding = "UTF-8", open = "w+b")
  
    sink(temp)
    print(bar)
    sink()
    
    readBin(temp, "raw", 20)
  })
})
rawToChar(x1)
```

**Comment by gaborcsardi** [comment]
In theory, we could always change the native encoding to UTF-8, before the printing, but UTF-8 is not supported as a native encoding on windows.

**Comment by krlmlr** [comment]
The best I know to portably read UTF-8 encoded files is https://github.com/krlmlr/enc/blob/af4b7aaaca1bd860538473c0e3ec63671e9e7a08/R/io.R#L15-L21

I'm about to release enc to CRAN, happy to add it to r-lib too.

I've been working on this particular `cat()` problem with the support of Duncan Murdoch, but this has been on hold now for a while.

**Comment by gaborcsardi** [comment]
@hadley I think we need to fix this before the release, because `testthat` itself  fails its tests on Windows currently.

**Comment by gaborcsardi** [comment]
@hadley, @krlmlr PR: #679

**Comment by trevorld** [comment]
``expect_output`` still seems broken on Windows (in particular on AppVeyor) for certain Unicode strings:

```
test_that("text diagrams", {
    string <- "\u2600\u20dd\u2503\u263d\u20dd\u2502"
    expect_output(cat(string), string)
})
```

It looks like the "actual" string has extra ``\`` characters that the "comparison" string does not.

```
  > test_check("ppgames")
  -- 1. Failure: text diagrams (@test_unicode.R#10)  -----------------------------
  `cat\(string\)` does not match "<U+2600><U+20DD><U+2503><U+263D><U+20DD>�".
  Actual value: "<U\+2600><U\+20DD><U\+2503><U\+263D><U\+20DD>�"
```

**Comment by hadley** [comment]
@trevorld can you please file a reprex in a new issue?

**Comment by kevinushey** [comment]
The problem is that `sink()` attempts to round-trip text through the native encoding. Unfortunately this means if you have text which cannot be represented in the native encoding this issue will occur, and to the best of my knowledge there's not much you can do about it :-/
