### ISSUE TITLE
expect_equal fails when supplying objects via `...`

### ISSUE THREAD

**Issue by mschubert** [r-lib/testthat#677]
The documentation of `expect_equal` states:

> expect_equal(object, expected, ..., info = NULL, label = NULL,
>   expected.label = NULL)
>
> expected: Expected value
> ...: other values passed to ‘all.equal()’

This works fine for testing two objects:

    expect_equal(1, 1)

When adding a third, it is not tested:

    expect_equal(1, 1, 2) # no error

And it fails when adding a fourth:

    expect_equal(1, 1, 1, 1)
  
> Error in all.equal.numeric(x, y, tolerance = tolerance, check.attributes = check.attributes,  :
>   'check.attributes' must be logical

R version 3.4.2
testthat_1.0.2.9000

**Comment by hadley** [comment]
I think you’re misinterpreting the docs - additional args are passed on to all.equal. Have a look at its docs to see what it accepts.
