### ISSUE TITLE
expect_known_display()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#681]
Cleaning up the pillar API, we could consider offering:

- `expect_known_display()`: same as `expect_known_output(print = TRUE)`
- Adding a `crayon = NA` argument with the following semantics:
    - `NA`: don't touch
    - `TRUE`: Enable, set to 16 colors
    - `FALSE`: Disable

For now this will live in `pillar::export_known_display()`.

**Comment by hadley** [comment]
I think this is now subsumed by #782
