### ISSUE TITLE
expect_equal_to_reference default behavior changed

### ISSUE THREAD

**Issue by brodieG** [r-lib/testthat#683]
With the transition to `expect_known`, I think there was a regression introduced with respect to [`expect_equal_to_reference` ](https://github.com/r-lib/testthat/blob/master/R/expect-known.R#L124):
```
 #' @export
-#' @rdname expect_known_value
+#' @rdname expect_known_output
 #' @usage NULL
-expect_equal_to_reference <- expect_known_value
+expect_equal_to_reference <- function(..., update = FALSE) {
+  expect_known_value(..., update = TRUE)
+}
```
Should be:
```
expect_equal_to_reference <- function(..., update = FALSE) {
  expect_known_value(..., update = update)
}
```
Happy to submit a PR if you want, but it may be easier for you guys to fix.  Let me know.  For reference, the NEWS entry suggests the change is not intentional:

> expect_known_value() replaces expect_equal_to_reference(), which has been soft-deprecated. It gains an update argument defaulting to TRUE. This changes behaviour from the previous version, and soft-deprecated expect_equal_to_reference() gets update = FALSE.

**Comment by hadley** [comment]
Doh. A PR would be great, although it's already been submitted to CRAN 😢

**Comment by brodieG** [comment]
Oh well, will submit PR later this week then.  Still have to get my update to `unitizer` out so that it works with `testthat` 2.0.

**Comment by jimhester** [comment]
closed by https://github.com/r-lib/testthat/pull/687/

**Comment by jrcpulliam** [comment]
This bug seems to have reappeared somewhere along the line. I'm using 2.0.1, just reinstalled from CRAN. `testthat::expect_equal_to_reference` yields:

```r
function (..., update = FALSE) 
{
    expect_known_value(..., update = TRUE)
}
<bytecode: 0x10d0ebd70>
<environment: namespace:testthat>
```
I'm switching to `expect_known_value()` but thought I should flag this.
