### ISSUE TITLE
expect_known_value default for update param

### ISSUE THREAD

**Issue by brodieG** [r-lib/testthat#684]
I've been using `expect_equal_to_reference` extensively for a long time and have also written a testing framework that specializes in these reference value comparisons ([`unitizer`](https://github.com/brodieG/unitizer)).  So I say the following as someone who has a lot of cycles doing tests with stored objects:

Based on my experience I think setting `update=TRUE` as the default for `expect_known_value` is sub-optimal.  The `git diff` base workflow suggested in the documentation will not work because the reference values are stored as RDS files.  `expect_known_output` is okay with `update=TRUE` because you can actually do a diff there.

Given that the `git diff` method doesn't work with RDSes, the workflow becomes:

1. Run test_check() or some such, see failures
2. Run interactively to actually look at the objects
3. Realize that you've over-written your reference objects
4. git checkout your reference objects
5. etc.

I realize the appeal of defaulting to `update=TRUE` because when the changes to values are intended, the update process is a pain when `update` defaults to FALSE.  Maybe a possibility is to have options `testthat.update.value` and `testthat.update.output` that are set to FALSE and TRUE respectively by default, and use those as the default values for `expect_known_value` and `expect_known_output` respectively?

PS: I guess I could add a [git versioned RDS comparison to `diffobj`](https://github.com/brodieG/diffobj/issues/110) since that can already compare `rds` files.

**Comment by hadley** [comment]
I never use `expect_equal_to_reference()` because I don't like the pattern of storing opaque binary objects, so I'm happy to do whatever you suggest.

It seems reasonable popular in CRAN packages: https://github.com/search?q=org%3Acran+expect_equal_to_reference&type=Code, so any changes would need to be a large net positive in return for changing the default.

**Comment by brodieG** [comment]
I think I'm just going to add a feature to `diffobj` to be able to diff RDSes across versions.  I do agree the ship has sailed on this one.
