### ISSUE TITLE
The cli package is listed in Imports, but missing from namespace

### ISSUE THREAD

**Issue by andrie** [r-lib/testthat#688]
I can see that `cli` is an `Imports` dependency.  However, it's missing from the `NAMESPACE`.

This is causing issues with the testing of `checkpoint` (see https://github.com/RevolutionAnalytics/checkpoint/commit/615803d227f6c47d0fa40cf7336635af12d8e129).

I suspect this is an accidental removal of `@import cli` or similar statement.

**Comment by gaborcsardi** [comment]
It does not have to be in `NAMESPACE`, if you only use it in the fully qualified form, i.e. `cli::fun`.

**Comment by andrie** [comment]
That's true. However, that wasn't the issue for me.

For reasons I don't understand `R CMD check` succeeds for `checkpoint`, but `R CMD check --as-cran` fails. The failure message basically says that `cli` isn't installed.  The failure message is lying - `cli` is in fact installed.

If I include `library(cli); library(testthat)` in my `test-all.R` in `checkpoint`, all the problems disappear.  Likewise, if I add `cli` to the `NAMESPACE`, all my problems disappear.

I never use any `cli` directly from `checkpoint`.

So this is a mystery to me.

**Comment by andrie** [comment]
It seems this happens only on Windows. @colearendt tested this on Mac and is unable to replicate.

**Comment by gaborcsardi** [comment]
`R CMD check --as-cran` needs a `-l` argument if you use a custom library path. See
```r
R --vanilla -q -e ".libPaths()"
```
vs.
```r
R -q -e ".libPaths()"
```
