### ISSUE TITLE
helper file sourced twice

### ISSUE THREAD

**Issue by Christoph999** [r-lib/testthat#689]
Hi, the helper-file is sourced twiced. As I test creation and manipulation of folders this causes problems - although I found a workaround. See [here](https://stackoverflow.com/q/47350561/5784831). 

A stand-alone example can be found [here](https://github.com/Christoph999/test/tree/master/tests)

I would be happy if anybody could solve the problem or explain the behaviour. Thanks in advance, Christoph

**Comment by jimhester** [comment]
This is fixed in the development version of devtools

**Comment by Christoph999** [comment]
@jimhester Thanks! Really cool package! :-)
