### ISSUE TITLE
Test fails when run using test_that but not when executed line-by-line

### ISSUE THREAD

**Issue by briencj** [r-lib/testthat#692]
I have a bizarre problem that arises in testing asremlPlus, which also requires a commercial package asreml. In running one of the tests for the asremlPlus function predictPlus I get the following Error
#### Test for predictPlus.asreml
[31m1. Error: predictPlus.asreml (@testPredictionsPresentation.r#17) [39m---------------
could not find function "ie"
1: predictPlus.asreml(classify = "Sources:Type", asreml.obj = current.asr, tables = "none", 
       wald.tab = current.asrt$wald.tab, present = c("Type", "Species", "Sources")) at testthat/testPredictionsPresentation.r:17
2: predict(asreml.obj, classify = classify, sed = pairwise, trace = trace, ...)
3: predict.asreml(asreml.obj, classify = classify, sed = pairwise, trace = trace, ...)

So predict.asreml can not be found. The function predict.asreml is a function provided by the package asreml, which is loaded within the test using the library function, but predict.asreml is not exported by asreml. However, it can be accessed when asreml is loaded, as is evidenced by the fact that the code for the test executes correctly if I execute it line-by-line in the console.

Is there something that can be done such that testthat will successfully run the test?

It really would be much better if it could be made to work and so any help would be greatly appreciated, 

Regards, Chris Brien, University of South Australia

**Comment by gaborcsardi** [comment]
`predict.asreml` is found, it is in the call stack. However, the `ie` function cannot be found, as the error says:
```
could not find function "ie"
```

Where is this function?

**Comment by briencj** [comment]
I took "ie" to be some strange punctuation around "that is". Thanks for straightening that out.

As for the function I have no idea. It cannot be accessed from either asreml or asremlPlus via the ':::' operator. Not looking good.

**Comment by jimhester** [comment]
Please provide a more reproducible example, perhaps including the package where you are seeing this error.

**Comment by briencj** [comment]
I have found out that "ie" is a function internal to asreml. Unfortunately, asreml is a commercial package and so I cannot provide it. I have negotiated with the package maintainer to export predict.asreml, which I hope will solve the present issue. 

I did try to construct a reproducible example, without success. So I have closed the issue.
