### ISSUE TITLE
Cannot capture messages in testthat version 2.0

### ISSUE THREAD

**Issue by arendsee** [r-lib/testthat#693]
This issue may be related to #691.

The following test passes in the last `testthat` release (75c30cc), but fails in the current one (2.0.0):

```R
test_that("asdf", {
  expect_equal(capture.output({message('hi')}, type='message'), "hi")
})
```

In v2.0.0, I get the error message:

```
***: failure: asdf
`y` not equal to "hi".
Lengths differ: 0 is not 1
```

It seems `testthat` is eating the output before I can capture it.

This is currently breaking the dev version of my package `rmonad`. Internal functions that capture messages are now all failing.

**Comment by hadley** [comment]
Could you use `expect_message()` directly?

**Comment by jimhester** [comment]
A workaround is to just run the code where you are capturing the messages outside the `test_that()` block.

``` r
foo <- function(x){
  message(paste('hi', x))
}

bar <- function(x){
  msg <- capture.output(foo(x), type='message')
  sub('hi', 'bi', msg)
}

library(testthat)

res <- bar('alice')
test_that("msg is caught", {
  expect_equal(res, 'bi alice')
})
```

Created on 2018-03-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
I don't think this is really a bug in testthat, more like an issue with `capture.output(type = "message")`, so am going to close this.
