### ISSUE TITLE
Should TESTTHAT envvar be set inside individual `test_that()`s?

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#697]
The new TESTTHAT envvar is very useful for telling "if your code is being run inside a testing environment". However when I run a single `test_that()` test, i.e. during test development, interactive menus still appear in the Console. Should the TESTTHAT envvar be set in this context?

**Comment by jennybc** [comment]
In the absence of this behaviour, I've created a little helper for myself that makes it easy to fake it during test development, then back out again:

https://github.com/r-lib/usethis/pull/175/commits/4f6fad72263b3ca73da7d5b3cd95c427ca4554f6

**Comment by jimhester** [comment]
I don't know, setting the variable for every `test_that()` block seems heavyweight to me, but we can let this ruminate for a bit.

**Comment by hadley** [comment]
It feels too heavy to me. I'm going to close, but @jennybc you should feel free to re-open if you're passionate about it.

**Comment by jennybc** [comment]
This is converging with something in rlang:

https://github.com/r-lib/rlang/issues/738

I think either `rlang::is_interactive()` should be sensitive to the `TESTTHAT` env var or testthat should start to set the `rlang_interactive` option to `FALSE` everywhere that it sets the `TESTTHAT` env var to "true".

**Comment by jennybc** [comment]
But I have let go of the idea of setting/unsetting anything inside an individual test. I will be happy when we pick a single preferred convention for managing (shutting down) interactivity.
