### ISSUE TITLE
Provide expectations inspired by rlang `is_` functions

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#702]
e.g.

```R
expect_numeric(x, n = 10)
expect_call(x, "foo", n = 3)
...
```

This would complete the set started by `expect_null()`

**Comment by dugan131** [comment]
What would the 'n =' argument do; is that typo?

Is `expect_numeric(x)` the same as `expect_true(is.numeric(x))`?

**Comment by hadley** [comment]
Superseded by #846
