### ISSUE TITLE
Unexpected error within the context of 'test_that' function

### ISSUE THREAD

**Issue by mjpnijmeijer** [r-lib/testthat#706]
Hello,
The following strikes me as a bug. My aplogies if that is not the case. 

Define a function and a wrapper function:
```
f <- function(x){
  return(x)
}

fw <- function(x){
  argList = as.list(match.call()[-1])
  do.call( f, argList)
}
```
Test the wrapper function and notice that no errors are given:
```
library(testthat)
xx = 10
expect_equal( fw(xx), 10)
rm(xx)
```
Now carry out the same test in the context of `test_that`:
```
test_that( "wrapper function works fine", {
  xx = 10
  expect_equal( fw(xx), 10)
})
```
This time the error `object 'xx' not found` is returned. To me, this does not make sense but maybe it does or there is a solution.

**Comment by hadley** [comment]
The problem is that you can't capture function arguments that way because you lose the environment that they belong to. It works for your simple case, but a slightly different argument name illustrates the problem:

``` r
f <- function(x) {
  x
}

fw <- function(x){
  argList <- as.list(match.call()[-1])
  do.call(f, argList)
}

argList <- 10
fw(argList)
#> $x
#> argList
```

If you want to learn about better approaches, the best place is probably the metaprogramming chapter  of [advanced R](https://adv-r.hadley.nz) — I'm still working on it but it should be readable.

**Comment by itcarroll** [comment]
@mjpnijmeijer Came here also thinking this was a bug. I appreciate hadley's statement that there is probably a better approach, but wanted to share my finding that specifying the environment in your `do.call` appears to rescue the test_that:

```r
fw <- function(x){
    argList <- as.list(match.call()[-1])
    do.call(f, argList, envir = parent.frame())
}
```
I know that looks like the default, but [note](https://stackoverflow.com/questions/15504960/when-how-where-is-parent-frame-in-a-default-argument-interpreted) that true defaults are evaluated within the evaluation frame of the function call, from which place `parent.frame()` is the calling environment. Here, `parent.frame()` is the testing environment.
