### ISSUE TITLE
enhancement: extend test_example to validate output

### ISSUE THREAD

**Issue by itcarroll** [r-lib/testthat#710]
Currently, `test_examples()` does no more than `R CMD check`. If the developer has copied "*pkg*.Rcheck/*pkg*-Ex.Rout" from a previous run to "tests/Examples/*pkg*-Ex.Rout.save", then `test_examples()` in fact does less.

Twice (#335 and #255) it has been suggested that testthat could improve on `R CMD check` by individually validating Rd examples. I'm adding a third vote for this enhancement. If it remains outisde the scope of testthat, is there an alternative package where this feature could be welcome?

If a PR would be considered, please offer any additional guidance that would be critical for its adoption.

**Comment by jimhester** [comment]
We still have no plans to support this workflow, I would suggested implementing it in a new package if you want these features.
