### ISSUE TITLE
Likely an incorrect usage of Sys.timezone on R-devel and issues on SOLARIS

### ISSUE THREAD

**Issue by vspinu** [r-lib/testthat#713]
Lubridate runs 55 minutes on SOLARIS due to excessive use of Sys.timezone in testthat (identified by Prof Brian Ripley). 

AFAICS  testthat's [compare.POSIXt code](https://github.com/hadley/testthat/blob/master/R/compare-time.R#L29-L31) is not using `Sys.timezone` as intended (at least not in R-devel). R-devel news states:

> ‘Sys.timezone()’ on a Unix-alike caches the value at first use in a session: _inter alia_ this means that setting ‘TZ’ later in the session affects only the _current_ time zone and not the _system_ one. 

This means that `Sys.timezone` is system time zone and not the current time-zone implied by `""`  `tzone` attribute. For example:

```R
> Sys.setenv(TZ = "America/New_York")
> Sys.timezone()
[1] "Europe/Amsterdam"
> (tt <- now(""))
[1] "2018-02-02 10:33:34 EST"
> attr(tt, "tzone")
[1] ""
```

Also setting `Sys.setenv(TZ="")` results in an unpredictable system dependent behavior. Currently there is no way to get the time zone which R uses when `tzone` attribute is "". This seems to be the intent of testthat's snippet referenced above. 

----

Here are relevant parts from my CRAN submission regarding  SOLARIS issues. The following tracebacks appear if Sys.timezone is instrumented to break before reaching to "cmp".

```R

── 1. Error: int_start and int_end work as expected (@test-intervals.R#193)  ───
Sys.timezone reached last gasp
1: expect_equal(int_start(int1), time1) at testthat/test-intervals.R:193
2: compare(act$val, exp$val, ...)
3: compare.POSIXt(act$val, exp$val, ...)
4: standardise_tzone(as.POSIXct(x))
5: identical(attr(x, "tzone"), Sys.timezone())
6: Sys.timezone()
7: stop("Sys.timezone reached last gasp")

── 2. Error: addition handles daylight savings time (@test-ops-addition.R#7)  ──
Sys.timezone reached last gasp
1: expect_that(x + days(1), equals(as.POSIXct("2010-03-15 00:00:00", tz = "America/New_York"))) at testthat/test-ops-addition.R:7
2: condition(object)
3: expect_equal(x, expected, ..., expected.label = label)
4: compare(act$val, exp$val, ...)
5: compare.POSIXt(act$val, exp$val, ...)
6: standardise_tzone(as.POSIXct(x))
7: identical(attr(x, "tzone"), Sys.timezone())
8: Sys.timezone()
9: stop("Sys.timezone reached last gasp")

── 3. Error: subtraction handles daylight savings time (@test-ops-addition.R#16)
Sys.timezone reached last gasp
1: expect_that(x - days(1), equals(as.POSIXct("2010-03-14 00:00:00", tz = "America/New_York"))) at testthat/test-ops-addition.R:16
2: condition(object)
3: expect_equal(x, expected, ..., expected.label = label)
4: compare(act$val, exp$val, ...)
5: compare.POSIXt(act$val, exp$val, ...)
6: standardise_tzone(as.POSIXct(x))
7: identical(attr(x, "tzone"), Sys.timezone())
8: Sys.timezone()
9: stop("Sys.timezone reached last gasp")
```

Judging from Prof Ripley's comment this part should never be reached unless TZ is unset:

```
>> It seems it is running 'cmp' repeatedly, so I suspect something wrong with your
>> use of Sys.timezone (on Solaris TZ should always be set, and is on the check
>> farm, so that part of Sys.timezone should never be used).
```

So I am puzzled of why Sys.timezone ends in `cmp` in the first place.

**Comment by hadley** [comment]
It looks like this has been resolved? It looks like lubridate only takes 160s on solaris: https://cran.r-project.org/web/checks/check_results_lubridate.html
