### ISSUE TITLE
Ability to run come set up code across all tests

### ISSUE THREAD

**Issue by anandkkumar** [r-lib/testthat#715]
This is pretty much what was asked in issue [544](https://github.com/r-lib/testthat/issues/544)

As outlined in that issue, we have some common machine environment set up commands that need to run exactly once before all tests defined in the package. However, we only want these to be run in the context of running our unit tests.

Creating a helper.R file in the tests/testthat does work however it appears to have a side effect:  the lines in the helper file also executed when we build the documentation as part of a Makefile target, which calls 
R -e 'devtools::document(pkg="mypackage", roclets=c("namespace", "rd"))

So on our target production machine even though we are not running any unit tests, when we build & install our package with the Makefile, it ends up running those commands in helper.R

Is there a different way to accomplish this? Or are there parameters to the document method I can pass in, to not have it source the helper file?

Thanks.

**Comment by anandkkumar** [comment]
I suppose an alternative is to rename the helper.R file to test_0setup.R or something that is alphabetically before all other test scripts to force it to run first but I would reckon there's a better way than that to bootstrap the tests.

**Comment by hadley** [comment]
Use a setup file, instead of a helper.

**Comment by anandkkumar** [comment]
what do you mean by set up file? what I mentioned in my follow up comment i.e. just name something alphabetically first or is there a set up file construct for testthat which I am missing? 

Thanks.

**Comment by hadley** [comment]
Use `setup-` instead of `helper-`
