### ISSUE TITLE
Run tests only once in CI (e.g. Travis) setting with covr enabled

### ISSUE THREAD

**Issue by nbenn** [r-lib/testthat#717]
As far as I understand, in a typical CI setting, e.g. on Travis, all tests are run twice, once during `R CMD check` and once again during `covr::codecov()`. This seems wasteful. Wouldn't it make more sense, to skip testing during checking and instead have covr fail if a test fails? Is this currently possible?

I'm sorry if this has been discussed somewhere before - I couldn't find anything on the topic.

**Comment by jimhester** [comment]
covr modifies the package source in order to instrument the R code, which can change the behavior in some rare cases. It is better to do the coverage checks in a separate operation.
