### ISSUE TITLE
cat_line namespace error - maybe require cli >= 1.0.0 ?

### ISSUE THREAD

**Issue by BarkleyBG** [r-lib/testthat#718]
I just ran into a strange namespace issue. (Sorry, no good MWE). I'll suggest that testthat depends on the 'cli' package version >= 1.0.0.

I had been running testthat 1.2.0, and I used install.packages() to update to testthat 2.0.0. Then, I ran:
```
> testthat::test_file(
+   path = ftt,
+   reporter = "minimal"
+ )
Error: 'cat_line' is not an exported object from 'namespace:cli'
```
Similarly and unsurprisingly, running `devtools::test()` from the Rstudio hotkeys:
```
==> devtools::test()

Loading mypkg
Loading required package: testthat
Testing mypkg
Error: 'cat_line' is not an exported object from 'namespace:cli'
In addition: Warning message:
package 'testthat' was built under R version 3.3.3 
Execution halted
```

I saw that I had cli version 0.0.0.9000 installed. I didn't check to see what commit, or when it had been installed. 

#### Installing cli v1.0.0 from CRAN fixed the above issue.

- Perhaps change testthat to depend on cli >=1.0.0? It worked for me.
- I looked through the [GH history](https://github.com/r-lib/cli/blob/master/R/cat.R) of the cli package, and it seems that `cat_line()` has had `@export` in the roxygen docs since Hadley first added the function. I'm stumped.

**Comment by gaborcsardi** [comment]
0.0.0.9000 was never officially released, so you must have installed it from GitHub. But yeah, in an ideal world, all packages that depend on cli, should specify >= 1.0.0.

**Comment by BarkleyBG** [comment]
I have no idea when I would have installed cli, but I guess you're right that it would not have been installed from CRAN. Another mystery!

I suppose this error is pretty low-likelihood. Please feel free to close it if you'd like.
