### ISSUE TITLE
test_that does not search for S3 methods the same as its calling environment

### ISSUE THREAD

**Issue by billdenney** [r-lib/testthat#720]
This is the same issue as #266 (with an updated title).

`test_that` does not search for the same S3 methods as its calling environment.  If the S3 method is defined within `test_that`, it is not found when running the test.  (The issue could also be in expect_equal-- mainly, the code below should work.)

``` r
library(testthat)
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

test_that("foo2 fails", {
  foo.character <- function(obj) {
    paste(obj, obj)
  }
  expect_equal(foo2("hi"), "hi hi")
})
#> Error: Test failed: 'foo2 fails'
#> * no applicable method for 'foo' applied to an object of class "character"
#> 1: expect_equal(foo2("hi"), "hi hi") at <text>:12
#> 2: compare(object, expected, ...)
#> 3: foo2("hi")
#> 4: foo(obj) at <text>:5
```
``` r
library(testthat)
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

# foo2 has the expected result
foo.character <- function(obj) {
  paste(obj, obj)
}
foo2("hi")
#> [1] "hi hi"
```

**Comment by jimhester** [comment]
S3 uses lexical scoping if the S3 method is not registered. In your example the `foo.character` method is not defined in the scope of `foo2`, so the method is not used.

So this is working as intended, and even if it was not there isn't really a way to fix this behavior in testthat.

**Comment by JohnMount** [comment]
I'd say it is a `testthat` limitation.  In code that works when the user types it in at the console can't be quickly built as a test.  In the user's case the on-the fly `S3` function is in the .GlobalEnv`, which seems to be enough to make it findable.  In may case it was a function from a package that was trying to use `S3` methods which were not found- so placing them all together wasn't an option.

There is an (ugly) work around: copy you function to the `.GlobalEnv` for testing which does seem to be on the search path.  Here is a failing and working `reprex`.  This fix worked for the package function I was trying to test.

```r
reprex::reprex(input = '
library("testthat")
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

test_that("foo2 fails", {
  foo.character <- function(obj) {
    paste(obj, obj)
  }
  expect_equal(foo2("hi"), "hi hi")
})
')
#> Error: Test failed: 'foo2 fails'
#> * no applicable method for 'foo' applied to an object of class "character"
#> 1: expect_equal(foo2("hi"), "hi hi") at <text>:13
#> 2: quasi_label(enquo(object), label)
#> 3: eval_bare(get_expr(quo), get_env(quo))
#> 4: foo2("hi")
#> 5: foo(obj) at <text>:6
```

```r
reprex::reprex(input = '
library("testthat")
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

test_that("foo2 fails", {
  foo.character <- function(obj) {
    paste(obj, obj)
  }
  assign("foo.character", foo.character, envir = .GlobalEnv)
  expect_equal(foo2("hi"), "hi hi")
  rm(list = "foo.character", envir = .GlobalEnv)
})
')
```
