### ISSUE TITLE
Consider traceback of expectation failures

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#729]
And minimise impact of quasiquotation as much as possible.

**Comment by gaborcsardi** [comment]
Traceback would be great! Especially for things like `expect_error_free()`, etc.

**Comment by hadley** [comment]
Probably should use insights from `lobstr::cst()` to select more informative frames from stack.

**Comment by hadley** [comment]
And now insights from rlang

**Comment by lionel-** [comment]
Is this for compound expectations? We shouldn't get a backtrace in simple cases right? This doesn't seem very informative:

```
✔ |  OK F W S | Context
✖ |   2 2     | catch
────────────────────────────────────────────────────────────────────────────
test-catch.R:3: failure: bim bam boum
TRUE isn't false.
    █
 1. └─testthat::expect_false(TRUE) tests/testthat/test-catch.R:3:2
```

**Comment by lionel-** [comment]
We could print the trace only when it has more than one call:

```r
expect_this_and_that <- function(x) {
  expect_true(x)
  expect_false(x)
}

test_that("bim bam boum", {
  expect_false(TRUE)
  expect_this_and_that(TRUE)
})
```

```
✔ |  OK F W S | Context
✖ |   3 3     | catch
────────────────────────────────────────────────────────────────────────────
test-catch.R:8: failure: bim bam boum
TRUE isn't false.

test-catch.R:9: failure: bim bam boum
Message: `x` isn't false.
Backtrace:
    █
 1. └─testthat:::expect_this_and_that(TRUE) tests/testthat/test-catch.R:9:2
 2.   └─testthat::expect_false(x) tests/testthat/test-catch.R:4:2
```

**Comment by gaborcsardi** [comment]
I would think this is most useful for expectations that take an expression, like `expect_error`, `expect_silent()`, etc.

**Comment by jimhester** [comment]
Often the most important traceback is when there is an unexpected error during a test. 

If we could avoid having the testthat calls in the traceback in these cases it would clear up debugging greatly.

**Comment by lionel-** [comment]
When run from R CMD check, how about recording backtraces for all test failures, and creating a `testthat-failures.Rout.fail` file? This way we get backtraces for all unexpected results on the CRAN check page and on Travis.

**Comment by lionel-** [comment]
Scratch that, it wouldn't be very useful since the relevant call stack (from the code that produced the result) has already unwound at the time the expectation is signalled.
