### ISSUE TITLE
Support for setup and cleanup

### ISSUE THREAD

**Issue by nathaneastwood** [r-lib/testthat#730]
This issue has been discussed a few times before (#544 is the best example), but I really think it needs more discussion. I'm currently working on a package which uses `sparklyr`. In order to test my functions I must open a Spark connection. There are three ways that I can see to do this at the moment:

1. Include a `sparklyr::spark_connect()` command at the start of each test script and a `sparklyr::spark_disconnect()` at the end. 
2. Include a `sparklyr::spark_connect()` in a `helper-00_open_connection.R` file and a `sparklyr::spark_disconnect()` in a `test-99_close_connection.R` file (note 99 represents the last test number).
3. Write a wrapper function around `testthat::test_package()` which would open a connection, run `testthat::test_package()` and then close the connection.

The first method is tedious and requires potentially opening up a lot of connections. The second method is what I am currently using - it works fine but the naming convention isn't particularly nice. The third method isn't ideal for using testing platforms like Travis (plus would need testing itself presumably). 

My current file structure is along the lines of

```
├── tests
    ├── testthat
    │   ├── helper-00_open_connection.R
    │   ├── helper-01_function_1.R
    │   ├── test-01_function_1.R
    │   └── test-99_close_connection.R
    └── testthat.R
```

But it would look a lot nicer if we could have it more like:

```
├── tests
    ├── testthat
    │   ├── cleanup-01_close_connection.R
    │   ├── helper-01_function_1.R
    │   ├── setup-01_open_connection.R
    │   └── test-01_function_1.R
    └── testthat.R
```

It would be even better if we could choose names that made "cleanup" files at the bottom and "setup" at the top. It would look more logical.

**Comment by nathaneastwood** [comment]
Looking at the `sparklyr` package, there is a nice way of testing for and using a global connection [here](https://github.com/rstudio/sparklyr/blob/master/tests/testthat/helper-initialize.R#L1). Moving forwards, I may use this. But I still believe there is a case for a setup and cleanup in `testthat`.

**Comment by hadley** [comment]
Or use paired setup and teardown files.

**Comment by nathaneastwood** [comment]
Sorry @hadley, could you please explain what you mean by a "teardown file".

**Comment by hadley** [comment]
You have a `setup-` file. You also need a `teardown-` file.

**Comment by nathaneastwood** [comment]
Ok thanks, I just couldn't really see where this is documented anywhere. I see now that there are `setup()` and `teardown()` functions in `testthat`.

**Comment by flying-sheep** [comment]
Where’s the documentation? @hadley I know you’re super busy, but your replies are a bit too terse to be really useful.

**Comment by gaborcsardi** [comment]
See `?setup` and `?test_dir`.

**Comment by flying-sheep** [comment]
> Setup files start with ‘setup’ and are executed before tests

…from the `test_dir` docs is ambiguous, it could also mean “before each test”.

and no support for per-test-setup/-teardown?

**Comment by gaborcsardi** [comment]
You mean per `test_that()` call? Not that I know of, but that's easy to work around with sg. like:

```r
my_test_that <- function(desc, code) {
  my_setup()
  on.exit(my_teardown(), add = TRUE)
  test_that(desc, code)
}
```

**Comment by flying-sheep** [comment]
That’s a lot of boilerplate for something that is supported by virtually any test library.

**Comment by schradj** [comment]
I have built a package in which propbably at least 75% of the functions it contains require the presence of a package-specific S4 class object in the global environment.  Thus, all of the tests in testthat need an oject of that type to be present.  I suppose I could you setup- and teardown- to create the object for each test, but it seems more efficient just to create it once in a helper- for all of the tests to use.  I also came searching for a way to ensure cleanup of that object is taken care off at the end of testing.  If a suggestion has been posted for this type of request already, I haven't found it 
 so hopefully I'm not adding noise to this discussion.  But, it finally dawned on me to try just adding cleanup operations at the end of "/tests/testthat.R" after the test_check("package_name") function.
I created an object needed for all test in a helper- file, then just added a simple rm() command at the end of "/tests/testthat.R".

Seems to be working as desired, so if your situation sounds similar to mine, give it a shot!
