### ISSUE TITLE
Add warnings are errors option

### ISSUE THREAD

**Issue by michaellevy** [r-lib/testthat#731]
From @jimhester [here](https://community.rstudio.com/t/fail-ci-on-warnings-in-tests/6187/9):

> What you would likely want to do is modify https://github.com/r-lib/testthat/blob/master/R/reporter-check.R to additionally tally expectation_warning and then stop for warnings in a similar way to how it stops for errors.

> But maybe at this point it would be better to open an issue in the testthat repository and we can consider adding a stop_for_warning option to the check reporter.

**Comment by jimhester** [comment]
As of #721 you can now set `options(warn = 2)` to change warnings into errors in your tests, which would then fail the build if desired. So I am going to close this for now.
