### ISSUE TITLE
docs: improve documentation for code consumers

### ISSUE THREAD

**Issue by kortschak** [r-lib/testthat#733]
I have just needed to use testthat as a consumer of a package tested by testthat. The package provides a wealth of documentation for authors for use in testing their code, but there is not (I possible I just can't find) a simple and introduction and use vignette for consumer users wanting to run the tests on a package.

As a user of someone else's code, I'd like to be able to do `library(pkg); library(testthat); test_package("pkg")`. Reducing the friction on this particular action is what wold make people generally more inclined to randomly test packages and for that user behaviour to become ingrained, but finding that set of commands took more effort than I would have expected. When I tried it (and other permutations I was not successful in getting the tests to run) - see https://github.com/openjournals/joss-reviews/issues/593#issuecomment-375323491 (I posted `test_package("pkg")` but had also tried `test_package(pkg)`).

I'm coming from a Go background where the build chains testing infrastructure can be invoked from any location, e.g. `go test package/path/identifier`. Which was my understanding for the behaviour of `test_package`.

The author of that package has hooked travis to do the build, so I don't need to run them locally now. Related to this, is there an option to verbosely output the names of package tests that have been run (e.g. [from a set of our tests](https://travis-ci.org/gonum/gonum/jobs/357065778#L578))?

Apologies for the ramble. Hopefully I have made my concern clear enough.

**Comment by jimhester** [comment]
The way to do this is to use `devtools::test()`, which automatically loads and runs tests on a package. This is mentioned in the [Test Workflow](http://r-pkgs.had.co.nz/tests.html#test-workflow) section of the R packages book.

If you wanted to run all the checks used by CRAN (which include more than just tests) you can use `devtools::check()` to run the command line equivalent `R CMD check`.

**Comment by jimhester** [comment]
Packages are not installed with tests by default, so many users can't run the tests for installed packages anyway.

If they are installed then you can use [tools::testInstalledPackage()](https://www.rdocumentation.org/packages/tools/versions/3.4.3/topics/testInstalledPackage) to run them.

**Comment by kortschak** [comment]
Thank you, `tools::testInstallPackage` does whatish I want.
