### ISSUE TITLE
ProgressReporter overwrites previously printed lines in RTVS terminal

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [r-lib/testthat#735]
A simple scenario of `testthat::test_dir(some_path)` when there are multiple contexts tested, executed in VS Community.
ProgressReporter displays only summary of the latest context tested plus overall results. Table header and all results of previous contexts are overwritten. It has something to do with the way RTVS terminal handles `\r`, `\n` symbols and so on. 
Maybe something in the inherited `self$cat_tight(...)` or `end_context(...)` in [reporter-progress.R](../blob/master/R/reporter-progress.R) is causing this issue.
`sink`ed to a file results show all updates line-by-line (in my case of a hundred of light tests - one line per each passed test)

**Comment by hadley** [comment]
Isn't this an RTVS problem?

**Comment by Ilia-Kosenkov** [comment]
It is likely but I thought you might support RTVS by introducing some *if* condition and slightly altering output. Plus I noticed this issue after the package was updated so assumed there might be an error in `test_that`.

**Comment by gaborcsardi** [comment]
If RTVS does not handle `\n` and `\r` properly then the progress reporter cannot support it, I am afraid. I think the best option right now is to use another reporter, e.g. the summary reporter.
