### ISSUE TITLE
Continue with code after a test fail

### ISSUE THREAD

**Issue by shinsukato** [r-lib/testthat#741]
I'm using testthat as part of an automated test package done in rselenium.

Currently if any of my tests fail, it comes through as an error and code execution stops. Is it possible to set it up such that code will continue to execute after a test failure?

**Comment by MiloParigi** [comment]
Simply use the command try() !
```
return_value <- try(your_test_function())
```

If you want to know wether it failed or not, check the class of return_value
```
if (class(return_value) == "try-error") {
# That's an error
} else {
# Your test didn't failed and return_value is set to the result of your command
}
```

Hope this help ^^

**Comment by jimhester** [comment]
Use `testthat::test_dir()` or `testthat::test_file()` to run the tests.
