### ISSUE TITLE
Improve error message with missing arguments

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#743]
```
expect_identical("foo")
#> Error in eval_bare(get_expr(quo), get_env(quo)) (from eval.R#97) : object '' not found
```

**Comment by jimhester** [comment]
Any thoughts on a good way to handle this for all expectations?

I can do something like this, but the error message then is not much better.

```diff
diff --git a/R/expectation.R b/R/expectation.R
index 6dfd504..2f248c0 100644
--- a/R/expectation.R
+++ b/R/expectation.R
@@ -85,7 +85,9 @@ is.expectation <- function(x) inherits(x, "expectation")
 #' # variable name
 #' show_failure(expect_equal(f(!!i), !!(i * 10)))
 quasi_label <- function(quo, label = NULL) {
-  force(quo)
+  if (quo_is_missing(quo)) {
+    stop("`quo` is missing", call. = FALSE)
+  }

   list(
     val = eval_bare(get_expr(quo), get_env(quo)),
```

```r
expect_identical("foo")
#> Error: quo is missing
```

Ideally this would be 

```
`expected` is missing
```

I could hoist the `quo_is_missing()` check up to the `expect_identical()` body I guess, but then I would need to modify all of the other expectations in a similar way, which seems painful.

**Comment by lionel-** [comment]
Unfortunately I think there's no great way around this other than adding an explicit argument to `quasi_label()` to pass the argument name.

**Comment by lionel-** [comment]
Something like `"Missing argument in expectation"` Would already be much better though.
