### ISSUE TITLE
Confusing error when argument is missing in comparison expecation

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#749]
``` r
testthat::expect_equal(42)
#> Error in eval_bare(get_expr(quo), get_env(quo)): object '' not found
```

> Created on 2018-04-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I'd expect something like `` `expected` argument missing`` .

**Comment by czeildi** [comment]
#743 is I believe essentially the same issue

**Comment by krlmlr** [comment]
Thanks, totally missed that.
