### ISSUE TITLE
could not find function "test_dir"

### ISSUE THREAD

**Issue by danielmurran** [r-lib/testthat#752]
Any solutions for this? continuing to get this error from every r file I test on

**Comment by cderv** [comment]
Can you provide a little more context please ? 
How do you use this function ? 
Did you load `library(testthat)` ?

**Comment by danielmurran** [comment]
Hi, I followed the https://www.r-bloggers.com/unit-testing-with-r/ tutorial so I even get the error with that tutorial.

**Comment by danielmurran** [comment]
Thanks I will go ahead and do that!
