### ISSUE TITLE
Is it possible to gain access to `inst` in C++ code?

### ISSUE THREAD

**Issue by Shians** [r-lib/testthat#755]
I have example data that I would like to test C++ code with. But obviously I cannot call `system.file()` in C++. Is there mechanism I could use that would allow me to access the test data?

**Comment by gaborcsardi** [comment]
Can you get the file name in R, and then pass it to your C++ test?

If that is not an option, you can call back to R from C++, there are many examples, e.g.  this is how to do it with Rcpp: http://gallery.rcpp.org/articles/r-function-from-c++/

**Comment by Shians** [comment]
I used `testthat::use_catch()` to set up my testing environment. I don't know enough about the scaffolding set up to pass it through to C++. I guess the same applies to the Rcpp call, I'm not sure where the correct entry point is to pass things from R to C++ such that all the `Catch` tests have access to the values.
