### ISSUE TITLE
skip_on_cran skips a test ALWAYS

### ISSUE THREAD

**Issue by jromanowska** [r-lib/testthat#756]
I've noticed that when I use "skip_on_cran" in my tests, the tests would not run, even if I explicitly had set the NOT_CRAN variable to TRUE. Looking at the code here, it seems that the "skip( "On CRAN") " is misplaced - should be before the curly brace, not after. Please correct!

**Comment by gaborcsardi** [comment]
You have to set it to "true"  (lowercase), it is case sensitive.

**Comment by jromanowska** [comment]
Yes, of course - I'm sorry for the stupid mistake!

**Comment by gaborcsardi** [comment]
Also, note that this is an environment variable, not an R variable. I have the impression that  you set an R variable, maybe?

**Comment by jromanowska** [comment]
No, I did use Sys.setenv. But the mistake was in the case. I should have noticed that, sorry!
