### ISSUE TITLE
How to differentiate if syntax error in file or testcase failed?

### ISSUE THREAD

**Issue by riteshkukreja** [r-lib/testthat#758]
I wish to differentiate between valid testcases and invalid testcases in R using **list** reporter.

**Invalid**
```r
test_that("Invalid case", {
    fdrgdg
})
```

**Valid**
```r
test_that("valid case", {
    expect_true(FALSE)
})
```

**Comment by gaborcsardi** [comment]
I am not  sure what your motivation is, but note that  
```r
test_that("Invalid case", {
    fdrgdg
})
```
is  actually valid  R code.

**Comment by riteshkukreja** [comment]
@gaborcsardi Thanks. It was my mistake.
