### ISSUE TITLE
Idea: use as arg-checker

### ISSUE THREAD

**Issue by kenahoo** [r-lib/testthat#762]
It occurred to me that many of the checks I'd use as arg-checking code at the beginnings of exported functions might be the same things I'd use as `expect_*` functions in unit tests.  Is this a use case you've thought about?  It would be nice to get all the semantics of the expectation functions, and their more readable error messages.  In general unit test libraries tend to be a bit more feature-rich and have smoother interfaces than arg-checking libraries.  And it would be nice to have a unified model for both.

I don't like to go overboard with arg-checking, but for some high-level entry points (e.g. R code that we expose in Java APIs) it helps us fail fast when arg shapes aren't aligned, or aren't [coercible to] the right class, etc.

It probably wouldn't really make sense to actually do `library(testthat)` in application code, but a simple repackaging of the same functions into an arg-checking package could be cool.

**Comment by jimhester** [comment]
You can use the `expect_()` functions in package code now, unless they are in a `test_that()` block they signal an error, so you can just use them directly.
