### ISSUE TITLE
Suppression of JIT compilation within testthat environments

### ISSUE THREAD

**Issue by owenjonesuob** [r-lib/testthat#765]
This may be intentional behaviour (or perhaps a bug with **compiler** rather than **testthat**), but just-in-time compilation seems to be suppressed when code is executed by **testthat**.

---

#### System info:
**R** 3.4.3, 3.5.0
**testthat** 2.0.0
Windows, RHEL6 and 7

#### Example: `test-jit.R`
```r
context("Use of JIT compilation within testthat")

test_that("JIT compilation", {
  
  # Define a function
  collatz <- function(k, iters) {
    
    for (i in seq_len(iters)) {
      if (k %% 2 == 0) {
        k <- k/2
      } else {
        k <- 3*k + 1
      }
    }
    
    k
  }
  
  # No JIT compilation
  compiler::enableJIT(0)
  disabled <- system.time(collatz(77031, 1000000))
  
  
  # With JIT compilation (collatz() is a closure, so any level above 0 is fine)
  compiler::enableJIT(3)
  enabled <- system.time(collatz(77031, 1000000))
  
  print(disabled)
  print(enabled)
  
  expect_lt(enabled["user.self"], disabled["user.self"])
  expect_lt(enabled["elapsed"], disabled["elapsed"])
})
```

Running the contents of the `test_that()` block line-by-line yields, with reasonable consistency on my machine:
```
> print(disabled)
   user  system elapsed 
   1.38    0.02    1.49 
> print(enabled)
   user  system elapsed 
   0.40    0.00    0.41 
```

Running the `test_that()` block as a whole yields, again with reasonable consistency:
```
   user  system elapsed 
   1.44    0.02    1.50 
   user  system elapsed 
   1.46    0.02    1.49 
Error: Test failed: 'JIT compilation'
Not expected: enabled["user.self"] is not less than disabled["user.self"]. Difference: -0.02.
```

`test_file("test-jit.R")` produces the latter result, regardless of whether the function definition/execution/timing occurs within or before the `test_that()` block.

---

Having quickly tested on another version of R I have lying around, this does _not_ appear to be an issue on R 3.2.5 with **testthat** 1.0.2 - i.e. compiled code executes more quickly, as expected.

**Comment by hadley** [comment]
Unfortunately I don't know how `compiler::enableJIT()` works, so if you want to dig into this, unfortunately you'll have to investigate yourself.
