### ISSUE TITLE
S4 method test fails when passing load_all env

### ISSUE THREAD

**Issue by cdeterman** [r-lib/testthat#766]
I have a new method that I have exported in my package [here](https://github.com/gpuRcore/gpuRsparse) for the `typeof` generic for a new S4 class.  When I call `test_dir` on my package, everything runs fine.  However, if I extract the `load_all` env:

```r
pkg <- as.package(".")
ns_env <- load_all(pkg$path, quiet = TRUE)$env
```

This will result in the S4 method failing (i.e. `typeof` returns "S4" instead of what it should) in my test when I pass the object to `test_dir`

```r
test_dir("tests/testthat/", env = ns_env)
```

I don't know why this is happening.  I am interested in this because it is how the `devtools::test()` call works.  I suspect I am somehow overlooking something that makes sure the new S4 methods work.  I am importing the `methods` package and I have the new `typeof` method exported.  Any insight would be great.

**Comment by hadley** [comment]
We did a bunch of work to make `devtools::test()` work with S4 and unfortunately I don't remember exactly what is required.
