### ISSUE TITLE
expect_known_error()

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#768]
Might be same as or combinable with #681 expect_known_display() 

Re: Slack conversation about `expect_error()` and friends in the presence of crayon usage. We need nice way to write tests that are robust to presence/absence of, e.g., ANSI escape codes.

Quoting @hadley:
> I think what we really want here is `expect_known_error()` analogous to `expect_known_output()`.
> It's really a regression test to make sure that you haven't accidentally changed the error output, not a unit test of desired output
> We should probably have `crayon` options for both functions, defaulting to `FALSE`

**Comment by hadley** [comment]
I think this is now subsumed by #782
