### ISSUE TITLE
Add option to ignore all warnings

### ISSUE THREAD

**Issue by Serenthia** [r-lib/testthat#772]
As of #721, warnings are handled as errors (the equivalent of options(warn = 2)).  Is there any plan also to recognise a setting of options(warn = -1)?

I have a use case where functions will throw a warning when using a deprecated version of an object, but both deprecated and current still require testing for the period of rollout.  After testing once that the warning is thrown correctly, I'd prefer then just to verify that the function still works with either object type without the test being overrun by uncaught warnings.

**Comment by Serenthia** [comment]
Alternatively, might an option be to include the function output in expect_warning, so that this can be tested alongside the fact that a warning was generated.

**Comment by hadley** [comment]
If you want to do this, I think you should just make a small wrapper that either uses `expect_warning()` or `suppressWarnings()` to silent warnings when you don't care about them.
