### ISSUE TITLE
Adding test_that_file() function

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/testthat#776]
We used the following function in styler and elsewhere to create the absolute path to testthat files when running R CMD check and executing test interactively. Because if you run R CMD check, the working directory is changed to `./tests`. I know it's a pretty small function and it needs the rprojroot dependency but I found it rather helpful. Do you think it fits into testthat?
```r
#' Create the path to a test that file
#' 
#' @param ... Arguments passed to [file.path()] to construct the path after
#'   ".../tests/testthat/"
#' @keywords internal
testthat_file <- function(...) {
  file.path(rprojroot::find_testthat_root_file(), ...)
}
```

cc: @krlmlr

**Comment by krlmlr** [comment]
It's just a wrapper around an exported _rprojroot_ function, I'm not sure. Would we `Suggests:` or `Imports:` the _rprojroot_ package?

**Comment by jimhester** [comment]
We have http://testthat.r-lib.org/reference/test_path.html for this.

**Comment by lorenzwalthert** [comment]
Thanks @jimhester, I did not know about it. Should have searched more thoroughly.
