### ISSUE TITLE
expect_lt* and expect_gt* with dates and times

### ISSUE THREAD

**Issue by boshek** [r-lib/testthat#777]
I would expect that this should work:

``` r
library(testthat)
expect_lte(Sys.time()- 1E5, Sys.time())
#> Error in expect_compare("<=", act, exp): is.numeric(act$val) is not TRUE
```

Instead I have to resort to this:

```r
library(testthat)
expect_true(Sys.time()- 1E5 <= Sys.time())
```

Possibly one could add `inherits(Sys.time(), "POSIXct")` to

https://github.com/r-lib/testthat/blob/ef9c814e07233d26f67dd64bdc8a3388022a90af/R/expect-comparison.R#L27-L28

Am I understanding usage properly here? It could be that these were never meant to be used with dates and times.

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/testthat/commit/d43ed65dfe107b7751af92d7328088a57375bf6a

Now any objects which define the appropriate comparison method should work.
