### ISSUE TITLE
testthat crash (including a trivial package to reproduce)

### ISSUE THREAD

**Issue by KallyopeBio** [r-lib/testthat#778]
RStudio (as well as R sessions run from the terminal) crashes when devtools::test is invoked twice in succession on a package that uses Catch, via package testthat. The crash occurs in testthat/include/testthat/vendor/catch.h.

I've attached a trivial package that reproduces the problem:
[ttcrash.tar.gz](https://github.com/r-lib/testthat/files/2225953/ttcrash.tar.gz)

Exact steps to reproduce:
1.) Simply install the package to "some_directory".
2.) > "library(devtools)"
3.) > test("some_directory/ttcrash")
4.) > test("some_directory/ttcrash")

The crash will occur on the last step. I'm using R version 3.4.4 and testthat version 2.0.0

**Comment by KallyopeBio** [comment]
I've posted the same issue on the github repo for devtools

**Comment by jimhester** [comment]
I am going to close this one in favor of https://github.com/r-lib/devtools/issues/1832
