### ISSUE TITLE
retest option

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/testthat#784]
Feature request: it would be nice to have a `retest` function which tested only the previous failures. Or, only *from* the previous failures, in the case where tests bail out on the first failure. Useful for quick testing in development.

**Comment by hadley** [comment]
We don't currently record the previous test run in any way, so this is currently too hard to make implementing it worthwhile. But you might like `devtools::test_file()` which allows you to run the tests in just the one test file corresponding to the current R file.
