### ISSUE TITLE
Reporters: end_file() method is never called

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#785]
AFAICT. I am not sure, if this is expected, just ran into this when trying to write a reporter that cleans up  sub-processes (optionally) at the end of each test file.

**Comment by jimhester** [comment]
You are right, looks like it needs to be added at 

https://github.com/r-lib/testthat/blob/42e3a7992cd4b011db8bddd279e7482fef6271ce/R/test-files.R#L128-L140

**Comment by gaborcsardi** [comment]
Maybe it is called, except for the last context? But I am not sure, I forgot. I guess contexts are going away, anyway....

**Comment by hadley** [comment]
As far as I can `end_context` isn't actually bound to anything in the scope of this function.
