### ISSUE TITLE
Remove test that mocks devtools::add_path()

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#786]
`devtools::add_path()` does not exist in current devtools (https://github.com/r-lib/devtools/commit/dbf00241ec0a48ea1a19e7c96be2ace21d7e726d) and this test mocks it and therefore fails for me:

https://github.com/r-lib/testthat/blob/1faa32fc1afa769ac16bdb5792fd597324143c57/tests/testthat/test-mock.R#L81-L87

I can't decide if this test should be deleted or modified, so will not make a PR to fix this.

**Comment by hadley** [comment]
Fixed in #803
