### ISSUE TITLE
test_dir() does not set TESTTHAT_PKG env var

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#787]
`devtools::test()` calls `testthat::test_dir()`, which doesn't set the TESTTHAT_PKG env var. I get this failure using `devtools::test()` on testthat itself:

```
✖ |  12 1     | test_dir [0.1 s]
─────────────────────────────────────────────────────────────
test-test_dir.R:12: failure: TESTHAT_PKG env var set to the package being tested
testing_package() not equal to "testthat".
1/1 mismatches
x[1]: ""
y[1]: "testthat"
```

**Comment by lionel-** [comment]
We also need this for the new deprecation tools, so we can check that the caller inherits from the namespace of the package being tested and only warn then.

**Comment by lionel-** [comment]
Thanks!
