### ISSUE TITLE
expect_equal() fails for numeric vectors containing Inf values

### ISSUE THREAD

**Issue by andypea** [r-lib/testthat#789]
Calls to `expect_equal()` fail whenever the values to be compared are numeric vectors with coincident entries having the value `Inf`. For example, on my machine, the following code:

`
library(testthat)
expect_equal(c(0, Inf), c(1, Inf))
`

produces the error:

`
Error in is.character(message) : missing value where TRUE/FALSE needed
`

This should probably be fixed by handling `Inf` values explicitly in the function `vector_equal_tol()`, making the result consistent with a call to `vector_equal()`. Alternatively, `mismatch_numeric()` could be altered, so that it handles a `diff` argument containing entries which are neither `TRUE` nor `FALSE`.

[expect_equal_inf_bug.txt](https://github.com/r-lib/testthat/files/2276437/expect_equal_inf_bug.txt)

**Comment by hadley** [comment]
Reprex

``` r
library(testthat)
expect_equal(c(0, Inf), c(1, Inf))
#> Error in is.character(message): missing value where TRUE/FALSE needed
```

<sup>Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Even more minimal reprex:

```R
vector_equal_tol(c(0, Inf), c(1, Inf))
#> [1] FALSE    NA
```
