### ISSUE TITLE
Error: 'local_envvar' is not an exported object from 'namespace:withr'

### ISSUE THREAD

**Issue by Lei-Duan** [r-lib/testthat#792]
Hi, I'm trying follow the steps in [test]("http://r-pkgs.had.co.nz/tests.html") and run into an error when I'm runing the `devtools::test()` :

`Error: 'local_envvar' is not an exported object from 'namespace:withr'`

I would say that my test-functionname.R file is in the directory : pkg_wd/tests/testthat 
Anyone could help on this one?

**Comment by hadley** [comment]
It currently requires 2.0.0, which does contain `local_envvar`
