### ISSUE TITLE
stop_on_failure option for progress and summary reporters

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#797]
Or all reporters? 

I would like to have a reporter with  more output for `R CMD check`, but then these need to throw an error on failure.

**Comment by jimhester** [comment]
There is a stop reporter you coudl use (https://github.com/r-lib/testthat/blob/master/R/reporter-stop.R), I guess I am not 100% clear on your use-case.

**Comment by gaborcsardi** [comment]
I want to see the progress, and I want to `stop()` if there was a failure, _after_ running the whole test suite. The stop reporter does not really help here.

**Comment by hadley** [comment]
I'd rather just make the `CheckReporter` better. I'll take a look when I'm next working on testthat (after tidyr)
