### ISSUE TITLE
"testthat:::all_passed" method returns TRUE even when some tests fail

### ISSUE THREAD

**Issue by anirudhacharya** [r-lib/testthat#799]
While writing a test if I made a typo and used `testthat` instead of `test_that`( [doc](https://www.rdocumentation.org/packages/testthat/versions/2.0.0/topics/test_that)) it will fail the test, but calling `all_passed` on the test result will return TRUE.

For example if I write the test as follows -
```bash
testthat("sample", {
       expect_equal(1, 1)
   })
```
and run the test with `res<-test_dir("R-package/tests/testthat")` then it will fail with syntax errors, as expected, but calling `testthat:::all_passed(res)` will return TRUE.

**Comment by hadley** [comment]
I don't see the problem:

``` r
library(testthat)
testthat("sample", {
  expect_equal(1, 1)
})
#> Error in testthat("sample", {: could not find function "testthat"
```

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I suspect there is something else going on in your environment.
