### ISSUE TITLE
Disable cutesy, encouraging messages?

### ISSUE THREAD

**Issue by ddheart** [r-lib/testthat#804]
Is there a way to disable the cute messages when tests fail? (a la "No one is perfect" et al.?) 
It can get to be cumbersome during repeated unit tests. 

```
> test_file('myscript.R')
✔ | OK F W S | Context
⠹ |  3       | 0Error in x[[method]](...) : attempt to apply non-function

══ Results ════════════════════════════════════════════
OK:       3
Failed:   5
Warnings: 0
Skipped:  0

No-one is perfect!
```

Apologies if there's an obvious answer or configurable option I'm missing.

**Comment by jimhester** [comment]
The ProgressReporter has a `show_praise` option you can use to disable this.

```r
devtools::test(reporter = testthat::ProgressReporter$new(show_praise=FALSE))
```

**Comment by Kodiologist** [comment]
I had to find this issue to figure out how to turn the messages off. Is the above method documented anywhere? All I could find is that https://testthat.r-lib.org/reference/SummaryReporter.html says "As an additional benefit, this reporter will praise you from time-to-time if all your tests pass." 

Sidebar: I have no clue why this was implemented, let alone enabled by default. It adds visual noise to a function you're running a lot that produces a lot of output, and you need to look at the output every time to see how it's changed. So this is about the worst place to add random noisy messages.
