### ISSUE TITLE
expect_output doesn't let you control console width

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/testthat#805]
Unlike `expect_known_output()`, which lets you pass a [`width` argument](https://github.com/r-lib/testthat/blob/0dbb49c883fe99c7256f357dc50be7d631f8dd1d/R/expect-known.R#L46), `expect_output()` has a hard-coded 80-character width. Even though `capture_output()` does take a width arg, `expect_output()` calls `quasi_capture()`, which calls `capture_output()` with no additional args, so you can't pass it through. 

Here's a test that illustrates:

```
context("debug")
test_that("expect_output respects 'width'", {
    withr::local_options(list(width = 10))
    expect_equal(getOption("width"), 10)
    expect_output(
        expect_equal(getOption("width"), 10),
        NA
    )
})
```

The width check inside of `expect_output` fails:

```
debug: .1.

══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure: expect_output respects 'width' (@test-debug.R#5)  ───────────────
getOption("width") not equal to 10.
1/1 mismatches
[1] 80 - 10 == 70
```

I'm happy to submit a patch if you can provide guidance on where you'd like it solved. My instinct would be to move the `withr::local_options` setting from where it is inside [`eval_with_output`](https://github.com/r-lib/testthat/blob/0dbb49c883fe99c7256f357dc50be7d631f8dd1d/R/capture-output.R#L43) to `test_file()` or somewhere higher so that you can control print width options within your test files normally using `options(width = whatever)`. You could also extend `expect_output` to have a width argument to match `expect_known_output`, but I suspect that's a bigger refactor.

**Comment by hadley** [comment]
I think the right fix is to add an explicit `width` option to `expect_output()`. I don't think you want to inherit the width from your options because that might differ from system to system, leading to spurious failures.
