### ISSUE TITLE
with_mock missing from pkgdown reference

### ISSUE THREAD

**Issue by maelle** [r-lib/testthat#807]

**Comment by jimhester** [comment]
I think this may be intentional, `testthat::with_mock()` is somewhat deprecated in favor of the mockery package.

**Comment by maelle** [comment]
Aaah okay, it makes sense. I :eyes: "“Can’t mock functions in base packages”: You can no longer use with_mock() to mock functions in base packages, because this no longer works in R-devel due to changes with the byte code compiler. I recommend using mockery or mockr instead." in [the release post](https://www.tidyverse.org/articles/2017/12/testthat-2-0-0/). With your comment above, I wrote "the testthat package itself has a with_mock() function, but it’s now recommended to rather use the mockery or mockr packages." in [this post](https://itsalocke.com/blog/packages-for-testing-your-r-package/)

**Comment by maelle** [comment]
Should the recommendation to use `r-lib/mockery` be a bit more visible in the docs? :slightly_smiling_face:
