### ISSUE TITLE
Make auto_test_package work with C++ tests

### ISSUE THREAD

**Issue by Yuri-M-Dias** [r-lib/testthat#809]
Hello, and thanks for the for awesome package! 
I was wondering if there's any way to make the `autotest` function work with C++ tests too? I used `use_catch()` to add the tests to my project, however I need to rerun the tests for the C++ part manually, and can't rely on `autotest` for that. 

From what I can gleam in the code ([here](https://github.com/r-lib/testthat/blob/master/R/auto-test.R)) , it's not made for looking anywhere else that isn't `tests/` and `R/`, so I don't think that there's a way of doing this now, correct? I can submit a PR for this if it's desirable/the correct place to do so.

**Comment by hadley** [comment]
It looks like this should be a fairly straightforward modification to `auto_test_package()` to add `file.path(pkg$path, "src")` to `code_path` if it exists. Do you want to have a go at implementing this?
