### ISSUE TITLE
skip_on_cran() ignored on RBlas

### ISSUE THREAD

**Issue by dmenne** [r-lib/testthat#814]
I have a test that fails on some OpenBLAS variants, so I tried to skip it with skip_on_cran

https://github.com/dmenne/gastempt/blob/master/tests/testthat/test-fitnlme.R

However, the test runs nevertheless on OpenBLAS (and ATLAS)

https://www.stats.ox.ac.uk/pub/bdr/Rblas/OpenBLAS/gastempt.out

**Comment by dmenne** [comment]
See also 
https://cran.r-project.org/web/checks/check_results_gastempt.html

**Comment by jimhester** [comment]
The tests results seen to be passing fine to me.
