### ISSUE TITLE
Introduce let and subject

### ISSUE THREAD

**Issue by smbache** [r-lib/testthat#818]
Maybe there's already a way to do this, but I missed it.

How about introducing `let` and `subject` ala RSpec to allow for the following test:

```R
describe("function hello", {
  
  # this will be the test subject for all cases below
  subject(hello(name))

  # some default value for the test data
  let(name, "Harry")
  
  # the default/standard case
  it("says hello to `name`", {
    expect_equal(subject, "hello Harry")
  })

  # some variations to consider
  describe("when name is a vector", {
    let(name, c("Harry", "Potter"))

    it("collapses the string to a scalar", {
      expect_equal(subject, "hello Harry Potter")
    })
  })

  describe("when name is not a string", {
    let(name, 5)

    it ("throws an error", {
      expect_error(subject)
    })
  })

  describe("when name is not 'let' for this describe", {
    it("knows Harry from the top level", {
      expect_equal(subject, "hello Harry")
    })
  })
})
```
(the equivalent Rspec notation is `let(:name) { "Harry" }` and `subject { hello(name) }`).

This is obviously a simple example, and not too much is gained from the lazy re-evaluation of `subject` and `let` defines, but in realistic examples it is useful.

Can be implemented e.g. like
```R
let <- function(symbol, expression) {
  expr <- substitute(expression)
  sym <- as.character(substitute(symbol))

  parent <- parent.frame()
  attr(parent, "__has_let__") <- TRUE

  makeActiveBinding(sym, function(v) {
    has_let <- function(x) isTRUE(attr(x, "__has_let__"))
    if (missing(v)) {
      frames <- sys.frames()
      latest <- frames[[max(which(vapply(frames, has_let, logical(1))))]]
      eval(expr, latest, latest)
    }
  }, parent)
}

subject <- function(expression) {
  let_subject <- call("let", "subject", substitute(expression))
  eval.parent(let_subject)
}
```
but maybe there's a better way if you know the internals of `testthat`.

I can open a PR if there's interest in this addition...

**Comment by smbache** [comment]
This function would pass the tests :)

```R
hello <- function(name)
{
  if (!is.character(name))
    stop("name is not character")

  paste("hello", paste(name, collapse=" "))
}
```

**Comment by jimhester** [comment]
If we did go this route the natural way to do it would be to use the glue package

**Comment by smbache** [comment]
Are you talking about the `hello` function (😆) or the proposed addition?

**Comment by hadley** [comment]
Hmmm, I'm not sure if we want to add more to the `describe` framework. I think that probably would've been better off as a separate package from the beginning.

**Comment by hadley** [comment]
Ok, same answer as #747: we don't ever use this style, so it really belongs in its own package with a maintainer that cares about this style of testing.
