### ISSUE TITLE
expect_identical() doesn't dispatch on identical() methods defined in other packages

### ISSUE THREAD

**Issue by jarodmeng** [r-lib/testthat#820]
The core comparison within `expect_identical()` is carried out by calling `identical(x, y)` ([code link](https://github.com/r-lib/testthat/blob/master/R/expect-equality.R#L107)).

Currently, since `identical()` is not a generic, `expect_identical()` always calls `base::identical()`. However, user might want to define some specific `identical()` method for specific objects. For instance, `RProtoBuf` package defines an `identical()` method for comparing two `Message`s ([code link](https://github.com/eddelbuettel/rprotobuf/blob/master/R/identical.R#L3)). Those user-defined methods are not visible to `testthat` and are not used (see [this issue](https://github.com/eddelbuettel/rprotobuf/issues/55) in `RProtoBuf` repo for context).

It would be great if `testthat` can define a generic on top of `identical()` so that it can dispatch to specific methods defined by other packages.

**Comment by jimhester** [comment]
I think the proper solution to this is for the package (RProtoBuf) to define a `compare.Message()` method for the `compare()` generic already defined in testthat.

**Comment by jarodmeng** [comment]
Isn't `compare()` more comparable to `all.equal()` rather than `identical()`? See comment [here](https://github.com/r-lib/testthat/blob/master/R/compare.R#L3).

**Comment by hadley** [comment]
I don't think it makes sense for `identical()` to have methods; I think you do actually want a method for `all.equal()` or `compare()` here.
