### ISSUE TITLE
Support for temporary files and directories

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#828]
These should be cleaned up, so it would be nice to support them "natively". E.g. something like:

```r
tmpf <- test_temp_file()
tmpd <- test_temp_dir(cleanup = "block")
```

`cleanup` can be `block` or `file` or `testsuite`, to specify when to clean up the files.

`withr::local_tempfile()` is almost good, and testthat could use it internally, but it is annoying that it fails if you copy and paste a test case to the console:
```r
❯ withr::local_tempfile("foobar")
Error in defer(unlink(mget(new, envir = envir)), envir = envir) :
  attempt to defer event on global environment
```

The testthat function could just ignore these calls.

Happy to do a PR.

**Comment by jimhester** [comment]
That error would be fixed by https://github.com/r-lib/withr/pull/76, which basically we just need to settle on an API for.

**Comment by gaborcsardi** [comment]
FWIW, here are some simple versions:
```r
test_temp_file <- function(fileext = "", pattern = "test-file-",
                           envir = parent.frame()) {
  tmp <- tempfile(pattern = pattern, fileext = fileext)
  withr::defer(
    try(unlink(tmp, recursive = TRUE, force = TRUE), silent = TRUE),
    envir = envir)
  tmp
}

test_temp_dir <- function(pattern = "test-dir-", envir = parent.frame()) {
  tmp <- test_temp_file(pattern, envir = envir)
  dir.create(tmp, recursive = TRUE, showWarnings = FALSE)
  tmp
}
```

**Comment by hadley** [comment]
Can this now be handled by withr?

**Comment by hadley** [comment]
Yes, it seems clear this is now the responsibility of withr.
