### ISSUE TITLE
Would like to know Warnings / messages in expect output

### ISSUE THREAD

**Issue by zappingseb** [r-lib/testthat#832]
he Error message from expect_output is not detailed enough for certain tests.

```
f <- function(x) {
	if (x < 0) warning("*x* is already negative")
	-x
}
expect_silent(f(-1))
```

Message: `f(-1) produced warnings.`

I would expect sth like:

Message: `f(-1) produced warnings. Warning 1: 'x* is already negative'`

In case of this function:

```
f <- function(x) {
	if (x < 0) warning("*x* is already negative")
       message("This ran")
	-x
}
expect_silent(f(-1))
```

Message: `f(-1) produced warnings and messages. Warning 1: 'x* is already negative', Message1: 'This ran'`

Can this be implemented?

**Comment by hadley** [comment]
`expect_silent()` is a catch-all, so it's not designed for much information. I'd recommend using `expect_warning(f(-1), NA)` instead.
