### ISSUE TITLE
Regression versus failure

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#834]
This is about better support for tests that should not cause R CMD check failures because they are testing output that is not under the developer's control, at least not entirely. For instance, rlang has a lot of `expect_known_output()` tests for the backtraces. These outputs sometimes change across R versions, e.g. because `eval()` produces a different backtrace. Another case is vdiffr tests, because the appearance of plots is sensitive to upstream code such as computation of margins or spacing between elements.

Such tests should fail on platforms where the `CI` envvar is set (Travis, Appveyor), or where the `NOT_CRAN` envvar is set (tests run locally). This allows the developer to monitor and assess regressions during development.

@hadley suggested calling these tests regression tests. They could be implemented with a new expectation class `expectation_regression`.

**Comment by jimhester** [comment]
I don't really see what the advantage to what you describe over using `skip_on_cran()` for these blocks.

**Comment by lionel-** [comment]
This is what I planned to do initially but Hadley suggested using a special expectation. Perhaps it is about giving more structure to this class of expectation?

Is `NOT_CRAN` set on Appveyor as well?

**Comment by hadley** [comment]
I think there's a class of expectations that should be ignored on CRAN by default (i.e. regression tests). I don't have any strong feelings about how it should be implemented.

**Comment by lionel-** [comment]
If these tests are mostly about outputs, it would be useful to send a structured expectation with before/after fields. We could then provide tools to review and validate regressions similar to what we have in vdiffr.

**Comment by jimhester** [comment]
Would it make sense to use the standard testing machinery, but name the test files different? e.g. `reg-xyz.R` and these tests only get run when `NOT_CRAN` is set, or some other regression test specific switch?

**Comment by lionel-** [comment]
Interesting idea. Advantages:

* It works with all expectations.
* It would be easy to move a test from one file to the other to change its semantics.

Disadvantages:

* Most users would probably just keep using the test- files, even for things that should clearly be in reg- files.
* This would multiply the number of files in the test folders. This could be a problem in ggplot2 which has already many files, though I guess that's an extreme case. Could also be mitigated by having support for `setup`, `helper`, `test`, and `reg` folders. 

About `NOT_CRAN`, I think using a different skip that checks for both `NOT_CRAN || CI` would be better, because r-appveyor is documented not to set `NOT_CRAN` by default.

**Comment by hadley** [comment]
Oh yeah, I like that idea too. Maybe `check_that()`?

**Comment by lionel-** [comment]
`skip_on_cran()` (or similar) might not be right because we still need the code to be evaluated. If the code throws an unexpected error, this should be a hard failure.

The motivation for this is that while we cannot always control how an exact output evolves over time, the code generating the output should be robust and always work.
