### ISSUE TITLE
AppVeyor badge on README shows "unknown"

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/testthat#838]
This repository has `appveyor.yml` and the badge on README, but it seems no checks are invoked actually. Is AppVeyor intentionally disabled? Or, did you forget to make a change when the repo was moved from `hadley/testthat` to `r-lib/testthat`?

https://ci.appveyor.com/project/hadley/testthat

**Comment by hadley** [comment]
This is because appveyor is a disaster when you an repo moves organisations. @jimhester do you remember what we need to do to fix this?
