### ISSUE TITLE
expect_failure with multiple expectations

### ISSUE THREAD

**Issue by mb706** [r-lib/testthat#839]
When calling `expect_failure` with an expression that executes multiple `expect()` in a row then only the first of these expectations is evaluated. It would be useful to have an `expect_failure`-like function that evaluates all of `expr` to check for failures. This would make it possible to evaluate test functions that test complicated requirements with many successive `expect_*` calls.

Example:
```r
> testfun <- function(x) { expect_gt(x, 0) ; expect_lt(x, 1) }
> testfun(2)
Error: `x` is not strictly less than 1. Difference: 1
> expect_failure(testfun(2))
Error: Expectation did not fail
```

**Comment by hadley** [comment]
You need to use `test_that()` to set up the right infrastructure for that to work.
