### ISSUE TITLE
Test with no expectation becomes a "skip" (problem for test_examples)

### ISSUE THREAD

**Issue by colearendt** [r-lib/testthat#841]
When `testthat` runs a `test_that` with no expectations in it, the result is "Skipped." I think this behavior would preferably be "Passed", since the code was executed without error or `skip()`.

In particular, this is certainly not correct behavior for `test_examples()`, which should not be expected to have an expectation. As a result, if we can change the behavior for `test_example` or `test_examples()` at least, that would be helpful! 

Also, if we are not changing the default, is it possible that we could make the "Skip" note more informative? Something like `Skipped: No expectation found`. I found it quite confusing trying to debug why my tests were getting skipped, when they were in fact being executed but did not have an expectation. 

Thanks!

**Comment by hadley** [comment]
Two features:

* [ ] `skip_empty()` should return a more informative message
* [ ] `skip_empty()` should not be called within `test_example()`

**Comment by hadley** [comment]
First problem was #868
