### ISSUE TITLE
expect_success Fails on Success

### ISSUE THREAD

**Issue by wsherwin** [r-lib/testthat#844]
When trying to test a function with valid output, expect_success fails as if it was being fed a NULL value. Here is a test case:
```
funcDummy <- function(x, y) {
   return(x + y)
}
```
Running `expect_success(funcDummy(2,3))` yields the following error:
> Error: no expectation used.

However, per line 19 of `expect-self-test.R`, this should succeed (because its value is 5, not NULL).

**Comment by jimhester** [comment]
`expect_success()` tests if a single expectation succeeds. 

There is no expectation used in this example, so it is working as intended.

To get it to work you would have to use something like `expect_success(expect_equal(funcDummy(2, 3), 5))`

But in most cases you would just use `expect_equal()` directly.

**Comment by a-kramer** [comment]
How would you write a test for a function with no return value? 
The name `expect_success` really sounds like it _is_ an expectation.

```R
test_that("example data set is valid",{
 data(example)
 expect_success(data.is.valid(example))
```
