### ISSUE TITLE
Inconsistency in test script naming conventions

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/testthat#850]
In the help for `test_dir`, it states that test files start with "test", and this is backed up by the code in `find_test_scripts`. On the other hand, the `filter` argument is only applied once the string "test-" (with hyphen) is stripped from the filename. This could potentially lead to issues if a script is named "testfoo.R" or "test_foo.R".

**Comment by hadley** [comment]
It is as documented, and I'd prefer not to make changes unless there are compelling reasons to do so.
