### ISSUE TITLE
StopReporter doesn't stop

### ISSUE THREAD

**Issue by HughParsonage** [r-lib/testthat#851]
How can I run the test suite of a package so that any failure immediately halts so that the following tests do not run? 

My use-case is I have a package with a moderately long-running test suite with some 1000 tests. Often a failure occurs in the first dozen or so, but if I just run `devtools::test()` I have to wait till the other tests succeed before I can debug. 

I note that there is an argument `stop_on_failure` but this doesn't seem to do what I want. I'm guessing I could achieve this via a reporter but not sure if there is a better way.

**Comment by jimhester** [comment]
I generally just interrupt the tests once a failure happens, but understand this is not ideal.

There is a `stop` reporter, e.g. `devtools::test(reporter = "stop")` but with limited testing it seems broken...

**Comment by hadley** [comment]
It works ok interactively:

``` r
library(testthat)

with_reporter("stop", {
  test_that("this should fail", {
    expect_equal(1, 2)
  })
})
#> Error: Test failed: 'this should fail'
#> * 1 not equal to 2.
#> 1/1 mismatches
#> [1] 1 - 2 == -1
```

<sup>Created on 2019-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

But ` devtools::test(reporter = "stop")` doesn't fail.

**Comment by hadley** [comment]
Hmmm, a little interactive browsing reveals that the `StopReporter` is throwing the error, so something must be silently eating it.

**Comment by hadley** [comment]
I thought this might be an easy fix but it's something to do with the error being swallowed by the tooling that detects errors _inside_ tests. I'll need to come back to it when I'm deeper into testthat.

**Comment by hadley** [comment]
Good reprex:

```R
testthat::test_file("tests/testthat/test_dir/test-failures.R", reporter = "stop")
```

**Comment by hadley** [comment]
Ok, I have a hacky way to fix this, which is to throw a special type of error that terminates the test run early. But I'd rather not add even more complication to the code before we've reviewed it to make sure the current process mostly makes sense. That will happen as part of #729
