### ISSUE TITLE
expect_cpp_tests_pass() failing CRAN checks on os X 

### ISSUE THREAD

**Issue by bflammers** [r-lib/testthat#854]
Hi, 

I have recently started using the testthat package to test my package. I especially like the integration with the c++ Catch library and the possibility to run all tests using a single testthat entrypoint. Nice!

My package is passing the CRAN checks for most flavours. On os X (specifically x86_64-apple-darwin17.7.0 (64-bit)) however, the package is failing with a segmentation fault:

> * using R Under development (unstable) (2019-03-21 r76259)
>* using platform: x86_64-apple-darwin17.7.0 (64-bit)
> ...
> * checking tests ...
>   Running ‘testthat.R’/Users/ripley/R/R-devel/bin/BATCH: line 60: 86988 Illegal instruction: 4  ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1
> 
>  ERROR
> Running the tests in ‘tests/testthat.R’ failed.
> Complete output:
>   > library(testthat)
>   > library(ANN2)
>   > 
>   > test_check("ANN2")
>   
>    *** caught illegal operation ***
>   address 0x112906a2e, cause 'illegal opcode'
>   
>   Traceback:
>    1: withVisible(code)
>    2: force(code)
>    3: withr::with_output_sink(temp, withVisible(code))
>    4: eval_with_output(code, print = print, width = width)
>    5: capture_output_lines(tests_passed <- .Call(run_testthat_tests))
>    6: doTryCatch(return(expr), name, parentenv, handler)
>    7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
>    8: tryCatchList(expr, classes, parentenv, handlers)
>    9: tryCatch(output <- capture_output_lines(tests_passed <- .Call(run_testthat_tests)),     error = function(e) {        warning(sprintf("failed to call test entrypoint '%s'",             run_testthat_tests))    })
>   10: expect_cpp_tests_pass("ANN2")
>   11: ...

Any idea where this error is coming from? I am pretty new to the testthat package, so I might be doing something wrong! Unfortunately, I have not been able to replicate the error myself. I am quite in the dark on why this error is occurring.

**Comment by bflammers** [comment]
The complete log:

[ANN2.txt](https://github.com/r-lib/testthat/files/3002986/ANN2.txt)

**Comment by hadley** [comment]
You'll need to run to run the code in an interactive environment with a debugger: https://r-pkgs.org/src.html#src-debugging

Unfortunately this sort of problem tends to be very painful to track down.
