### ISSUE TITLE
Avoid `\r` in dumb terminals without basic curses support

### ISSUE THREAD

**Issue by randy3k** [r-lib/testthat#857]
A dumb terminal may not support some escape sequences that ProgressReporter requires. For those devices, SummaryReporter should be used instead.

related: #746 and https://github.com/r-lib/rcmdcheck/issues/94

**Comment by gaborcsardi** [comment]
To clarify, `\r` is not an escape sequence, it is just a carriage return character. I am not sure if there is any terminal that does not support it. 

However, if the output is redirected to a non-terminal fd, then it makes sense to get rid of it.

**Comment by randy3k** [comment]
Thanks for the clarification.

**Comment by hadley** [comment]
I don't think this is a widespread problem, and it's hard to tell if the output stream supports `\r` or not, so I think you're better off just manually selecting the reporter that you want.
