### ISSUE TITLE
compare dies comparing tbls with list columns

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/testthat#859]
In testthat-2.0.1, compare throws an error when given tbl's with columns of type "list".

> z <- group_data( group_by( tibble(x=c(101L,102L,101L)), x) )
> compare(z, z)
Error: Can't join on '.rows' x '.rows' because of incompatible types (list / list)
> dput(z)
structure(list(x = 101:102, .rows = list(c(1L, 3L), 2L)), row.names = c(NA,
-2L), class = c("tbl_df", "tbl", "data.frame"), .drop = TRUE)
> packageVersion("testthat")
[1] ‘2.0.1’

**Comment by hadley** [comment]
The root cause of this is dplyr, and this should naturally resolve itself once we switch to using vctrs internally, or through #447 since we'd presumably use vctrs directly.
