### ISSUE TITLE
More informative message for expected error class

### ISSUE THREAD

**Issue by lionel-** [r-lib/testthat#861]
```
test-assert.R:164: failure: assertion is not applied on proxy
`vec_assert(x, list())` threw an error with unexpected class.
Expected class: vctrs_error_assert_ptype
Actual class:   simpleError/error/condition
```

Perhaps add a `Message: ` line to provide context about the failure?

**Comment by wlandau** [comment]
Would you also consider amending the message for `simpleError`s as well? Maybe something like `"Please declare any custom conditions with the `class` argument of `expect_error()`"? I have spoken with users who find the [existing message](https://github.com/r-lib/testthat/blob/feb5c939829fb392727ec1511d9d686fef72efe4/R/expect-output.R#L138) confusing.

**Comment by hadley** [comment]
@wlandau please file a new issue — comments on closed issues are easily lost.
