### ISSUE TITLE
Update documentation: expect_s3_class returns false for base types (list, matrix, etc)

### ISSUE THREAD

**Issue by gabrielodom** [r-lib/testthat#865]
Related to Issue #521.

Lists and matrices are S3 objects, thus I expect `expect_s3_class(myList, "list")` to pass. In fact, `class(myList)` returns `"list"`. Instead, this function returns "Error: `myList` is not an S3 object". I understand now that I should be using `expect_type(myList, "list")` instead, but this is not made clear from the help file for `inheritance-expectations`.  I understand that this gets at the minutiae of the differences between "types" and "classes" in R, but this is nonetheless confusing.

Please update the help file and examples to mention that `expect_s3_class()` is not appropriate for checking base R types, especially because the example in this help file uses the older `expect_is(a, "matrix")` syntax to test if an object is a matrix, instead of `expect_type(a, "matrix)` per the recommendation in Details.

**Comment by hadley** [comment]
I'd recommend reading https://adv-r.hadley.nz/base-types.html and https://adv-r.hadley.nz/s3.html, and I'll clarify the docs, since I'm sure they were written before I understood the difference.

**Comment by gabrielodom** [comment]
I'll read them, and I'll have my students read them. Thank you!
