### ISSUE TITLE
tweak default messages for skip_if, skip_if_not

### ISSUE THREAD

**Issue by kevinushey** [r-lib/testthat#868]
E.g.

```
> skip_if_not(FALSE)
Error: FALSE
```

It'd be nice if this showed something more like `Error: FALSE is not TRUE` or something with slightly more text.

As an example, the reported skip condition in `devtools::test()` is something like:

```
test-file.R:33: skip: we can do the thing
check_thing()
```

It would be a little more descriptive to instead write something like:

```
test-file.R:33: skip: we can do the thing
check_thing() is not TRUE
```

**Comment by hadley** [comment]
Yeah, agreed. Want to do a PR?

**Comment by hadley** [comment]
```
test-unnest.R:93: skip: unnesting zero row column preserves names
empty
```

Should be:

```
test-unnest.R:93: skipped: unnesting zero row column preserves names
Reason: empty
```
