### ISSUE TITLE
as.data.frame.testthat_results creating data.frame with columns of type list

### ISSUE THREAD

**Issue by mwmclean** [r-lib/testthat#872]
My travis builds ([e.g. here](https://travis-ci.com/Displayr/flipMultivariates/builds/109229358)) have started to fail after the latest update because I have code along the lines of `write.csv(as.data.frame(devtools::test()), file = "foo.csv")`, which is failing with the error `"Error in write.csv... unimplemented type 'list' in 'EncodeElement'"`. `vapply(as.data.frame(devtools::test()), typeof, "")` returns `"list"` for each element. I haven't been able to reproduce outside of travis.

**Comment by hadley** [comment]
Likely due to the list columns introduced in #675. You could just remove the new `results` column prior to saving.
