### ISSUE TITLE
Save the results to disk

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#875]
Probably only for some reporters, e.g. the check reporter. This would be useful to programmatically inspect the results post mortem, e.g. to implement a test result summary in rcmdcheck: https://github.com/r-lib/rcmdcheck/issues/106

printing (part of) the results to the screen, and then parsing them back is a suboptimal solution.

I can send a PR, if you think this is a good idea.

**Comment by gaborcsardi** [comment]
> test_check() already returns the results (invisibly), so can't you write this now by adding additional code to the package's testthat.R without any changes to testthat?

Yes, I can, but then we'll need to update all packages to get https://github.com/r-lib/rcmdcheck/issues/106
Well, the ones where we want to have this.

**Comment by jimhester** [comment]
Yeah true, I guess there is pretty limited downside to writing tsv or similar with the full results

**Comment by gaborcsardi** [comment]
I would just write an RDS with the returned option.

We can make it optional for now, though, e.g. triggered by an env var, and then rcmdcheck can set it.

**Comment by jimhester** [comment]
Yeah that sounds good to me, though we might want to make sure it uses the pre-3.6 RDS format

**Comment by gaborcsardi** [comment]
Right. I'll submit a PR. 

So we'd want this only for the check reporter, right?

**Comment by gaborcsardi** [comment]
And the file name can be `testthat.rds` or `testthat-results.rds`?

**Comment by gaborcsardi** [comment]
It could be actually useful for other reporters as well....

**Comment by hadley** [comment]
Couldn't this be its own reporter that just saves the results to disk at the end?

**Comment by gaborcsardi** [comment]
Yeah, I guess it could. I'll give it a go.

**Comment by hadley** [comment]
I think this file needs to be human and machine readable (i.e. we might want to expose from CI), so I'd suggest we use yaml.

**Comment by gaborcsardi** [comment]
IDK if a non-trivial YAML file with a data frame in it will be human readable, though. OTOH I am fairly sure that the R -> YAML -> R conversion is lossy. It seems to me that an RDS file is better. 

In addition to the RDS, on a CI we could also print way more output, in a nice human readable form.

Re reporters, I am not sure any more if this should be a new reporter. Maybe the  existing default reporter (check?) could just be more verbose and save the output if `CI` is set. 

I wonder how we could save a file on CRAN without a check error.

**Comment by jimhester** [comment]
I am definitely on team anything-but-yaml in general, and for this particular situation as well.

**Comment by hadley** [comment]
In that case, we should have a pair of files, an RDS + a nicely formatted text file. Then it's just a matter of figuring out how to save in a way that doesn't offend R CMD check. Assuming we figure that out, I think we could make `test_check()` always produce the files.

**Comment by gaborcsardi** [comment]
If the reporter produces nice human readable output in the `.Rout` file, can that be that text file?

**Comment by hadley** [comment]
Yeah, that would be fine, I think.

**Comment by hadley** [comment]
Moved into #1073
