### ISSUE TITLE
message never goes to 'success' after updating to 2.1.1

### ISSUE THREAD

**Issue by theclue** [r-lib/testthat#877]
I use the list results to get the test messages to a data.frame which in turns I drop into a PDF report

After updating from 2.0.1 to 2.1.1 the 'message' field is never set to 'success', unregarding the test results. This brings my report to all KOs

This is the MinimalSummary log showing that some tests eventually succeeded:

```
> funreq01 <- test_file("tests/testthat/test_FUNREQ01.R", reporter = MinimalReporter)
....F.....F.....F.....F...FF...FF...FF...FF...FF...FFS..FF.....F...FF...FF...FF...FF...FF...FFF..FFF..FF......F.....F...FF...FF...FF...FF......F.....FF..FF.....F...FF.....F...FF.........F....F..........F..................................................................................................................................................................................................................F.........................................F...............F............F.....................................
```

Inspecting the results from 2.1.1...

![2.1.1.](https://user-images.githubusercontent.com/1724406/57385934-a605e680-71b3-11e9-8d16-62a3f77d0617.png)

...and from 2.0.1

![2.0.1](https://user-images.githubusercontent.com/1724406/57385988-be760100-71b3-11e9-88b1-c0ee92ae48ec.png)

**Comment by hadley** [comment]
This is by design - see #836.
