### ISSUE TITLE
How to flush output from `helper*.R` or `setup*.R` before starting test reporting

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#878]
Sometimes I print something, from a helper or setup file, before starting tests. It's possible that I'm doing this in a suboptimal way, in which case this is a documentation issue.

But here's an example `message()`, emanating from `tests/testthat/setup-testing.R` that often gets interleaved with the test reporting. It doesn't always happen, it doesn't always land in the same place, etc. How can I prevent this?

<img width="407" alt="Screen Shot 2019-05-07 at 6 00 39 PM" src="https://user-images.githubusercontent.com/599454/57388546-471d7e80-716d-11e9-9c8e-7193a92c8a46.png">

**Comment by jimhester** [comment]
Try `flush(stderr())` to flush the stderr connection.

**Comment by jennybc** [comment]
I put `flush(stderr())` right after my `message()` call and it did not change the result.

**Comment by hadley** [comment]
Try `flush.console()`? 

Are you sure it only occurs with `message()`?

**Comment by hadley** [comment]
Would you mind making a small package reprex for this?

**Comment by hadley** [comment]
Ok - I see this occasionally with a `message()` in a setup file (but not a helper)

**Comment by hadley** [comment]
I only see this in the RStudio build pane

**Comment by hadley** [comment]
I'm going to close this since it seems like it's actually a bug with the RStudio build pane

**Comment by hadley** [comment]
Issue at https://github.com/rstudio/rstudio/issues/5126
