### ISSUE TITLE
`expect()` evaluates `failure_message` even when a test has passed

### ISSUE THREAD

**Issue by cosi1** [r-lib/testthat#880]
This issue appeared in version 2.1.1, breaking one of the tests in my project -- error message was meant to be a valid expression when the test failed, but would throw an error for a successful test (invalid input for `paste0()` used for the formatting).

*Steps to reproduce:*
```
errors <- list("error")
testthat::expect(length(errors) == 0, failure_message = paste(mapply(paste0, errors, "."), collapse = "\n")) # testthat throws an error, as expected

errors <- list()
testthat::expect(length(errors) == 0, failure_message = paste(mapply(paste0, errors, "."), collapse = "\n")) # Error in mapply(...)
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by cosi1** [comment]
Sure:

``` r
errors <- list("error")
testthat::expect(length(errors) == 0, failure_message = paste(mapply(paste0, errors, "."), collapse = "\n")) # testthat throws an error, as expected
#> Error: error.

errors <- list()
testthat::expect(length(errors) == 0, failure_message = paste(mapply(paste0, errors, "."), collapse = "\n")) # Error in mapply(...)
#> Error in mapply(paste0, errors, "."): zero-length inputs cannot be mixed with those of non-zero length
```

<sup>Created on 2019-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
The failure message is now evaluated, and I don't want to touch this code any more, so you should just do something like:

```R
errors <- list("error")
if (length(errors) == 0) {
  succeed()
} else {
  fail(paste(mapply(paste0, errors, "."), collapse = "\n"))
}
```

(And in this case you don't need to use `mapply()` at all, so you could simply your expression to something that works regardless of the length of `errors`)
