### ISSUE TITLE
MultiReporter to allow Junit (file) and List (console)?

### ISSUE THREAD

**Issue by Nachtfeuer** [r-lib/testthat#882]
Hi,

for a CI build it is sufficient to have a tests.xml for the JUnit results and this works fine. But how do I configure the tests that I can see a list of currently executed tests **and** the Junit results in file finally?

If I do someting like following ... (as an example) ... I get complete output by testthat inside the XML and the console does show nothing. I tried to pass the name of the file to the Junit ONLY but no difference ...

Any help is appreciated :)
(Used: R 3.5.2 and testhat 2.1.1)

```
library(testthat)

options(testthat.use_colours = TRUE)
options(testthat.output_file = "tests.xml")

reporter <- MultiReporter$new(reporters = list(
	StopReporter$new(),
	JunitReporter$new()
))

test_dir("src/test/r", reporter=reporter)
```

**Comment by hadley** [comment]
Just specify the file for one reporter:

```R
library(testthat)

reporter <- MultiReporter$new(list(
  StopReporter$new(),
  JunitReporter$new(file = "tests.xml")
))

test_dir("src/test/r", reporter = reporter)
```
