### ISSUE TITLE
Is it intentional that expect_xxx functions use tidyeval semantics?

### ISSUE THREAD

**Issue by jcheng5** [r-lib/testthat#884]
In particular, I found it surprising that `!!` (and in `rlang` version 0.3.99.9003, `{{...}}`) are evaluated at the `expect_xxx` level.

```r
> identical(rlang::expr(!!quote(!!foo)), quote(!!foo))
[1] TRUE
> expect_identical(rlang::expr(!!quote(!!foo)), quote(!!foo))
Error in enexpr(expr) : object 'foo' not found
```

This is relevant for the shinymeta project; in that context, it's easy to break the results by evaluating `!!` at the wrong moment.

**Comment by hadley** [comment]
Yes, because we unquoting to generate better failure messages when you're reducing duplication in tests with a for loop or function.

**Comment by hadley** [comment]
Closing for now, but happy to discuss if you think it's really problematic.
