### ISSUE TITLE
expect_s3_class for class hierarchies

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#885]
What's a good way to test that an object inherits from multiple classes? `expect_s3_class()` uses `inherits()` which tests if the object inherits from *one* of the classes passed.

Can we add a new `expect_s3_classes()` ?

``` r
# This is expected
testthat::expect_s3_classes(tibble::tibble(), c("tbl_df", "data.frame"))
# This should be a failure?
testthat::expect_s3_classes(tibble::tibble(), c("tbl_df", "data.table"))
```

<sup>Created on 2019-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
You can use `inherits(which = TRUE)` to test all classes, it returns the indexes of the matches, or 0 if there are no matches.

``` r
all(inherits(tibble::tibble(), c("tbl_df", "data.frame"), which = TRUE) > 0)
#> [1] TRUE
all(inherits(tibble::tibble(), c("tbl_df", "data.table"), which = TRUE) > 0)
#> [1] FALSE
```

<sup>Created on 2019-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Is it worthwhile to turn this pattern into a first-class expectation?

**Comment by jimhester** [comment]
It might be worth seeing how many packages break if we just make this behavior the default for `expect_s3_class()`, it seems to me like testing for _all_ the classes is a more useful default than testing for _any_ of them, like it is currently.

**Comment by lionel-** [comment]
You can also use `rlang::inherits_all()` and `rlang::inherits_only()` in combination with `expect_true()`.

**Comment by Eluvias** [comment]
Similar to  #667

**Comment by hadley** [comment]
Maybe we could add an `exact = TRUE` argument?

**Comment by ha0ye** [comment]
Adding a +1 that I think `exact = TRUE` should be a default, as I otherwise missed a typo in checking against a vector of classes.
