### ISSUE TITLE
environment trouble

### ISSUE THREAD

**Issue by jpritikin** [r-lib/testthat#886]
With respect to the `master` branch of [OpenMx](https://github.com/OpenMx/OpenMx)

When run a test independently, it passes,
````
R --no-save -f tests/testthat/test-AlgebraComputePassing.R
````
However, when I run the same test with `devtools::test()` (in RStudio) then I get,

```
test-AlgebraComputePassing.R:317: error: (unknown)
Unknown reference 'zeta' detected in the entity 'test30p' in model 'model'
1: mxRun(model) at /home/joshua/OpenMx/tests/testthat/test-AlgebraComputePassing.R:317
```

I suspect the issue is that OpenMx does unusual things with environments,

```
zeta <- 'z'   # line 50
model <- mxModel(model, mxAlgebra(A[,zeta], name = 'test30p'))  # line 136
# then
modelOut <- mxRun(model)  # line 317
```

Within line 317, `mxRun` tries to locate `zeta` in the environment and can't. Any idea what is going on? Is there a workaround? Suggestions?

**Comment by jpritikin** [comment]
Ugh, looks like OpenMx code tries to use `globalenv()`. This is a bug, isn't it?

**Comment by jpritikin** [comment]
Is the correct fix to use `parent.frame(n)` with `n` determined empirically to reference to correct parent frame? (No recursion used here.)

**Comment by hadley** [comment]
Yes, generally. (To do it 100% correctly you need something like quosures, but you can often get a 99% correct solution with `parent.frame()` with an empirically verified `n`)
