### ISSUE TITLE
invalid multibyte character for UTF-8 strings

### ISSUE THREAD

**Issue by shrektan** [r-lib/testthat#889]
Let's say you have a test file named `test-utf8.R` (modified based on "utf8.R" in testthat), with the content below. You are using on Windows, with whatever locale (mine is CP936).

```r
test_that("sourced with correct encoding", {
  expect_equal("ä", "\u00e4")
  expect_equal('债券基', '\u503a\u5238\u57fa')
})
```

Running `devtools::test(filter = 'utf8')`, always resulting in the below error message.

```
Error in parse(con, n = -1, srcfile = srcfile, encoding = "UTF-8") : 
  invalid multibyte character in parser at line xxx
```

The related source code is (I've tried to fix but failed. It seems like it's impossible to parse correctly if the file contains characters that can't be converted to the native encoding - the case here is "ä" can't be presented corrected in CP936 while '债券基' can - although UTF-8 is specified in everywhere)

https://github.com/r-lib/testthat/blob/4a546faf6b41feff2ab74e02a55e0f9e443b677c/R/source.R#L29-L31

<details>
<summary> The session info  </summary> 

- Session info ---------------------------------------------------------------------------------------
 setting  value                                              
 version  R version 3.4.4 (2018-03-15)                       
 os       Windows 7 x64 SP 1                                 
 system   x86_64, mingw32                                    
 ui       RStudio                                            
 language (EN)                                               
 collate  Chinese (Simplified)_People's Republic of China.936
 ctype    Chinese (Simplified)_People's Republic of China.936
 tz       Asia/Taipei                                        
 date     2019-06-22                                         

- Packages -------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.4.4)
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.4.4)
 callr         3.2.0   2019-03-15 [1] CRAN (R 3.4.4)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.4.4)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.4.4)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.4.4)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.4.4)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.4.4)
 fs            1.2.7   2019-03-19 [1] CRAN (R 3.4.4)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.4.4)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.4.4)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.4.4)
 pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.4.4)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.4.4)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.4.1)
 processx      3.3.0   2019-03-10 [1] CRAN (R 3.4.4)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.4.4)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.4.4)
 Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.4.4)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.4.4)
 rlang         0.3.3   2019-03-29 [1] CRAN (R 3.4.4)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.4.3)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.4.4)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.4.4)
 testthat    * 2.1.1   2019-04-23 [1] CRAN (R 3.4.4)
 usethis     * 1.4.0   2018-08-14 [1] CRAN (R 3.4.4)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.4.4)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.4.4)

[1] D:/app/R_lib/3.1
[2] D:/app/R/library
</details>

**Comment by kevinushey** [comment]
Things seem to work fine if I force a C locale before the parse. Perhaps that could be used as a workaround to avoid having R try to convert things to the native encoding?

**Comment by hadley** [comment]
I don't think there's anything testthat can do about this 😞
