### ISSUE TITLE
Proposal) Clarify the testthat summary report

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#891]
@topepo and I have both had (minor) annoyances where we glance at the testthat summary and immediately read:

`OK: 878 SKIPPED: 5 FAILED: 2`

as `878 SKIPPED`

We would like to propose the alternative, as I think the lack of divider between the number of OK tests and the word `SKIPPED` is throwing us off:

`OK 878 / SKIPPED 5 / FAILED 2`

Happy to do a PR if you approve, relevant location is here:
https://github.com/r-lib/testthat/blob/d11d8546e4930b98e25aa4890a66d224a94463b1/R/reporter-check.R#L52

**Comment by kevinushey** [comment]
How about:

```
[ OK: 878 | SKIPPED: 5 | FAILED: 2 ]
```

I think keeping the `:` improves readability as well. (Definitely agree a separator helps)

**Comment by hadley** [comment]
PR would be great!
