### ISSUE TITLE
strange behavior for auto_test_package on testthat itself

### ISSUE THREAD

**Issue by CorradoLanera** [r-lib/testthat#893]
RStudio button "test" and `auto_test_that_package` return different results (and don't skip some test it should) when testing the package testthat itself.

Moreover in this situation, `auto_test_package` provide a messy report (it seems that it remembers the first value for each case (success, error, skip) and continue to report it. Names of tests are not reported). 

It is difficult to describe; you can find a screenshot [here](https://1drv.ms/u/s!AtlSkmthbrG4lIxMLjrwGoev8L9Gkg)

Win 10 pro/Ubuntu 18.04 + RStudio 1.2.1522 + R3.6.0 + testthat 2.1.1.9000

**Comment by hadley** [comment]
`auto_test_package()` is mostly retired; it's just too hard to get it to work correctly.
