### ISSUE TITLE
Feature Request: Add if_on_cran() and Related Functions

### ISSUE THREAD

**Issue by billdenney** [r-lib/testthat#898]
In some cases, I want to have a test with a slightly different method on CRAN.  In one recent instance, I have a test that when run locally, I want it to have a tolerance of completing within 0.01 second, but on CRAN, I'd like that tolerance to increase to something like 10 seconds.

For that, it would help if there were a function like:  `if_on_cran()`

If that were of interest, I think that having the full family of functions, `skip_if_on_*()`, replicated with `if_on_*()` methods.

If of interest, I'm happy to make a PR.

**Comment by hadley** [comment]
I think this pattern is needed so rarely that you're best off just writing your own function.
