### ISSUE TITLE
Mock objects within a package

### ISSUE THREAD

**Issue by aneudecker** [r-lib/testthat#901]
Right now it is not possible to mock an object within an R package as the `extract_mocks` function checks if the mocked object is a function:

https://github.com/r-lib/testthat/blob/c5ae6a87a51dbe7d3696de17578dcaca373a3c92/R/mock.R#L128

Is this something possible to add within R or would it be necessary to change the underlying C code? I would be happy to file a PR if this is something not too complicated.

**Comment by gaborcsardi** [comment]
This is a compromise with CRAN, I think. They don't want people to "replace" functions in other packages. Maybe the mockery package can help you, it uses a different mocking implementation.

**Comment by aneudecker** [comment]
@gaborcsardi mockery seems like the way to go here. I will give it a go. Thanks!
