### ISSUE TITLE
Mechanism for skipping entire test file on conditions

### ISSUE THREAD

**Issue by KrishanBhasin** [r-lib/testthat#902]
Using `testthat` across an R package, there are some tests that I cannot run in my CI environment (e.g. the actual database connections for a package that provides helper functionality for pulling data).

If I mark all the tests in a file to `skip_on_CI()` while keeping the database connection setup/teardown in the `setup()`/`teardown()` method, my CI build fails.

How hard would it be to add `skip_on_CI()` style functionality for entire files? I would be happy to have a go at creating a PR if someone could help me find where to start.

**Comment by gaborcsardi** [comment]
I think you can just put this in your test file:

```
if (my-condition) return()
```

You might need to add a dummy `test_that()` block before the return.

**Comment by hadley** [comment]
Or you can do `skip_if(my_condition)` at the top of your test file.
