### ISSUE TITLE
What license does this library have?

### ISSUE THREAD

**Issue by nalzok** [r-lib/testthat#904]
The current LICENSE file isn't clear, and it's outdated. 

https://github.com/r-lib/testthat/blob/de6a87033021326a521c8db0483d0654e33e5eed/LICENSE#L1-L2

I notice some GPL-licensed files in this repository, and since the GPL is infectious, I suppose this library is licensed under a GPL too?

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/testthat/blob/de6a87033021326a521c8db0483d0654e33e5eed/DESCRIPTION#L13

**Comment by nalzok** [comment]
Cool, thanks for the reply!

**Comment by oxr463** [comment]
@nalzok, other than [`R/stack.R`](https://github.com/r-lib/testthat/commit/53b5b635f298de1b52e12fe24265b07c0f689466#diff-a3dd38952aa234e2fb229f7484ebf704), what files are licensed under the GPL?

**Comment by hadley** [comment]
@oxr463 the original is GPL-3 licensed, but it's relicensed as MIT with permission of the original authors.
