### ISSUE TITLE
'expect_output' failure in AppVeyor and C locale for certain Unicode characters

### ISSUE THREAD

**Issue by trevorld** [r-lib/testthat#907]
``expect_output`` gives me a failure on AppVeyor and locally if I set a C locale.  Possibly related to #672.  Here is a minimal example that works on Linux.

```
> Sys.setlocale("LC_ALL", "C")
> string <- "\u2600"
> expect_output(cat(string), string)
Error: `cat\(string\)` does not match "<U+2600>".
Actual value: "<U\+2600>"
```

It looks like the "actual" string has extra ``\`` characters that the "comparison" string does not.

**Comment by hadley** [comment]
Is `cat()` a key part of your real code, or just used for illustration?

**Comment by trevorld** [comment]
> Is ``cat()`` a key part of your real code, or just used for illustration?

For now my function is directly using ``cat`` to output Unicode text diagrams to my terminal.  I'm actually testing output like the following with ``expect_output`` (this is working fine locally and on Linux/OSX on Travis-CI since those are Unicode locales so for now I've added a ``skip_on_appveyor()``):

```
> cat_piece(df_fide_chess())
 ┌─┰─┬─┰─┬─┰─┬─┰─┐
 │↋⃞┃ɐ⃝│☀⃟┃ᔭ⃝│ↅ̲⃝┃☽⃟│ɐ⃝┃↋⃞│
 ┝━╋━┿━╋━┿━╋━┿━╋━┥
 │☀⃝┃☽⃝│☀⃝┃☽⃝│☀⃝┃☽⃝│☀⃝┃☽⃝│
 ├─╂─┼─╂─┼─╂─┼─╂─┤
 │ ┃ │ ┃ │ ┃ │ ┃ │
 ┝━╋━┿━╋━┿━╋━┿━╋━┥
 │ ┃ │ ┃ │ ┃ │ ┃ │
 ├─╂─┼─╂─┼─╂─┼─╂─┤
 │ ┃ │ ┃ │ ┃ │ ┃ │
 ┝━╋━┿━╋━┿━╋━┿━╋━┥
 │ ┃ │ ┃ │ ┃ │ ┃ │
 ├─╂─┼─╂─┼─╂─┼─╂─┤
 │⸸⃝┃♛⃝│⸸⃝┃♛⃝│⸸⃝┃♛⃝│⸸⃝┃♛⃝│
 ┝━╋━┿━╋━┿━╋━┿━╋━┥
 │3⃞┃a⃝│⸸⃟┃4⃝│5⃝┃♛⃟│a⃝┃3⃞│
 └─┸─┴─┸─┴─┸─┴─┸─┘
```

[Link to what it looks like in my terminal with the right fonts installed and selected](https://boardgamegeek.com/image/4848471/piecepack).

**Comment by hadley** [comment]
I think you'll need an alternative way to test this code, as discussed in the linked issue, `sink()` (used by `expect_output()`) always round trips through the native encoding. It's possible `verify_output()` would do better because it doesn't use `sink()`.
