### ISSUE TITLE
question on stop_on_failure default

### ISSUE THREAD

**Issue by jameslamb** [r-lib/testthat#912]
I see the following in `?testthat::test_dir`

![image](https://user-images.githubusercontent.com/7608904/62001805-19860880-b0be-11e9-8312-3eebdf337a72.png)

Why is the default for `stop_on_failure` in `test_dir()` `FALSE` when it is `TRUE` for `test_package()` and `test_check()`? Is that intentional or an oversight?

In my opinion, the default behavior of a testing framework should be to fail (cause a non-zero exit code) if any tests fail. If you agree with me and this is an oversight, please let me know and I'd be happy to make a PR to change it.

Thanks!

**Comment by hadley** [comment]
It’s probably used elsewhere. Could you do a little git history exploration to check?

**Comment by jameslamb** [comment]
Looking through the blame, I got back to [this commit](https://github.com/r-lib/testthat/commit/767f1dc314464b1676928d025fd811c80ed3c763). I don't see anything in there that explains why `test_dir()` would have a different default (that and the linked issue look like they're just related to documentation).

If you can't recall a reason for them having different defaults, I recommend we change the default to `TRUE`.

**Comment by jimhester** [comment]
devtools calls `test_dir()` with the default arguments, so this is likely why `stop_on_failure = FALSE`.

**Comment by jameslamb** [comment]
Thanks Jim! Would you be open to `devtools` being changed to *explicitly use stop_on_failure = FALSE* (if that's the desired behavior) so the default in this library could be changed?

I feel strongly that having a testing library NOT return a non-zero exit code when one or more tests fail violates the principle of least surprise.

Also, regardless of what changes here in `testthat` I think would be preferable for `devtools::test()` to explicitly set arguments to `testthat` stuff wherever it has an opinion, instead of relying on this default.

**Comment by hadley** [comment]
I think it would make more sense if the default has `stop_on_failure = TRUE`, but since devtools depends on testthat (and not the other way around), it's going to be very difficult to synchronise the versions of devtools and testthat. I think the best we could do would be to add an explicit argument to devtools, and then in a year (say) update testthat. But that feels like a lot of work for a function that is used very rarely, so I think the most appropriate action would be to just highlight the different in the documentation.

**Comment by jameslamb** [comment]
Thank you, that totally makes sense. I agree it would be tough to deal with people having mismatched versions of `devtools` and `testthat` and that it would be too much to go through that  effort to address this inconsistency.

I would be willing to make a PR to update the relevant information in the `testthat` docs!

I also will make one to `devtools` to add the explicit argument. I understand that the default behavior in `testthat` won't be changing, but I still think it would be better for the behavior of `devtools::test()` to be "do not stop on failure"  instead of "do whatever the default behavior of `testthat::test_dir()` is", if for no other reason than that it will make the source code of `devtools` a bit more obvious.

**Comment by jameslamb** [comment]
Thanks for hearing me out on this. I've proposed #932 and r-lib/devtools#2099 . I think #932 is sufficient to close this issue.
