### ISSUE TITLE
testthat should have an option not to update packages

### ISSUE THREAD

**Issue by sebastiangonsal** [r-lib/testthat#914]
Is there a way to ask `testthat` not to prompt for updating packages? 

When i run `test_dir` and it prompts to update packages. I am running this as part of a script and it is becoming a problem to automate. (I am relying on `test_dir` due to its verbose output instead of `R CMD check`

**Comment by hadley** [comment]
testthat does not update packages.

**Comment by sebastiangonsal** [comment]
That's not true. If you are running `test_dir` on a directory and one of the dependency is an old one, you get a prompt like the following:
`Installing 2 packages: `

**Comment by gaborcsardi** [comment]
`test_dir()` runs the code in all the `^test.*` R files in that directory, so you probably have some code in there that updates packages.

**Comment by sebastiangonsal** [comment]
*facepalm* you are right. I was doing a `devtools::install_github`
