### ISSUE TITLE
Remind users about `expect_error()` for custom conditions if `class` is NULL

### ISSUE THREAD

**Issue by wlandau** [r-lib/testthat#918]
Folks are still adjusting to [this warning](https://github.com/r-lib/testthat/blob/feb5c939829fb392727ec1511d9d686fef72efe4/R/expect-output.R#L136-L139):

``` r
library(testthat)
custom_condition <- function(message) {
  structure(
    list(message = message),
    class = c("custom", "error", "condition")
  )
}
expect_error(stop(custom_condition("my message")), regexp = "my message")
#> Warning: `stop(custom_condition("my message"))` generated a condition with class custom/error/condition.
#> It is less fragile to test custom conditions with `class`
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

When I first saw it, I did not know it was talking about the `class` argument of `expect_error()`. Just today, I saw similar confusion in the R/stats chatter.

Related: #861 

By the way, thank you for creating and maintaining `testthat`. When I learned about `testthat` 3 years ago, it was my first exposure to unit testing and test-driven development, concepts I still find liberating and foundational.

**Comment by chasemc** [comment]
I just ran into this and have to admit I'm terribly confused:

Using @wlandau 's example:
``` r
library(testthat)
custom_condition <- function(message) {
  structure(
    list(message = message),
    class = c("custom", "error", "condition")
  )
}
expect_error(stop(custom_condition("my message")), class="custom/error/condition")
#> Error: `stop(custom_condition("my message"))` threw an error with unexpected class.
#> Expected class: custom/error/condition
#> Actual class:   custom/error/condition
#> Message:        my message
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


``` r
testthat::expect_error(shiny::validate(shiny::need(1 == 2, "Hello")), 
    class = "shiny.silent.error/validation/error/condition")
#> Error: `shiny::validate(shiny::need(1 == 2, "Hello"))` threw an error with unexpected class.
#> Expected class: shiny.silent.error/validation/error/condition
#> Actual class:   shiny.silent.error/validation/error/condition
#> Message:        Hello
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
