### ISSUE TITLE
Offer a simple way to rerun failing tests only

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#919]
One way to do this would be to have the default reporter print a line of code that executes only the failing tests, in the form of

```r
devtools::test(filter = "^(test1|test2)$")
```

or the like. This could be copy-pasted from the test output or picked up by the IDE.

**Comment by hadley** [comment]
I'm now uncertain whether or not we'd ever implement this — we have a new convention that matches R files to test files, so we can now use `devtools::test_file()` to rapidly iterate on a small part of the tests. This proposal feels like it's going to be less useful than that — if one change breaks a bunch of tests across files, I think that implies the function you are modifying is fundamental to the package, and you're going to have to re-run all the tests again anyway. Or your tests/code is poorly organised, and you'd be best served by reorganising.

**Comment by krlmlr** [comment]
Can we please reconsider?

> if one change breaks a bunch of tests across files, ... you're going to have to re-run all the tests again anyway

Yes, I need to re-run at some point, but it's still faster to run the tests that are failing right now, and then do a last (hopefully successful) pass when all failing tests are fixed.

The ability to re-run failing tests seems fairly standard in GUIs. Maybe this can be solved with a custom reporter?
