### ISSUE TITLE
auto_test_package: propagate filter argument to test_dir()

### ISSUE THREAD

**Issue by torbjorn** [r-lib/testthat#922]
It would be nice to work with only a subset of test files with auto_test_package.

There are some test scripts that take a long time, others are fast.

If I work with a faster script, it'd be a bummer to have to wait for those longer, not so interesting at the moment, test files.

it looks like it can be solved by simply allowing auto_test_package() to have a filter=NULL argument and pass that to test_dir further down.

**Comment by hadley** [comment]
`auto_test_package()` is basically retired; we don't use it anymore and don't plan to add any more features to it.

**Comment by torbjorn** [comment]
I see. Is there any other watch-like mechanic in testthat that I should use instead or is the concept retired too?

**Comment by torbjorn** [comment]
Sorry for whipping this dead horse, but isn't anyone auto running tests as they write code like this? I find it an awesome way to develop. No need to alt-tab somewhere else to run tests, or hit key combos to run them. Just save the buffer and watch the tests run.
