### ISSUE TITLE
expect_silent doesn't handle !! well

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/testthat#934]
```
i <- 3
f <- function (x) g(x)
g <- function (x) stop("stopped")
expect_silent(f(!!i))
#> Error in g(x) : stopped
> expect_error(f(!!i), regexp = NA)
#> Error: `f(3)` threw an error.
```

If `expect_silent()` is meant to be very basic then fine, but document it.

**Comment by cderv** [comment]
FWIW I don't think error are captured by `expect_silent` 

Here, the error message when using `stop` is not one capture and post-processed using `quasi_label` but just the function `e()` throwing an error. 
``` r
library(testthat)
w <- function() warning("warning")
m <- function() message("message")
e <- function() stop("error")
expect_silent(w())
#> Error: `w()` produced warnings.
expect_silent(m())
#> Error: `m()` produced messages.
expect_silent(e())
#> Error in e(): error
```

<sup>Created on 2019-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Some other hints on this: 
* Error are not tested in [test-expect-silent.R](https://github.com/r-lib/testthat/blob/master/tests/testthat/test-expect-silent.R)
* Code don't capture error in `expect_silent`
https://github.com/r-lib/testthat/blob/213d5efbd95638d7b90f9273458c5c87930ce0f0/R/expect-output.R#L202-L217

`expect_silent` does the job indeed as an error is thrown, so the test does not pass but the error is not capture as in `expect_error` (see reprex in first post), so the error message thrown does not deal with quasi quotation as for warnings and messages.

Hopes it helps.
