### ISSUE TITLE
R numerical equals issue

### ISSUE THREAD

**Issue by keesh0** [r-lib/testthat#935]
I am using R 3.5.2 under Centos.
 
I am wondering why the following does not fail?
>library('testthat')
>expect_that( 12345.70, equals(12345.67, tolerance  = 0.01) )

Am I missing to set some R global option?
thx e.-

**Comment by jimhester** [comment]
testthat is using `all.equal()`, which exhibits the same behavior.

``` r
all.equal(12345.70, 12345.67, tolerance = .0001)
#> [1] TRUE
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you read the Details of `?all.equal` it says

> Numerical comparisons for scale = NULL (the default) are typically on relative difference scale unless the target values are close to zero: First, the mean absolute difference of the two numerical vectors is computed.  If this is smaller than tolerance or not finite, absolute differences are used, otherwise relative differences scaled by the mean absolute target value.

And also later on

> If scale is numeric (and positive), absolute comparisons are made after scaling (dividing) by scale.

To do what you would expect you can use `scale = 1` as well as `tolerance`

``` r
all.equal(12345.70, 12345.67, tolerance = .01, scale = 1)
#> [1] "Mean absolute difference: 0.03"
library(testthat)
expect_equal(12345.70, 12345.67, tolerance = .01, scale = 1)
#> Error: 12345.7 not equal to 12345.67.
#> 1/1 mismatches
#> [1] 12346 - 12346 == 0.03
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I agree the behavior of `all.equals()` is very unintuitive

**Comment by keesh0** [comment]
thx, that clarifies my confusion with when to use scale.
