### ISSUE TITLE
Failure to fail when a test fails

### ISSUE THREAD

**Issue by kenahoo** [r-lib/testthat#936]
I'm tracking down a Heisenbug where sometimes a test failure in a testthat script doesn't actually cause failure of the test suite.

Changing various random things in the tests can get it to fail properly, and most importantly, **running under `devtools::test()` makes it fail properly while running under `R CMD check` masks the failure**.  It also masks the failure when I run `tools:::.check_packages()`, the function in R that implements `R CMD check`.

Also, importantly, changing my `testthat.R` file from **`tmp <- test_check("gene", reporter="tap")`** to `tmp <- test_check("gene")` also makes it fail properly when running under `R CMD check`.  So I'm suspecting a problem in `TapReporter` somehow.

The `testthat.Rout` file does show a failure in all cases - it includes the following (I've put in `[...]` various places to elide the output):

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.7.0 (64-bit)
[...]
Loading required package: gene
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
WARN [2019-09-11 14:27:47] New power surface models need at least a timestamp argument ruc.ts, falling back to old models
1..23
# Context Testing sag and windspeed model generation
ok 1 # WARNING namespace 'wra.ops' is not available and has been replaced
by .GlobalEnv when processing object ''
ok 2 # WARNING namespace 'wra.ops' is not available and has been replaced
by .GlobalEnv when processing object ''
[...]
ok 20 # WARNING the condition has length > 1 and only the first element will be used
ok 21 # WARNING the condition has length > 1 and only the first element will be used
not ok 22 (unknown)
  object 'latitude' not found
  1: runTest(outputDirectory = "test-output", expectedFile = "expectedDailyClassification.rds") at testthat/test_daily-classification_output-files.R:68
  2: run.daily.classification(jsonInputFilePath) at testthat/test_daily-classification_output-files.R:38
[...]
  24: map(.x[sel], .f, ...)
  25: .f(.x[[i]], ...)
ok 23 multiplication works
Warning message:
replacing previous import 'dplyr::rename' by 'plyr::rename' when loading 'gene' 
> cat('Tests done', file='/tmp/testsdone')
> 
> proc.time()
   user  system elapsed 
  3.727   0.546   4.936 
```

Notice the `not ok 22` in the output.  But the `R CMD check` output contains this:

```
* checking tests ...
  Running ‘testthat.R’
 OK
```

To help me track this down - does this file get written and then *parsed* to determine whether there was a failure?  Or do the results get tracked internally and then `TapReporter` simply writes out a file, the contents of which `testthat` never does anything with?

I've been trying to isolate the problem by doing the following:

```
# Location in R version 3.6.1:
trace(tools:::.check_packages, browser, at=list(c(34, 3, 3, 4, 3, 3, 14)))
tools:::.check_packages('../gene_2.18.tar.gz')
```

But as you probably know, debugging the `R CMD blah` code is super difficult because of how it keeps calling R through the command line over & over, so I'm trying to boil this down to something inside `testthat` that will be easier to figure out.

Thanks, hope that was coherent enough! 😄

**Comment by hadley** [comment]
Do you have the dev version? It might be the same problem as #851

**Comment by kenahoo** [comment]
I don't have the dev version, but I'll give that a shot.

I don't understand #851 very well yet, but I don't **think** it's the same problem - in my case the end result is a "failure to fail" (succeeds when it shouldn't), whereas it looks like in #851 it was failing correctly but just not soon enough?

**Comment by kenahoo** [comment]
I just confirmed that I'm seeing the same problem on `testthat_2.2.1.9000.tar.gz` from GitHub:

`tools:::.check_packages('../gene_2.18.tar.gz')` completes without reporting an error, despite there being a failure in the tests.

After the run, `gene.Rcheck/tests/testthat.Rout` does show the failure. It doesn't get moved to `gene.Rcheck/tests/testthat.Rout.fail` since the failure wasn't detected.

**Comment by kenahoo** [comment]
I figured out that this actually *doesn't* depend on `R CMD check` or its in-R equivalent `tools:::.check_packages()`, it can be demonstrated only using `testthat::test_dir()` (**much** easier and faster!) or even `testthat::test_file()`:

```
> result <- testthat::test_file('tests/testthat/test_daily-classification_output-files.R')
[... bunch of output, ending with: ]
══ Results ═════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.3 s

OK:       0
Failed:   1
Warnings: 6
Skipped:  0

> result
 [1] file    context test    nb      failed  skipped error   warning user    system  real    passed 
<0 rows> (or 0-length row.names)
```

So even though it *shows* a failure in the results, there's no information about the failure in the return value, so it doesn't fail the suite overall.

**Comment by kenahoo** [comment]
Simpler demonstration:

```
> cat("stop('failing test')\n", file="/tmp/test-file.R")
> result <- testthat::test_file('/tmp/test-file.R')
✔ |  OK F W S | Context
⠋ |   0 1     | 
══ Results ═════════════════════════════════════════════════════════════════════════════════════════════
OK:       0
Failed:   1
Warnings: 0
Skipped:  0
> result
 [1] file    context test    nb      failed  skipped error   warning user    system  real    passed 
<0 rows> (or 0-length row.names)
```

**Comment by hadley** [comment]
Here the problem isn't so much a test failure as an uncaught error, but it may have same root cause as #781

**Comment by kenahoo** [comment]
I don't see the connection to #781 myself, but it could be.

I believe this bug didn't appear in previous versions of `testthat`, because an older test server we had, running an older `testthat`, didn't show this problem.  I haven't confirmed that yet, though.  Might do a `git bisect` on it.

**Comment by kenahoo** [comment]
Looks like this was introduced in 25e7d93030bc594aa92f287e10d8eb3d678e4977:

```
index 9117518..0856985 100644
--- a/R/reporter-progress.R
+++ b/R/reporter-progress.R
@@ -60,6 +60,10 @@ ProgressReporter <- R6::R6Class("ProgressReporter",
 
     start_file = function(file) {
       self$file_name <- file
+
+      # Need to set here in case file doesn't contain any tests
+      self$ctxt_issues <- Stack$new()
+      self$ctxt_start_time <- proc.time()
     },
 
     start_test = function(context, test) {
diff --git a/R/test-files.R b/R/test-files.R
index 1582b44..5ad8247 100644
--- a/R/test-files.R
+++ b/R/test-files.R
@@ -128,7 +128,7 @@ test_file <- function(path, reporter = default_reporter(), env = test_env(),
     {
       # We need to notify the lister separately from the reporter, which is why
       # we call start_file methods twice.
-      get_reporter()$start_file(basename(path))
+      reporter$start_file(basename(path))
       lister$start_file(basename(path))
 
       source_file(
@@ -136,7 +136,8 @@ test_file <- function(path, reporter = default_reporter(), env = test_env(),
         chdir = TRUE, wrap = wrap
       )
 
-      end_context()
+      reporter$end_context()
+      reporter$end_file()
     }
   )
 
```

Before that commit:

```
% Rscript -e 'devtools::load_all(); test_files("/tmp/test-file.R", stop_on_failure=TRUE)'
Loading testthat
✔ |  OK F W S | Context
Error in x[[method]](...) : attempt to apply non-function
Calls: test_files ... <Anonymous> -> o_apply -> lapply -> FUN -> <Anonymous>

══ Results ═════════════════════════════════════════════════════════════════════
OK:       0
Failed:   2
Warnings: 0
Skipped:  0
Execution halted

% echo $?
1
```

After that commit:

```
% Rscript -e 'devtools::load_all(); test_files("/tmp/test-file.R", stop_on_failure=TRUE)'
Loading testthat
✔ |  OK F W S | Context
✖ |   0 1     | 
────────────────────────────────────────────────────────────────────────────────
test-file.R:1: error: (unknown)
failing test
1: stop("failing test") at /tmp/test-file.R:1
────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════
OK:       0
Failed:   1
Warnings: 0
Skipped:  0

% echo $?
0
```

Note the difference in exit status.

**Comment by kenahoo** [comment]
For completeness (to make sure I wasn't doing something dumb), I also ran a non-failing test before & after this commit, here are the results:

```
% echo "expect_equal(2, 2)" > /tmp/test-ok.R

% co 25e7d93030bc594aa92f287e10d8eb3d678e4977^                                         
Previous HEAD position was 25e7d93 Call end_file() on reporter
HEAD is now at 5db9225 Better error messages for missing arguments

% Rscript -e 'devtools::load_all(); test_files("/tmp/test-ok.R", stop_on_failure=TRUE)'
Loading testthat
✔ |  OK F W S | Context
⠋ |   1       | 
══ Results ═════════════════════════════════════════════════════════════════════
OK:       1
Failed:   0
Warnings: 0
Skipped:  0

Nice code.

% co 25e7d93030bc594aa92f287e10d8eb3d678e4977                                          
Previous HEAD position was 5db9225 Better error messages for missing arguments
HEAD is now at 25e7d93 Call end_file() on reporter

% Rscript -e 'devtools::load_all(); test_files("/tmp/test-ok.R", stop_on_failure=TRUE)'
Loading testthat
✔ |  OK F W S | Context
✔ |   1       | 

══ Results ═════════════════════════════════════════════════════════════════════
OK:       1
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by kenahoo** [comment]
I have created a branch here that shows a failing test for this problem: https://github.com/kenahoo/test_that/tree/bug-936-failure-to-fail-when-test-fails

I also started to make a fix, I found the problem point in the code (see the 2nd commit), but I don't know how to tell the testing infrastructure that something failed.  Any help?

**Comment by kenahoo** [comment]
@hadley I'd love a pointer here in the right direction if you could, this is hitting us kind of hard lately.

**Comment by hadley** [comment]
@lionel- can you take a look please?

**Comment by kenahoo** [comment]
@hadley and @lionel- this seems like quite a major bug to be lying dormant, any updates?

**Comment by lionel-** [comment]
Will take a look today, sorry for missing this.

**Comment by lionel-** [comment]
I'm still discovering testthat internals but it looks like:

- An empty results value is to be expected if you're stopping or failing outside a testthat block. It looks unrelated to the problem at hand.

- Most reporters are not designed to throw an error if a failure occurs. Exceptions are the "check" and "fail" reporters. This is why the tap reporter doesn't stop on failure.

- The documentation of the "fail" reporter mentions it is designed to be combined with other reporters to force them to throw an error when an unexpected result occurs.

The following seems to fix the issue:

```r
reporter <- MultiReporter$new(list(
  FailReporter$new(),
  TapReporter$new()
))
test_check("mypackage", reporter = reporter)
```

Perhaps `test_check()` should always combine non-default reporters with the fail reporter. This would make it easy to use reporters within `tests/` files.

**Comment by hadley** [comment]
This doesn't sound like a major bug, in fact, it sounds like testthat is acting as designed.

**Comment by lionel-** [comment]
That's my take as well. Perhaps the design could be improved along the lines suggested above, since `test_check()` is meant for checking packages and it doesn't make much sense to not report failures to R CMD check (IIUC).

**Comment by kenahoo** [comment]
Maybe I'm misunderstanding something - it's designed to pass tests if a test completely dies?

**Comment by kenahoo** [comment]
I guess I'm not sure why/when (or even whether?) it used to work in the past.  The behavior I started seeing was that if there is a code error (like referencing an unknown variable) that triggers death when testing, it didn't make `R CMD check` fail.  This led to some of our code going to production despite it dying during unit tests, because there was no real way for us to know something went wrong.

Seemed like a pretty obvious bug somewhere in R or `devtools` or `testthat`.  Trying to track it down, maybe I've misidentified where the problem lies?

I don't think this has anything to do with the tap reporter though, as I first thought - the unit test I added in my branch to demonstrate the failure doesn't use the tap reporter.

**Comment by lionel-** [comment]
> I don't think this has anything to do with the tap reporter though, as I first thought - the unit test I added in my branch to demonstrate the failure doesn't use the tap reporter.

I think you were looking into the return value of `test_file()`. An empty results value is to be expected if you're stopping or failing outside a testthat block.

**Comment by kenahoo** [comment]
No, in fact it *doesn't* throw an exception.  Notice that `finished` ends up as `TRUE`.  That's what I'm saying, there's no indication whatsoever that a problem happened.

**Comment by lionel-** [comment]
oh yeah but you're using an empty reporter that doesn't do anything: `Reporter$new()`. You need to use a failing reporter like "check" or "fail".

**Comment by hadley** [comment]
The point of most of the reporters is to produce output, and you don't want them to fail because that would prevent other code from running (I think there may have been a previous bug where errors outside of test blocks caused reporters to fail). If you're using a reporter other than `CheckReporter` you have to figure out yourself what should happen if the tests fail.

**Comment by kenahoo** [comment]
Let me step back a bit - if I set up a dummy package with the following test structure:

```
# file tests/testthat/test-dummy.R
stop("Test died")
```

```
# file tests/testthat.R
library(testthat)
library(TestPackage)
test_check("TestPackage", reporter='tap')
```

Then this is my output from `R CMD check`:

```
...
* checking tests ...
  Running ‘testthat.R’
 OK
* DONE

Status: OK

── R CMD check results ──────────────────────────────────── TestPackage 0.9 ────
Duration: 21.4s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded
```

There's no indication anywhere that anything bad happened.  This is (a highly distilled version of) the situation that led us to deploy faulty code.

Surely that can't be as designed?

**Comment by lionel-** [comment]
Currently the design is that you need to do this:

```r
reporter <- MultiReporter$new(list(
  FailReporter$new(),
  TapReporter$new()
))
test_check("mypackage", reporter = reporter)
```

I have suggested a possible improvement above.

**Comment by lionel-** [comment]
Another possible improvement would be for `test_check()` to test the reporter on a dummy failing test and signal an informative warning when the reporter doesn't fail.

**Comment by kenahoo** [comment]
Am I correct that the `TapReporter` object is never informed that a test died?  Could that be made a common property of all reporters - to know whether the tests completed successfully without dying?  That does seem like something within its purview, inasmuch as it's something worth "producing output" about.

**Comment by lionel-** [comment]
A redesign of reporters is most likely not warranted at this point.

**Comment by hadley** [comment]
Minimal reprex for future reference:

``` r
cat("stop('failing test')\n", file="/tmp/test-file.R")
(testthat::test_file('/tmp/test-file.R', reporter = NULL))
#>  [1] file    context test    nb      failed  skipped error   warning
#>  [9] user    system  real    passed 
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@kenahoo Ok, now I get what you're saying — very shortly you'll get these results:

``` r
cat("stop('failing test')\n", file="/tmp/test-file.R")
(testthat::test_file('/tmp/test-file.R', reporter = NULL))
#>          file     context   test nb failed skipped error warning user
#> 1 test-file.R test-file.R <bare>  0      0   FALSE  TRUE       0   NA
#>   system real passed result
#> 1     NA   NA      0   NULL
(testthat:::test_files('/tmp/test-file.R', stop_on_failure = TRUE))
#> ✔ |  OK F W S | Context
#> 
⠋ |   0 1     | 
#> ══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════
#> Duration: 0.1 s
#> 
#> OK:       0
#> Failed:   1
#> Warnings: 0
#> Skipped:  0
#> Error: Test failures
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kenahoo** [comment]
Perfect, @hadley - thanks for sticking with me.  This will be a big help and let us remove a bunch of workarounds for detecting failures.
