### ISSUE TITLE
expect_error could be more user friendly for "strange" characters

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#943]
```
x80 = rawToChar(as.raw(128))
expect_error(stop('bad input: ', x80), 'bad input')
```

somewhat-unexpectedly doesn't catch the correct error:

```
Error: `stop("bad input: ", rawToChar(as.raw(128)))` threw an error with unexpected message.
Expected match: "bad input"
Actual message: "bad input: \x80"
In addition: Warning message:
In grepl(regexp, cond$message, ...) :
  input string 1 is invalid in this locale
```

The issue is that `grepl` doesn't like "weird" characters: `grepl(x80, x80)` (we need to use `useBytes`).

I can fix this in `testthat` by passing `useBytes`:

```
expect_error(stop('bad input: ', x80), 'bad input', useBytes = TRUE)
```

A test to anticipate this from `testthat` would be very helpful as I had to stare at the output for a while before figuring out what's going on/how to proceed (in fact this is the first time I've ever had to use `useBytes`!)

(for context I'm trying to write a test on a function that should fail on input outside raw range `00`-`7f` and I landed on 128 in the hopes that it'll translate easily to testing on Windows)

**Comment by hadley** [comment]
I'm not sure there's much I can do here — we're relying on `grepl()` here, so I think the only option would be to set `useBytes = TRUE` by default, but I have no sense of how that will affect existing code, so it seems risky to change the default given that it only affects a few people (i.e. just you 😉 )

**Comment by MichaelChirico** [comment]
I had in mind something like

```
tryCatch(grepl(...), warning = function(w) {
msg = w$message
if (grepl('invalid in this locale', w$message)) 
  msg = paste0(msg, '\nConsider useBytes=TRUE for this test')
warning(msg)
})
```

**Comment by hadley** [comment]
I really dislike testing condition text because of the fragility 😞

**Comment by MichaelChirico** [comment]
Makes sense! FWIW that string has never changed since its introduction 15 years ago :)

https://github.com/wch/r-source/commit/60bd66d8d0bd3532494e807b17c1c6f053cd7b68#diff-4dc8ff6af2795ca2715483089ad0c006R879

**Comment by hadley** [comment]
Yeah, but it won't work if translated — I know that probably doesn't occur that often, but it just feels too inelegant to justify the small benefit.

**Comment by MichaelChirico** [comment]
Ah, a different kind of fragility than I had in mind. Agreed

**Comment by MichaelChirico** [comment]
Got bit by this again. I still think there may be room for some improvement... here was my output from `testthat::test_dir('tests')`:

```
── 1. Failure: geohash decoder works (@test-decode.R#108)  ───────────────────────────────────────────────────────────────────────────────────────
`gh_decode(rawToChar(as.raw(128)))` threw an error with unexpected message.
Expected match: "Non-ASCII character at index 1"
Actual message: "Non-ASCII character at index 1. If this is surprising, use charToRaw('\x80') and look for values outside 00-7f"
Backtrace:
 1. testthat::expect_error(...)
 6. geohashTools::gh_decode(rawToChar(as.raw(128))) /Users/michael.chirico/github/rlang/R/eval.R:99:2
```

I stared at this for a while wondering if I had missed capitalization or if maybe it was a different hyphen?

However, when I run the `expect_error` snippet alone, the output is more helpful:

```
Error: `gh_decode(rawToChar(as.raw(128)))` threw an error with unexpected message.
Expected match: "Non-ASCII character at index 1"
Actual message: "Non-ASCII character at index 1. If this is surprising, use charToRaw('\x80') and look for values outside 00-7f"
In addition: Warning message:
In grepl(regexp, message, ...) : input string 1 is invalid in this locale
```

That bit about "input string 1 is invalid in this locale" from `grepl` is a dead giveaway about the root of the problem; I'm not sure why the unanticipated warning message is suppressed from the `test_dir` output.

**Comment by hadley** [comment]
Re-opening, so we think about it more in the future.

**Comment by hadley** [comment]
BTW if I run this now I see:

```
test-reporter-progress.R:3: warning: ok
input string 1 is invalid in this locale

test-reporter-progress.R:3: failure: ok
`stop("bad input: ", x80)` threw an error with unexpected message.
Expected match: "bad input"
Actual message: "bad input: \x80"
Backtrace:
 1. testthat::expect_error(stop("bad input: ", x80), "bad input") tests/testthat/test-reporter-progress.R:3:2
 2. testthat::quasi_capture(...) R/expect-condition.R:68:2
 5. rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo)) R/capture-condition.R:23:26
```

So the warning does get funnelled to the top-level, which I think is probably the best we can do here. 

Well, we could also provide a backtrace for the warning, which seems like a useful thing to do:

```
test-reporter-progress.R:3: warning: ok
input string 1 is invalid in this locale
Backtrace:
 1. testthat::expect_error(stop("bad input: ", x80), "bad input") tests/testthat/test-reporter-progress.R:3:2
 2. testthat::compare_condition(...) R/expect-condition.R:69:2
 3. base::grepl(regexp, message, ...) R/expect-condition.R:137:2
```

**Comment by MichaelChirico** [comment]
LGTM, thanks
