### ISSUE TITLE
Update global environement with test_check and test_file

### ISSUE THREAD

**Issue by jcubic** [r-lib/testthat#944]
I have tests where I mock shiny functions that may be imported and global, the problem was that my mock install function was not working when used inside test_file, here is code that works in test_file:
```R
#' Helper function to be used in test files that overwrite shiny functions (after test
#' you should run clearMocks since they are global and if you run shiny application
#' after test that use mocks it will break)
#'
#' @export
useMocks <- function() {
  observeEvent <- battery::observeEventMock
  assignInNamespace('observeEvent', observeEvent, 'battery')
  assignInNamespace('observeEvent', observeEvent, 'shiny')
  isolate <- battery::isolate
  assignInNamespace('isolate', isolate, 'shiny')
  makeReactiveBinding <- battery::makeReactiveBinding
  assignInNamespace('makeReactiveBinding', makeReactiveBinding, 'shiny')
  renderUI <- battery::renderUI
  assignInNamespace('renderUI', renderUI, 'shiny')
  ## we modify global environment so it update env when function is called not the package
  env <- globalenv()
  env$observeEvent <- observeEvent
  env$isolate <- isolate
  env$renderUI <- renderUI
  env$makeReactiveBinding <- makeReactiveBinding
}
```

Previous version was using `parent.env()` (that didn't work with test_file) above works in `testthat::test_file` and when using `devtools::test()` but with `devtools::check()` that call `test_check("battery")` it fails.

I use code like this because (as in comment) it was not working when testing code in the package.

**Comment by hadley** [comment]
I'd recommend using a package like [mockr](https://krlmlr.github.io/mockr/) or [mockery](https://cran.r-project.org/web/packages/mockery/index.html), since they'll use the correct environment.
