### ISSUE TITLE
Check that error outside of test causes code to terminate

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#950]
ie.

```R
test_that("", expect_true(TRUE))
stop("!")
test_that("", expect_true(TRUE))
```

should only have one passing expectation.

**Comment by kforner** [comment]
> should only have one passing expectation.

or `test_file()` should die ==> no results reported by e.g. the ListReporter ?

**Comment by hadley** [comment]
I think you're probably right but that feels like a big design change, and I think it's probably too late to make it. I'll add a note to the `test_file()` documentation that this function turns bare errors into test failures.
