### ISSUE TITLE
Document nesting expectations

### ISSUE THREAD

**Issue by aaronrudkin** [r-lib/testthat#954]
Say you have a function where you want to test both the return value and the presence of a warning:

```
test_func <- function(x) {
  if(x > 10) {
    warning("Don't supply large values")
    return(10)
  }
  return(x)
}
```

A correct way to do this in `testthat` is:

```
expect_equal(expect_warning(test_func(11)), 10)
```

However, this is not actually documented anywhere as far as I can tell. It might be useful to document this. I discovered it accidentally when trying to test the two expectation separately led to the built in devtools pretty-printer complaining about the warning in the expect_equal test and I was trying to think of a clever way to combine the warning-absorbing behaviour of the warning test.

Perhaps I have missed the documentation somewhere, but I could not find it in `testthat`'s website or the Advanced R book.

(P.S. Apologies -- I prematurely submitted this issue so the initial email may have a stub of the above reproduction code with none of the description! Oops!)

**Comment by hadley** [comment]
I'd write it as:

```R
expect_warning(out <- test_func(11))
expect_equal(out, 10)
```

then you don't need to know anything special about testthat. 

I'll add an example to `expect_warning()` and `expect_message()` to make it more clear.
