### ISSUE TITLE
Testthat reporting warnings that do not appear in code

### ISSUE THREAD

**Issue by jeroen** [r-lib/testthat#958]
## Minimal reprex 

from @gaborcsardi 

```r
test_that("x", {
  op <- options(warn = -1)  
  warning("not see this")
  options(op)
  expect_true(TRUE)
})
```

## Real world case

If you run this in R, there is no warning:

```r
out <- available.packages(repos = 'https://cloud.r-project.org', type = 'mac.binary.el-capitan')
```

However if you run this code anywhere in testthat:

<img width="747" alt="Screen Shot 2019-11-04 at 8 44 45 PM" src="https://user-images.githubusercontent.com/216319/68152452-f8964480-ff43-11e9-9f57-bd7a1a57ace8.png">

This warning should never appear because [R sets `options(warn = -1L)` internally](https://github.com/wch/r-source/blob/c85acc47b4c3857b5a72f1871053bb5c90f2d08a/src/library/utils/R/packages.R#L87-L93).

**Comment by gaborcsardi** [comment]
Even better reprex:

``` r


code <- quote(test_that("x", {
  op <- options(warn = -1)  
  warning("not see this")
  options(op)
  expect_true(TRUE)
}))


cat(deparse(code), sep = "\n", file = tmp <- tempfile())

testthat::test_file(tmp)
#> ✔ |  OK F W S | Context
#> 
⠏ |   0       | filebd63127caaed
✔ |   1   1   | filebd63127caaed
#> ───────────────────────────────────────────────────────────────────────────
#> filebd63127caaed:3: warning: x
#> not see this
#> ───────────────────────────────────────────────────────────────────────────
#> 
#> ══ Results ════════════════════════════════════════════════════════════════
#> Duration: 0.2 s
#> 
#> OK:       1
#> Failed:   0
#> Warnings: 1
#> Skipped:  0
```

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
But there is no warning coming out here:
``` r

withCallingHandlers(
  testthat::test_that("x", {
    op <- options(warn = -1)  
    warning("not see this")
    options(op)
    testthat::expect_true(TRUE)
  }),
  warning = function(w) { print(w); browser() }
)
```

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Probably needs special handling around here: https://github.com/r-lib/testthat/blob/windows-check/R/test-that.R#L120-L123

**Comment by gaborcsardi** [comment]
But how does the warning get to testthat at all. I guess I am missing the fine bits of the `options(warn = -1)` implementation...

**Comment by jeroen** [comment]
I am guessing the default R warning handler checks `options(warn)` on how to proceed, but testthat overrides this with a custom warning handler that doesn't do this?

**Comment by gaborcsardi** [comment]
How can you define a default condition handler? I am clearly missing something about the condition system. :(
