### ISSUE TITLE
Feature request: native support for parameterized unit tests

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/testthat#962]
Hi, currently I'm using the [patrick](https://github.com/google/patrick) package to run parameterized unit tests via the `with_parameters_test_that()` function. It's incredibly useful in some cases, but the package no longer seems to be actively developed. I'm of the opinion that this functionality is generally useful enough that it should be integrated directly into testthat.

It's been requested as a native feature in testthat for a while -- see related issue #563 .

Thoughts on this @michaelquinn32?

Best,
Mike

**Comment by mjsteinbaugh** [comment]
Also somewhat related to #486

**Comment by hadley** [comment]
Could you please provide a small inline example so I don't have to read a bunch of documentation elsewhere? Because when you say "parameterised unit test", I hear "function" 😉

**Comment by mjsteinbaugh** [comment]
Sure @hadley, here's the patrick implementation code:
https://github.com/google/patrick/blob/master/R/with_parameters.R#L58

And some examples of how I'm currently using this (e.g. in my basejump package):
https://github.com/acidgenomics/basejump/search?q=with_parameters_test_that&unscoped_q=with_parameters_test_that

**Comment by hadley** [comment]
Can you please put the example in this issue?

**Comment by mjsteinbaugh** [comment]
Here's a really minimal example. If there's a better way to do this that's already in testthat, I'm all ears:

```r
library(testthat)
library(patrick)

with_parameters_test_that(
    "'mapply()'-style tests are cool", {
        object <- sum(a, b)
        expect_identical(object, expected)
    },
    a = list(1, 2, 3),
    b = list(2, 3, 4),
    expected = list(3, 5, 7)
)
```

Inside my package, here's a decent example:

```r
context("detectOrganism")

with_parameters_test_that(
    "Homo sapiens", {
        expect_identical(
            object = detectOrganism(object),
            expected = "Homo sapiens"
        )
    },
    object = c(
        "Homo sapiens",
        "hsapiens",
        "GRCh38",
        "hg38",
        "ENSG00000000001",
        "ENST00000000001"
    )
)
```

**Comment by jimhester** [comment]
Presumably this is how you would do it in testthat

```r
test_that("Homo sapiens", {
  for (object in c("Homo sapiens", "hsapiens", "GRCh38", "hg38", "ENSG00000000001", "ENST00000000001")) {
    expect_identical(!!object, expected = "Homo sapiens")
  }
})

**Comment by michaelquinn32** [comment]
Hi Michael!

Thanks for pinging me! Patrick is still maintained. There have been no FRS and no reported issues, but I don't have any plans to change anything with the package.

If there's something I can do to improve the package, please let me know.

Best wishes,
Michael
