### ISSUE TITLE
Add stop_on_failure argument to test_file

### ISSUE THREAD

**Issue by vspinu** [r-lib/testthat#968]
My use case is the same as in #515. I want to be able to get the non-0 exit value from `test_file`. 

It's a bit strange that `test_dir`, `test_check` and the internal `test_files` accept the `stop_on_failure`, but the workhorse `test_file` doesn't. 

The simplest way to address this might be to export `test_files`.

**Comment by DDorch** [comment]
Exporting `test_files` could also be a way to solve the feature #916 :)

**Comment by jimhester** [comment]
I the meantime `testthat::test_file("tests/testthat.R", reporter = c("summary", "fail"))` will do this without any code changes to testthat.

**Comment by hadley** [comment]
It might make sense to export `test_files()` and then push people towards using that. `test_files()` really seems like the natural primitive here; `test_file()` is just a special case with one path.

Something about the whole structure of `test-files.R` and `test-directory.R` feels a bit off, and I think would benefit from refactoring.

**Comment by hadley** [comment]
Currently `test_file()` is half an internal helper that's used by `test_dir()` and half an equivalent of `test_dir()` for a single file. It does neither thing well: as an internal helper, it could assume that more setup is done in `test_files()`, and as a runner for a single file, it fails to run setup and teardown code.

**Comment by hadley** [comment]
It turns out that `test_file()` had one additional use — it was also used for testing. So it really had 3 uses, and was optimised for none of them.
