### ISSUE TITLE
Are the tests failed or not?

### ISSUE THREAD

**Issue by fannieywf** [r-lib/testthat#969]
Hi team,
I am trying to translate the unittest elements from Python in R using testthat(). This is my test code in test_trick.R (similar test in test_magic.R):
```
context("check the sum")
library(testthat)

test_that("check the sum", {
  expect_equal(trick(parse_line("D2.html")), 6972)
  }
)
```
with the bash output as follows:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/40841100/69428951-b8500800-0d32-11ea-9eee-980336c7ae6b.png">

I read the `failed: 1` as the test results but there are no failed messages. That's why I do not get it whether the tests are failed or not. 
Also `No one gets it right on their first try` is literally understood. What does it mean actually?

**Comment by hadley** [comment]
Hi @fannieywf,

This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio community](https://community.rstudio.com). 

Thanks!
