### ISSUE TITLE
Add a skip on GitHub actions function

### ISSUE THREAD

**Issue by boshek** [r-lib/testthat#970]
Apologies if you've already implemented this and I missed it but I think testthat needs a `skip_on_actions` function like this:

```
skip_on_actions <- function() {
  if (!identical(Sys.getenv("GITHUB_ACTIONS"), "true")) {
    return(invisible(TRUE))
  }
  skip("On GitHub Actions")
}

```

I can submit a PR if that would be desired.

**Comment by njtierney** [comment]
Came here looking for this, going to submit a PR - hope you don't mind, @boshek :)

**Comment by boshek** [comment]
👍 Thanks for the h/t in the NEWS. Miiiight have been space here for a co-authored commit but _very_ low stakes.

**Comment by njtierney** [comment]
Of course - thank you for writing the issue and the code! :) I'm not quite sure what a co-authored commit is, but happy to help rectify anything if need be :)

**Comment by jimhester** [comment]
https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors has some info on how to make a co-authored commit if you are interested

**Comment by boshek** [comment]
😄  Probably not worth it @njtierney. More likely a symptom of me being a little grumpy on a Friday afternoon 🤦‍♂ .

**Comment by njtierney** [comment]
Just got to this after the break - thanks for the link, Jim - this was super neat and easier than I thought :) Thanks for the suggestion on adding a co-authored commit @boshek

**Comment by hadley** [comment]
I'm now wondering if this is needed — does `skip_on_ci()` not work?

**Comment by boshek** [comment]
Given there is already `skip_on_travis` and `skip_on_appveyor` it feels like the natural extension is to add an actions specific function.

**Comment by hadley** [comment]
I don't think that reasoning is sound; if we've made two mistakes in the past, it doesn't imply that we should make a third.

**Comment by boshek** [comment]
Oh ok - I didn't realize those were mistakes.

**Comment by jimhester** [comment]
`skip_on_ci()` will work assuming the workflows are using the `setup-r` action, which sets `CI=true`
