### ISSUE TITLE
set TESTTHAT envvar within test_file()?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/testthat#971]
Currently, `testthat` sets a number of environment variables within `test_dir()`:

https://github.com/r-lib/testthat/blob/3633dfeb30fe89aac17b43e5f919447c2a1185da/R/test-directory.R#L82-L86

However, it's possible to run test files individually; e.g. with `testthat::test_file()`. (RStudio uses this when running a single testthat test file.)

Would it make sense to set TESTTHAT (or maybe TESTTHAT_FILE) within `test_file()`?

**Comment by hadley** [comment]
Yeah, that seems reasonable to me.
