### ISSUE TITLE
expect_condition() fails when multiple conditions emitted

### ISSUE THREAD

**Issue by kevinushey** [r-lib/testthat#972]
This might be my misunderstanding of how `expect_condition()` should work, but...

``` r
library(testthat)

signal <- function(class) {
  condition <- simpleCondition(NULL)
  class(condition) <- c(class, "condition")
  signalCondition(condition)
}

test_that("conditions can be expected", {
  expect_condition(signal("hello"), class = "hello")                     # OK
  expect_condition({signal("hello"); signal("world")}, class = "hello")  # OK
  expect_condition({signal("hello"); signal("world")}, class = "world")  # FAIL
})
#> Error: Test failed: 'conditions can be expected'
#> * <text>:13: `{ ... }` threw an condition with unexpected class.
#> 
#> Backtrace:
#>  1. testthat::expect_condition(...)
#>  6. global::signal("hello")
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Should `expect_condition()` succeed if at least one condition is thrown matching the requested class?

**Comment by kevinushey** [comment]
I guess my surprise is that `expect_condition()` stops after the first condition rather than executing the whole block of code:

``` r

library(testthat)

signal <- function(class) {
  condition <- simpleCondition(NULL)
  class(condition) <- c(class, "condition")
  signalCondition(condition)
}

f <- function() {
  signal("hello")
  print("f()")
}

f()
#> [1] "f()"
expect_condition(f(), class = "hello")
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Yeah this is deliberate because I couldn't figure out how the logic should work. If you are throwing multiple conditions and want to test one specific one, I think you're better off writing your own code.
