### ISSUE TITLE
Does a test badge exists? 

### ISSUE THREAD

**Issue by neonira** [r-lib/testthat#981]
There exists many badges that can be used to show build status, CRAN status, test coverage percentage, and many more other things.

**I wonder if there is badge to show number of unit tests for a package, that could be used as easily as other badges.**

That's important to know, and could bring some light about package robustness

**Comment by cderv** [comment]
For reference, this is also asked on community.rstudio.com
https://community.rstudio.com/t/does-test-badges-exist/49574

Please, if you cross post, add a link. Also for such question, community.rstudio.com is the right place and I think there is no need to open at the same time an issue in Github which is more for Bug Report and Feature Request.

**Comment by neonira** [comment]
Got it. Gonna close the issue and let rstudio community deal with it. 
Thanks for help.
