### ISSUE TITLE
Weird failure due to system environment variable not seen

### ISSUE THREAD

**Issue by neonira** [r-lib/testthat#982]
Got some weird behavior under **testthat** context. 

When I run a piece of R code as a script, it works fine. 
When I run it inside a **testthat** file, it systematically fails. 

I guess this is related to execution context. 
I use "Sys.getenv" to get a variable name in order to use the variable data. This is very probably the main root cause of the issue. 

Hints and ideas welcome. 
Any documentation related to **testthat** execution context management ?

**Comment by neonira** [comment]
Consider following code in a package to reproduce issue

[R code](https://github.com/r-lib/testthat/files/4091342/getVariable.txt)
[testthat code](https://github.com/r-lib/testthat/files/4091358/test_getVariableByFunction.txt)


<pre>
⠏ |   0       | getVariableByFunction
[1] "immediate name []\n"     
[2] "immediate name [lala]\n"
[1] "direct name []\n"                              
[2] "direct name [lala] value 1, 2, 3, 4, 5, 6, 7\n"
[3] "direct name [zz] value Inf\n"                  
[1] "indirect name []\n"                                
[2] "indirect name [lala] value 1, 2, 3, 4, 5, 6, 7\n"
[3] "indirect name [zz] value Inf\n"                  
✖ |  10 2     | getVariableByFunction
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_getVariableByFunction.R:33: failure: getVariableByFunction - direct by function
`cv` not equal to if (value_s_1 == "zz") NA else v.
Modes: logical, numeric
Lengths: 1, 7
target is logical, current is numeric

test_getVariableByFunction.R:44: failure: getVariableByFunction - indirect by function
`cv` not equal to if (value_s_1 == "zz") NA else v.
Modes: logical, numeric
Lengths: 1, 7
target is logical, current is numeric
</pre>


I see no reason for not getting correct access to variable lala either directly or indirectly. Very weird ...

**Comment by hadley** [comment]
I'd recommend not using `Sys.getenv()` to retrieve variable names

**Comment by neonira** [comment]
I understand. What other way may I use instead of Sys.getenv() to retrieve variable name ?

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by neonira** [comment]
Solved. Replaced Sys.getenv by options. 
Thanks for reliable suggestion.
