### ISSUE TITLE
Export context_name()

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/testthat#983]
(See https://github.com/r-lib/vdiffr/issues/71#issuecomment-578483625 for the background)

vdiffr depends on the context of the reporter to determine the path to store the image files. So, it needs to imitate what `ProgressReporter` does in order to infer the context from the name of the test file. But, currently `context_name()` is not exported. Can it be exported so that custom `Reporter`s can use it? Or, am I doing the things wrong...?

**Comment by stufield** [comment]
Ok. I will handle this during #1041

**Comment by yutannihilation** [comment]
Great, thanks!
