### ISSUE TITLE
FR: method `only()` to isolate tests

### ISSUE THREAD

**Issue by chris-perts** [r-lib/testthat#984]
Requested feature: a function `only` that, when present in a block, skips all other tests in the file.

Example:

```
library(testthat)
describe('suite with many tests', {
  it('is the test I want to focus on', {
    only()
    # expectations here...
  })

  it('some other test', {
    # this test is skipped
  })

  # any other tests are skipped
})
```

This is very useful when debugging as it isolates output to the thing you're focused on. This would be similar to facilities in other test frameworks, like [jest](https://jestjs.io/docs/en/api#testonlyname-fn-timeout). It would also be a natural addition to the behavior of `skip()`.

**Comment by hadley** [comment]
Unfortunately `describe()`/`it()` are basically retired in testthat; they need to live in their own package with a maintainer that cares about them.
