### ISSUE TITLE
Examples in documentation for `quasi_label` do not feature `quasi_label`

### ISSUE THREAD

**Issue by jarauh** [r-lib/testthat#987]
See title.

**Comment by hadley** [comment]
Right, because I don't expect anyone to ever call this function.

**Comment by jarauh** [comment]
Ok.
1. It would be good if "internal" functions would be marked as internal, somehow.  That would prevent me from opening more such bug reports (cf. https://github.com/tidyverse/dplyr/issues/5030).
2. In this case, the situation is slightly different: I used to use `testthat::expect...` with the argument `info` that has recently been deprecated.  The documentation tells me:
> Instead see alternatives in quasi_label.

So - if noone should ever call `quasi_label`, it should not be mentioned in the documentation of "legal" functions.

**Comment by jarauh** [comment]
By the way, at least you were right with your expectation - I did not call this function (yet). 😏

**Comment by hadley** [comment]
Don't the examples show you what you need to know?

**Comment by jarauh** [comment]
Concerning my own use case: I need a substitute for:
```r
> x <- c(1, 2, 3, 5)
> for (i in 1:4) testthat::expect_equal(x[i], i, info = paste0("Problem with i = ", i))
```

I understand that I can do:
```r
> for (i in 1:4) testthat::expect_equal(x[!! i], !! i)
```
But that's not quite the same: `info` let's me add arbitrary text easily to single expect statements, which I found quite convenient.

**Comment by jarauh** [comment]
Concerning the general issue: I guess what I found confusing is that the page `quasi_label` mixes a general explanation of quasi labelling (with examples) and an explanation of the syntax of the general function `quasi_label` (without example).  So, two separate but related topics are mixed into one page.
