### ISSUE TITLE
Allow for conditional export in NAMESPACE

### ISSUE THREAD

**Issue by nbenn** [r-lib/testthat#989]
I have a conditional export in my `NAMESPACE` file, something like

```r
if (getRversion() >= "4.0.0") { S3method(cbind, my_class) }
```

any my problem is, if `cbind.my_class` is available for `getRversion() < "4.0.0"`, my code breaks. I was able to fix my issue by modifying

https://github.com/r-lib/testthat/blob/b7e06829672cc4f05c8552194eda1dde64e7f5da/R/test-directory.R#L240-L245

and conditionally removing `cbind.my_class` from the object list.

I realize, my issue represents a bit of an edge-case and it might not be worthwhile to add the option of preventing an object from becoming available during testing. Nevertheless, for my use case, this would be convenient.

**Comment by hadley** [comment]
Can you please provide more details? How exactly does the test fail.

**Comment by jimhester** [comment]
Also that conditional export does not prevent `cbind.my_class` from being an object in your namespace, it just prevents it from being an _exported_ object from the namespace. See the difference between the two following calls.

```r
getNamespaceExports("dplyr")
names(getNamespace("dplyr"))
```
