### ISSUE TITLE
verify_output() and non-syntactic names

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#993]
This makes tibble tests more complicated than they might be. Replacing `expr_deparse` by `deparse` in the `verify_output()` code fixes the issue for me.

``` r
testthat::verify_output("test.txt", list(`a b` = 1))
#> Warning: Creating reference output
cat(testthat:::read_lines("test.txt"), sep = "\n")
#> > list(a b = 1)
#> Error: <text>:1:8: unexpected symbol
#> 1: list(a b
#>            ^
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Fixed upstream in rlang
