### ISSUE TITLE
all_passed is not exported

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/testthat#996]
I need to run testthat from Rscript invocation and have the return status of the process be zero if successful, not zero if failed. Currently, there's no way from the testthat_result to know if things are all passed unless I convert it to data.frame and do some math. 

This is already done by the all_passed function, which unfortunately is not exported nor documented.

**Comment by jimhester** [comment]
You don't need to use `all_passed()`, you can use the `fail` reporter along with another reporter to show the results. e.g.

```r
Rscript -e 'testthat::test_dir("my_dir", reporter = c("summary", "fail"))'
```
