### ISSUE TITLE
Assigning inside expect_condition() does not work

### ISSUE THREAD

**Issue by torockel** [r-lib/testthat#998]
Hi testthat team,
It seems like assigning does not work inside `expect_condition()` but does work inside `expect_message()` and `expect_warning()`:
``` r
library(testthat)
foo_message <- function() {
  message("a message")
  5
}

expect_message(a <- foo_message())
a
#> [1] 5

expect_condition(b <- foo_message())
b
#> Error in eval(expr, envir, enclos): object 'b' not found


foo_warning <- function() {
  warning("a warning")
  5
}

expect_warning(c <- foo_warning())
c
#> [1] 5

expect_condition(d <- foo_warning())
d
#> Error in eval(expr, envir, enclos): object 'd' not found
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don’t know, if this difference is intended. However, I find it sometimes useful to do stuff like this, which is inspired by the examples of `expect_message`:
``` r
expect_warning(c <- foo_warning())
expect_equal(c, 5)
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Hmmm, I'm not sure that the current behaviour is wrong. Note that the problem isn't actually assignment:

``` r
library(testthat)
a <- 1
expect_condition(a <- 2, NA)
a
#> [1] 2
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It's that `expect_condition()` stops running any code after it captures the first condition. `expect_message()` and `expect_warning()` work differently as they capture all messages and warnings so evaluate all code.

**Comment by torockel** [comment]
Thank you for your explanation. My expectation of the function `expect_condition()` was wrong. Lead by your very interesting book (https://adv-r.hadley.nz/conditions.html), I thought `expect_condition()` was a more general form of `expect_message()`, `expect_warning()` and `expect_error()`). So, I came to the (wrong) conclusion that it would behave like these functions. However, it seems to be behave different to all three. Even `expect_error()` does not stop after a message, which I first expected after reading your reply and because `expect_error()`  and `expect_condition()`  are documented together:
``` r
library(testthat)

foo_message <- function() {
  message("a message")
  5
}

expect_error(d <- foo_message(), NA)
#> a message
d
#> [1] 5
```
<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I seem to be not the only one, who misunderstood `expect_condition()` (#972). Maybe just add the sentence you wrote in your reply (“`expect_condition()` stops running any code after it captures the first condition.”) to the documentation of `expect_condition()`?

**Comment by hadley** [comment]
I've changed my mind: this isn't a documentation problem, it's a bug that's worth fixing.
